### ISSUE TITLE
configurable or consistent name for etherpad links

### ISSUE THREAD

**Issue by tomryanx** [jitsi/jitsi-meet#1016]
It would be great if the pad used in 'Shared document' could have a configurable link/address, or failing that at least a consistent / predictable one.

So eg if I go to meet.site.com/Meeting123 and we use a shared document, rather than it being `https://pad.site.com/p/2f68f4657df049d99a3585c8db330149` it could be something more like `https://pad.site.com/p/Meeting123`

Something configurable would be ideal, so that the pad-based agendas we use for our weekly meetings (in the form `https://pad.site.com/p/weekly-2016.01.01`) could be pulled in and annotated live. But using the jitsi room name as above would allow us to effectively do that by naming the room in line with the pad.

**Comment by donarek** [comment]
Been searching for this everywhere, 
asi it turns out in _[jicofo/src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java](https://github.com/jitsi/jicofo/blob/e64ab497284aa9bad38b7fa92b80bc6c07825565/src/main/java/org/jitsi/jicofo/JitsiMeetConfig.java)_ ,
you can use directive **useRoomAsSharedDocumentName: true** after your **etherpad_base** definition
in your _/etc/jisti/meet/example.com-config.js_
