### ISSUE TITLE
Disappointing install instructions

### ISSUE THREAD

**Issue by sangramrath** [jitsi/jitsi-meet#103]
I am very disappointed at the install instructions. This in no way helps in duplication the installation you have at https://meet.jit.si/

I understand this is a start but there is quick install which also is a failure and does not work as per the steps outlined. Documentation is key to any new software if you really need it adopted.

This is a request to all contributors and developers to start creating one.

**Comment by LIAOYUZHE** [comment]
i also met a lot of problem when installing the jitsi meet, i just fellow the detailed installatiom instruction to install my jitsi meet, every step i'm very carefully, but it dosen't work. i don't konw how to solve it.
i even don't konw what is YOURSECRET1 or YOURSECRET2 mean!

**Comment by elimisteve** [comment]
I strongly agree that installing the .deb is impressively painful.

I've spent ~~45~~ 60+ minutes on this and finally made some progress thanks to https://github.com/turint/jitsi-meet/blob/master/doc/quick-install.md

**Comment by bgrozev** [comment]
> I've spent 45 60+ minutes on this and finally made some progress thanks to https://github.com/turint/jitsi-meet/blob/master/doc/quick-install.md

How does that differ from the [official documentation](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) refferred to in our [README](https://github.com/jitsi/jitsi-meet/#installation)?

**Comment by elimisteve** [comment]
@bgrozev Ah, maybe they're no different, but I didn't see those docs you're referring to and just followed the instructions in the Download section of your website, specifically [here](https://jitsi.org/Main/DebianRepository).

But those instructions ultimately haven't worked for me, either, or maybe they would if I hadn't first installed `jitsi-meet-prosody` via `dpkg`, which `dpkg` and `apt-get` are not letting me uninstall for some reason.

**Comment by damencho** [comment]
These are instructions for the desktop client, on the download page it is said this is for Jitsi (SIP communicator). Going on the jitsi-meet page (https://jitsi.org/Projects/JitsiMeet) from the main page, there are no directions to these instructions, just to the official one that Boris mentioned.

**Comment by jodumont** [comment]
it broke my system;
Now I'm unable to force the installation, update my system or remove jitsi ;(

**Comment by ivandiv** [comment]
It's just absurd that there are no general pointers: 
Does installing give you a skype/wire/signal-like app?
Are you installing a 'server' for other 'users'?
When I want to 'Start using it now!' (front page), I followed the instructions found here: https://desktop.jitsi.org/Main/InstallJitsiVideobridgeDebianStableRepository
And then, after no luck, here: https://jitsi.org/downloads/ubuntu-debian-installations-instructions/
.. there is no app installed in Ubuntu.
Zero idea what is going on. 
Why should a new user be so at a loss? 
Why should we go to a message board somewhere to figure this out?
I know its free open source, etc. But that's the problem. It doesn't "JUST WORK".

**Comment by bgrozev** [comment]
> Does installing give you a skype/wire/signal-like app?

We have a whole set of different projects, so there is no one single answer to this question. Since you are posting on the Jitsi-Meet github project, perhaps you should take a look at the [first paragraph of the README](https://github.com/jitsi/jitsi-meet#jitsi-meet---secure-simple-and-scalable-video-conferences). 

> When I want to 'Start using it now!' (front page), I followed the instructions found here:

I don't see a "start using it now" link on the front page. There is a "try jitsi" link, which will open the conference application right there in your browser for you to try. The links that you posted are valid documentation, just not what you are looking for.

> Why should a new user be so at a loss?

There is definitely room for improvement on the current website, and we would be happy to get feedback on how we can improve it. But the most common use-cases are covered at visible places. Use the "try jitsi" link if you want to see the product in action, browse the "jitsi projects" links if you are looking for a specific project. 

> I know its free open source, etc. But that's the problem.

Yes, the projects here are open source. That's clearly stated, and if it's a problem for you, perhaps you should look elsewhere. 

> It doesn't "JUST WORK".

Mostly, it does. If you want to just use the conferencing application the "try jitsi" link "just work". And If you want to deploy a full conferencing solution on your own servers, I believe the instructions you will find in the readme are as close to "just works" as it gets. 

We welcome feedback on how we can improve the user experience on our website. But posting a generic "doesn't just work" message without details or suggestions on what we can do doesn't help us or anyone else. You seem to have stumbled upon the wrong documentation pages. How did this happen? Perhaps we can improve the links on the website, or add clarifying text somewhere.

**Comment by ivandiv** [comment]
Hi,

I would like to be constructive. The problem is, there is no easy introduction for the uninitiated, especially the non-specialist. You jump into  
"Jitsi Meet is an open-source (Apache) WebRTC JavaScript application that uses Jitsi Videobridge to provide high quality, secure and scalable video conferences. You can see Jitsi Meet in action here at the session #482 of the VoIP Users Conference."

What? #482? Sure! 
All I understand is "video conferences". 

Ok. Two steps back. See the attached? It does say "start using it now" in a pointer to the download link. With quite a bit of pre-knowledge of ubuntu, I know to do this https://desktop.jitsi.org/Main/DebianRepository.
and nothing pops up in my apps. After searching, I try this
https://jitsi.org/downloads/ubuntu-debian-installations-instructions/
Still no app in my ubuntu search bar.
I'm stuck. No idea how to launch any of the projects in the 'full package'. No idea which one I need.

Next, I would work through some Github pages, hoping to strike upon gold.. I'm sure it will work - if I try hard enough. But if someone with a higher degree in mathematics has to struggle, how about the ordinary person?

But all I want is a piece of software that I install, and my contact installs, and we can use chat/videoconferencing. Just like any other service. Is that too much to ask for?

BTW. I really would like it to work. And to work well. And to work with utmost security. I am the director of www.ArtistsatRisk.org, and we have highly sensitive cases. It needs to be secure. And it needs to be damn easy so that stressed out people, on the run from bloodthirsty dictators, can use it without pre-knowledge.

Unfortunately, we're stuck with the commercial bros.

Thank you for you work so far. I hope it gets easier for the end user.

I

What I meant not that free/libre software is the problem. It's that the coders of this stuff often forget the normal end-user. They don't make it easy. It's not just: do this, then run that, and presto. 


![screenshot from 2018-03-06 11-46-38](https://user-images.githubusercontent.com/2873180/37028260-1b160814-2134-11e8-83a5-09027d5f3ea6.png)

**Comment by bgrozev** [comment]
Hi, 

> I would like to be constructive. The problem is, there is no easy introduction for the uninitiated, especially the non-specialist. 

Thank you for providing more details. Bear in mind that this is on the guthub page of the project, so it is expected to be more technical. If you go to the main website at https://jitsi.org you will see a "Try Jitsi" button on the top right. This will open the video conferencing application in your browser for you to try. No installation required.

> What? #482? Sure!

No, "#482" does not refer to a github issue number. It also isn't hyperlinked, but earlier in the sentence there is a hyperlink to the referenced resource. Also, the very next line indicates where you can try jitsi-meet.

I've opened [this pr](https://github.com/jitsi/jitsi-meet/pull/2567) to make the text more clear.

> Ok. Two steps back. See the attached?

The screenshot that you post shows the "desktop.jitsi.org" website, the website for one of our projects. This project doesn't see much updates anymore, which is why it was moved to a separate URL.

> It's that the coders of this stuff often forget the normal end-user. They don't make it easy. It's not just: do this, then run that, and presto.

We try. And as I already mentioned, there are links to just try jitsi-meet on the main page of the website and in the top paragraph in the readme. I think this goes a long way. 

However, you are correct that we don't have a single page with step by step instructions that we can point to. This is not because we don't want to make it easy for end users. It is because we have much more going on -- we have many different projects which are used separately, and a big part of their development happens here.

Thank you for your feedback. Unfortunately, apart from the little update to the readme, I can't extract anything specific that we can work on. If you have more suggestions, let us know (or open a PR).
