### ISSUE TITLE
Conference with Password and Moderator (without having to formally register users)

### ISSUE THREAD

**Issue by helmutkaufmann** [jitsi/jitsi-meet#10485]
I have come across Jitsi only lately and I love the concept of not having to register in order to hold a VC. What I somehow dislike is the fact that I cannot easily ensure ownership over the conferences I am hosting. What I would love to see is 
- no need to register in order to participate in a VC (as is today)
- all participants staying muted in the lobby (as is)
- the moderator to join any time (and not as the first one) and let participants enter

There are a few open feature requests regarding lobby and/or password and there are not too many proposed solutions to this.

**Describe the solution you'd like**
I would propose the following, which probably would not require to much code changes
- When creating a conference, let the creator chose to optionally enter a password
- The password is one-way hashed and added to the invite that can be sent to all participants (or the hashed password becomes the conference ID)
- When someone tries to join the conference, the system prompts if the person is the moderator, who can then enter the plain text password. If the hash of this password equals the has passed on with the conference ID, the person is made a moderator and let in

Theoretically, this should be fairly straightforward to implement.

**Describe alternatives you've considered**
Move to Zoom :(

**Comment by damencho** [comment]
> * When creating a conference, let the creator chose to optionally enter a password

There is no such concept as creating a conference. The first joining creates it and after the last one leaves it is destroyed.

Storing a password for a room and assigning a moderator to a room will be possible only if you have authentication enabled which removes the `no need to register in order to participate in a VC`. This is already possible using custom prosody modules. You can check 8x8.vc where you can pre-assign a password to your room and also setup whether all authenticated participants will be moderators or not, whether lobby is turned on or off by default for the room - things that require storage and authentication.

For meet.jit.si you can use moderated.jitsi.net where you have the option to join a meeting as a moderator and have a guest link that you can distribute.

**Comment by saghul** [comment]
I believe what you need can be accomplished using "moderated meetings", please see: https://moderated.jitsi.net/

**Comment by helmutkaufmann** [comment]
@saghul ... Great, yes, that is what I wanted. Great to have an active community. May I ask if moderated meetings are a standard feature that is available in the open source distribution of Jitsi Meet?

**Comment by damencho** [comment]
Yes, you can deploy your version of it the same way. https://github.com/jitsi/moderated-meetings

**Comment by helmutkaufmann** [comment]
> I believe what you need can be accomplished using "moderated meetings", please see: https://moderated.jitsi.net/
> 
> LoL, looks like damencho and I were typing at the same time!

@saghul ... Great, yes, that is what I wanted. Great to have an active community. May I ask if moderated meetings are a standard feature that is available in the open source distribution of Jitsi Meet?
