### ISSUE TITLE
Disabling audio only mode starts the camera

### ISSUE THREAD

**Issue by c0m1t** [jitsi/jitsi-meet#11034]
### Description:
Enabling and disabling audio only mode leads to starting the video which is not desired.

#### Scenario 1
When there is no jitsi video track in the store, enabling and disabling audio only mode results in starting the video.

#### Scenario 2
When local participant's video is not muted, enabling and disabling audio only mode unmutes the local participant's video.

**I think these are privacy issues.** Someone may be able to justify the behavior in the second scenario (which I don't believe is a desired behavior for many users), but I dont think the first one is justifiable at all, because the user never started their camera and does not expect it to be turned on after toggling audio only mode.

#### Scenario 1
1. Join a conference where there is no jitsi video track
2. Open performance settings
3. Select best performance
4. Select any other option

#### Scenario 2
1. Start your video
2. Open performance settings
3. Select best performance
4. Select any other option

### Expected behavior:

Local participant's video should not start.

### Actual behavior:

Local participant's video starts.

**Comment by saghul** [comment]
Scenario 1 is a bug, 2 is expected behavior since it was the previous state.

**Comment by nbeckindy** [comment]
@saghul
Would it be possible to reconsider addressing scenario 2? Our team had a couple of concerns when it comes to enabling local video automatically in this case:

- A participant may toggle audio-only on, and then 5, 10 or more minutes later toggle it off. By that point, they have forgotten what their video setting was initially, and are not expecting their local video to start again.
- If a participant toggles audio-only on while their video is on, there is no way, while audio-only mode is active, to prevent the video from toggling back on again. Since the video would be currently treated as off, they can't toggle it off again.

Thank you!

**Comment by saghul** [comment]
We'll take another look at this.
