### ISSUE TITLE
Authentication and prosody reservations plugin

### ISSUE THREAD

**Issue by ajntc** [jitsi/jitsi-meet#11144]
### Description:

After authenticating user my reservation API is properly requested. But when my API responds with status code 403 ( given room does not exist) authentication dialog gets stuck at "obtaining session ID" even though i return proper (regarding documentation) JSON object with `message = "Room not found!"`.

In JS console I can see errors like this:
```
[features/authentication] <74/_onLogin/</<>:  authenticateAndUpgradeRole failed 
Object { authenticationError: "service-unavailable", message: "Room not found!" }
```

### Steps to reproduce:

1. Install latest Jitsi 2.0.7001 on Ubuntu 20.04
2. Enable prosody user authentication with guests access to rooms
3. Enable prosody reservations plugin

### Expected behavior:

There should be an error shown to user with returned from reservation API message..

### Actual behavior:

Authentication stuck with "obtaining session ID" message.

**Comment by ajntc** [comment]
Could someone please help with this issue? It's not Prosody issue IMO, it's Jitsi that doesn't want to display a message.

**Comment by saghul** [comment]
I think the problem comes from here: https://github.com/jitsi/jitsi-meet/blob/db16250e6e182d2a7b3ea4e2d00f987b2ae4e27d/react/features/authentication/actions.any.js#L104

If there is an authentication error at that stage we set the progress to 0.5. Then in the login dialog we perform this check: https://github.com/jitsi/jitsi-meet/blob/db16250e6e182d2a7b3ea4e2d00f987b2ae4e27d/react/features/authentication/components/web/LoginDialog.js#L202

Which means we'll be waiting there on the fetch session ID error pretty much forever AFAICT.

I wonder if we shouldn't just not set progress in that case, which would lead to the error being displayed in the dialog.

WDYT @damencho? I followed the logic changes there and Calin just moved the code around, it was like this already. What implications could the change have, I think none, but want 2 brains on this one ;-)

**Comment by damencho** [comment]
Well, you know more about this code at the moment than me :) so I'm good :)

**Comment by saghul** [comment]
Hehe, I'll make a PR tomorrow after some testing.

**Comment by ajntc** [comment]
@saghul Any good news for this issue? It it going to be fixed?

**Comment by saghul** [comment]
It will, but I haven't gotten around working on it yet.

**Comment by stefanplk3** [comment]
It would be awesome if you could fix the issue as it is still present in the latest version. Still no error message when the reservation API returns 403 and the authentication screen is stuck on "obtaining session id".

**Comment by saghul** [comment]
Looks like this one fell through the cracks. As we don't use the reservations API it's not easy to test fixes. If you could provide a patch that would be very welcome.

**Comment by stefanplk3** [comment]
Unfortunately I have no idea where the problem lies. I could provide you with a testing reservation server of some sort for testing?
