### ISSUE TITLE
Screen share not working on chrome for jitsi

### ISSUE THREAD

**Issue by donnierisk** [jitsi/jitsi-meet#11159]
### Description:

Screen sharing not working on latest chrome using latest jitsi.

### Steps to reproduce:

1. Open https://meet.jit.si/VerticalArraysGazeSomewhat in chrome on mac
2. try share your whole screen or window.
3. Nothing happens, logs show permission denied, but it never prompts me for permission to share screen

### Expected behavior:

Should either share my screen or prompt me to allow screenshare followed by screen being shared

### Actual behavior:

Nothing happens for user

### Server information:

- Jitsi Meet version: Latest online (And a few version back that we use internally)
- Operating System: N/A

### Client information:

- Browser / app version: Chrome latest version / Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
- Operating System: macOS Version 10.15.7 - 12.2.1

**Comment by donnierisk** [comment]
UPDATE: Firefox also not working.
Also Apparently Google Meet suffers from the same problem. so no idea what is going on

**Comment by donnierisk** [comment]
It says I cancelled prompt, but I did not. this is after I select 'Entire screen'

<img width="1617" alt="Screenshot 2022-03-17 at 16 33 48" src="https://user-images.githubusercontent.com/17927429/158829128-5c151dbb-2778-4900-9ca9-db444b234bfc.png">
<img width="1633" alt="Screenshot 2022-03-17 at 16 34 14" src="https://user-images.githubusercontent.com/17927429/158829195-61d566e4-c67b-4524-8f52-583952b24201.png">

**Comment by jaonoctus** [comment]
I have the same issue on chrome, but only when E2EE (End-to-End Encryption) is on.

**Comment by pierreozoux** [comment]
It looks like it is due to permission at os level, check these permission, like described here:
https://success.highfive.com/hc/en-us/articles/360018627692

**Comment by Antzus** [comment]
This issue is still relevant in Mac today (May/2024).
Link from pierreozoux is currently dead.
Comment by pedro-nonfree is also worthwhile - it led me to find a fix.

https://apple.stackexchange.com/questions/384228/how-do-i-configure-screen-recording-permission-on-macos-catalina

This worked for me in BigSur (even though the question was about Catalina). It's to do with privacy settings in macOS - some update must have disabled the permission setting at some stage without notifying me. You need to manually turn it back on for the browser in which you're using Jitsi.

**Comment by saghul** [comment]
Las there is nothing Jitsi can do here since it's the browser the entity that isn't grated the permission and a Web app has no way around it.
