### ISSUE TITLE
No dataChannelOpened message in iframe API

### ISSUE THREAD

**Issue by edemaine** [jitsi/jitsi-meet#11186]
### Description:

I never receive the `dataChannelOpened` message via the iframe API.

### Steps to reproduce:

1. `const jitsi = new JitsiMeetExternalAPI('meet.jit.si', {roomName: 'test-dataChannelOpened'})`
2. `jitsi.addListener('dataChannelOpened', () => console.log('OPENED'))`

### Expected behavior:

`OPENED` logs to console

### Actual behavior:

No such event.

### Server information:

meet.jit.si

### Client information:

- Browser / app version: Chrome 99.0.4844.74
- Operating System: Windows 10

### Additional information:

I tried logging all events via `jitsi._transport.on('event', ({name}) => console.log('----', name))`. Many events log, but not this one.

Perhaps the event has already fired before I can possibly listen to it? Is there another way? It looks like the `browserSupport` event occurs around the same time, so that might suffice.

**Comment by saghul** [comment]
@horymury can you PTAL when you get a chance?

**Comment by damencho** [comment]
You should not add `https://` to the domain when passing it to the iframeAPI.

**Comment by edemaine** [comment]
Sorry, that's a typo. I'm using `meet.jit.si` for the host.

**Comment by san-rizz-777** [comment]
Root cause: `data-channel-opened` fires during ICE setup before the
parent page can register a listener via `addListener()`.

Fix in `modules/API/external/external_api.js`:
- Cache `_dataChannelOpened = true` when the event arrives in `_setupListeners`
- Override `addListener` to replay via `setTimeout(0)` if flag is already set.

PR: #17172
