### ISSUE TITLE
option to set the own local video quality to the same as the remote 

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/jitsi-meet#11181]
Currently one does not have any idea about how bad the video quality is of oneself as seen by the other participant. The local video is always high quality. This is of course good in an environment where you sell conferencing services, because people are being fooled that the connection is always great. But for own 1 to 1 communication it is better to straightaway see if there is a connection issue when the video is bad.
In case of multiple participants this could work like displaying the worse quality.

**Comment by saghul** [comment]
Not sure I understand.

> The local video is always high quality.

That's really not the case. We'll always send video in the requested quality. If nobody is rendering our video in 720p then layer suspension will kick in and we'll send a 180p stream.

The local video video will always be rendered at the unscaled resolution, however.

**Comment by f1-outsourcing** [comment]
> Not sure I understand.

If there is a meeting with two participants A and B, then
at A, the video of A is better quality then the video of A at B

> The local video video will always be rendered at the unscaled resolution, however.

Indeed, but then you never see how bad your video actually is. Currently I have quite a bit of latency issue on my connection although I am able to up/download at 35Mbit/s

If I compare the 720p youtube livestream that generates ~4.20Mbits peak downloads every x seconds, to my meet continuous upload stream of 3.2Mbits. The visual experience is that it is nowhere near the quality of the youtube stream.

**Comment by saghul** [comment]
> If there is a meeting with two participants A and B, then
> at A, the video of A is better quality then the video of A at B

This is true for every meeting.

> Indeed, but then you never see how bad your video actually is.

Of course, you need to be on the receiving end for that. If the user has a lossy connection they will you poorly, what do you expect to happen locally, when you have no problems? We already show the connectivity icon for each participant.

**Comment by f1-outsourcing** [comment]
> We already show the connectivity icon for each participant.

I prefer to see the same video quality stream

Currently I have the perception that I am not having any problems, yet my video stream is bad at the receiving side. While I see others in much better quality. 

How does jitsi decide this is a nonoptimal connection? 500Kbps / 200 Kbps is nothing, speed test is giving me 35Mbps. I have the impression how the connection is being tested is not correct.



![Untitled](https://user-images.githubusercontent.com/13450219/159483260-8090f33c-9604-4560-b1c0-922de0e3dad4.png)
.

**Comment by saghul** [comment]
It takes some time for the stats to stabilize. Packet loss is a big factor determining connection quality.

**Comment by f1-outsourcing** [comment]
But how is this determined? The bad video is during the whole meeting, the attached results are from 5-10min into the conversation. 
Is there some override to this quality detection so I can force the connection to be on some minimum quality level. If then the meeting is still ok, it would prove that the detection mechanism is not 100%

**Comment by paweldomas** [comment]
The way connection indicators work right now, is they compare the actual outgoing bitrate to the target (optimal bitrate for the currently selected resolution). See [this code](https://github.com/jitsi/lib-jitsi-meet/blob/90f8d11d003b10fe768f36309d1200e1028fbe8f/modules/connectivity/ConnectionQuality.js#L381). After calculating the actual/target ratio, the result is penalized for high packet loss. The approach takes advantage of Chrome bandwidth estimation to figure out if the connection is good or bad. The problem is for the most part that only checks the uplink direction (because it's estimation on how much Chrome can send). The packet loss component of the logic works in both directions, but there are often cases with 0 packet loss and still having problems (which seems to be the case from your screenshot). There are two components for Chrome BWE: packet loss and delay. If there's 0 packet loss you should look at the RTT stats (for spikes) and jitter if you want to diagnose this further. The first place to look at will be "candidate pair" graphs in webrtc internals which also include the available outgoing bitrate which is the current Chrome estimation.

**Comment by f1-outsourcing** [comment]
Hmmm I installed new ubuntu vm with new jitsi packages, but I still do not have this ConnectionQuality.js anywhere on disk. I found this code in some map file and changed the return to:

`return Math.min(100,100)`

However I still have mostly bad connections. I will try this online jitsi service next, see if it is exactly the same.

**Comment by saghul** [comment]
All the source is bundles in app.js and some workers, you won't have the individual files on disk.
