### ISSUE TITLE
Missing translation (at least in french)

### ISSUE THREAD

**Issue by HumanG33k** [jitsi/jitsi-meet#11346]
I identify several place where translation not exist : 
- the example prefill form for conference name  (InitialParents[...], etc)
- My default name when join (me)
-  Others default name when join (Fellow Jitser )

It can be disturbing when people not speak english.

**Comment by nirajsharma2022** [comment]
Contact me for jitsi meet installation 
https:/wa.me/+919782533298
skype : ersonusaini

**Comment by HumanG33k** [comment]
Yes i talk about random room names. 
Why they are not localizable ? 

I talk about my own server.

**Comment by gpatel-fr** [comment]
because code to allow for easy localization has never been written. If you patch the code in your setup and build a new verison, you will lock yourself out of easy upgrades. You will have to modify roomNameGenerator.js, link modified js-utils to the main jitsi-meet project, and rebuild. This should not be very difficult but could easily turn into a big pain if this has to be done every month for each new stable version (unless you want to be exposed to security risks)

**Comment by HumanG33k** [comment]
I never do stuff in my side because i m aware of all issue that's lead to. 
If i do that kind of modification i will push here.
