### ISSUE TITLE
User agent rejection

### ISSUE THREAD

**Issue by andrewrunxiyu** [jitsi/jitsi-meet#11464]
I was attempting to access [the "default" Jitsi instance](https://meet.jit.si/) with my unpublished fork of Chromium, GNUB.  The default `User-Agent` is `GNU!` (which I should change in the future).

The instance outright rejects my request and redirects me to <https://web-cdn.jitsi.net/static/recommendedBrowsers.html>, displaying:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code>
       <Message>Access Denied</Message>
       <RequestId>X04VYK72C30FA0RX</RequestId> 
       <HostId>4GbyDciofEetQrFcOY8CrwNaRLmTzYm3X4H4Y/tgk9kgYYIzG3kpz0AmrJYhNPD71GHM5JtE1EQ=</HostId></Error>
```

Spoofing the `User-Agent` to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36` obviously solves the immediate problem.

I understand that it is not a day-to-day thing of people developing weird Web browsers.  But at the same time, I propose testing the capabilities of the browser during a meeting, or using a pre-meeting test, primarily for WebRTC, rather than assuming bad support solely based on the `User-Agent` HTTP header.  It may be desirable to leave the user a note that per browser is not officially supported; it is bad to reject the user.

**Comment by andrewrunxiyu** [comment]
I understand that feature detection is sometimes inaccurate for example transceivers being slow in Chromium < 96.  However, it is still desirable to have the inaccuracy rather than avoidable rejection.

**Comment by andrewrunxiyu** [comment]
@saghul has written in <https://github.com/jitsi/jitsi-meet/issues/4836#issuecomment-728827544> that:

> > Isn't displaying a warning banner enough?

> It has proven to not be the case.

Where has this been "proven"?

**Comment by saghul** [comment]
We had to add Safari version checks because of changes in behavior which were not feature-detectable. That's just one example.

The transceivers and SDP plan is another.

Firefox just fixed a longstanding bug where opening mutiple input devices would lead to failures.

Brave was spoofing the UA only on iframes, leading to incorrect behavior because we don't know you are using a touch device.

Internet Explorer doesn't support the minimum JS features we need in the app bundle so we can't even load the app.

The list goes on.

Presently the only thing that actually works is UA string parsing, for some stuff. We do try to feature-detect as much as possible still.

Any PRs improving the status quo are welcome, but this is not an effort we are going to make, sorry.
