### ISSUE TITLE
Three people can't make video call through Android SDK

### ISSUE THREAD

**Issue by ldm0330** [jitsi/jitsi-meet#11536]
Because of some special reasons, we can only use jitsi-meet-android-sdk-2.4.0 to make the Andoriod version of the sdk. We have tested some problems here, that is, when three people enter the room at the same time, they cannot see each other 's video. Please how to solve this problem

**Comment by saghul** [comment]
Sorry, your only way forward is updating.

There are backend changes which are not supported by that SDK because it's so old.

Given how old it is is virtually impossible to know how many changes you'd need to backport.

This will only get worse with time, so I'd suggest you spend the required amount of time updating instead.
