### ISSUE TITLE
Moderation should be able to lower hands

### ISSUE THREAD

**Issue by tzugen** [jitsi/jitsi-meet#11618]
The moderation should be able to lower hands of those participants who just have spoken.
Often participants don't lower the hands themselves. Instead of reminding them it might be quicker to just do it yourself.
This is possible in BBB, but I couldn't find it in Jitsi.

**Comment by saghul** [comment]
Hands are lowered automatically when the participants speak. Are you not observing this behavior?

**Comment by tzugen** [comment]
No than this feature doesn't seem to work...
I can sent u the URL of the server privately if you want to have a look

**Comment by saghul** [comment]
Can you reproduce it on meet.jit.si ?

**Comment by nbeckindy** [comment]
A slightly different use case for this: there could be a situation where not all users with raised hands can be called on for a specific question (maybe because of time restraints, etc). After the question, sometimes users forget to lower their hands themselves. It would be nice for the moderator to have a way to clear these hands before the next question, maybe a Lower All Hands feature.
