### ISSUE TITLE
Android 'react-native-gesture-handler' error in android release build

### ISSUE THREAD

**Issue by md-ajju** [jitsi/jitsi-meet#11745]
### Description:

I am getting react-native-gesture-handler missing error when I click the join meet button  in the react-native app where I integrated this sdk.

### Server information:

- Jitsi Meet version:  org.jitsi.react:jitsi-meet-sdk:5.0.2
- Operating System: MacOs

### Client information:

- Browser / app version:
- Operating System:

**Comment by saghul** [comment]
Dow did you do the integration?

**Comment by md-ajju** [comment]
> Dow did you do the integration?
Using this https://www.npmjs.com/package/@bortolilucas/react-native-jitsimeet 
library which internally uses sdk of jitsi.

**Comment by saghul** [comment]
Note that that build is deprecated.

Also see this note from the original package: https://github.com/skrafft/react-native-jitsi-meet

I do not recommend you use either of them.

We are working on a RN module, but it's not ready yet.

**Comment by sword007** [comment]
npm install --save react-native-gesture-handler@2.1.0

**Comment by sword007** [comment]
it work fine for me
npm install --save react-native-gesture-handler@2.1.0

**Comment by MinaSamir11** [comment]
@saghul  can you update the gesture handler above 3.5.0 because react-native-gesture-handler they change the classes name in android and I'm using a version higher than 2.1.0, and when running the app you are using my higher version on the gesture handler which we have a conflict with the classes name because as I said it was changed or deprecated. 

Can you upgrade the gesture handler and use the new name of there package, please?

**Comment by saghul** [comment]
We can update, yeah. A PR would be welcome.

**Comment by MinaSamir11** [comment]
> We can update, yeah. A PR would be welcome.

So, if anyone/I working on this issue, we are going to work on SDK 5 
Because [react native skart](https://github.com/skrafft/react-native-jitsi-meet) depends on SDK 5 and he isn't willing to change his package to SDK6+ 

I'm asking also about when react native package got released. 
because it required also an update on react native gesture-handler package if anyone/I will work on SDK5.

**Comment by MinaSamir11** [comment]
> SDK 5 will receive no further updates, sorry.
> 
> This change would be applied to SDK 6.

I notice you are working on react native package, when it will be ready to release?

**Comment by saghul** [comment]
Hopefully soon, but I can't provide an ETA.
