### ISSUE TITLE
Share Video Controls on Android Cause Video to Loop for Users

### ISSUE THREAD

**Issue by vmags** [jitsi/jitsi-meet#11831]
### Description:

When an individual using the Jitsi Meet mobile application attempts to pause or drag the progress slider of a video being shared, it causes the video being transmitted to other users to loop and repeat. Sometimes it will eventually sync to the point the sharer's video is at, but other times it will not.

### Steps to reproduce:

1. Join a meeting with several users.
2. Have one user using the android or iOS Jitsi Meet application share video.
3. Pause the video and drag the progress slider to rewind/fast forward.

### Expected behavior:

If the individual sharing the video pauses or adjusts the point the video is playing at, it should update accordingly to all other users.

### Actual behavior:

The video starts looping at its current point. It will play for a few seconds and then start over. It does not pause or catch up to where the sharer has adjusted the video to resume playing from.

This occurs for users who have joined the meeting via broswer and mobile app.

### Client information:

- Browser / app version: meet.jit.si on Google Chrome and current Jitsi Meet application on Android and iOS (version

**Comment by qcsvc** [comment]
It appears that using the scenario described Share Video works as expected with a YouTube video link. 

For other links such as https://mysite.com/video.mp4 - the video plays but the controls (pause, advancing to another point in the video or going back to an earlier point - do lead to the issues described above.

**Comment by saghul** [comment]
Thanks for sharing @wfleischer ! Are you able to test on iOS? If it works ok, I'd  take a PR updating to the new alpha.

**Comment by wfleischer** [comment]
> Thanks for sharing @wfleischer ! Are you able to test on iOS? If it works ok, I'd take a PR updating to the new alpha.

Thanks, @saghul, for considering. I built an iOS app, but could not yet test as thoroughly. I will update here with the results.

**Comment by wfleischer** [comment]
Here are my test results:

#### Jitsi Meet 22.4.0 with current react-native-video 5.2.0

|test |iOS |Android
|------|-----|--------
| Playing a video shared by a peer | echo* | echo*
| - pausing	| ok | ok
| - seeking	| ok | ok
| Sharing video | Android peer jumps (back and forth) | iOS peer jumps
| - pausing	| peers continue | peers continue and jump
| - seeking	| peers jump | peers jump

#### Jitsi Meet 22.4.0 with react-native-video 6.0.0 alpha.2
|test |iOS |Android
|------|-----|--------
| Playing a video shared by a peer | echo* | echo*
| - pausing	| sometimes continues late* | continues as a slide show*
| - seeking	| ok | ok
| Sharing video | app unresponsive after stopping the video | video starts paused, playing is ok
| - pausing	| peers continue* | ok
| - seeking	| peers jump* | mostly works once, on further tries pauses and play button is unresponsive*

\*The echo and peers jumping seems to be related to https://github.com/react-native-video/react-native-video/issues/664. The video plays twice, so audio has echoing. If you pause, the other video continues to play and listeners follow. If you click on play you can hear mixed audio from the two parts of the video. This also  explains why peers jump back and forth. They seem to receive signals from both streams. I am confident that all issues marked with (\*) will be resolved, when this component issue will be fixed. Unfortunately it is open since 2017.

No good news 😞. So upgrading the `react-native-video` component would allow the Android app to share and pause videos. However it will not correctly handle pausing on peers and the iOS app gets unresponsive after stopping the video as a sharer. I think these two issues could be fixed on the Jitsi client side. The Android issue might be related to the video component now correctly triggering `onPlaybackRateChange` on pause. But I don't have cycles to further debug this issue.

**Comment by saghul** [comment]
Thanks for digging deep into this @wfleischer ! @Calinteodor can you PTAL? (maybe there is a way to force unmounting screens, or at the very least we can avoid rendering the largevideo screen when that's not the active screen)

**Comment by Calinteodor** [comment]
@wfleischer Thank you for looking into this. 

The problem with react-navigation is that screens don't get unmounted unless we navigate from A to B( B gets mounted ) and after that we go back from B to A( B gets unmounted ). So if we navigate forward, like B to C, in our case from Prejoin to Conference( B aka Prejoin, remains mounted, but it's no longer focused ).

**Comment by wfleischer** [comment]
Thanks, @Calinteodor! That makes sense. Your patch looks good and works very well for me. Good job!
