### ISSUE TITLE
Upside down video

### ISSUE THREAD

**Issue by amunizp** [jitsi/jitsi-meet#1187]
Using https://meet.jit.si/NameOfMeeting with Firefox 50.0.2 Ubuntu 14.04 I see the video upside down.

I had a similar problem with skype which was fixed by editing the start up script. 

There are several work arounds for different software packages but none seem to fit jitsi running on firefox:

http://askubuntu.com/search?q=upside+down+webcam

This seems to be a hardware problem but I was hoping to have a work around before I go down the line of updating the full OS.

**Comment by amunizp** [comment]
This is still an issue for me.

**Comment by saghul** [comment]
Can you try a newer Firefox version? We no longer support 50. Please update to the next ESR release at the very least.

That said, I don’t think there is anything we can do in our software to detect and flip the video again for you. As you said, it seems to be a system problem since other applications are affected.
