### ISSUE TITLE
How use feature: Shared Record Link

### ISSUE THREAD

**Issue by DmitriyMurzin** [jitsi/jitsi-meet#11903]
Hello everyone!)

I upload meeting records to nextcloud using a bash script and curl.

I want to add a feature with sharing the urls of files after recording, how to implement this in my scheme?
I looking at the javascript code and I don't see such functionality.

How does it work in dropbox?

Thank you all for the answers.

**Comment by saghul** [comment]
Hey there!

We don't have this functionality, this is very dependent on the storage backend. On Dropbox you'll get the recording on the account of the person that started the recording, and that's about it.

Since we work without user accounts, there is no way to get back to the user, the person who made the recording is responsible for sharing it. 

PS: Please use our community forum for discussions next time.
