### ISSUE TITLE
Video zoomed and offset

### ISSUE THREAD

**Issue by kevincolten** [jitsi/jitsi-meet#1191]
Self-hosting, I'm seeing the video as zoomed and offset. Only seems to happen on Chrome. Anyone else encountering this?

**Comment by kevincolten** [comment]
seems to be just my machine

**Comment by m0se** [comment]
I'm experiencing this too. It looks to me like a measure to deal with low bandwidth, since it never happens with clients in the same LAN, only with remote ones. But when it happens the video fees is "zoomed-in" and low resolution on all clients also local ones.

I generally don't have a issue with the low-resolution to mitigate low bandwidth, but whats annoying to me is that only the center part of the video feed is visible when this zoom-thing happens.

Since this is the only issue I'm able to find concerning this, I'm starting to suspect, that this is a thing WebRTC does on it's own and it might be beyond the control of jitsi meet. I'll test if it also happens, when all participants use Firefox.

**Comment by saghul** [comment]
Can you share a screenshot? We don't do any zooming ourselves, but I'm really curious about what you're seeing.

**Comment by m0se** [comment]
Sure,.. I was able to reproduce it in my LAN by using the Throttling-Feture in Chromium Dev-Tools (set to "Regular G2"-speed). 

_I'm not entirely sure if that actually did the trick, after turning throttling off I had to reconnect several times before I got the regular non-zoomed video again._

This is how it normally looks:
![screenshot from 2017-05-01 10 14 23](https://cloud.githubusercontent.com/assets/2543808/25575415/7ff556d4-2e57-11e7-9d06-523f8a872d6a.png)
(notice that there is also a bit missing on the top and bottom, the black&whit border is on all 4 sides of the image, but that might be due to the aspect ration and is in my opinion neglectable since not to much area is lost with this)

This is How it looks when the Zoom-thing happens:
![screenshot from 2017-05-01 10 12 07](https://cloud.githubusercontent.com/assets/2543808/25575475/197e0792-2e58-11e7-94fd-86c92bf022c4.png)

As I'm using Jitsi-Meet with OBS to do presentations, screensharing and combined multi-cam things via the video-feed, it's annoying not being able to relay on the full area of the video I stream. Frame-drops or varying resolution wouldn't be that much of a issue.

**Comment by saghul** [comment]
Interesting.  I'm afraid that might be some Chrome shenanigans... have you tried Firefox? (both as the sender and / or the receiver)

**Comment by m0se** [comment]
I haven't tried FF only yet. On the receiving side I always had at least one Chrome when it happend, but when it happens all clients receiving the video-stream are affected by this (FF and Chrome).
On the sending side I only use FF, since I don't get the v4l2dummy video capturing device to work in Chromium. So it looks like something Chrome-receiver requests and FF-sender does, from what I can tell.
I'll try it with FF-only on the next occasion and report back here.

**Comment by kevincolten** [comment]
Mine is corrected by enabling the `Override software rendering list` flag in chrome://flags/

**Comment by daytonturner** [comment]
@m0se I'm experiencing the same thing, and it appears to be bandwidth throttling when it really shouldn't be.  Feel like I'm missing something - perfectly fast connections are "zooming" and going down to 320/180 resolution.  Any other ideas on this?

Also, how are you using OBS with Jitsi?  Jitsi screen capture + running OBS in a full screen view mode, or are you able to feed video output directly from OBS to Jitsi somehow?

**Comment by m0se** [comment]
@daytonturner Sorry, I haven't looked into it any more.

As for the OBS thing,.. I'm not sure what platform your on, my solution probably only works for Linux. I basically created a "dummy video device" with v4l-loopback kernel module which is presented to the browser like a regular webcam. OBS then streams Video via ffmpeg to the dummy video device.

Here in case you are on Linux:
```
# initialize dummy ddevice
sudo modprobe v4l2loopback video_nr=1 exclusive_caps=1

# start ffmpeg to receive stream from OBS and send it to /dev/video1 (aka the fake webcam)
ffmpeg -i tcp://127.0.0.1:2000?listen -f v4l2 /dev/video1
```
..and the following settings in OBS:
![screenshot from 2017-09-18 17-15-01](https://user-images.githubusercontent.com/2543808/30549518-3d58e870-9c95-11e7-8aca-d7b5316e6b64.png)
