### ISSUE TITLE
Calendar integration broken

### ISSUE THREAD

**Issue by ligi** [jitsi/jitsi-meet#12082]
When using the calendar integration I am getting this error:
 
> You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide 6](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information.

seems the calendar integration needs to be migrated to this new method.
others seem to also have this problem: https://community.jitsi.org/t/integration-google-calendar-on-self-hosted-jitsi-server/27471/35

**Comment by saghul** [comment]
Thanks for the report! This is not an area of the code that gets a lot of love, any help here would be welcome.

**Comment by kb-0311** [comment]
> Thanks for the report! This is not an area of the code that gets a lot of love, any help here would be welcome.

Seems the problem here is that we are directing using the google API as a script tag here-

https://github.com/jitsi/jitsi-meet/blob/b4f98e7386e75bea52fa4b31c0f109d07621a7ee/react/features/google-api/googleApi.web.js#L9

And consuming it as a script src on load here-

https://github.com/jitsi/jitsi-meet/blob/b4f98e7386e75bea52fa4b31c0f109d07621a7ee/react/features/google-api/googleApi.web.js#L131

This is a deprecated package OP is talking about. Seems like for authentication we will need to migrate it to the new [GOOGLE Identity library api.](https://developers.google.com/identity/oauth2/web/guides/overview)

Do we need to change the Client URL to https://developers.google.com/identity/gsi/web/guides/client-library

What is your opinion on this?

**Comment by saghul** [comment]
I don't have an opinion :-) If it's deprecated and we need to migrate then that's what needs to be done.

There are likely more changes necessary to accommodate the new API.

Any help in the form of PRs would be very welcome.

**Comment by damencho** [comment]
This had been fixed.
https://github.com/jitsi/jitsi-meet/commit/39991da2cf6feea0617a9dc1e62eff1b3b607e41
