### ISSUE TITLE
Javascript potential problem/black screen

### ISSUE THREAD

**Issue by hbarnard** [jitsi/jitsi-meet#1215]
I've done a quick setup (actually 3 times) for jitsi-meet on Ubuntu 64bit AWS. The logs are looking good and I can use curl to get the bosh connection. I'm not using Apache or Nginx.

I've opened every TCP and UDP port towards my own IP only. 

However, I'm getting a black screen from Firefox and Chrome on a Linux desktop. I've switched on Firebug and lots of javascript is coming across, so it's 'nearly' there. However I did notice this:
`ReferenceError: loggingConfig is not defined	 app.bun...?v=1575 (line 74, col 11967)`
I'm not sure whether this is a big deal, but thought I'd signal it anyway?

Any other suggestions welcome for the black screen, of course. I've read through most of the existing material about this! Thanks for all the work, too.

**Comment by damencho** [comment]
Please when you have question or problems, discuss them on the mailinglist before opening issues.

There is a bug in latest stable jitsi-meet-web-config when configuring jetty to serve jitsi-meet, it is fixed in nightlies. There is a workaround though: http://lists.jitsi.org/pipermail/dev/2016-December/030655.html
