### ISSUE TITLE
When start screen share with chrome tab and share tab audio, audio button will open

### ISSUE THREAD

**Issue by cgri1** [jitsi/jitsi-meet#12618]
### Description:

When start screen share with chrome tab and share tab audio, audio button will open

### Steps to reproduce:

1 - Participant starts screen share with chrome tab
2 - And share tab audio is selected
3 - Participant microphone off
4 - Other participant see participant's audio button who share screen is open on thumbnail. But no sounds. 

<img width="1715" alt="Screen Shot 2022-11-25 at 10 54 28" src="https://user-images.githubusercontent.com/39028198/203931330-ea2400fb-8a8f-44df-984c-c563363dc89e.png">

<img width="1728" alt="Screen Shot 2022-11-25 at 10 54 35" src="https://user-images.githubusercontent.com/39028198/203931350-22b20a5c-7b84-419c-9f6f-bc10d5f1df8c.png">

### Expected behavior:

Audio Button on thumbnail will not open.

### Actual behavior:

Audio Button on thumbnail will open.

### Server information:

- Jitsi Meet version: 8044
- Operating System: MacOS

### Client information:

- Browser / app version: Chrome
- Operating System: 107.0.5304.87

**Comment by saghul** [comment]
This does not happen when you're unmuted, right?

Ping @andrei-gavrilescu @jallamsetty1

**Comment by cgri1** [comment]
Yes @saghul

**Comment by SatyarajRana** [comment]
@cgri1 , Can you please elaborate the issue??

**Comment by keremkaradenzz** [comment]
@saghul  this error  continues.

**Comment by cgri1** [comment]
@SatyarajRan

1- Moderator creates a room.
2- Start Screen Share on Chrome tab with share tab audio.
3- Participants join room.
4- Participants see that moderator's audio is opened but moderator did not open his audio.

Note: Participants do not hear any sounds from moderator. Just a visual problem.

**Comment by jallamsetty1** [comment]
@cgri1, I am not able to reproduce this issue on meet.jit.si.

**Comment by keremkaradenzz** [comment]
`<iframe src="https://www.veed.io/embed/e11e14cf-ca78-4f86-a9f0-2fe96b94a591" width="744" height="504" frameborder="0" title="jitsi-chrome-tab-error.mov" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

**Comment by keremkaradenzz** [comment]
@jallamsetty1  hello 
i got a video recording ;
video link : 
[https://www.veed.io/view/e11e14cf-ca78-4f86-a9f0-2fe96b94a591?panel=share 
](url)

**Comment by jallamsetty1** [comment]
@keremkaradenzz Thanks for the video, the issue reproduces only when a desktop source with an audio track is selected. I will work on fixing the issue.

**Comment by jallamsetty1** [comment]
@cgri1 @keremkaradenzz It appears that this is happening by design since currently we do not show mic mute state on the screenshare thumbnail. 

When an audio stream (from the share) is added locally on the sender, it causes an audio source to be signaled to all the other participants in the call and since we do not have a separate mic icon on the screenshare thumbnail, the sender's video thumbnail's mic icon shows as unmuted. In order to fix this, we would have to add the mic icon on the screenshare thumbnail  and show that as unmuted instead. Since, fixing this is not high on our priority list right now, we may not be able to get to it soon.

However, we will accept a PR that introduces this change in the current behavior. Please let us know if you need any guidance in this regard, happy to help. Thanks!

**Comment by gizembg** [comment]
This issue continues with the current version. Is there any fix yet? Thanks!

**Comment by saghul** [comment]
No, and by the looks of it we have no plans to make one though PRs are welcome.
