### ISSUE TITLE
Whiteboard Images

### ISSUE THREAD

**Issue by ToThePeterCopter** [jitsi/jitsi-meet#12675]
Add ability to upload images to whiteboard.

**Comment by saghul** [comment]
We are currently not able to do this because Excalidraw seems to only support Firebase for that, and we are not keen on using it.

**Comment by fv-chrisc** [comment]
I think this would still be a very useful feature. I found this article https://medium.com/@alswl/self-hosted-online-collaborative-drawing-platform-excalidraw-a9bcda614186 which point to a [repo](https://github.com/alswl/excalidraw) with changes related to self hosted storage.

I was able to enable the shared whiteboard, but I can't see where the Excalidraw code fits in the process. How would one go with using a fork of Excalidraw instead of the official release?

**Comment by mfuezesi** [comment]
Oh, this would really be nice!
