### ISSUE TITLE
Add support for Hermes JS engine

### ISSUE THREAD

**Issue by chema0** [jitsi/jitsi-meet#12748]
**Is your feature request related to a problem you are facing?**
Yes, my team can't enable hermes as JS engine in our React Native application due to Jitsi SDK limitations. Jitsi adopted hermes in version 2.6.0 and left it again in version 2.10.0, since then is not possible to support Hermes if Jitsi SDK is used.

**Describe the solution you'd like**
I'd like Jitsi Meet SDK to use Hermes as JS engine. Hermes is now the default engine for all React Native apps (due to improvements) starting at React Native 0.70.0, this fact is even more important now that new RN architecture in near .

**Describe alternatives you've considered**
None.

I am sure that Jitsi's team is making his best effort but I know this topic has been discussed in the past. I'd like to know if there is an estimated ETA for this change.

Thanks.

**Comment by saghul** [comment]
Hi there!

We currently have no ETA for this. We are on 0.68 at the moment, which has been very stable for us. We will update but have no ETA for that.

The native SDKs are not meant to be embedded in RN apps since our SDKs are using RN themselves. We have a RN SDK almost ready, which would allow you to pick the engine you want, since it'll be "just another RN dependency". You can track the progress here: https://github.com/jitsi/jitsi-meet/pull/11959

**Comment by chema0** [comment]
I understand. We've been using it thanks to Android Native Modules in order to integrate with RN App. 

We're looking forward to check the new RN SDK, thanks!

**Comment by tamdvyounetgroup** [comment]
I can help you.
