### ISSUE TITLE
[Bug] Jitsi Meet goes fullscreen, hiding system controls! (Android 10)

### ISSUE THREAD

**Issue by esrat** [jitsi/jitsi-meet#12789]
### Description:

When you enter a meeting in normal mode (no "low bandwidth mode"!) the app sets its display to fullscreen, hiding the system buttons for Back, Home and App-Switching completely - without any visible user controls to leave this mode!

### Steps to reproduce:

1. Enter any conference room with the normal blue button; doesn't matter if in landscape or portrait mode

### Expected behavior:

Expected would be the behavior seen in "low bandwidth mode".
This mode does preserve the system's buttons. The user can use their device normally while attending a meeting.

In general:
The app should not switch to fullscreen mode without user consent! - If the user explicitly chooses so, e.g. by tapping on some icon they should be able to switch back by tapping on the same option again.

### Actual behavior:

After completing the loading process, the app is hiding the system buttons, rendering a normal user "helpless" - only option to leave this mode seams to be leaving the meeting!

### Client information:

Jitsi Meet from F-Droid, version 22.7.1, on Android 10

### Additional information:

There are two known workarounds which are both "invisible" to any unknowing user:
1. Swiping down to open the notification area also displays the system's buttons above the Jitsi app.
2. Using the little "hook" in the upper left corner is closing the main app window, replacing it with a picture-in-picture one which then can be closed to be able to use other apps in the foreground without leaving the meeting.

None of these could be called a valid way to navigate the device for users who are used to the three-buttons-navigation since many generations of the Android operation system.

**Comment by saghul** [comment]
This is by design.

We use immersive mode, in order to use as much available real state in the screen to render video. This is its intended usage, along with things like gaming: https://developer.android.com/develop/ui/views/layout/immersive

When immersive mode is activated for the first time a system animation shows how you can bring back the navigation bar (swiping up from the bottom edge).

**Comment by esrat** [comment]
I do not really know what you are referring to. When I think of Jitsi, I do not think of a video player or an immersive game but of a background task which helps us to speak to friends and colleagues.
Normally I am on a desktop system in a browser. That way, the Jitsi-tab will be mostly in the background unless I am watching someone's shared screen.
My intended use on the Tablet PC is the same.

Thanks for the hint of the swiping-up-gesture. (I am mostly on older Android versions or virtual machines where I do not have this issue.)
I am sure that I was never told to do so. (I just did a factory reset the day before yesterday, some hours before I had this terrible audio experience I wrote about within the other issue. So I am really sure!)
This gesture blends the system buttons transparently above the Jitsi buttons, resulting in a display which shows all the buttons in 50 % gray. This seems suboptimal to me. But at least it works.

Have you looked at other great apps like the VLC for Android?
The Jitsi app is the only one I know of (not playing games on Android) which "steals" the system buttons. I've never seen the VLC (or NewPipe or others) doing this, even so it is playing in fullscreen. Just touching the screen displays their own UI, including the system buttons.

Your link is really good. - Did you read this resource yourself?
It states "However, be mindful of how often users jump in and out of apps to check notifications, to conduct impromptu searches, or to take other actions. Because immersive mode causes users to lose easy access to system navigation, use immersive mode only when the benefit to the user experience goes beyond simply using extra screen space.".
So I do not even have to argue with my big screen space (black bars if someone shares a Full-HD-screen). Your own source seems to suggest that you might have made the wrong design decision.

In my opinion the user should have the choice.
Your resource is even showing how to configure "a button to hide and show the system bars".

**Comment by saghul** [comment]
> I do not really know what you are referring to. When I think of Jitsi, I do not think of a video player or an immersive game but of a background task which helps us to speak to friends and colleagues.
> Normally I am on a desktop system in a browser. That way, the Jitsi-tab will be mostly in the background unless I am watching someone's shared screen.
> My intended use on the Tablet PC is the same.

Why do you think you represent the majority of people using Jitsi?

Jitsi Meet is a **video** conferencing application. User attention is by design. The audio-only case is for those who opt for it for whatever reason, but it's not the main use case our users use.

> Thanks for the hint of the swiping-up-gesture. (I am mostly on older Android versions or virtual machines where I do not have this issue.)
> I am sure that I was never told to do so.

It's Android who tells you, not the app. It might do so the first time the mdoe is used regardless of the app, I don't know.

> Have you looked at other great apps like the VLC for Android?
> The Jitsi app is the only one I know of (not playing games on Android) which "steals" the system buttons. I've never seen the VLC (or NewPipe or others) doing this, even so it is playing in fullscreen. Just touching the screen displays their own UI, including the system buttons.

A video player is not a good comparison. A video calling app is. But even then, this is an Android feature which perfectly matches our use case and we just opt to use it. Showing those controls on tap would make the UI "jump" since the toolbar and filmstrip are at the bottom. That is not great UX.



> Your link is really good. - Did you read this resource yourself?
> It states "However, be mindful of how often users jump in and out of apps to check notifications, to conduct impromptu searches, or to take other actions. Because immersive mode causes users to lose easy access to system navigation, use immersive mode only when the benefit to the user experience goes beyond simply using extra screen space.".
> So I do not even have to argue with my big screen space (black bars if someone shares a Full-HD-screen). Your own source seems to suggest that you might have made the wrong design decision.

That is of course subject to interpretation.

We are not adding an option, sorry.

**Comment by s-tefan** [comment]
Recently, the behaviour of the Android app on my device (Samsung Galaxy s24) has changed so that no control buttons show up in landscape mode, and there is no swipe action that brings them up. That means, for example, that I can't change camera, or switch to panel mode in landscape. I hope that this is a bug and not by design, because that is no good UI in any way in my book.

**Comment by saghul** [comment]
That's odd. They should show up when you tap on the screen.

**Comment by s-tefan** [comment]
> That's odd. They should show up when you tap on the screen.

Nothing happens when I tap or swipe the screen. I've got a black band at the bottom, though. I tried reinstalling the jitsi app, no difference noticed.

Works fine in portrait view, Also works as expected in browser (Chrome)
Another thing that does not work in the app now, but as far as I remember worked earlier: I can't se my own camera view in panel view mode.

[Samsung Galaxy S24, Android  16, One UI 8.0]
