### ISSUE TITLE
Headphone sounds increasing when joining jitsi meet

### ISSUE THREAD

**Issue by cgri1** [jitsi/jitsi-meet#13273]
### Description:

Headphone sounds increasing when joining jitsi meet

### Steps to reproduce:

1. Open some youtube videos with headphones.
2. Keep playing youtube videos
3. At the same time join the jitsi meet.
4. And sound which comes headphones increasing, so uncomfortable.

### Expected behavior:

Sound level should not change.

### Actual behavior:

Sound increasing.

### Server information:

- Jitsi Meet version: latest
- Operating System:

### Client information:

- Browser / app version: Chrome
- Operating System:

**Comment by saghul** [comment]
Are your headphones Bluetooth?

**Comment by cgri1** [comment]
Yes @saghul

**Comment by saghul** [comment]
Then this is caused by the the switch of Bluetooth profiles.

When you are listening to musing BT can use all the available bandwidth for the music, but when you join a meeting and enable the microphone the headset will switch to HFP (Hands Free Protocol) and split the bandwidth so the microphone data can also be transmitted.

Since it's a different audio profile the volume might change. There nothing specific we do regarding volume nor there is anything we can do about it.

**Comment by cgri1** [comment]
Thank you for your answer 👍
