### ISSUE TITLE
When do translation file changes take effect?

### ISSUE THREAD

**Issue by rasos** [jitsi/jitsi-meet#1358]
We have slightly modified the language files /usr/share/jitsi-meet/lang/main-de.json and main.json  
However, we can't see the changes, not even when restaring jitsi-videobridge . Seems to be caching somewhere - any hint?

And how do we embed a static link with URL in the json file correctly? 

In fact what we try is when users want to install the desktop sharing extension and get a "Permission denied" (happening on Windows 7 or Xubuntu), then we would like to give them advice how to install it manually.

**Comment by saghul** [comment]
> We have slightly modified the language files /usr/share/jitsi-meet/lang/main-de.json and main.json
> However, we can't see the changes, not even when restaring jitsi-videobridge . Seems to be caching somewhere - any hint?

That's weird. Do you see your browser fetching the file? (use developer tools to check)

**Comment by damencho** [comment]
We used to embed english inside the appbundle, but I see this is no longer the case. We have seen some problems with translations and I think we need to update that and return embedding english.
@rasos depends on your version, cause we had updated recently i18n because of react. but definitely DE should be downloaded from the server.

**Comment by damencho** [comment]
Hum, I just saw it should be still embedded.
