### ISSUE TITLE
Can no longer start a meeting without logging in via Google, Facebook, Microsoft

### ISSUE THREAD

**Issue by exercismnow** [jitsi/jitsi-meet#13753]
### Description:

Previously, you could start a meeting at https://meet.jit.si without entering any sort of credentials. This made Jitsi extremely convenient to use, and also good for privacy, as you didn't have to provide credentials that were associated with your Personally Identifying Information.

Now, when you start a new meeting, you get this message when attempting to join the meeting:
> Waiting for a moderator...
> The conference has not yet started because no moderators have yet arrived. If you'd like to become a moderator please log-in. Otherwise, please wait.

Clicking "Wait for moderator" will result in you waiting forever, and clicking "Log-in" gives you the choice to login through one of the following:
- Google
- Facebook
- GitHub

This is inconvenient, and also bad for privacy, as Google, Facebook, and Microsoft require PII to open an account.

### Steps to reproduce:

1.  Visit https://meet.jit.si
2.  Enter a meeting name and click "Start meeting"
3.  Enter your display name and click "Join meeting"
4. Observe that you no longer join the meeting directly, and must instead log-in via a privacy-violating account.

### Expected behavior:

Users should be able to start a meeting without credentials, like before.

### Actual behavior:

Users can no longer start a meeting without credentials, and are required to Log-in via privacy-violating Google, Facebook, or Microsoft accounts.

### Server information:
https://meet.jit.si
- Jitsi Meet version: 
- Operating System: 

### Client information:

- Browser / app version: Firefox
- Operating System: All

**Comment by AbdouEsi** [comment]
Yes, you are right. We want it to return as it was or find a solution

**Comment by AbdouEsi** [comment]
https://jitsi.org/blog/authentication-on-meet-jit-si/

**Comment by geokala** [comment]
Agreed, the range of options are pretty much a who's who of "Which companies should you try to avoid using if you care about privacy". If there absolutely has to be authentication (rather than, say, allowing setting a password for a given meeting alone), I'd prefer if it were siloed to just jitsi, not to some external provider that will happily sell any and all information they can.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

You can always [self-host](https://jitsi.org/qi) a deployment, the installing it by default does not have any authentication.

**Comment by Vectornaut** [comment]
Having no warning of this change was really frustrating for me. When I tried to open the Jitsi room for my Friday meetings, I spent several minutes trying to figure out what was going on before giving up and switching to another meeting platform. This is the second time I've been unable to hold a meeting on meet.jit.si because an update suddenly broke a key feature.

**Comment by monstro1** [comment]
please fix

**Comment by trekjaziyah** [comment]
"Offering the possibility to anonymously use the service felt like a good way to help with both its privacy and the usability...

Earlier this year we saw an increase in the number of reports we received about some people using our service in ways that we cannot tolerate. To be more clear, this was not about some people merely saying things that others disliked."

Authentication on meet.jit.si
https://jitsi.org/blog/authentication-on-meet-jit-si/

What an absolutely arrogant BS reason. What exactly can you 'not tolerate', and who cares if you cannot tolerate it. Even if people are doing illegal things, unless 8x8 gets a specific demand from authorities to take action  (track or block an IP, etc), it should not be acting to decide what is or is not appropriate behaviour.

You have effectively killed the 'privacy and the usability' of the platform.

Guess the only thing left is to start a discussion about alternatives to jitsi, which used to be the alternative to zoom for those who cares about privacy and usability.

Bye, jitsi.

(Sent using a disposable email through TOR)

**Comment by saghul** [comment]
Read the full article please. The change only applies to meet.jit.si not to any other deployment. If you self-host you can do auth whichever way you want.

**Comment by trekjaziyah** [comment]
Suggesting that self-hosting jitsi is an alternative to meet.jit.si is ridiculous. For starters, it completely obviates the reason people used meet.jit.si in the first instance, which 8x8 acknowledges in its BS post, namely 'usability and privacy'. Setting up a self-hosted instance is not trivial, and requires sgn-up for and use of other hosted services (domain registrar, ISP, shared server, etc) which are not private.

Anyhow, there is another post on github regarding 'User- and/or community-run jit.si instances by region'. These are not without inherent risks, namely not knowing what if anything these users and/or communities are tracking or logging when using their servers.

You really screwed the pooch, 8x8. No one will trust you going forward, so good luck with the commercial offering.

**Comment by saghul** [comment]
I won't try to convince you, if that's what you think, you do you.

I do think reactions like this miss to read between the lines, and fail to see that you still (and always) will have a way to run Jitsi Meet to suit your needs.

**Comment by trekjaziyah** [comment]
That is what everyone thinks, apologist simp, hence the down-votes.

As others have noted, not having to sign in with an email was the primary reason people who were aware of jitsi used it instead of zoom.

Saying 'read between the lines' and 'always have a way to run Jitsi Meet to suit your needs' without elaborating, especially after it was clearly explained exactly why self-hosting does not meet most users' needs, is just more BS.

**Comment by saghul** [comment]
One more personal insult and you are banned from this org. Plain and simple.

**Comment by trekjaziyah** [comment]
Thanks for underscoring that you have nothing useful or substantive to add. Not sure why you bothered with those nonsensical replies.

**Comment by monstro1** [comment]
every time I log in via gmail it changes my name, and every time someone joins a call it changes my name. please make it stop doing that

me using jitsi and being forced to relinquish personal information:

https://github.com/jitsi/jitsi-meet/assets/67171463/12a2d8b2-dc03-4337-813f-8a60add07cae

**Comment by damencho** [comment]
You can change the name of your account, this is what it uses.

**Comment by monstro1** [comment]
> You can change the name of your account, this is what it uses.

I want to set my names for gmail and jitsi separately

**Comment by damencho** [comment]
there is no such option at the moment.

**Comment by monstro1** [comment]
ayúdame por favor

**Comment by JakeQZ** [comment]
> privacy-violating Google, Facebook, or Microsoft accounts.

This is the real issue.  Why is there no option to create an account with Jitsi?

I fail to see how requiring someone's GAFAM credentials will solve the [problem](https://jitsi.org/blog/authentication-on-meet-jit-si/), whatever it is.  More explanation on how this will help is required.

How do you plan to sanction people based on GAFAM login details, given that those companies will not supply you with any more information than you already have (i.e. just an email address).  The police will not act either.

You don't state what the problem is that you are trying to solve (other than violations of the TOS).  We could speculate.  But it would be better if you told us, so we don't have to.  Transparency is key, but you have been totally obfuscatingly opaque.

> One more personal insult and you are banned from this org. Plain and simple.

What?!

Fork it.  This is a mismanaged disaster.

**Comment by saghul** [comment]
We HAD TO add auth, that's why we're here.

Yes, we knew it was going to resonate badly with many but there was no choice for us.

It's not possible to get into the details, you'll have you read between the lines and imagine why that would be.

Having a civil discussion here is more than welcome though as I've said we can't talk many details.

What is not welcome and will result in a ban is to attack others with personal insults.

**Comment by geokala** [comment]
@saghul The biggest problem with it from my POV is requiring that auth to link back to a set of data-hungry large corporations rather than having something more siloed.

In any case, there seems little point trying to discuss it here given this was immediately closed telling people that they should've discussed it on community forums first (despite that not appearing (prominently? at all?) in the issue templates on here).

**Comment by saghul** [comment]
We feed no data at all to the auth provider.

We get back an authentication token and modified our own auth mechanism so no extra data is necessary.

Basically, a user logs in with an auth provider, we get a token and load the meeting with it.

There is currently a pinned topic in the News section of our community.

**Comment by saghul** [comment]
Fair point.

I just wanted to make clear how we use the auth.

**Comment by snj33v** [comment]
can we have passwordless support like WebAuthn. its a best compromise

**Comment by edmunddontavius** [comment]
That people are being banned for legitimate criticism and pointing out the absurdity of the continued refusal to directly address it speaks volumes to the type of people involved with this project. No one should trust any developers that cannot directly explain the rationale for requiring authentication through the most privacy-invasive services while simultaneously claiming to protect user privacy.

Those who care about privacy should move on to another platform, perhaps try a community-hosted instance. Those who do not can use the more stable zoom platform, since now there is effectively no difference in terms of privacy protection with jitsi.

EDIT: It appears that not only are they banning criticism, they are apparently deleting critical comments. Again, this speaks volumes to the type of people involved with this project.

**Comment by saghul** [comment]
A user which didn't want to engage in civil discourse was banned, yes. It's not the criticism that got the banned but the insults to myself personally.

I'll repeat it one last time, and lock the issue since we are going in circles here: what the blog post said the degree of detail we are able to discuss.

If that means you are no longer able to use meet.jit.si, that's unfortunate. You are still able to use any other suitable instance out there or better yet, self-host it.
