### ISSUE TITLE
Firefox blurry vp9 video

### ISSUE THREAD

**Issue by javierckr** [jitsi/jitsi-meet#13864]
### Description:

In a meeting with google chrome and Firefox browsers, if chrome sends video in vp9, the  Firefox browsers only watch a blurry video with some artifacts while the chrome browsers watch it as expected. It could be a FF issue with vp9 decoding, but this is not happening on YouTube vp9. #10657

### Steps to reproduce:

We reproduce every time  that a browser is using vp9

### Actual behavior:

Firefox:

![](https://user-images.githubusercontent.com/42911254/269661456-a89bcb80-fb66-4599-b41e-73bf162524f2.png)
![](https://user-images.githubusercontent.com/42911254/269661718-b52f2d2f-f1ce-4391-8506-3572bc4e0f29.png)

Chrome:

![](https://user-images.githubusercontent.com/42911254/269662672-3344f691-ad32-4eda-a467-80fdd754dbb0.png)

### Server information:

- Jitsi Meet version:  public meet.jit.si, and latest jitsi meet release, but it was in previous versions of jitsi, when you use enforce preferred codec vp9

### Client information:

- Browser / app version: Firefox 117, 118 ...
- Operating System: Ubuntu

**Comment by saghul** [comment]
Do you observe the same behavior when the feed is a camera and not a screen share?

**Comment by javierckr** [comment]
That feed is the camera, recording a virtual blackboard.
But there are problems with screen share too #13860

**Comment by javierckr** [comment]
I think this is the same issue: https://community.jitsi.org/t/very-poor-video-quality/127013/6

**Comment by kkarhan** [comment]
This issue seems to be commonplace across browsers, espechally when screensharing high resolution video with tiny text.

This resulted in one project that I can't name (for legal reasons) having to use Cisco WebEx to screenshare IDE sessions...
 
Possible Ideas on how to tackle the issue:
 
- Ideally a screenshare would begin with like a high-resolution, (ideally nearly-uncompressed PNG) screenshot of the shared screen/window. 
Tho that would only improve things at the start.
 
- Another option would be to increase the amount of "golden frames" at the encoder for screensharing as a setting.
This will consume more bandwith unless the screen has few colours and a lot of equal-coloured space that can be compressed intra-frame.

Either way, it would be good if the "mushy video" could be fixed - maybe at the cost of having some settings selectable at the user side.
Cuz H.264 alone can't be the reason why 720p24 looks sharper in WebEx than VP9 2160p60 in Jitsi Meet when given basically unlimited bandwith.

**Comment by kkarhan** [comment]
And yes, that issue seems to also exist in Chromium / Google Chrome: fine details get mushed unreadably to the point that I'd rather want to use Dayon!...

**Comment by fippo** [comment]
This means Firefox is unable to decode VP9 SVC? Taggng @JonathanLennox @jallamsetty1
