### ISSUE TITLE
share youtube video in a class, sound delayed

### ISSUE THREAD

**Issue by atuctuc** [jitsi/jitsi-meet#13868]
hallo. 

i use jitsi in class at school and would like to watch a video together in class without the need for a central beamer projection. i transmit the sound via a stereo system. 

unfortunately, the video of the students to the common sound is always delayed by about a second, it should be possible that, if all in class play the video from the cache, the start and stop should work almost time-synchronous. 

unfortunately this does not work, could this be improved?
best, anan

**Comment by saghul** [comment]
I don't think it can, alas.

The way the feature works is that each participant will open the video themselves and seek to the same position.

The idea is that everyone watches the same video roughly at the same time, but not to the second, since there are delays in the signalling and also opening the YouTube iframe.
