### ISSUE TITLE
12 factor - use env variables to configure hostname

### ISSUE THREAD

**Issue by pierreozoux** [jitsi/jitsi-meet#1398]
Modern web app - [12 factor](https://12factor.net/) web app understand env variables, it makes it a lot easier to run them.

It would ease the configuration of this part:
https://github.com/jitsi/jitsi-meet/blob/master/config.js#L6-L18

It would be really nice if jitsi meet would understand env variables to configure these.

**Comment by saghul** [comment]
config.js gets loaded by the web application / browser. How would environment variables be read there?

**Comment by pierreozoux** [comment]
Did you read 12factor? I think it is a really good read, and really important piece to understand how to build beautiful web application that are easy to maintain and scale.

To give a bit of context, I'm working on #1388, and docker is just an implementation of 12factor.

For the web application, it is easy, the node process can read easily from the env.
(Is the web application using it, or is it just the frontend?)
For the browser, I don't know what are the best practices to configure a frontend application, but one way I could imagine right now is the following:
 - one server route: /config.js
 - this would get rendered by node with the env variables
 - the application would be happy with the configuration

Or there is an other way:
 - domain is read at run time in js
 - other variables are conventions based on the domain:
  - muc: 'conference.' + domain
  - focus: 'focus.' + domain

Maybe the second approach is a lot easier.
If you like the idea, I can PR :)

**Comment by saghul** [comment]
@pierreozoux I see where you come from, but that won't work with the current way of deploying jitsi-meet. There is no Node involved other than for building the application, the resulting site is to be served by Apache or Nginx. 

If you look at how our template configs are like, we serve config.js explicitly, because it's usually called /etc/jitsi/meet/your-domain.js

I don't think I understand how you can achieve that with the setup I described above, but I'll definitely take a look at a PR and it might be easier to have a discussion that way. The rule of thumb is: don't assume the web is running on Node.
