### ISSUE TITLE
Force mute participants

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#14]
Add the possibility for the focus to force mute, kick and ban participants (i.e. without giving them the technical option of disobeying).

This would also mean placing their Jitsi Videobridge channel on hold, etc.

It would also mean that we would need to first finish #16

**Comment by paweldomas** [comment]
Force muting is implemented in Jicofo. Audio channel of muted participant is switched to recv only mode.

**Comment by paulvt** [comment]
IMO the scope of the original issue by @emcho was much broader than just switching a participant's audio channel to receive-only mode.  I see that in the current Jitsi-Meet version (1.0.760) I can mute someone as moderator, but this person can unmute himself/herself at will.  (The moderator can then not unmute, which does make sense because this person can have a private converstation.)  In a sense there are two forms of muting: local muting (i.e. a personal choice of not sending audio at all) or moderated forced mute, which means blocking the stream at the bridge.

Besides this, a more permanent form of kicking/banning seems not to be dealt with yet.

**Comment by SamsungGalaxyPlayer** [comment]
I concur. My projects could absolutely benefit from the ability to force mute participants. I would like the ability to force mute all users unless I explicitly grant the permission to speak. I would also like the ability to revoke this permission. This is important for open-source community discussion calls.

**Comment by FaizanZahid** [comment]
As a moderator i can mute people, but they can unmute themselves. This moderation feature is useless, because spammers who want to spam can keep unmuting.
Is there any way to force mute the participant or permanently ban a user from joining a meeting?

**Comment by rykel** [comment]
I am trying to switch over to Jitsi Meet from Zoom and GotoWebinar, and I found precisely these 2 anomalies... people can unmute themselves and rejoin a chat. I feel that they should NOT be allowed to do so, if a moderator has already muted them or kicked them out! While, granted, these 2 issues will not pose a problem when chatting among friends, but they will botch up an otherwise perfect conference with 100 pax. Please help? (13 April 2020)
