### ISSUE TITLE
fresh ios build fails with missing RNBackgroundTimer library

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1400]
Hi all,

Just did a fresh git pull to see if the iOS app is finally working with a locked down (authentication needed) jitsi-meet install, and now Xcode fails to build and complains about missing RNBackgroundTimer library.

Where can I get this library?

Cheers

ld: library not found for -lRNBackgroundTimer
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by petervnv** [comment]
Forgot to add the link to my earlier bug report regarding authentication
http://lists.jitsi.org/pipermail/dev/2017-February/031513.html

**Comment by damencho** [comment]
Authentication is still not supported in the mobile app.

**Comment by saghul** [comment]
Did you get any errors when running npm install? That library is a dependency you should have got when installing all dependencies.

I did a fresh build this morning I didn't see this.

**Comment by petervnv** [comment]
Thanks for the update guys.
Indeed when I ran npm install again it seems that the library is now there.
I guess now we still have to wait to have authentication supported in the mobile app.

Should I open a new issue just for that?

Cheers

**Comment by saghul** [comment]
We're already tracking that IIRC. I'm glad you got it built!

-Saúl

On 17 Mar 2017, at 15:41, petervnv <notifications@github.com> wrote:

Thanks for the update guys.
Indeed when I ran npm install again it seems that the library is now there.
I guess now we still have to wait to have authentication supported in the
mobile app.

Should I open a new issue just for that?

Cheers

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jitsi/jitsi-meet/issues/1400#issuecomment-287372227>,
or mute the thread
