### ISSUE TITLE
Robotic Voice Problem in Windows 11 - Chrome 119

### ISSUE THREAD

**Issue by cgri1** [jitsi/jitsi-meet#14125]
### Description:

Participant joins a meeting. Noise suppression is default open. A participant opens their audio. And minimize the meeting in Chrome. And he/she opens another application like Excel, Outlook, etc. And then the participant's voice comes to robotics. 

### Steps to reproduce:

1. Participant joins a meeting.
2. Noise suppression is default open.
3. Participant open audio.
4. Minimize the browser (Chrome).
5. open another application (Excel, Outlook),
6. the participant's voice comes to robotics

### Server information:

- Jitsi Meet version: Latest version
- Operating System: Windows 11

### Client information:

- Browser / app version: Chrome 119.0.6045.199
- Operating System: Windows 11

### Additional information:

https://github.com/jitsi/jitsi-meet/assets/39028198/63cbd75f-18ad-495c-bf85-cf6714ed95db

**Comment by cgri1** [comment]
@saghul Do you have any comments on this issue? Can you reproduce it?

**Comment by saghul** [comment]
Sorry I don't quite have the environment to try to replicate it. Are you able to reproduce it if you disable the noise suppression setting?

**Comment by saghul** [comment]
@andrei-gavrilescu Ping. Are you aware of any issues if the browser gets backgrounded?

**Comment by cgri1** [comment]
We didn't come across it on macOS. But We always reproduce in Windows 11 on Chrome.

**Comment by cgri1** [comment]
Is there any progress on this problem? Can you reproduce this problem? @andrei-gavrilescu

**Comment by andrei-gavrilescu** [comment]
Hello @cgri1, I've managed to reproduce the scenario, while under heavy load this type of problem can occur (because we remove the noise from the audio via a AudioWorklet), this seems to happen with normal load as well.
After doing some digging it seems that windows 11 has this neat feature called 'Efficiency  mode' in which it limits resource usage for some processes, background processes such as a minimized chrome are affected by this.
We could try and further refine the way we do noise suppression, but considering the impact on CPU is already negligible with the current implementation it might not improve anything.
The obvious, easy workaround is to keep chrome maximized. However there is a way to tell chrome to not use 'Efficiency mode', simply open chrome with this additional flag '--disable-features=UseEcoQoSForBackgroundProcess'.
In order to do that on windows 11, simply:
- find the chrome shortcut
- right click it
- select 'Properties'
- in the 'Target' section add ' --disable-features=UseEcoQoSForBackgroundProcess' at the end (without the quotes). 
- reopen everything.

**Comment by saghul** [comment]
Great find @andrei-gavrilescu ! Can you see the compute pressure logs while doing the testing? What values were being reported?

**Comment by andrei-gavrilescu** [comment]
Compute logs oscillated between "fair" and "nominal" and there wasn't a compute log when windows enabled 'Efficiency mode' and the voice went robotic. It seems the pressure API doesn't pick that up.

**Comment by saghul** [comment]
Good to know, thanks for checking!

**Comment by gizembg** [comment]
I'm experiencing a similar issue with sound quality on the meetings. Here's what I've observed:

1. Noise Suppression ON + Browser Efficiency Mode ON: The voice becomes robotic.
2. Noise Suppression ON + Browser Efficiency Mode OFF: The voice sounds normal.
3. Noise Suppression OFF + Browser Efficiency Mode ON / OFF: The voice sounds normal.

Is there any fix or workaround for this issue?

Thanks in advance!

**Comment by saghul** [comment]
Alas there isn't because we cannot know if efficiency mode is enabled, so we cannot react to that.

**Comment by gizembg** [comment]
I did some further testing:

On Microsoft Edge with Efficiency Mode ON and using https://meet.jit.si/ with Noise Suppression ON, the voice was normal.
However, when I used my local app with a previous version of Jitsi on the same browser, I still heard the robotic voice.
I was under the impression that this issue was fixed in the newer version. Am I mistaken?

Thanks for your help!

**Comment by saghul** [comment]
I don't remember us fixing anything in this regard.
