### ISSUE TITLE
BroadcastEvent.Type.PARTICIPANT_LEFT Event is calling on stop screen sharing by menu option(Android/IOS) 

### ISSUE THREAD

**Issue by shubham7111999** [jitsi/jitsi-meet#14433]
Currently i am using the Jitsi version 8.6.1 in both IOS & Android . In Customized JitsiView when is start to share the screen its working fine but when i stop the screen share by menu option then BroadcastEvent.Type.PARTICIPANT_LEFT event is calling.
please suggest me how to resolve following issue.

please check following link we are using 8.6.1 version
https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md

Steps to reproduce issue:
1.Join two users in same room
2.Click on menu option start screen share
3.Click on menu option stop screen  share
then we are getting event PARTICIPANT_LEFT please suggest me how to resolve this.

**Comment by saghul** [comment]
@Calinteodor we should skip fake participants when emitting this event. Please add this to your list.

**Comment by shubham7111999** [comment]
I don't able to understand what is fake participants and what is can add in list or how ?

**Comment by mehtanitish875** [comment]
Basically I faced same issue in iOS but when I try to stop screen share between two persons then CONFERENCE_TERMINATED is triggered please support how to handle this.

**Comment by saghul** [comment]
> I don't able to understand what is fake participants and what is can add in list or how ?

A screen-share is displayed as a participant without actually being one, so we call those "fake" participants. It's an internal implementation detail which should not leak through the SDK boundary, hence my message.

**Comment by saghul** [comment]
> Basically I faced same issue in iOS but when I try to stop screen share between two persons then CONFERENCE_TERMINATED is triggered please support how to handle this.

I don't see how this is related.

**Comment by Vikrant2411** [comment]
@saghul ,
When I am in a group call and sharing screen then, stopped screen sharing, one of the participant got callback from Jitsi for the method Conference_terminated, because of which that participant got out of the call. Why I am getting the Conference_terminated. If it is for the dummy user you are adding while sharing the screen then how can I handle this.
Can you please help me for this?

**Comment by Vikrant2411** [comment]
No I am not calling any api on PARTICIPANT_LEFT.
I will explain you whole scenario here, 
I am adding three people into call one after other, now when I am sharing the screen from one of the user and then stopping the Screen share one of the other users on call are getting PARTICIPANT_LEFT and CONFERENCE_TERMINATED methods are getting called.
Now in  PARTICIPANT_LEFT method we have added a check if User count on Jitsi screen is more than 1 then we are reducing it by one on our side so, that we can manage the users on call are multiple or single user is there, if there's single user than we are removing that user as well from the call.

**Comment by saghul** [comment]
Can you please share the full logcat?

**Comment by Vikrant2411** [comment]
-[WCSession onqueue_handleUpdateSessionState:]_block_invoke dropping as pairingIDs no longer match. pairingID (null), client pairingID: (null)
WCSession is not paired
Using video encoder factory: RTCDefaultVideoEncoderFactory
Using video decoder factory: RTCDefaultVideoDecoderFactory
Running "App
[features/full-screen] Setting full-screen mode: false
[features/base/redux] redux state persisted. 99914b932bd37a50b983c5e7c90ae93b -> 5bdd0990dda624069fba2f514b6cfb5e
[features/base/sounds] PLAY_SOUND: no sound found for id: RECORDING_OFF_SOUND
[features/app] Disabling CallKit because this is a simulator
RCTStatusBarManager module requires that the                 UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
RCTStatusBarManager module requires that the                 UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO
[GESTURE HANDLER] Initialize gesture handler for view <RCTRootContentView: 0x104ded0c0; frame = (0 0; 0 0); gestureRecognizers = <NSArray: 0x600000e22310>; layer = <CALayer: 0x6000003b4580>> reactTag: 1; frame = {{0, 0}, {0, 0}}; layer = <CALayer: 0x6000003b4580>
[features/app] appNavigate to https://staging.realtimeaudio.com/97dac7b2-3b11-49be-8fea-9d7355623cd6#config.startAudioOnly=false&config.startWithVideoMuted=true&config.startWithAudioMuted=false
[features/base/connection] No connection found while disconnecting.
[features/app] Loaded SDK 9.0.0
[features/base/net-info] Network changed {"isOnline":false,"details":{"ipAddress":"192.168.0.43","subnet":"255.255.255.0","isConnectionExpensive":false},"networkType":"wifi"}
[modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: false }
[features/base/net-info] Network changed {"isOnline":false,"details":{"ipAddress":"192.168.0.43","subnet":"255.255.255.0","isConnectionExpensive":false},"networkType":"wifi"}
[modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: false }
[features/base/net-info] Network changed {"isOnline":false,"details":{"ipAddress":"192.168.0.43","subnet":"255.255.255.0","isConnectionExpensive":false},"networkType":"wifi"}
[modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: false }
[features/base/net-info] Network changed {"isOnline":true,"details":{"ipAddress":"192.168.0.43","subnet":"255.255.255.0","isConnectionExpensive":false},"networkType":"wifi"}
[modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
[features/base/lib-jitsi-meet] Config loaded from https://staging.realtimeaudio.com/config.js?room=97dac7b2-3b11-49be-8fea-9d7355623cd6
[features/base/config] Extending config with: {"startAudioOnly":false,"startWithAudioMuted":false,"startWithVideoMuted":true}
[JitsiMeetJS.ts] This appears to be react-native, ver: 0.72.9
[modules/statistics/statistics.js] Cannot initialize WatchRTC in a react native environment!
[JitsiMeetJS.ts] Analytics disabled, disposing.
[modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
[modules/RTC/RTCUtils.js] Disable AEC: false
[modules/RTC/RTCUtils.js] Disable NS: false
[modules/RTC/RTCUtils.js] Disable AP: false
[modules/RTC/RTCUtils.js] Disable AGC: false
[modules/RTC/RTCUtils.js] Stereo: false
[modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
[features/base/lib-jitsi-meet] lib-jitsi-meet version:639ad566
[modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
[features/base/media] Start muted: video
[features/base/media] Start audio only set to false
[features/base/connection] Using service URL wss://staging.realtimeaudio.com/realtimeuat/xmpp-websocket
[modules/xmpp/moderator.js] Using xmpp for conference requests.
[modules/xmpp/xmpp.js] P2P STUN servers:  [ { urls: 'stun:turn.avstack.net:443' } ]
[modules/xmpp/xmpp.js] Source-name signaling is enabled
[modules/xmpp/xmpp.js] Receiving multiple video streams is enabled
[modules/xmpp/xmpp.js] (TIME) Strophe connecting:	 3892624.139541
[modules/RTC/RTCUtils.js] Got media constraints:  {"video":false,"audio":{"autoGainControl":true,"echoCancellation":true,"noiseSuppression":true}}
[modules/RTC/RTCUtils.js] Available devices:  []
Thread Performance Checker: Thread running at User-interactive quality-of-service class waiting on a lower QoS thread running at Default quality-of-service class. Investigate ways to avoid priority inversions
PID: 6441, TID: 61246
Backtrace
=================================================================
3   JitsiMeetSDK                        0x00000001063b20d8 -[SRRunLoopThread runLoop] + 36
4   JitsiMeetSDK                        0x00000001063ae90c +[NSRunLoop(SRWebSocket) SR_networkRunLoop] + 40
5   JitsiMeetSDK                        0x00000001063b12f4 -[SRProxyConnect _openConnection] + 56
6   JitsiMeetSDK                        0x00000001063b0bf8 -[SRProxyConnect _configureProxy] + 468
7   JitsiMeetSDK                        0x00000001063b2f1c -[SRWebSocket open] + 296
8   JitsiMeetSDK                        0x000000010633bdd8 -[RCTWebSocketModule connect:protocols:options:socketID:] + 744
9   CoreFoundation                      0x0000000180497750 __invoking___ + 144
10  CoreFoundation                      0x0000000180494ab4 -[NSInvocation invoke] + 276
11  CoreFoundation                      0x0000000180494d4c -[NSInvocation invokeWithTarget:] + 60
12  JitsiMeetSDK                        0x00000001062f5550 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 388
13  JitsiMeetSDK                        0x00000001062f75f4 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 456
14  JitsiMeetSDK                        0x00000001062f7244 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 112
15  libdispatch.dylib                   0x000000010431c0f0 _dispatch_call_block_and_release + 24
16  libdispatch.dylib                   0x000000010431d93c _dispatch_client_callout + 16
17  libdispatch.dylib                   0x000000010432d5e4 _dispatch_main_queue_drain + 1228
18  libdispatch.dylib                   0x000000010432d108 _dispatch_main_queue_callback_4CF + 40
19  CoreFoundation                      0x00000001803f1a30 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
20  CoreFoundation                      0x00000001803ec148 __CFRunLoopRun + 1936
21  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
22  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
23  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
24  UIKitCore                           0x00000001852f3f5c UIApplicationMain + 124
25  CellularBackupContacts              0x0000000102826bb8 main + 64
[features/base/lastn] There is no active conference, not updating last N
[features/base/redux] redux state persisted. 5bdd0990dda624069fba2f514b6cfb5e -> 7760c72cd33282826edebe89a6a6d6f4
[modules/RTC/RTCUtils.js] onUserMediaSuccess
[modules/RTC/JitsiLocalTrack.js] Setting new MSID: 94b32d3d-ef58-2138-cce8-8a181498e60e 955E0001-2A80-46A3-8C77-B1386EBCB86A on LocalTrack[undefined,audio]
[features/base/lastn] There is no active conference, not updating last N
[modules/xmpp/XmppConnection.js] Enabling XEP-0198 stream management
[modules/xmpp/strophe.ping.js] XMPP pings will be sent every 10000 ms
[modules/xmpp/xmpp.js] (TIME) Strophe connected:	 3897122.787416
[modules/xmpp/xmpp.js] My Jabber ID: 07f3c8fa-09cc-43e9-98f2-64868bc826d6@realtimeuat.onavstack.net/40XsaYGV-2c0
[modules/RTC/CodecSelection.js] Codec preference order for jvb connection is vp9,vp8,h264
[modules/RTC/CodecSelection.js] Codec preference order for p2p connection is vp9,h264,vp8,av1
[modules/settings/Settings.js] generated stats id Jaylan-Txa
[modules/xmpp/xmpp.js] JID 07f3c8fa-09cc-43e9-98f2-64868bc826d6@realtimeuat.onavstack.net/40XsaYGV-2c0 using MUC nickname 07f3c8fa
[modules/statistics/AvgRTPStatsReporter.js] Avg RTP stats will be calculated every 15 samples
[JitsiConference.js] backToP2PDelay: 5
[modules/videosipgw/VideoSIPGW.js] creating VideoSIPGW
[JitsiConference.js] _doReplaceTrack - no JVB JingleSession
[JitsiConference.js] _doReplaceTrack - no P2P JingleSession
[features/full-screen] Setting full-screen mode: true
[modules/xmpp/moderator.js] Sending conference request over XMPP to focus.realtimeuat.onavstack.net
[modules/settings/Settings.js] generated id d7045d78dbff27245b13bdca2f23d91d
[modules/xmpp/xmpp.js] {"userRegion":"iad","environment":"avstack","releaseNumber":"8252","id":"deployment_info"}
[modules/xmpp/moderator.js] Adding focus JID: focus@auth.realtimeuat.onavstack.net
[modules/xmpp/moderator.js] Authentication enabled: false
[modules/xmpp/moderator.js] Sip gateway enabled: true
[modules/xmpp/moderator.js] Conference-request successful, ready to join the MUC.
[modules/version/ComponentsVersions.js] Got focus version: 1.1.SNAPSHOT
[JitsiConference.js] Audio unmute permissions set by Jicofo to false
[JitsiConference.js] Video unmute permissions set by Jicofo to false
[JitsiConference.js] Auto P2P disabled
[features/video-quality] Setting sender resolution to 720
[features/video-quality] Configured preferred receiver video frame height to: 720
[JitsiConference.js] Auto P2P disabled
Calling -viewWillAppear: directly on a view controller is not supported, and may result in out-of-order callbacks and other inconsistent behavior. Use the -beginAppearanceTransition:animated: and -endAppearanceTransition APIs on UIViewController to manually drive appearance callbacks instead. Make a symbolic breakpoint at UIViewControllerAlertForAppearanceCallbackMisuse to catch this in the debugger. View controller: <CellularBackupContacts.ReceiveCallViewController: 0x109812800>
           AQMEIO_HAL.cpp:2773  iOSSimulatorAudioDevice-6441-2: Abandoning I/O cycle because reconfig pending (1).
      HALC_ShellObject.mm:217    HALC_ShellObject::HasProperty: call to the proxy failed, Error: -308 (\M^?\M^?\M-~\M-L)
     HALC_ProxySystem.cpp:163    HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj)
      HALC_ShellObject.mm:213    HALC_ShellObject::HasProperty: there is no proxy object
     HALC_ProxySystem.cpp:163    HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj)
      HALC_ShellObject.mm:213    HALC_ShellObject::HasProperty: there is no proxy object
     HALC_ProxySystem.cpp:163    HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj)
      HALC_ShellObject.mm:213    HALC_ShellObject::HasProperty: there is no proxy object
     HALC_ProxySystem.cpp:163    HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj)
      HALC_ShellObject.mm:213    HALC_ShellObject::HasProperty: there is no proxy object
AudioHardware-mac-imp.cpp:1224   AudioObjectRemovePropertyListener: no object with given ID 127
[JitsiConference.js] Auto P2P disabled
[modules/xmpp/strophe.jingle.js] Found a JSON-encoded element in session-initiate, translating to standard Jingle.
[modules/xmpp/strophe.jingle.js] (TIME) received session-initiate:	 3899856.070666
rn-webrtc:pc:DEBUG 0 ctor +0ms
[modules/RTC/TraceablePeerConnection.js] Using RTCRtpTransceiver#setCodecPreferences for codec selection
rn-webrtc:pc:DEBUG 0 addTrack +4ms
rn-webrtc:pc:DEBUG 0 getStats +7ms
[modules/RTC/TraceablePeerConnection.js] Create new TPC[id=1,type=JVB]
[JitsiConference.js] SCTP: offered=false, prefered=false
[JitsiConference.js] Using colibri-ws url wss://staging.realtimeaudio.com/colibri-ws/bom-5d59fffdb6-rpf2k/b92956b3e1fccf3d/07f3c8fa?pwd=1muva7u7uttvbauifqcuki35u7
[modules/RTC/BridgeChannel.js] constructor() with wsUrl:"wss://staging.realtimeaudio.com/colibri-ws/bom-5d59fffdb6-rpf2k/b92956b3e1fccf3d/07f3c8fa?pwd=1muva7u7uttvbauifqcuki35u7"
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] adding LocalTrack[1,audio]
rn-webrtc:pc:DEBUG 0 setRemoteDescription +10ms
[features/base/redux] redux state persisted. 7760c72cd33282826edebe89a6a6d6f4 -> 0e2321f293f59838cb6510e270edef72
rn-webrtc:pc:DEBUG 0 ontrack +10ms
rn-webrtc:pc:DEBUG 0 ontrack +0ms
rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +1ms
rn-webrtc:pc:DEBUG 0 createAnswer +1ms
rn-webrtc:pc:DEBUG 0 setLocalDescription +3ms
[AudioMode] Audio session didSetActive:1
rn-webrtc:pc:DEBUG 0 setLocalDescription OK +15ms
[modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=1kph4lqdm2sum] Sending session-accept
[modules/xmpp/JingleSessionPC.js] (TIME) ICE checking JVB:	 3899924.134208
[modules/xmpp/SignalingLayerImpl.js] Mute state of 07f3c8fa-a0 changed to muted=false
[JitsiConference.js] Mute state of LocalTrack[1,audio] changed to muted=false
[JitsiConference.js] Updating mute state of LocalTrack[1,audio] in presence to muted=false
[modules/RTC/BridgeChannel.js] websocket channel opened
[JitsiConferenceEventManager.js] (TIME) data.channel.opened:	 3900482.592
[modules/RTC/BridgeChannel.js] Sending ReceiverVideoConstraints with {"assumedBandwidthBps":-1,"constraints":{},"defaultConstraints":{"maxHeight":2160},"lastN":-1}
[modules/RTC/JitsiLocalTrack.js] Mute LocalTrack[1,audio]: true
[modules/xmpp/SignalingLayerImpl.js] Mute state of 07f3c8fa-a0 changed to muted=true
[JitsiConference.js] Mute state of LocalTrack[1,audio] changed to muted=true
[modules/xmpp/JingleSessionPC.js] (TIME) ICE connected JVB:	 3900519.155
[modules/xmpp/strophe.jingle.js] Found a JSON-encoded element in source-add, translating to standard Jingle.
[modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=1kph4lqdm2sum] Processing addRemoteStream
rn-webrtc:pc:DEBUG 0 setRemoteDescription +1s
rn-webrtc:pc:DEBUG 0 ontrack +2ms
rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +5ms
rn-webrtc:pc:DEBUG 0 createAnswer +1ms
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Received track event for remote stream[id=fa9be7ec-audio-0-1,type=audio]
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] creating remote track[endpoint=fa9be7ec,ssrc=3655713993,type=audio,sourceName=fa9be7ec-a0]
[modules/RTC/JitsiRemoteTrack.js] New remote track created: RemoteTrack[userID: fa9be7ec, type: audio, ssrc: 3655713993, p2p: false, sourceName: fa9be7ec-a0, status: {readyState: live, muted: false, enabled: true}]
[modules/RTC/JitsiRemoteTrack.js] "onunmute" event(1710307082676): RemoteTrack[userID: fa9be7ec, type: audio, ssrc: 3655713993, p2p: false, sourceName: fa9be7ec-a0, status: {readyState: live, muted: false, enabled: true}]
rn-webrtc:pc:DEBUG 0 setLocalDescription +3ms
rn-webrtc:pc:DEBUG 0 setLocalDescription OK +2ms
[modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=1kph4lqdm2sum] addRemoteStream - OK
[modules/RTC/BridgeChannel.js] Received ServerHello, version=undefined.
[modules/RTC/BridgeChannel.js] New forwarded sources:
[modules/RTC/RTC.js] Fowarded sources changed leaving=, entering= at 1710307083005
[modules/RTC/BridgeChannel.js] Dominant speaker: 07f3c8fa, previous speakers:
[modules/RTC/JitsiRemoteTrack.js] Mute RemoteTrack[userID: fa9be7ec, type: audio, ssrc: 3655713993, p2p: false, sourceName: fa9be7ec-a0, status: {readyState: live, muted: false, enabled: true}]: false
[modules/RTC/JitsiRemoteTrack.js] Mute RemoteTrack[userID: fa9be7ec, type: audio, ssrc: 3655713993, p2p: false, sourceName: fa9be7ec-a0, status: {readyState: live, muted: false, enabled: true}]: true
[VideoTrackAdapter] Mute event for pc 0 track mixedlabelvideo0
     AudioQueueObject.cpp:5933  DetermineMetadataTimestamp unable to obtain valid timestamp, estimate:45551.000000
rn-webrtc:pc:DEBUG 0 getStats +9s
rn-webrtc:pc:DEBUG 0 getStats +10s
rn-webrtc:pc:DEBUG 0 getStats +10s
[modules/event/Jvb121EventGenerator.js] JVB121 status true => false
     AudioQueueObject.cpp:5933  DetermineMetadataTimestamp unable to obtain valid timestamp, estimate:45551.000000
[JitsiConference.js] Auto P2P disabled
[modules/xmpp/strophe.jingle.js] Found a JSON-encoded element in source-add, translating to standard Jingle.
[modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=1kph4lqdm2sum] Processing addRemoteStream
rn-webrtc:pc:DEBUG 0 setRemoteDescription +6s
rn-webrtc:pc:DEBUG 0 ontrack +3ms
rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +6ms
rn-webrtc:pc:DEBUG 0 createAnswer +1ms
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Received track event for remote stream[id=13e0d0b0-audio-0-1,type=audio]
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] creating remote track[endpoint=13e0d0b0,ssrc=3296182662,type=audio,sourceName=13e0d0b0-a0]
[modules/RTC/JitsiRemoteTrack.js] New remote track created: RemoteTrack[userID: 13e0d0b0, type: audio, ssrc: 3296182662, p2p: false, sourceName: 13e0d0b0-a0, status: {readyState: live, muted: false, enabled: true}]
[modules/RTC/JitsiRemoteTrack.js] "onunmute" event(1710307117043): RemoteTrack[userID: 13e0d0b0, type: audio, ssrc: 3296182662, p2p: false, sourceName: 13e0d0b0-a0, status: {readyState: live, muted: false, enabled: true}]
rn-webrtc:pc:DEBUG 0 setLocalDescription +4ms
rn-webrtc:pc:DEBUG 0 setLocalDescription OK +2ms
[modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=1kph4lqdm2sum] addRemoteStream - OK
[modules/RTC/JitsiRemoteTrack.js] Mute RemoteTrack[userID: 13e0d0b0, type: audio, ssrc: 3296182662, p2p: false, sourceName: 13e0d0b0-a0, status: {readyState: live, muted: false, enabled: true}]: false
[modules/RTC/BridgeChannel.js] Dominant speaker: 13e0d0b0, previous speakers: 07f3c8fa
[modules/RTC/JitsiRemoteTrack.js] Mute RemoteTrack[userID: 13e0d0b0, type: audio, ssrc: 3296182662, p2p: false, sourceName: 13e0d0b0-a0, status: {readyState: live, muted: false, enabled: true}]: true
rn-webrtc:pc:DEBUG 0 getStats +4s
rn-webrtc:pc:DEBUG 0 getStats +10s
rn-webrtc:pc:DEBUG 0 getStats +10s
rn-webrtc:pc:DEBUG 0 getStats +10s
rn-webrtc:pc:DEBUG 0 getStats +10s
rn-webrtc:pc:DEBUG 0 getStats +10s
rn-webrtc:pc:DEBUG 0 getStats +10s
[modules/RTC/BridgeChannel.js] New forwarded sources: fa9be7ec-v0
[modules/RTC/RTC.js] Fowarded sources changed leaving=, entering=fa9be7ec-v0 at 1710307181416
[modules/xmpp/strophe.jingle.js] Found a JSON-encoded element in source-add, translating to standard Jingle.
[modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=1kph4lqdm2sum] Processing addRemoteStream
rn-webrtc:pc:DEBUG 0 setRemoteDescription +103ms
rn-webrtc:pc:DEBUG 0 ontrack +5ms
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Received track event for remote stream[id=fa9be7ec-video-0-1,type=video]
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] creating remote track[endpoint=fa9be7ec,ssrc=675931275,type=video,sourceName=fa9be7ec-v0]
[modules/RTC/JitsiRemoteTrack.js] New remote track created: RemoteTrack[userID: fa9be7ec, type: video, ssrc: 675931275, p2p: false, sourceName: fa9be7ec-v0, status: {readyState: live, muted: false, enabled: true}]
[modules/qualitycontrol/ReceiveVideoController.js] Updating ReceiverVideoConstraints {"constraints":{"fa9be7ec-v0":{"maxHeight":180}},"defaultConstraints":{"maxHeight":0},"lastN":-1,"onStageSources":[],"selectedSources":[]}
[modules/RTC/BridgeChannel.js] Sending ReceiverVideoConstraints with {"constraints":{"fa9be7ec-v0":{"maxHeight":180}},"defaultConstraints":{"maxHeight":0},"lastN":-1,"onStageSources":[],"selectedSources":[]}
[modules/connectivity/TrackStreamingStatus.ts] RtcMuteTimeout set to: 10000
[modules/RTC/JitsiRemoteTrack.js] Initializing track streaming status: fa9be7ec-v0
[modules/qualitycontrol/ReceiveVideoController.js] Updating ReceiverVideoConstraints {"constraints":{"fa9be7ec-v0":{"maxHeight":720}},"defaultConstraints":{"maxHeight":0},"lastN":-1,"onStageSources":["fa9be7ec-v0"],"selectedSources":[]}
[modules/RTC/BridgeChannel.js] Sending ReceiverVideoConstraints with {"constraints":{"fa9be7ec-v0":{"maxHeight":720}},"defaultConstraints":{"maxHeight":0},"lastN":-1,"onStageSources":["fa9be7ec-v0"],"selectedSources":[]}
[modules/RTC/JitsiRemoteTrack.js] "onunmute" event(1710307181511): RemoteTrack[userID: fa9be7ec, type: video, ssrc: 675931275, p2p: false, sourceName: fa9be7ec-v0, status: {readyState: live, muted: false, enabled: true}]
rn-webrtc:pc:DEBUG 0 setRemoteDescription OK +37ms
rn-webrtc:pc:DEBUG 0 createAnswer +3ms
[modules/connectivity/TrackStreamingStatus.ts] Detector track RTC unmuted: fa9be7ec-v0 1710307181511
[modules/connectivity/TrackStreamingStatus.ts] Figure out conn status for fa9be7ec-v0, is video muted: false video track frozen: false p2p mode: false is in forwarded sources: true currentStatus => newStatus: active => active
rn-webrtc:pc:DEBUG 0 setLocalDescription +8ms
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
rn-webrtc:pc:DEBUG 0 setLocalDescription OK +11ms
[modules/xmpp/JingleSessionPC.js] JingleSessionPC[session=JVB,initiator=false,sid=1kph4lqdm2sum] addRemoteStream - OK
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
[modules/RTC/BridgeChannel.js] New forwarded sources:
[modules/RTC/RTC.js] Fowarded sources changed leaving=fa9be7ec-v0, entering= at 1710307185621
[modules/connectivity/TrackStreamingStatus.ts] Figure out conn status for fa9be7ec-v0, is video muted: false video track frozen: false p2p mode: false is in forwarded sources: false currentStatus => newStatus: active => active
[modules/RTC/JitsiRemoteTrack.js] Mute RemoteTrack[userID: fa9be7ec, type: video, ssrc: 675931275, p2p: false, sourceName: fa9be7ec-v0, status: {readyState: live, muted: false, enabled: true}]: true
 67179          HALC_ProxyIOContext.cpp:1328  HALC_ProxyIOContext::IOWorkLoop: skipping cycle due to overload
[modules/connectivity/TrackStreamingStatus.ts] Figure out conn status for fa9be7ec-v0, is video muted: true video track frozen: false p2p mode: false is in forwarded sources: false currentStatus => newStatus: active => active
[modules/RTC/JitsiRemoteTrack.js] Disposing track streaming status: fa9be7ec-v0
[VideoTrackAdapter] Mute event for pc 0 track 8299e0b7-cb19-4fb8-8a96-166f31be4c04-1
 67179          HALC_ProxyIOContext.cpp:1328  HALC_ProxyIOContext::IOWorkLoop: skipping cycle due to overload
 67179          HALC_ProxyIOContext.cpp:1328  HALC_ProxyIOContext::IOWorkLoop: skipping cycle due to overload
 67179          HALC_ProxyIOContext.cpp:1328  HALC_ProxyIOContext::IOWorkLoop: skipping cycle due to overload
[modules/connectivity/TrackStreamingStatus.ts] Figure out conn status for fa9be7ec-v0, is video muted: true video track frozen: false p2p mode: false is in forwarded sources: false currentStatus => newStatus: null => active
[modules/connectivity/TrackStreamingStatus.ts] Emit track streaming status(1710307194703) fa9be7ec-v0: active
Running "App
[features/app] appNavigate to https://staging.realtimeaudio.com
[features/full-screen] Setting full-screen mode: false
     AudioQueueObject.cpp:5933  DetermineMetadataTimestamp unable to obtain valid timestamp, estimate:45551.000000
[JitsiMeetJS.ts] This appears to be react-native, ver: 0.72.9
[modules/statistics/statistics.js] Cannot initialize WatchRTC in a react native environment!
[JitsiMeetJS.ts] Analytics disabled, disposing.
[modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
[modules/RTC/RTCUtils.js] Disable AEC: false
[modules/RTC/RTCUtils.js] Disable NS: false
[modules/RTC/RTCUtils.js] Disable AP: false
[modules/RTC/RTCUtils.js] Disable AGC: false
[modules/RTC/RTCUtils.js] Stereo: false
[modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
[features/base/lib-jitsi-meet] lib-jitsi-meet version:639ad566
[modules/statistics/AnalyticsAdapter.js] Disposing of analytics adapter.
[features/base/media] Start muted:
rn-webrtc:pc:DEBUG 0 close +13s
[features/base/media] Start audio only set to false
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Removing remote track stream[id=fa9be7ec-audio-0-1,trackId=8E42F457-CD87-450D-83E6-54A15DFEB332-1]
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Removing remote track stream[id=fa9be7ec-video-0-1,trackId=8299e0b7-cb19-4fb8-8a96-166f31be4c04-1]
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Removing remote track stream[id=13e0d0b0-audio-0-1,trackId=0B2FEDA1-502E-427F-B7C1-7F9F9EAF2913-1]
[modules/RTC/TraceablePeerConnection.js] TPC[id=1,type=JVB] Closing peerconnection
[modules/RTC/RTCUtils.js] Available devices:  []
[features/base/lastn] There is no active conference, not updating last N
            HALSystem.cpp:2216   AudioObjectPropertiesChanged: no such object
[modules/RTC/BridgeChannel.js] Channel closed by client
[modules/RTC/BridgeChannel.js] Skip close handler, channel instance is not equal to stored one
[modules/event/Jvb121EventGenerator.js] JVB121 status false => true
[modules/xmpp/xmpp.js] (TIME) Strophe disconnecting:	 4013657.648291
["user_type": "P", "call_type": Optional("Audio"), "sender_userid": "6492887957c027384566dffa", "status": "5", "parent_id": "97dac7b2-3b11-49be-8fea-9d7355623cd6", "sender_username": "vikrant742", "_id": "65f136fec040aada2c9772a4"]
[modules/xmpp/strophe.ping.js] Ping interval cleared
[modules/xmpp/xmpp.js] (TIME) Strophe disconnected:	 4013658.500541
[features/base/redux] redux state persisted. 0e2321f293f59838cb6510e270edef72 -> 482acfbb23de6e087b3b2f526710a34f
           AQMEIO_HAL.cpp:2552  timeout
AudioHardware-mac-imp.cpp:2706   AudioDeviceStop: no device with given ID
[AudioMode] Audio session didSetActive:0
           AQMEIO_HAL.cpp:2773  iOSSimulatorAudioDevice-6441-4: Abandoning I/O cycle because reconfig pending (1).
      HALC_ShellObject.mm:217    HALC_ShellObject::HasProperty: call to the proxy failed, Error: 268435459 (\^P)
     HALC_ProxySystem.cpp:163    HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj)
      HALC_ShellObject.mm:213    HALC_ShellObject::HasProperty: there is no proxy object
     HALC_ProxySystem.cpp:163    HALC_ProxySystem::GetObjectInfo: got an error from the server, Error: 560947818 (!obj)
      HALC_ShellObject.mm:213    HALC_ShellObject::HasProperty: there is no proxy object
AudioHardware-mac-imp.cpp:1224   AudioObjectRemovePropertyListener: no object with given ID 135
            HALSystem.cpp:2216   AudioObjectPropertiesChanged: no such object
           AQMEIO_HAL.cpp:2552  timeout
AudioHardware-mac-imp.cpp:2706   AudioDeviceStop: no device with given ID
