### ISSUE TITLE
jitsi-meet self hosted works only with firefox

### ISSUE THREAD

**Issue by mhenninghaus77** [jitsi/jitsi-meet#1465]
Hi,

i installed a docker Container with jitsi-meet nad started it up. my Problem: i´m only able to use Video and Sound on Firefox when both participants are using this browser.
With Chrome i´m only able to Chat, no video is beeing seen
i´m using chome 57 on Windows 10

**Comment by saghul** [comment]
We currently don't have an official Docker container, so I can't vouch for the correctness of the container you are testing.

Chrome definitely works (check meet.jit.si) so it's most certainly a setup issue, or the software versions might not be up to date in the container. It's impossible for me to tell.

Please use the mailing list for such questions, specially if they are related to setups not officially supported by us.

**Comment by mhenninghaus77** [comment]
Mhhh, but i´m not the only one having questions regarding the configuration of jitsi .... the documentation for your very well apllication is not so detailed or i am not able to find it. it would be interesting how you configured your reference system

**Comment by saghul** [comment]
I agree that our documentation is far from perfect. I'm taking those matters into my own hands, but it will take a while to complete.

I don't think your problem is configuration, there is no `breatStuffForChrome` setting :-) I suggest you try setting Jitsi Meet up in a Ubuntu VM, using our provided packages. That works out of the box. But if doesn't, open and issue and yell at me :-)
