### ISSUE TITLE
Make Libravatar the default instead of Gravatar

### ISSUE THREAD

**Issue by NameLessGO** [jitsi/jitsi-meet#14743]
Users
Jitsi: @saghul
Libravatar: @ofalk @hybridpicker

This is the continuation of 2020-21 Discussion: #8149 and https://community.jitsi.org/t/jitsi-meet-mobile-libravatar-as-the-default/131608

> Saghul (may 2023): I think it is indeed a good time to revisit. Can you please open a new issue on GH and tag Oliver too?
----------

# Context

[Libravatar](https://www.libravatar.org/) is a service which delivers your avatar (profile picture) to other websites. If you create an account with us, your photo could start popping up next to forum posts or blog comments on any site where you left your email address.

This service is an open source alternative to [Gravatar](https://www.gravatar.com/), which had their fair share of [Security concerns and data breaches](https://en.wikipedia.org/wiki/Gravatar) + proprietary/commercial license

# History
When Jitsi was adding Libravatar support, the service was migrating to a new infrastructure and this migration caused problems to Jitsi which lead them to revert: #8149 

> Saghul (nov 2020): We noticed high latency with libravatar and contacted them. They are in the process of migrating to a better infrastructure (it’s a single personal server at the moment) so we’ll re-evaluate once that has happened.

Lead dev of libravatar:

> Oliver (nov 2020): As also discussed via mail - I want to make sure everybody stumbling over this issue is also aware.
We’re working on new infrastructure and once we’ve moved over, the performance should be better again.

> Oliver (March 2021): Hi!
So, libravatar was migrated to new infrastructure on the last weekend and the service seems to be stable and much faster than before. If you, by any chance, would like to give it a try again, I’d be very happy!

After the last msg from libravatar dev, there wasn’t any progress/discussion towards making Libravatar as the default or any stance rejecting it

# UX
In Jitsi Meet Mobile (Android): Settings > Profile

There isn’t an indication of using libravatar, instead this msg appears:
“If your email is associated with Gravatar, we will use it to display your profile photo”

Environment: App version: 24.2.2 build 16757163

# Request
- Resume discussion into making libravatar as the default (Approve/Rejection)
- If libravatar is being used, mention in clients (Settings > Profile)
- Else implement libravatar as secondary option and mention it as well

**Comment by saghul** [comment]
Thank you for reviving the discussion!

Part of the effort we did back then was to make the Gravatar compatible service URL configurable.

At this point it's a matter of changing the default.

Not sure how we can tackle showing the service name in Settings, since it could really be anything that responds with an image. Perhaps we can take this in steps and figure that out later on.

**Comment by ofalk** [comment]
My take on this would be: Just switch to Libravatar and enable the (transparent) Gravatar proxy feature. This gives your users more privacy, as they don't hit the Gravatar service directly any more. And if someone is using Libravatar already, it's used instead of Gravatar. You can also choose a default image (or generated avatar) to fit your preferences.

Give it a try here: https://www.libravatar.org/tools/check/

**Comment by saghul** [comment]
That's what we did a few years ago, but the servers became very slow due to the increased traffic we sent. libravatar still needs to proxy the requests.

**Comment by saghul** [comment]
Ok, let me check what we can do!

**Comment by ofalk** [comment]
I know this hasn't sparked a lot of interest, but I'd be still happy to see this happening!
