### ISSUE TITLE
separate bandwidth/size setting in config.js for video and screen share

### ISSUE THREAD

**Issue by rjmaris** [jitsi/jitsi-meet#14824]
### What problem are you trying to solve?

Upon using jitsi meet using a platform with good capacity to handle multiple conferences at the same time (https://meet.ffmuc.net/), I encounter **readability problems while sharing the screen**. According to their config.js, the video size has been limited in order to save bandwidth (thus allow more concurrent sessions), which is effectively no problem at all.
However, it appears that screen sharing loses pixel resolution.

### What solution would you like to see?

In the case that this is due to configured video size limitation, it would make sense to let the size limitation only apply to video, not to screen sharing, or to add an extra setting specific to screen sharing.

**Comment by saghul** [comment]
We already have separate settings for those. @jallamsetty1 can you point out which settings they should be tweaking?

**Comment by jallamsetty1** [comment]
@rjmaris How have they limited the video size? If they have changed the capture resolution constraints, it doesn't have any affect on the screenshare resolution. Bitrate caps can be applied separately for video and screenshare. You can check out the `videoQuality` section in the [configuration guide](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-configuration), `ssHigh` needs to be updated for changing the max bitrate for screenshare.

**Comment by rjmaris** [comment]
Oh, I missed your comment last week. Quick answer: not bandwidth is restricted, but video size. See https://meet.ffmuc.net/config.js (I did diff with my own config)

**Comment by jallamsetty1** [comment]
It doesn't appear that they have restricted video size, the video constraints are set to 720p. Also, changing video constraints has no affect on screenshare quality. It appears that the max. fps for screenshare has been changed to 10 fps. 
```
// Optional desktop sharing frame rate options. Default value: min:5, max:5.
    desktopSharingFrameRate: {
        min: 5,
       max: 10
 }
```
When this setting is used, the browser will prefer fps (motion) over resolution (detail) and therefore whenever it encounters a cpu/bandwidth restriction, the resolution will be dropped to deliver a 10 fps share. I am closing this issue since we already have separate settings for video and screenshare.
