### ISSUE TITLE
Jitsi meet error for new SSL Certificate

### ISSUE THREAD

**Issue by roycecaballero** [jitsi/jitsi-meet#15088]
### What happened?

Hi, we just updated our SSL certificates. we updated the prosody and nginx certs. but when we connect to our url it keeps on kicking us out. Here is the error in jicofo. There were no changes to this server until the SSL certificate change.
[jicofo.log](https://github.com/user-attachments/files/16860329/jicofo.log)

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome-latest

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by damencho** [comment]
You should not touch the prosody certs. They are generated during install process and are trusted on local machine. Now when you updated the prosody certs jicofo cannot connect. Can you revert to prosody old certs?

**Comment by roycecaballero** [comment]
@damencho thanks for your input. Nope i cannot revert to the old prosody certs since I already copied the new certs to prosody. Is there any work around for this? or do i need to reinstall everything?

**Comment by damencho** [comment]
You need to generate a new cert for auth.meet.youdomain.app and use that and make it trusted on the machine. The problem is that your certificate does not include this virtual domain and you can see that in the errors in jicofo logs.

To generate it
https://github.com/jitsi/jitsi-meet/blob/6aa42f985093402f4cac9fcd4faad1f60c8e37be/debian/jitsi-meet-prosody.postinst#L227

Then links to the correct folders
https://github.com/jitsi/jitsi-meet/blob/6aa42f985093402f4cac9fcd4faad1f60c8e37be/debian/jitsi-meet-prosody.postinst#L232
If there are some old ones, maybe first remove them, to then execute `update-ca-certificates -f` and then create the links and execute it again.

Make sure this is the cert used in prosody for auth domain.

**Comment by roycecaballero** [comment]
Hi @damencho thanks for the assistance our jitsi is now working. I regenerated the auth and domain certs because it was overwritten during the changing of SSL certificates in nginx.
