### ISSUE TITLE
No sound, no video on Chromium 130

### ISSUE THREAD

**Issue by Thatoo** [jitsi/jitsi-meet#15263]
### What happened?

When I connect to a jitsi conference, it works on Firefox but I don't have any audio, nor video on Chromium and others don't see nor hear me.

### Platform

- [X] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

130.0.6723.69

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

### More details?

I don't know if I can reproduce on meet.jit.si, I don't have account there (no facebook, no google...)

**Comment by damencho** [comment]
Is this your deployment? Is this p2p or there are at least 3 participants in the call?

**Comment by damencho** [comment]
Works here. That deployment doesn't have a turn server, maybe you have some network restrictions or something on your side and that's why it fails.
There is nothing actionable for this project, so I will close the ticket.

Please, when you have questions or problems use the community forum before opening new issues, thank you.

Again, if you need help configuring that deployment, ask questions in the community forum.
