### ISSUE TITLE
Enter a meeting that has been created in advance (similar to teams or google)

### ISSUE THREAD

**Issue by lucaslevi-consultor-glpi** [jitsi/jitsi-meet#15333]
### What problem are you trying to solve?

Good afternoon, everyone,

I use jitsi meet for work and I like it very much, the latest releases have brought very useful corrections. What I'd like to bring up here, which in my opinion is the only thing that is still missing to reach the level of teams and google meet, would be the option to create a room that would be “created” so that when the user entered the link, they could already enter the password for the meeting or click on request entry.

The problem is that normally when I create a meeting for a client, I have to log in a few minutes before the room opens. As we see in teams or meet, the person can click on request entry, even if the organizer isn't in the meeting yet

Anyway, I'll leave it here as a suggestion for future improvement,

but the platform is very good, I use it every day

Thanks !

Translated with DeepL.com (free version)

**Comment by damencho** [comment]
I guess, you are talking here about meet.jit.si. With meet.jit.si that is not possible because of the way it is set up. No state for rooms is being kept, so when someone leaves the room any setting from the room is lost.

If you have your deployment you can handle that, by enabling lobby in advance, having a backend storage for room passwords, and so on. There are a lot of options to handle specific cases. 

You can also use jaas.8x8.vc where those stuff are already handled and you need to feed the system with your settings via some webhooks. 

Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
From https://jitsi.org/security/:

```
In many respects Jitsi meetings are simply private by design. To begin with, all meeting rooms are ephemeral: they only exist while the meeting is actually taking place. They get created when the first participant joins and they are destroyed when the last one leaves. If someone joins the same room again, a brand new meeting is created with the same name and there is no connection to any previous meeting that might have been held with the same name. 

This is all very important. Some of the systems that let people “pre-create” rooms, have subtle indications that let a potential attacker distinguish reserved from unreserved meetings which then makes the reserved meetings easier to identify and target.
```

If you just want to use meet.jit.si, there is no point of setting a password in advance, just send a very complicated room name, and if you want to make sure no one is able to join after you and the other participant are in, set a password then.

You can read more on the subject in the link above. Those are specific configuration and choices for meet.jit.si and you can use something else in your deployment.

**Comment by lucaslevi-consultor-glpi** [comment]
Thanks for reply !
