### ISSUE TITLE
How can I split Mobile React Native App?

### ISSUE THREAD

**Issue by ZuzooVn** [jitsi/jitsi-meet#1581]
Hi Jitsi team,

I just want to integrate your great Jitsi-Meet app with our existed app.
But AFAIK, the current source code include both of Mobile and Server source code.
Do you have any suggestion?

Thanks,

Nam Vu from ThinkLabs-VN.

**Comment by saghul** [comment]
Hi!

This repository just contains the frontend code, which shared between the web and the mobile app. There is no server code here, so you can use it as is.

**Comment by ZuzooVn** [comment]
Thanks @saghul 

I think there are a lot of unnecessary source code for web application. It is possible to use only mobile app source code?

Thanks

**Comment by saghul** [comment]
No. Our goal is to share as much code as possible between the web and the mobile app, in order to avoid doing twice the effort. What you as is not (and will never be) possible.

Why do you see this as a problem? Note that while not all code is used on the mobile app, it's not bundled, the app only includes the code it uses.
