### ISSUE TITLE
Easy way to hide Index page circles

### ISSUE THREAD

**Issue by anatomism** [jitsi/jitsi-meet#1584]
Does anyone know of a way to easily hide the circles on the index page. Every time I update Jitsi they reappear and it seems a pain to have to go in and find the (ever changing/evolving) code that generates this.

It used to be fairly easy, but now I believe it needs to be done within the CSS files?

![index](https://cloud.githubusercontent.com/assets/9029851/26256429/d8737384-3cb4-11e7-9b0b-7e06695a0270.jpg)

Thanks

**Comment by anatomism** [comment]
I guess not then

**Comment by saghul** [comment]
The code for it is now in written in React. You can start looking here: https://github.com/jitsi/jitsi-meet/blob/master/react/features/welcome/components/WelcomePage.web.js#L63 and comment out the parts you don't want.

Note that you will need to rebuild the source and your changes will be gone on the next update.

**Comment by StreamTitan** [comment]
I'm trying to understand the logic of Jitsi-Meet. 
Not how it works but rather, the unnecessary need for it to be this complicated.

There is no forum for Jitsi-Meet.
Going to the Jitsi.org website only tells of the products, developers and which companies uses JItsi-Meet. That's all.
So for everyone who would like to install it, you figure it out on your own either with the quick install or the manual install. Therein, lies the real problems.

Here on github the Jitsi-meet project caters only for issues. You have a better chance of meeting God in person than getting an answer on a "how-to" in here. There are questions asked on here that are 1yr plus with zero responses and I get that. Its an "issues" medium. I don't think that anyone is asking to be spoonfed or have a problem fixed for them. We mostly just need to be pointed into the right direction, if the fix pointed to is reasonable. 

If the fix is an abrupt "just build it out", most of us are like "huh?"

Case in point and what I'm trying to figure out. Editing the welcome page.
Now if you could access that page, then of course you can just do a direct edit. But that seems like a lost cause because that page is nowhere to be found. So as above stated "you have to build it out" and I'm like great, does that mean I have to do a Manual Install instead of the Quick Install.

That I have to do this install all over again?

I tried editing the main.json file to change the text on the welcome page. I even deleted some features but still all 8 features showed on the welcome page again. I'm staring at the main.json file with 4 features (after edit) and the resulting website page still showing 8 features (yes cache was cleared).

All I can do is laugh really. 

The Jitsi developers in here say "do the quick install". Ok, we do that, we get it working. Now for the obvious very FIRST step anyone would like to do - edit the welcomepage. "Oh, for that you need to build it out". Here's an idea, why not say that BEFORE telling us to do the quick install option?

Look, jitsi is a great app. No doubt about that. A lot of work went into it. I respect that. The app-bundle.js has 115k lines of code in it...and that's just 1 file. But without documentation, which is all we really need to be honest, you're making this for a select group of people and not for the intention of how you started (for everyone) when you made Jitsi. Why did you start Jitsi? Did someone forget that because the Jitsi project from the very beginning did a lot more to help people get started because there used to be documentation of some sort, but it helped. Now its resorted to a "quick install" and figure it out yourself.

I think the org needs to revisit this in the next meeting because like it or not, I do have a point here.
I see some answers from developers saying "I’m afraid we have no documentation on how to modify the site. You’ll have to find your way around the code and then rebuild the sources..."

I mean really?

**Comment by bbaldino** [comment]
hey @StreamTitan, these are my own thoughts but I'll try and address what I can from your comments:

> There is no forum for Jitsi-Meet.

> Here on github the Jitsi-meet project caters only for issues. You have a better chance of meeting God in person than getting an answer on a "how-to" in here. There are questions asked on here that are 1yr plus with zero responses and I get that. Its an "issues" medium. I don't think that anyone is asking to be spoonfed or have a problem fixed for them. We mostly just need to be pointed into the right direction, if the fix pointed to is reasonable.

This is true.  We do have mailings lists for users (users@jitsi.org) and developers (dev@jitsi.org) though, are you aware of those?  Things that don't fall under "issues" (which we try and limit github to) are welcome there and do typically get reasonable quick responses (in my opinion).

> So for everyone who would like to install it, you figure it out on your own either with the quick install or the manual install. Therein, lies the real problems.
> If the fix is an abrupt "just build it out", most of us are like "huh?"
> Case in point and what I'm trying to figure out. Editing the welcome page.
> Now if you could access that page, then of course you can just do a direct edit. But that seems like a lost cause because that page is nowhere to be found. So as above stated "you have to build it out" and I'm like great, does that mean I have to do a Manual Install instead of the Quick Install.
> The Jitsi developers in here say "do the quick install". Ok, we do that, we get it working. Now for the obvious very FIRST step anyone would like to do - edit the welcomepage. "Oh, for that you need to build it out". Here's an idea, why not say that BEFORE telling us to do the quick install option?
> The Jitsi developers in here say "do the quick install". Ok, we do that, we get it working. Now for the obvious very FIRST step anyone would like to do - edit the welcomepage. "Oh, for that you need to build it out". Here's an idea, why not say that BEFORE telling us to do the quick install option?

If any developer gave this advice, they must have been under the impression that the user was just interested in getting an installation of jitsi meet running that they could use, not to do any development on their own.  Sometimes it may be hard to tell what a user is trying to get done, so it's possible people err on the side of the more basic setup rather than flooding them with development-specific information.

As to the quick install/manual install thing, I think it's pretty common for projects to take the following approach:
```
Want to just use the software without changing anything?  --> Just install the packages (quick install)
Want to modify stuff? --> You'll need to build from source (manual install)
```
Do you mean that the difference between 'quick install' and 'manual install' is not clear?


> Look, jitsi is a great app. No doubt about that. A lot of work went into it. I respect that. The app-bundle.js has 115k lines of code in it...and that's just 1 file. 

Thanks!  (though to be fair app-bundle.js is the bundled version of all of the individual javascript files; I hope we never end up with a 115k line file)

> But without documentation, which is all we really need to be honest, you're making this for a select group of people and not for the intention of how you started (for everyone) when you made Jitsi. Why did you start Jitsi? Did someone forget that because the Jitsi project from the very beginning did a lot more to help people get started because there used to be documentation of some sort, but it helped. Now its resorted to a "quick install" and figure it out yourself.

I completely agree the documentation has room for improvement.  We do the best we can, and contributions from users and developers like you really help (as do the questions).  Sometimes when you work on something for so long, it's hard to write a doc from the perspective of a fresh user.  I'd definitely encourage you to ask your questions on the mailing list and, when you (hopefully) get the answer, contributions which help clarify the docs would be much appreciated.

> I think the org needs to revisit this in the next meeting because like it or not, I do have a point here.
> I see some answers from developers saying "I’m afraid we have no documentation on how to modify the site. You’ll have to find your way around the code and then rebuild the sources..."
> 
> I mean really?

Our next community call is this coming Monday (February 26th).  It's at 8:30am pacific time at https://meet.jit.si/TheCall, I'd definitely encourage you to join.

**Comment by MattB98** [comment]
So has anyone actually managed to update the welcome page?  Seriously?  I have found no step by step instructions anywhere, I'd have thought this would be the first post-install instructions in the documentation...

I've done a quick-install, it works, now I want to configure and change stuff.  Where do I start?
