### ISSUE TITLE
Video Freeze Listener

### ISSUE THREAD

**Issue by subsub** [jitsi/jitsi-meet#1589]
Is there any event that tells remote track is freezing? I see NO_DATA_FROM_SOURCE but I'm not sure.

**Comment by saghul** [comment]
You can listen to JitsiConferenceEvents.PARTICIPANT_CONN_STATUS_CHANGED, which will give you the participant's status: https://github.com/jitsi/lib-jitsi-meet/blob/3ca4b3dff9531a32b0d303ca2cc298371d429c8c/modules/connectivity/ParticipantConnectionStatus.js#L40

Unless a participant's status is active, it's video might be frozen / not available due to adaptivity, for example.
