### ISSUE TITLE
Open a meet with only video teacher

### ISSUE THREAD

**Issue by oscarmlage** [jitsi/jitsi-meet#1675]
Do you know if is there any way to start a `jitsi-meet` with only one video/audio (teacher) and no video/audio from the other attendees (students)? (just the chat as the main communication via, like a webinar or a remote lesson or similar).

I've been taking a look to the _config_ and _interface_config_ and you can disable audio/video by default but every client has the control in screen to be able to put it on again.

Even if the screen controls could be hidden in a way, would the video/audio from the attendees be consuming the bandwidth?.

Thanks in advance and thank you so much for this amazing project!.

**Comment by ruicruzpt** [comment]
No. Nuless you (the teacher) disable your own audio and let people know about it somehow.

The app is designet to be audio/video in both ways.

**Comment by oscarmlage** [comment]
Thanks @ruicruzpt, do you know if there is some open source piece of code designed specifically for webinars?

**Comment by ruicruzpt** [comment]
I don't know any, sorry.

**Comment by saghul** [comment]
> Do you know if is there any way to start a jitsi-meet with only one video/audio (teacher) and no video/audio from the other attendees (students)? (just the chat as the main communication via, like a webinar or a remote lesson or similar).
> 
> I've been taking a look to the config and interface_config and you can disable audio/video by default but every client has the control in screen to be able to put it on again.

Hi there! I'm afraid we don't support that scenario... you may be able to get there with a slightly modified deployment though.

> Even if the screen controls could be hidden in a way, would the video/audio from the attendees be consuming the bandwidth?.

If the video / audio is muted, no bandwidth will be consumed.

You could try to enable authentication in your deployment, so the teacher needs to join first, and then tweak the config so every participant after the first starts muted and video muted. Then the only problem left would be hiding the controls to do that. This can be done in interface_config.js, though you'd be hiding them for everyone, including the teacher. Now, since the teacher is the first one to join they will have audio / video, but the next participants (the students) won't.

There may be some problems down the road like when the teacher drops and rejoins (they would be audio and video muted) but hopefully you can fix that with a bit of creativity :-)

Hope that helps, and thanks for the kind words!

**Comment by damencho** [comment]
Or you can make the teacher joins in the meeting alone and stream to
youtube. Students receive the video link and watch and write comments
under the video. The only downside is that with this approach there is
a slight delay between teacher and the youtube stream (20-30 seconds I
think).

**Comment by oscarmlage** [comment]
The logical steps my mind followed were something similar what @saghul said. Start with the teacher as moderator, disable the audio/video of the students by default and hide the screen controls in the `interface_config.js`.

@damencho youtube is not an option due to copyrights, but the other way around (stream a video, not from youtube but from other rtmp source or even a recorded file) also would be a nice feature for a meet. 

Thanks both for the ideas!

**Comment by havid0707** [comment]
@oscarmlage do you have implemented this ? Can you share the solution? Thanks a lot

**Comment by oscarmlage** [comment]
@havid0707 no I haven't, at the end our team decided to adopte some other solutions for this (live stream using nginx + rtmp + ffmpeg with custom HTML + front application to control login, permissions, etc...).  Totally different approach but custom solution fit better with our's client premises.
