### ISSUE TITLE
icon not showing

### ISSUE THREAD

**Issue by subkhansarif** [jitsi/jitsi-meet#1688]
Whenever I run the android app, the icon is not showing and replaced by square icon. How to fix this?
Thank you

**Comment by gcobcqwe** [comment]
I have the same problem of android project.The icon is not working.How to fix this?
Thank you.
![img](http://imgur.com/a/E9HZe.png)

**Comment by saghul** [comment]
Hi there! Did you build the app yourselves or are you running it from the store?

**Comment by gcobcqwe** [comment]
I built the app based on android version of 5.1.1 myself.
I can join a video chat with other, but the icon is not showing.

**Comment by gcobcqwe** [comment]
The app from the store can show the icon, but the app I built myself can't show the icon.
Do you have keyword to help me to solve this problem? Thank you.

**Comment by saghul** [comment]
Are you using the latest master? Please describe every step you're following.

**Comment by gcobcqwe** [comment]
1.git clone master project from github
2.cd project
3.npm install
4.mkdir assets under the path android/app/src/main

5.`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

6.open android folder in android studio

7.modify build.gradle 
`classpath 'com.android.tools.build:gradle:3.0.0-alpha6'`
to
`classpath 'com.android.tools.build:gradle:2.3.3'`

8.cd app folder and modify build.gradle
`implementation project(':sdk')`
to
`compile project(':sdk') `

9.build and run project on a real device
10.The icon is not showing

**Comment by saghul** [comment]
Well, you are changing thing in the project and expect it to continue to work... that's not going to fly :-)

The app is now divided in 2 parts: the sdk and the app itself. The sdk uses React Native, but the app knows nothing about it. Also, you cannot downgrade gradle just because, there is a reason why it's that specific version, and it has everything to so with support for better building.

Thus, the steps are:

1. git clone master project from github
2. cd project
3. npm install
4. react-native run-android

Alternatively, you can use Android Studio 3.0 Preview, but will want comment out this line https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/build.gradle#L109 so the bundle is included automatically.

**Comment by CPLASF1925** [comment]
@gcobcqwe 


Is the problem solved?
