### ISSUE TITLE
New API external_api.min.js

### ISSUE THREAD

**Issue by eniltonangelim** [jitsi/jitsi-meet#1691]
Is there a way to access the previous pattern? Without the webpack?

I need to use the previous pattern, as in https://beta.meet.jit.si/external_api.js

Version: Master (update)

**Comment by lyubomir** [comment]
Could you please help us understand the scenario in which your need arises? Do you need to access the resource `https://beta.meet.jit.si/external_api.js` not caring whether it's minimized or not? Or do your rather want an unminimized form of `external_api`?

**Comment by eniltonangelim** [comment]
I'm using jitsi as a third-party software extension, however, the minimized version of the API causes the plugin to become unavailable after deployment.

Or do your rather want an unminimized form of external_api?

Yes, i need an unminimized version of external_api

**Comment by lyubomir** [comment]
> the minimized version of the API causes the plugin to become unavailable after deployment

Have you looked into why that happens? Is `external_api.min.js` causing a JS exception of some sort?

> What should I do?

It depends:

A. If you need that resource on https://beta.meet.jit.si, then you have to convince a developer of ours to modify the project jitsi-meet so that it builds and deploys the unminimized artifact via the debian package. That could also be accomplished by you/someone submitting a patch and a developer merging it into master.

B. If you need `external_api.js` for a deployment of your own, you can produce it yourself by running `webpack` with no arguments in a local clone of jitsi/jitsi-meet.

**Comment by eniltonangelim** [comment]
> Have you looked into why that happens? Is external_api.min.js causing a JS exception of some sort?

The application hides the exception, but it happens when I use the minimized version. During dynamic loading attempts Jitsi threw an exception in the JSON.parse method.

> A. If you need that resource on https://beta.meet.jit.si, then you have to convince a developer of ours to modify the project jitsi-meet so that it builds and deploys the unminimized artifact via the debian package. That could also be accomplished by you/someone submitting a patch and a developer merging it into master.

The https://beta.meet.jit.si was just a reference as an example.

> B. If you need external_api.js for a deployment of your own, you can produce it yourself by running webpack with no arguments in a local clone of jitsi/jitsi-meet.

I'll try to do that. Thank you very much for your support.

**Comment by lyubomir** [comment]
> Jitsi threw an exception in the JSON.parse method

Please send us the stack trace from that exception (and whatever additional console output that you can get) so that we have a chance to track the problem down and fix it.
