### ISSUE TITLE
1:1 call, not showing local video container (focus)

### ISSUE THREAD

**Issue by pedro-nonfree** [jitsi/jitsi-meet#1727]
Stable version is since "long" time ago (in debian). So this is still happening. Just reported a bug when I found little free time to do it. I hope is not a duplicate.

In 1:1 call I cannot see the local video container (focus?)

![2017-06-12-114156_866x515_scrot](https://user-images.githubusercontent.com/2603422/27808320-52fb3992-6047-11e7-9cd3-75edeb44353f.png)

With more and more participants (3 in this example), appears OK

![2017-06-12-114249_870x505_scrot](https://user-images.githubusercontent.com/2603422/27808323-56e21922-6047-11e7-9781-11ac7cd65cd9.png)

```
root@host:~# dpkg -l | grep jitsi-meet
ii  jitsi-meet                     1.0.2098-1                         all          WebRTC JavaScript video conferences
```

```
root@host:~# cat /etc/apt/sources.list.d/jitsi-stable.list 
deb https://download.jitsi.org stable/
#deb https://download.jitsi.org unstable/
```

**Comment by saghul** [comment]
Looks like your version is not old enough :-) We decided not to show the thumbnail for the remote participant for 1-1 calls because it confuses many people. Here is the commit: https://github.com/jitsi/jitsi-meet/commit/2333249b057ea61b440fa51a2aeb3f0b655ce1cf

You can disable it in your own deployment by setting `disable1On1Mode` to `true` in your config.js.
