### ISSUE TITLE
Safari 11 & iOS 11 WebRTC support (finally)

### ISSUE THREAD

**Issue by blackshrub** [jitsi/jitsi-meet#1769]
Does it still require TemWebRTC plugin for Safari v11 above?
Looks like Safari v11 and iOS 11's browser have supported WebRTC out of the box.

**Comment by saghul** [comment]
We will support Safari, but it's not yet supported without the plugin. Also, one major problem about Safari 11's WebRTC support is the lack of VP8. Simulcast is not supported for H264 in other browsers, so using H264 is not a viable option at the moment, since we can't use the advanced video routing features we need.

**Comment by Kukunin** [comment]
It's still good to have an option to use h264 without simulcast in `lib-jitsi-meet` for other applications

**Comment by saghul** [comment]
That's already possible.

**Comment by Kukunin** [comment]
afaik safari 11 is audio-only due to https://github.com/jitsi/lib-jitsi-meet/blob/fa58b973f09aab1d6e21f4d7f7023f678c7fe7ef/modules/RTC/RTCBrowserType.js#L324. I meant that it'd be better to enable video in Safari but make a warning about this item. 

Also, it seems it doesn't make sense to keep VP8 when preferring H264 since a client can't stream both codecs.
