### ISSUE TITLE
How to modify the code for a webinar mode?

### ISSUE THREAD

**Issue by RavinduRoshan** [jitsi/jitsi-meet#1887]
Actually I need a way to use jitsi videobridge as webinar mode. How to do that? Plz help

**Comment by saghul** [comment]
That is a very broad question, out of the scope of an issue tracker, I'd say.

Jitsi already offers you a number of features that can make it webinar friendly:

* authentication (users will wait for the moderator to enter)
* follow-me (users will follow the moderator)
* mandatory display names
* raise hand

There are, however, some missing pieces:

* force mute / unmute by the moderator
* (can't come up with more examples right now)

I suggest you install your own Jitsi Meet deployment, enable authentication and see how close it is to your expectations. I'm closing this because the question is too broad, but feel free to open new issues with more focused questions. Cheers!

**Comment by heyakyra** [comment]
#1675 and  #688 are relevant bugs to follow. 

Is there one for force mute as well?
