### ISSUE TITLE
Low Video Resolution / Bitrate

### ISSUE THREAD

**Issue by daytonturner** [jitsi/jitsi-meet#1986]
Heya,

Trying out the latest all-in-one installer, its incredibly often that participants have low resolution (320x180), including myself (640x360) when our cameras can do 720p, and we have plenty of bandwidth available.  Using the udp transport... Chrome..

The config file for jitsi-meet specifies  resolution: 720 ... 

Any other ideas?? What information can I gather?

**Comment by gpolitis** [comment]
Hi @daytonturner, thanks for raising this. Bandwidth is not the culprit here since you have plenty of it (how much?). Do you (or any of the other participants) run other network hungry programs running in the background? (Often times the congestion control algorithm that runs on the bridge fails to obtain a fair share of the bandwidth when it competes with TCP based flows. We don't have a solution for this, but we're working on it.)

Could you also please check if this is reproducible on https://beta.meet.jit.si/? We have a different congestion control algorithm running there that appears to be working better. (we use this environment for testing and we break it all the time, so please use it only for testing)

**Comment by daytonturner** [comment]
Hi @gpolitis thank you as well for your prompt reply!

Nobody else was running anything particularly network hungry.  There was at least 10mbps bi-directional bandwidth available on both ends.  We tried the beta URL
