### ISSUE TITLE
Firefox multiple transports & no p2p

### ISSUE THREAD

**Issue by petervnv** [jitsi/jitsi-meet#1993]
Hi guys,

As previously reported in https://github.com/jitsi/jitsi-meet/issues/1754.
Just tested with Ffox 55.0.2 on beta.meet.jit.si and still not able to get p2p working despite the same exact setup working fine with Chrome.

In fact the old multiple transports/ports bug is still there. See screenshot here https://imagebin.ca/v/3apH8pQVKl6P

Is anyone able to get p2p working with Firefox? If so, what version and platform?

Cheers,
Peter

**Comment by petervnv** [comment]
Just checked again with Firefox on https://beta.meet.jit.si and the issue remains.
Am I the only one seeing this behavior?

**Comment by damencho** [comment]
I can confirm I see the same error, you are not alone. We will fix this, no ETA at this point.

**Comment by petervnv** [comment]
Thanks @damencho 
I was beginning to think it was just me. I'll keep this issue open so we can keep track

**Comment by gpolitis** [comment]
Chrome and FF are not equals when it comes to p2p because of some technical limitations in [sdp-interop](https://github.com/jitsi/sdp-interop). More specifically P2P between two firefoxes has never worked because of https://github.com/jitsi/sdp-interop/issues/4. This issue is not trivial to fix, it's not on our roadmap and nobody's working on it afaik. We would love to have this working, it's just that we don't have enough bandwidth for that right now, but a contribution would be more than welcome.
