### ISSUE TITLE
Expired JWT can access to rooms

### ISSUE THREAD

**Issue by inkhey** [jitsi/jitsi-meet#2033]
I finally arrived to activate JWT token #2029 .
But expiration of token seems to not be supported.
Can someone else check ?

**Comment by inkhey** [comment]
I'm not sure but maybe it's a mistake from me, as token's error aren't correctly handled by jitsi, it isn't clear when we can or we cannot access to room.

**Comment by davidetrapani** [comment]
I wrote down a script in order to check the exp claim against current timestamp 
file is `/usr/share/jitsi-meet/prosody-plugins/token/util.lib.lua`

```
--- util.lib.orig.lua	2017-11-06 00:28:19.000000000 +0100
+++ util.lib.lua	2017-11-06 00:30:08.000000000 +0100
@@ -1,6 +1,6 @@
 -- Token authentication
 -- Copyright (C) 2015 Atlassian
-
+local socket = require "socket";
 local basexx = require "basexx";
 local have_async, async = pcall(require, "util.async");
 local hex = require "util.hex";
@@ -167,6 +167,19 @@
     return nil, "Invalid issuer ('iss' claim)";
 end
 
+--- Verifies expiration timestamp part of token
+-- @param 'expClaim' claim from the token to verify
+-- @return nil and error string or true for accepted claim
+function Util:verify_tokenExpirationTimestamp(expClaim)
+    local currentTimestamp = socket.gettime()*1000;
+    module:log("debug", "current timestamp %s, token expiration %s", currentTimestamp, expClaim); 
+    if expClaim >= currentTimestamp then
+        --claim greater or equal current timestamp so return success
+        return true;
+    end
+    return nil, "Invalid token expiration timestamp ('exp' claim)";
+end
+
 --- Verifies audience part of token
 -- @param 'aud' claim from the token to verify
 -- @return nil and error string or true for accepted claim
@@ -225,6 +238,14 @@
         return nil, audCheckErr;
     end
 
+    --check the expiration timestamp against current timestamp
+    local expClaim = claims["exp"];
+    local expCheck, expCheckErr = self:verify_tokenExpirationTimestamp(expClaim);
+    if expCheck == nil then
+        module:log("error", "token expired");
+        return nil, expCheckErr;
+    end
+
     return claims;
 end
 
@@ -238,7 +259,6 @@
 -- @param session the current session
 -- @return false and error
 function Util:process_and_verify_token(session)
-
     if session.auth_token == nil then
         if self.allowEmptyToken then
             return true;
@@ -308,7 +328,7 @@
             "debug",
             "Skipped room token verification - empty tokens are allowed");
         return true;
-    end
+     end
 
     -- extract room name using all chars, except the not allowed ones
     local room,_,_ = jid.split(room_address);
@@ -373,4 +393,4 @@
     end
 end
 
-return Util;
\ No newline at end of file
+return Util;
```

**Comment by damencho** [comment]
You don't need a custom code to check token expiration as this is already handled using, luajwtjitsi: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/token/util.lib.lua#L193

@yanas was testing tokens last week and trying the improve the error reporting. 
There is a general problem, that the errors are returned inside the bosh request and those errors cannot be accessed outside Strophe. In order to be able to differentiate and report different jwt errors, Strophe needs to be changed to expose those errors, we have it in out todo, but there is no ETA at the moment.

We also found a bug and fixed it. It was about not correctly replying to jwt errors: 
https://github.com/jitsi/jitsi-meet/commit/98111c3593ac0274c9f27dfd7d1e720829b62654#diff-b49ed3445813b2476951bfe808c1632a
Before this fix(in the period from Aug 8 to Oct 26) prosody was not responding at all to packets received which contain an invalid token.
