### ISSUE TITLE
JitsiMeetView.onBackPressed() return value

### ISSUE THREAD

**Issue by borune-k12** [jitsi/jitsi-meet#2059]
Hello, in what cases JitsiMeetView.onBackPressed() will return false? Seems it always returns true.

**Comment by lyubomir** [comment]
The static method `JitsiMeetView.onBackPressed()` will return `false` if you haven't created a `JitsiMeetView` instance yet; otherwise, it will return `true`.

Please note the static method `JitsiMeetView.onHostResume(Activity, DefaultHardwareBackBtnHandler)` which allows you to optionally specify your own implementation of `DefaultHardwareBackBtnHandler` and, thus, override the default behavior of `finish`ing the `Activity`.
