### ISSUE TITLE
How to install jitsi on android version 4.0

### ISSUE THREAD

**Issue by hieuptit93** [jitsi/jitsi-meet#2063]
Jitsi only support 4.1 or higher.
How to install jitsi on smart glasses Vuzix M100
Link here:
https://www.vuzix.com/Products/m100-smart-glasses

**Comment by ZuzooVn** [comment]
Does Jitsi have the plan to support  Android-based Smart Glasses?

**Comment by lyubomir** [comment]
We do not have immediate plans to support smart glasses or any other devices running Android 4.0.

**Comment by ZuzooVn** [comment]
Thanks @lyubomir 

We want to support smart glasses. Do you have any suggestion for us? Is it impossible?

**Comment by saghul** [comment]
I have 2 suggestions:

- Ask your vendor to update the Android version, 4.0 has been unsupported for years
- Try to modify the project to target API level 15 and solve all problems along the way

If you go with the latter, note that we probably wouldn't accept those patches because that version is simply too old for us to support.
