### ISSUE TITLE
Change Thumbnail Resolution!

### ISSUE THREAD

**Issue by hosseinsmart** [jitsi/jitsi-meet#2099]
hi
i want to change the resolution of remote video on thumbnails, default is 320x180 px. please help me!

**Comment by saghul** [comment]
Hi there! That is currently not possible.  Thumbnails will always be the lowest possible (is the sender supports simulcast). When a participant is selected (either manually or because they are speaking) we will switch to a higher resolution and show them on the large view.

What are you trying to accomplish?

**Comment by hosseinsmart** [comment]
thank you, i want to lower the traffic of bandwidth.

**Comment by saghul** [comment]
We don't have that capability on mobile yet. We do on the web, so we'll eventually have it on both.

**Comment by jesoa** [comment]
Hi dear sirs, current Thumbnail size is 80 * 80px at this moment. can I change the height size? for example 120 * 80px. thanks in advance for your help.
