### ISSUE TITLE
jitsi-meet(React-native ) Secondary development

### ISSUE THREAD

**Issue by yxwandroid** [jitsi/jitsi-meet#2171]
How do I add pages to the jitsi-meet project?
I want to add my own address book interface in the jitsi-meet(react-native) project,
but I don't know how to integrate the project
Is there any way?
I tried to integrate with the react-navigation but failed

**Comment by lyubomir** [comment]
If your address book (interface) is to be consumed strictly outside of a conference, then you'd probably want to do something similar to how react/features/welcome/components/WelcomePage and react/features/conference/components/Conference are used.

Otherwise, you'll probably want do an "overlay" rendered by react/features/conference/components/Conference like react/features/toolbox/components/Toolbox and react/features/filmstrip/components/Filmstrip.
