### ISSUE TITLE
recipe for target 'deploy-lib-jitsi-meet' failed

### ISSUE THREAD

**Issue by tcmalloc** [jitsi/jitsi-meet#2214]
mkdir -p libs
cp \
        build/app.bundle.min.js \
        build/app.bundle.min.map \
        build/do_external_connect.min.js \
        build/do_external_connect.min.map \
        build/external_api.min.js \
        build/external_api.min.map \
        build/device_selection_popup_bundle.min.js \
        build/device_selection_popup_bundle.min.map \
        build/alwaysontop.min.js \
        build/alwaysontop.min.map \
        ./analytics.js \
        libs
cp \
        node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js \
        node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map \
        node_modules/lib-jitsi-meet//connection_optimization/external_connect.js \
        libs
cp: cannot stat 'node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js': No such file or directory
cp: cannot stat 'node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map': No such file or directory
Makefile:42: recipe for target 'deploy-lib-jitsi-meet' failed

**Comment by damencho** [comment]
Did you run npm install before doing make?

**Comment by flberger** [comment]
Looks like I have the same issue here.

## Description
I am following the installation procedure at https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md At "Deploy Jitsi Meet", it says:

> cd /srv
> git clone https://github.com/jitsi/jitsi-meet.git
> cd jitsi-meet
> npm install
> make

## Current behavior
`make` fails with:

>cp \
>	node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js \
>	node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map \
>	node_modules/lib-jitsi-meet//connection_optimization/external_connect.js \
>	node_modules/lib-jitsi-meet//modules/browser/capabilities.json \
>	libs
>cp: cannot stat 'node_modules/lib-jitsi-meet//lib-jitsi-meet.min.js': No such file or directory
>cp: cannot stat 'node_modules/lib-jitsi-meet//lib-jitsi-meet.min.map': No such file or directory
>make: *** [Makefile:59: deploy-lib-jitsi-meet] Error 1

Everything above that message looks fine to me.

I had some issues with npm install before, see #5267 . But in theory, everything should be there now.

## Expected Behavior
The files should be there, and make should finish without errors.

# Environment details
OS is Gentoo linux, npm 6.12.0
