### ISSUE TITLE
android: provide option to put microphone/camera controls (mute/video on/off) at the top of screen

### ISSUE THREAD

**Issue by cloph** [jitsi/jitsi-meet#2223]
Right now, the controls to mute/unmute and turn on/off the camera are located at the bottom of the screen. This makes them hard to reach when you put your phone (or tablet) in a stand that partly obstructs the lower portion of the screen, especially with the slim-bezel type phones.
This in turn makes it hard to hit mute/unmute without either twisting your arm/fingers to approach the screen at a shallow angle, or pick up the phone.

An easy (for the user) solution would be to have the controls at the top of the screen. That way they're easily accessible and the world doesn't shake (when picking up the phone :-))

**Comment by nekohayo** [comment]
I would add to this: it makes it really hard to operate the phone (for mute/unmute/etc.) with one hand while you're taking a walk, because it's much easier to have a secure hold with one hand if you can use your thumb to interact with buttons at the top of the screen, than if you have to hold everything by a small corner at the bottom and contort your thumb finger to try to hit the bottom without hitting the Back/Home/Switcher buttons.

**Comment by saghul** [comment]
We are unlikely to change the current layout, sorry. The entire industry has decided on bottom toolbars and it's a sue case that most users are already familiar with.
