### ISSUE TITLE
Files in /var/lib/prosody are erroneously owned by root:root, after fresh install

### ISSUE THREAD

**Issue by afcady** [jitsi/jitsi-meet#2244]
I commented on this in #1331 and I will repeat what I wrote there:

-----

I have the same problem.  The logs in `/var/log/prosody/prosody.err` did show what happened:

    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/domainname.com.key': Check that the permissions allow Prosody to read this file. (for focus.domainname.com)
    Dec 03 14:49:55 focus.domainname.com:tls    error   Unable to initialize TLS: error loading private key (Permission denied)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/domainname.com.key': Previous error (see logs), or other system error. (for focus.domainname.com)
    Dec 03 14:49:55 focus.domainname.com:tls    error   Unable to initialize TLS: error loading private key (system lib)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/domainname.com.key': Previous error (see logs), or other system error. (for conference.domainname.com)
    Dec 03 14:49:55 conference.domainname.com:tls       error   Unable to initialize TLS: error loading private key (system lib)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/domainname.com.key': Check that the permissions allow Prosody to read this file. (for conference.domainname.com)
    Dec 03 14:49:55 conference.domainname.com:tls       error   Unable to initialize TLS: error loading private key (Permission denied)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/domainname.com.key': Previous error (see logs), or other system error. (for jitsi-videobridge.domainname.com)
    Dec 03 14:49:55 jitsi-videobridge.domainname.com:tls        error   Unable to initialize TLS: error loading private key (system lib)
    Dec 03 14:49:55 certmanager error   SSL/TLS: Failed to load '/etc/prosody/certs/domainname.com.key': Previous error (see logs), or other system error. (for jitsi-videobridge.domainname.com)
    Dec 03 14:49:55 jitsi-videobridge.domainname.com:tls        error   Unable to initialize TLS: error loading private key (system lib)

    [etc.]

Somehow the certificates in `/var/lib/prosody/` got installed with ownership `root:root`.

This fixed the issue:

    sudo chown prosody:prosody -R /var/lib/prosody/
    sudo service prosody restart

This was a fresh install of jitsi-meet (1.0.2635-1).  I had never touched that directory.  So there must be a bug in the jitsi-meet certificate install code.

Here is some more information about my system:

    ||/ Name               Version      Architecture Description
    +++-==================-============-============-=================================================
    ii  jitsi-meet         1.0.2635-1   all          WebRTC JavaScript video conferences
    ii  jitsi-meet-prosody 1.0.2441-1   all          Prosody configuration for Jitsi Meet
    ii  jitsi-videobridge  1011-1       amd64        WebRTC compatible Selective Forwarding Unit (SFU)

**Comment by damencho** [comment]
I will test this and will report it to the prosody community if needed. But the folder /var/lib/prosody is not anything we are controlling, this folder is created and managed by prosody packages.

**Comment by damencho** [comment]
And I haven't seen this problem before, doing a number of clean installs.
@afcady can you check and tell me which prosody version are you using?

**Comment by afcady** [comment]
||/ Name           Version      Architecture Description
    +++-==============-============-============-=================================
    ii  prosody        0.9.12-2     amd64        Lightweight Jabber/XMPP server

**Comment by afcady** [comment]
It's not true that jitsi is not doing anything in `/var/lib/prosody`.  See, e.g.,  https://github.com/jitsi/jitsi-meet/blob/ac3a74c47e61320aa42a1de06c269c62c971c7d6/debian/jitsi-meet-prosody.postinst#L117

**Comment by damencho** [comment]
Where do you see it to change the permissions of the /var/lib/prosody folder, as you have reported. This is a responsibility of prosody package. We are just writing a file in that folder.

**Comment by damencho** [comment]
By default, that folder is created with permissions prosody:prosody, and if it happens to be root:root, this will be a problem, but writing a file there will not change the parent folders permisisons.

**Comment by afcady** [comment]
The directory's permission wasn't the issue.  It was the files in the directory.  Here, I will show you:

    # ls -laR /var/lib/prosody
    /var/lib/prosody:
    total 16
    0 drwxr-x--- 1 prosody prosody  166 Dec  3 14:44 ./
    0 drwxr-xr-x 1 root    root     802 Dec  3 14:43 ../
    0 drwxr-x--- 1 prosody prosody   16 Dec  3 14:43 auth%2edomainname/
    4 -rw-r--r-- 1 root    root    2057 Dec  3 14:44 auth.domainname.crt
    4 -rw------- 1 root    root    3272 Dec  3 14:44 auth.domainname.key
    4 -rw-r--r-- 1 root    root    2045 Dec  3 14:43 domainname.crt
    4 -rw------- 1 root    root    3272 Dec  3 14:43 domainname.key

    /var/lib/prosody/auth%2edomainname:
    total 0
    0 drwxr-x--- 1 prosody prosody  16 Dec  3 14:43 ./
    0 drwxr-x--- 1 prosody prosody 166 Dec  3 14:44 ../
    0 drwxr-x--- 1 prosody prosody  18 Dec  3 14:43 accounts/

    /var/lib/prosody/auth%2edomainname/accounts:
    total 4
    0 drwxr-x--- 1 prosody prosody 18 Dec  3 14:43 ./
    0 drwxr-x--- 1 prosody prosody 16 Dec  3 14:43 ../
    4 -rw-r----- 1 prosody prosody 40 Dec  3 14:43 focus.dat

**Comment by damencho** [comment]
So it must be some setting on those machines, not sure is openssl managing the file permissions... I have checked two machines one 14.04 and one 16.04 both have:
-rw-r--r-- 1 root    root    2037 Oct  9 15:35 auth.domain.crt
I agree that those files can be changed to be prosody:prosody, I'm taking a note to change it.

**Comment by harindrarasanjali** [comment]
Hi damencho,
I am using Prosody server to communicate agents implemented in SPADE python. But after creating 31 agents the server seems to hang. And I can see the logs as "Client disconnected: closed". I have used self-signed cert files as described in the documentation.

Kindly help me to fix this issue. I was struggling for more than two weeks to fix these issues.

Following is my config file content:
-----------------------------------------

-- Prosody XMPP Configuration File
--
-- Information on configuring Prosody can be found on our
-- website at https://prosody.im/doc/configure
--
-- Tip: You can check that the syntax of this file is correct
-- when you have finished by running this command:
--     prosodyctl check config
-- If there are any errors, it will let you know what and where
-- they are, otherwise it will keep quiet.
--
-- Good luck, and happy Jabbering!


---------- Server-wide settings ----------
-- Settings in this section apply to the whole server and are the default settings
-- for any virtual hosts

-- This is a (by default, empty) list of accounts that are admins
-- for the server. Note that you must create the accounts separately
-- (see https://prosody.im/doc/creating_accounts for info)
-- Example: admins = { "user1@example.com", "user2@example.net" }
admins = { "harindra@ip-172-31-18-136.us-east-2.compute.internal" }

--HARINDRA
use_tls=False
allow_anonymous_s2s = true

log = {
       debug = "/var/log/prosody/prosodyDebug.log"; -- Send debug and higher here
       error = "/var/log/prosody/prosodyError.log"; -- Send error and higher to the syslog sink
       info = "/var/log/prosody/prosodyInfo.log"; 
       warn = "/var/log/prosody/prosodyWarn.log";   
 }
-- Enable use of libevent for better performance under high load
-- For more information see: https://prosody.im/doc/libevent
--use_libevent = true

-- Prosody will always look in its source directory for modules, but
-- this option allows you to specify additional locations where Prosody
-- will look for modules first. For community modules, see https://modules.prosody.im/
--plugin_paths = {}

-- This is the list of modules Prosody will load on startup.
-- It looks for mod_modulename.lua in the plugins folder, so make sure that exists too.
-- Documentation for bundled modules can be found at: https://prosody.im/doc/modules
modules_enabled = {

	-- Generally required
		"roster"; -- Allow users to have a roster. Recommended ;)
		"saslauth"; -- Authentication for clients and servers. Recommended if you want to log in.
		"tls"; -- Add support for secure TLS on c2s/s2s connections
		"dialback"; -- s2s dialback support
		"disco"; -- Service discovery

	-- Not essential, but recommended
		"carbons"; -- Keep multiple clients in sync
		"pep"; -- Enables users to publish their avatar, mood, activity, playing music and more
		"private"; -- Private XML storage (for room bookmarks, etc.)
		"blocklist"; -- Allow users to block communications with other users
		"vcard4"; -- User profiles (stored in PEP)
		"vcard_legacy"; -- Conversion between legacy vCard and PEP Avatar, vcard

	-- Nice to have
		"version"; -- Replies to server version requests
		"uptime"; -- Report how long server has been running
		"time"; -- Let others know the time here on this server
		"ping"; -- Replies to XMPP pings with pongs
		"register"; -- Allow users to register on this server using a client and change passwords
		--"mam"; -- Store messages in an archive and allow users to access it
		--"csi_simple"; -- Simple Mobile optimizations

	-- Admin interfaces
		"admin_adhoc"; -- Allows administration via an XMPP client that supports ad-hoc commands
		--"admin_telnet"; -- Opens telnet console interface on localhost port 5582

	-- HTTP modules
		--"bosh"; -- Enable BOSH clients, aka "Jabber over HTTP"
		--"websocket"; -- XMPP over WebSockets
		--"http_files"; -- Serve static files from a directory over HTTP

	-- Other specific functionality
		--"limits"; -- Enable bandwidth limiting for XMPP connections
		--"groups"; -- Shared roster support
		--"server_contact_info"; -- Publish contact information for this service
		--"announce"; -- Send announcement to all online users
		--"welcome"; -- Welcome users who register accounts
		--"watchregistrations"; -- Alert admins of registrations
		--"motd"; -- Send a message to users when they log in
		--"legacyauth"; -- Legacy authentication. Only used by some old clients and bots.
		--"proxy65"; -- Enables a file transfer proxy service which clients behind NAT can use
}

-- These modules are auto-loaded, but should you want
-- to disable them then uncomment them here:
modules_disabled = {
	-- "offline"; -- Store offline messages
	-- "c2s"; -- Handle client connections
	-- "s2s"; -- Handle server-to-server connections
	-- "posix"; -- POSIX functionality, sends server to background, enables syslog, etc.
}

-- Disable account creation by default, for security
-- For more information see https://prosody.im/doc/creating_accounts
allow_registration = true

-- Force clients to use encrypted connections? This option will
-- prevent clients from authenticating unless they are using encryption.

c2s_require_encryption = true

c2s_ports = { 5222 } -- Listen on 5322 as well as 5222


-- Force servers to use encrypted connections? This option will
-- prevent servers from authenticating unless they are using encryption.

s2s_require_encryption = true

-- Force certificate authentication for server-to-server connections?

s2s_secure_auth = true

-- Some servers have invalid or self-signed certificates. You can list
-- remote domains here that will not be required to authenticate using
-- certificates. They will be authenticated using DNS instead, even
-- when s2s_secure_auth is enabled.

--s2s_insecure_domains = { "insecure.example" }

-- Even if you disable s2s_secure_auth, you can still require valid
-- certificates for some domains by specifying a list here.

--s2s_secure_domains = { "jabber.org" }

-- Select the authentication backend to use. The 'internal' providers
-- use Prosody's configured data storage to store the authentication data.

authentication = "internal_hashed"

-- Select the storage backend to use. By default Prosody uses flat files
-- in its configured data directory, but it also supports more backends
-- through modules. An "sql" backend is included by default, but requires
-- additional dependencies. See https://prosody.im/doc/storage for more info.

--storage = "sql" -- Default is "internal" (Note: "sql" requires installed
-- lua-dbi RPM package)

-- For the "sql" backend, you can uncomment *one* of the below to configure:
--sql = { driver = "SQLite3", database = "prosody.sqlite" } -- Default. 'database' is the filename.
--sql = { driver = "MySQL", database = "prosody", username = "root", password = "9Xcjy7Y49CY", 
--host = "127.0.0.1" }
--sql = { driver = "PostgreSQL", database = "prosody", username = "prosody", password = "secret", host = "localhost" }


-- Archiving configuration
-- If mod_mam is enabled, Prosody will store a copy of every message. This
-- is used to synchronize conversations between multiple clients, even if
-- they are offline. This setting controls how long Prosody will keep
-- messages in the archive before removing them.

archive_expires_after = "1w" -- Remove archived messages after 1 week

-- You can also configure messages to be stored in-memory only. For more
-- archiving options, see https://prosody.im/doc/modules/mod_mam

-- Logging configuration
-- For advanced logging see https://prosody.im/doc/logging
log = {
	-- Log everything of level "info" and higher (that is, all except "debug" messages)
	-- to /var/log/prosody/prosody.log and errors also to /var/log/prosody/prosody.err
	info = "/var/log/prosody/prosody.log"; -- Change 'info' to 'debug' for verbose logging
	error = "/var/log/prosody/prosody.err"; -- Log errors also to file
	-- error = "*syslog"; -- Log errors also to syslog
	-- "*console"; -- Log to the console, useful for debugging with daemonize=false
}

-- Uncomment to enable statistics
-- For more info see https://prosody.im/doc/statistics
-- statistics = "internal"

-- Certificates
-- Every virtual host and component needs a certificate so that clients and
-- servers can securely verify its identity. Prosody will automatically load
-- certificates/keys from the directory specified here.
-- For more information, including how to use 'prosodyctl' to auto-import certificates
-- (from e.g. Let's Encrypt) see https://prosody.im/doc/certificates

-- Location of directory to find certificates in (relative to main config file):
--certificates = "/etc/pki/prosody/"
certificates = "/var/lib/prosody/ip-172-31-18-136.us-east-2.compute.internal.crt"

-- HTTPS currently only supports a single certificate, specify it here:
--https_certificate = "/etc/prosody/certs/localhost.crt"

-- POSIX configuration
-- For more info see https://prosody.im/doc/modules/mod_posix
pidfile = "/run/prosody/prosody.pid";
--daemonize = false -- Default is "true"

----------- Virtual hosts -----------
-- You need to add a VirtualHost entry for each domain you wish Prosody to serve.
-- Settings under each VirtualHost entry apply *only* to that host.

VirtualHost "ip-172-31-18-136.us-east-2.compute.internal"
      enabled = true  
      ssl = {
          key = "/var/lib/prosody/ip-172-31-18-136.us-east-2.compute.internal.key";
          certificate = "/var/lib/prosody/ip-172-31-18-136.us-east-2.compute.internal.crt";
	  } 
--	certificate = "/path/to/example.crt"

------ Components ------
-- You can specify components to add hosts that provide special services,
-- like multi-user conferences, and transports.
-- For more information on components, see https://prosody.im/doc/components

---Set up a MUC (multi-user chat) room server on conference.example.com:
--Component "conference.example.com" "muc"
--- Store MUC messages in an archive and allow users to access it
--modules_enabled = { "muc_mam" }

---Set up an external component (default component port is 5347)
--
-- External components allow adding various services, such as gateways/
-- transports to other networks like ICQ, MSN and Yahoo. For more info
-- see: https://prosody.im/doc/components#adding_an_external_component
--
--Component "gateway.example.com"
--	component_secret = "password"

------ Additional config files ------
-- For organizational purposes you may prefer to add VirtualHost and
-- Component definitions in their own config files. This line includes
-- all config files in /etc/prosody/conf.d/

Include "conf.d/*.cfg.lua"

**Comment by afcady** [comment]
@harindrarasanjali this is not the appropriate place to request support.  Your request has nothing to do with bug #2244.  File a new bug report under a new number and title.
