### ISSUE TITLE
Why jitsi-meet 's installation is so difficult?

### ISSUE THREAD

**Issue by huiminsi** [jitsi/jitsi-meet#2324]
I have install this system use below url:
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md
(system:debain 9.3.0)
After installation, there are so many errors.

and , I have install this system use below url:
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md
(system:ubuntu-16.04.3)
After installation, the video on the camera can't be seen .

unfortunately , Not success . I have spent more than a week to install it. 
How should I do ?

**Comment by damencho** [comment]
You have done the quick install on the same machine after doing the manual install? It is possible that even after cleaning up, there can be a lot left after the manual install and many things can go wrong.
One possible solution is to send some logs here so we can try helping you out to fix it, it shouldn't be so bad or you can try on clean debian/ubuntu to deploy it.

**Comment by huiminsi** [comment]
I deploy it in the Vmware.

**Comment by damencho** [comment]
If you don't see your own camera this maybe problem with prosody configuration or jicofo, we need js console logs, and jicofo logs to identify the problem.
With vms normally the problem is opening and forwarding ports and configuring the ip addresses in jvb configuration: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
