### ISSUE TITLE
[Bug Report] Jicofo doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by atb00ker** [jitsi/jitsi-meet#2386]
Steps to reproduce:
I spin up a new machine running Ubuntu 14.04 and follow this page: https://github.com/jitsi/jitsi-meet/wiki/Quick-install-on-Ubuntu-14.04LTS_x86_64
I get error with Jifoco.log:
Jicofo 2018-01-14 11:59:56.190 SEVERE: [26] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: The followi
ng addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connection refused (Conn
ection refused)

**Comment by damencho** [comment]
I think, this should go away and it connects after a moment. Is this right? Is it working, if you give it some time?
The time prosody restarts and then jicofo starts retrying connection several times.

**Comment by damencho** [comment]
I just tested it and I think the problem is the oracle-installer. Will update the wiki once I found the working steps.

**Comment by damencho** [comment]
Just created new 14.04 and installed using the edited wiki page and works without a problem.

Mind that you can still see the error:
The following addresses failed: 'localhost:5222'
and :
java.net.ConnectException: Connection refused (Connection refused), host:localhost, port:5347
But this is due to prosody loading, after that it connects and everything works fine.
