### ISSUE TITLE
Uninstalling and reinstalling jitsi-meet leads to javax.net.ssl.SSLHandshakeException

### ISSUE THREAD

**Issue by jean-ben-guigui** [jitsi/jitsi-meet#2391]
Hello,

I have tried the following steps:
- Installing Jitsi-meet on Ubuntu 16.04.
- Testing my installation: all is great!
- Uninstalling Jitsi-meet using this cmd "sudo apt-get purge jigasi prosody jitsi-meet jitsi-meet-web-config jitsi-meet-web jicofo jitsi-videobridge" and then "sudo apt-get autoremove".
- Installing Jitsi-meet again.
- Jitsi-meet works in P2P but when a third person enter the room, the screen becomes black.
These are my logs:
[jicofo.log](https://github.com/jitsi/jitsi-meet/files/1635802/jicofo.log)
[jvb.log](https://github.com/jitsi/jitsi-meet/files/1635855/jvb.log)
[prosody.log](https://github.com/jitsi/jitsi-meet/files/1635856/prosody.log)

From the client side, I can only see this warning:
![image](https://user-images.githubusercontent.com/15104156/34998516-8697c602-fadf-11e7-89b6-1fea2578f3f1.png)

I have tried using a proper certificate and a self-signed one, the problem remains the same.
I also tried to add my certificate to the javaKeyStore, led to nothing.

Maybe I am not uninstalling jitsi-meet properly? Else this is quite a bug... Is there a way around it?

Any help would be highly appreciated

**Comment by damencho** [comment]
Thanks for the steps to reproduce it, I will try it in a bit, I was planning to test it.
The problem is the certificate that is used for auth.domain is not trusted on the machine ... I kept telling people to try removing /etc/ssl/certs/java/cacerts and run update-ca-certificates, but maybe it doesn't fixes it (you can try it or maybe and update-ca-certificates -f). 
I was planning to test it today to see where is the problem, cause we had several such reports last few weeks.

**Comment by damencho** [comment]
So I just tested it and it works. 
To remove I used:
apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-web jitsi-meet-prosody jicofo jitsi-videobridge prosody
Then I did apt-get install jitsi-meet and it resulted the problem you have in the logs and executing the following command fixed it:
update-ca-certificates -f

**Comment by jean-ben-guigui** [comment]
Thanks a lot, that was it!
