### ISSUE TITLE
Grey screen and config not defined

### ISSUE THREAD

**Issue by HackerUnicorn** [jitsi/jitsi-meet#2574]
Hello,

I had to reinstall jitsi and now I'm having problem with a grey screen. With inspect I have errors: `Uncaught SyntaxError: Unexpected token <           (index):132 `

`Uncaught ReferenceError: config is not defined                               
    at Object.<anonymous> (AuthHandler.js:18)
    at Object.<anonymous> (AuthHandler.js:227)
    at t (bootstrap f4842a46b24bc2fc8a3d:19)
    at Object.<anonymous> (connection.js:184)
    at Object.<anonymous> (connection.js:144)
    at t (bootstrap f4842a46b24bc2fc8a3d:19)
    at Object.<anonymous> (jquery.autosize.js:274)
    at Object.<anonymous> (conference.js:2818)
    at t (bootstrap f4842a46b24bc2fc8a3d:19)
    at Object.<anonymous> (_replacer.js:6)
    at t (bootstrap f4842a46b24bc2fc8a3d:19)
    at Object.<anonymous> (Profile.js:191)
    at t (bootstrap f4842a46b24bc2fc8a3d:19)
    at bootstrap f4842a46b24bc2fc8a3d:62
    at bootstrap f4842a46b24bc2fc8a3d:62`

`Uncaught ReferenceError: config is not defined                          
    at Object.lookup (configLanguageDetector.js:22)
    at index.js:97
    at Array.forEach (<anonymous>)
    at e.value (index.js:95)
    at t.changeLanguage (i18next.js:286)
    at l (i18next.js:159)`

I have not modified my index.html file at /usr/share/jitsi-meet directory and I have no idea where these errors come.

**Comment by damencho** [comment]
You have an error in the ....-config.js file, I think and it is not loading. It is in /etc/jitsi/meet.

**Comment by HackerUnicorn** [comment]
I was able to fix it. My .config.js file was in a wrong location. After I copied it to the right place it worked fine.

**Comment by DigitalCoder** [comment]
Hi !
how did you fix it ?
where did you place it ?

thx

**Comment by Ark74** [comment]
Also please check all your ',' (commas) I've found myself on this before because of this.

**Comment by frankodoom** [comment]
> Also please check all your ',' (commas) I've found myself on this before because of this.
Had same issue with , and spacing...fixed it 👍

**Comment by WestleyArgentum** [comment]
😭

**Comment by WestleyArgentum** [comment]
For the next person who finds this:

I was on debian using the apt packages and nginx. It's confusing because some of the documentation references `/usr/share/jitsi-meet/config.js` and says simply that you should "adapt this file to your needs". That file doesn't exist by default though.

You may come across `/usr/share/jitsi-meet-web-config/config.js` and think you are finally on to something, but actually if you provided your domain name when installing the apt packages they will have already created `/etc/jitsi/meet/<domain_name>-config.js` (a semi-customized version of the default config) for you.

I don't know why this file doesn't get a mention in the docs (or why it isn't just copied to `/usr/share/jitsi-meet/config.js` like the docs seem to expect... but you can either copy / symlink it yourself or, if like me you are worried that might cause confusion down the line, you can drop something like this into your nginx config:

```
location = /config.js {
    alias /etc/jitsi/meet/<domain_name>-config.js;
}
```
