### ISSUE TITLE
How to match Jitsi Meet Play Store version with Github release version?

### ISSUE THREAD

**Issue by calamatitech** [jitsi/jitsi-meet#2710]
I tried to find in the release story the zip file matching the current version, 1.14.75, of the Android App in the Play Store.
If I look at the version written in the file android/app/build.gradle, the result is the following (date in the format dd/mm/yyyy):
2608 01/03/2018 version 1.9
2522 27/12/2017 version 1.9
2493 07/12/2017 version 1.9
2465 15/11/2017 version 1.9
2413 01/09/2017 version 1.4
2179 01/08/2017 version 1.4
2065 29/06/2017 version 1.4
and so on ...
The date in Play Store of the version 1.14.75 is 01/03/2018, so it is difficult to think that the version written in the file build.gradle can be help to find it.

**Comment by saghul** [comment]
Ignore the build number on the gradle file, as I mentioned here: https://github.com/jitsi/jitsi-meet/issues/2658#issuecomment-376439546 we cannot build straight out of GitHub, due to some limitations on how we sign the apps.

That said, the current version there can be misleading, so I'm going to try and set it to 0 or something more obvious.
