### ISSUE TITLE
Create a chat room for newcomers

### ISSUE THREAD

**Issue by patcon** [jitsi/jitsi-meet#2721]
Hi there!

I've been googling around, and trying to ask a quick question and basically just talk to humans in the community, but I'm not seeing an easy way to do that in realtime. Is that intentional?

First-off, I do see that you very generously provide a bunch of contact methods! Regular video calls, github issues, multiple mailing lists. There just doesn't seem to be a way for community members to talk amongst themselves in realtime, or at least for newcomers to easily do so :)

If you have a private Slack, you could easily set up a chat bridge between a public gitter channel and a Slack channel named `#public-lobby` or something like that. Matterbridge is a great tool that I use for things like that, and it [runs on Heroku](https://github.com/edgi-govdata-archiving/matterbridge-heroku). It can also be bridges with IRC channels, if that's a place where community also gathers.

**Comment by damencho** [comment]
There are people at https://desktop.jitsi.org/Development/MailingLists#irc ( jitsi @ freenode ). Not that we all hang in there, but there are people in there. But still, the best way to reach the community is through GitHub issues and the mailing lists.

**Comment by patcon** [comment]
Thanks @damencho! So to get clarity, are there any private synchronous chat tools that the core team uses amongst itself?

**Comment by patcon** [comment]
And I realize this might require some internal deliberation, but can the core team create a Gitter community from the github org? (You wouldn't need to use it, and so it requires no further effort after creation.) If so, I can bridge the default "Lobby" chat room with IRC, and would love to take a stab at animating it as a useful place for the community.

At the very least, the Gitter channel will be no more dead or alive than the existing IRC, which you already document as a place where the community exists (in a small way) -- but it will be accessible to new audiences :)

**Comment by patcon** [comment]
> I'm personally not for adding another synchronous communication channel.

Thanks a bunch for engaging with the premise @saghul. To your point -- too many comms channels -- I empathize with that as someone who has in past lives got stuck maintaining a bunch of places.

First off, I think everything y'all are doing for this project is rad. If anything here comes across as criticism, then it's cause I fucked up my finger-speak 💥 

Here are some :mag: facts, :heart: feelings and :bulb: ideas around this as I understand it:

1. :mag: **Communication channels** can be one-way or two-way.
1. :mag: **Conversation channels** are two-way communication channels.
1. :mag: We have 6 _conversation_ channels:
    - 4 async:  2 mailing lists (`user` and `dev`), GitHub Issues, [StackOverflow](https://stackoverflow.com/questions/tagged/jitsi)
    - 2 realtime: IRC and calls.
1. :mag: [Calls](https://www.youtube.com/channel/UCeMZszvzwsXv1HkLvZmeZVw) happen biweekly at 10:30am CT, up to 30 min. _(Doing this is AWESOME btw.)_
1. :mag: One time slot can't work for everyone.
    - People in Asia? People with day jobs?
    - It's frustratingly impossible to schedule one right time for an open source project :)
1. :mag: IRC is essentially inactive in its current form.
1. :mag: IRC lacks history for non-advanced users.
1. :heart: I feel that the Jitsi community offers limited realtime communication options at the moment.
1. :heart: I feel that realtime chat is ephemeral, with history or without.
1. :heart: I feel that social practices around ephemeral chat can support effective usage of GitHub tickets. Contributors can be gently encouraged to do support work that brings ephemeral conversation into places of long-term project memory.
1. :heart: I feel inspired by the Public Lab software dev community's [chat strategy](https://publiclab.org/chat) and their general [software outreach strategies](https://publiclab.org/wiki/software-outreach).
1. :mag: The Public Lab community bridges all the places -- IRC + [Gitter](https://gitter.im/publiclab/publiclab) + staff Slack + Riot
1. :heart: I feel that publiclab.org has a super-vibrant dev community, in part because it welcomes realtime chat as a way to build social bonds between community members. This lets community members hold themselves together, rather than the core dev team doing that "holding" work, like in Community Calls.
1. :mag: A simple and powerful open source chat bridge option is [Matterbridge](https://github.com/42wim/matterbridge).
1. :mag: @patcon is willing to bridge with his instance for free, to try it out indefinitely.
1. :mag: Creating a gitter community automatically creates a lobby chat room.
1. :mag: @patcon can connect IRC and Gitter without any effort from Team Jitsi.
1. :heart: I feel it will be simple/cheap to host the bridge yourself if you see value in it. If there's no value, there's no effort to discontinue usage.
1. :mag: Matterbridge can be hosted for $7/month on Heroku via [`matterbridge-heroku`](https://github.com/cadecairos/matterbridge-heroku).
1. :bulb: Team Jitsi could create a Gitter chat room. @patcon can then bridge it with IRC to not exclude that space. We can place links to the realtime chat in each repo, as a starting place to say hello and make initial newcomer interactions more welcoming. We can start developing social process and etiquette to help everyone to ensure important information gets into GitHub issues.

Ok, I think that's all the thoughts that are swimming in my head around this seemingly tiny decision. I hope it's not an intimidating wall of text. I tried to take a bunch of time to make it palatable, and I hope that comes across <3

**Comment by saghul** [comment]
@patcon Thanks for your thoughts! ❤️ the enthusiasm! Any chance you can jump on one of the next calls so we can discuss this? I think it's a good idea to do so.

**Comment by patcon** [comment]
I have something at the exact same time this week, but it's a one-off. I might make it, but if not, then next one for sure!

**Comment by mstyura** [comment]
Any progress on this issue?

**Comment by saghul** [comment]
Since then we have created our community forum: https://community.jitsi.org/ but there is still no synchronous chat.

**Comment by mstyura** [comment]
@saghul thank you very much, nice to hear that. But still hope some chat will eventually created. So far I've looked to videbridge, ice4j and libjitsi repositories and I'm a little bit scared of amount of issues and pull request which did not receive any feedback from maintainers of those repositories. From first glance they looks abandoned, but hopefully they are not. Maybe it's due to some of pull request/issues were not "advertised" properly by their creators, but where to advertise, if there is no chat? Community doesn't look very good for that. As a developer who want to contribute to Jitsi's projects I want faster feedback. Of course it's open source and nothing is guaranteed, but as I've said I wish to contribute some fixes and wish to hear feedback quickly to proceed my work, but looking at repository and community activity - it does not look feasible.

**Comment by damencho** [comment]
Have you checked the community forum at all? 
These are the daily posts from last week:
<img width="445" alt="screen shot 2018-10-18 at 06 55 55" src="https://user-images.githubusercontent.com/3263098/47152689-029ac600-d2a3-11e8-9aad-00d78c53973d.png">
This is an opensource project, people have their day jobs and there is no one paid to stay and answer questions on some chat. That's why the community forum is the best option for that.
The problem for some time in the past is that people were refusing to use mailinglists and it was easier to open an issue, which at the end ended with the projects having tons of issues, which are actually questions. 
We created the forum, as this is what people wanted and also posted a template for the issues where it is clearly written, that if you have a question post it to the forum, and still there are people creating issue for just a simple question (like one that Saul closed 30 minutes ago, an issue with a title with no description).
What do you see as not answered? Personally, I'm trying not to leave anything without some kind of feedback and I think almost any topic in the forum or issue created has some feedback.

**Comment by saghul** [comment]
@mstyura 

> From first glance they looks abandoned, but hopefully they are not.

Have you looked at their commit activity?

> As a developer who want to contribute to Jitsi's projects I want faster feedback.

And as a maintainer I want people to file issues following the guidelines and patches to be perfect and need no review, but we don't always get what we want :-)

> Of course it's open source and nothing is guaranteed, but as I've said I wish to contribute some fixes and wish to hear feedback quickly to proceed my work, but looking at repository and community activity - it does not look feasible.

Why don't you give it a try first, before thinking it's not feasible?

**Comment by mstyura** [comment]
Hi @damencho I'm really sorry that I offended you. That was not my intention. I see that you are very active at community site and I appreciate your effort, thank you very much. My initial frustration was due to quick inspection of list of issues and pull requests and "pulse" of [ice4j](https://github.com/jitsi/ice4j/pulse/monthly), [libjitsi](https://github.com/jitsi/libjitsi/pulse/monthly) and [videobridge](https://github.com/jitsi/jitsi-videobridge/pulse/monthly). There are some commits, but they are mostly come from maintainers and not from external developers, I've misinterpreted it as "unfriendly to newcomers", I'm really sorry for that. It looks live I was wrong, despite there is no much (at least in my expectation) commits/closed issue/closed pull request on "pulse" page. I apologize for offending project maintainers with my comments. I hope you will accept my apology and I'll be able to contribute to Jitsi.

> Why don't you give it a try first, before thinking it's not feasible?

@saghul I'm really sorry I did wrong conclusion and not given enough time to my pull requests and question to be reviewed. 

> And as a maintainer I want people to file issues following the guidelines and patches to be perfect and need no review, but we don't always get what we want :-)

Time to "advertise" my [pull request ice4j/#150](https://github.com/jitsi/ice4j/pull/150): should I open a github issue for it? :)

**Comment by damencho** [comment]
@mstyura You are not offending me don't worry, I'm frustrated with people opening issues for simple questions without reading the template... :)
You are welcome and any contribution is welcome. 
No need of issue about the PR, I'm sure @bgrozev had seen your PR, he just hadn't come to it yet.

**Comment by bgrozev** [comment]
Good discussion. I missed the ice4j PR, but I'll take a look later today.
