### ISSUE TITLE
Can't turn off camera until after one connects

### ISSUE THREAD

**Issue by jidanni** [jitsi/jitsi-meet#2737]
User browses ```https://meet.jit.si/whatever```.
But there is no way to make sure the camera is disabled before one connects.

Even one second of which usage might cause bandwidth or privacy concerns.

After connection the user must race to the controls to turn it off.

**Comment by saghul** [comment]
There are a couple of things to consider here: first, Jitsi Meet is a conferencing system, so why would one be surprised that the camera is opened? Then there is stuff the user can do to prevent it:

- deny camera permission
- join the room with #config.startWithVideoMuted=true, as in https://meet.jit.si/whatever#config.startWithVideoMuted=true

Adding an extra screen to choose the devices with which to join has been discussed in the past, with no clear way forward, so it was never implemented.

**Comment by jidanni** [comment]
OK I have an idea for the menus:
add a "Save current state in a URL" button!

That way one could set everything up just right, and save it for next
time.

E.g.,

(1) https://meet.jit.si/blabla#config.startWithVideoMuted=true#call.quality=audio_only

(Just guessing how to write it!)

But note that that button should be next to a share button, so one would
know (1) is for yourself, and just https://meet.jit.si/blabla is for
one's friends.

**Comment by snowymike** [comment]
just adding that i'd also find this very valuable.  invariably i'm turning off the camera immediately after joining meetings.  a setting of "Join calls with camera stopped" checkbox would be great for me.  so would a "Join calls muted" setting.

**Comment by eikaramba** [comment]
same for me. we do a lot of audio only calls. rarely use the webcams in our meetings. and its very annoying to have the camera on by default every time

**Comment by saghul** [comment]
We do have these settings on mobile, maybe it makes sense to bring them to web? Specially now that we have access to the settings on the welcome page.

**Comment by feliperaul** [comment]
@saghul Can you please consider reopening this?

Hangouts, Meet, Zoom, all have the option of muting your mic and/or camera before joining the room. 

Even if you don't want to make the user choose every time, we could just remember and honor his settings. So he joins any temp room, clicks on [x] Always joins with microphone muted and [x] Always joins with camera muted.

**Comment by syberphunk** [comment]
Even Microsoft Teams lets you choose an option before 'joining the call' just to re-assess whether you have everything setup and working 'right' before you join.

You get to choose if you want your camera on/off by default.
If you want your microphone muted or not by default.
If you want your background blurred on/off by default.

Because there are occasions you may want to join to show your face first, but not be heard because noise, but you can join via text.

There're times when you might just have selected the wrong audio recording, and so you're pushing the stereo mix instead of your microphone.

There're occasions where you may want to join being heard, but not be seen for various reasons (small people, you're topless, it's too bright)

And there're occasions where there may be content in the background you don't want to show by default, but in the foreground you do.

Then it's a usability matter, try finding anyone that can remember an arbitrary text string to add to an URL to get something to work, and I can probably count that on one hand, then how many people can remember how that's typed, and/or hasn't lost the bookmark, piece of paper or notepad document that had it written in, and that's even less.

It's such a shame this wasn't in already, but it's great that this's been re-opened.

**Comment by jwsp1** [comment]
Also, a "welcome page" could let the user select his preferred language too. Currently, everything's in English, even for people with IP addresses from other countries.

**Comment by rogerdahl** [comment]
> Jitsi Meet is a conferencing system, so why would one be surprised that the camera is opened?

This statement is problematic. As you're a developer, maybe this will help:

When you wake up in the morning, your state, let's call it `state_a`, is likely to involve concepts such as:

```python
state_a  = {
    'undressed', 
    'unshowered',
    'uncombed', 
    'unshaven', 
    'unmakeuped', 
    'untoothbrushed',
}
```

When you're at work, your state, let's call it `state_b`, is likely to involve concepts more in terms such as:

```python
state_b = { s[2:] for s in state_a }
```

Notably:

```python
assert state_a != state_b
```

Also, it turns out that:

```python
assert people != robots
```

And so people, usually when they're joining a conference from home,  may not always feel like it's necessary to move entirely to `state_b` in order to join a teleconference call.

However, as they still wish to be polite and professional, they will generally want to apply logic similar to this:

```python
camera_on = current_state == state_b
```

In particular, they want to avoid logic such as:

```python
camera_on = True
sleep(random(10))
camera_on = False
```

And that's essentially why your comment got frownyfaces and thumbs pointing in the wrong direction :)

**Comment by autoize** [comment]
Uncommenting these options in **.jitsi-meet-cfg/config.js** mutes the camera upon entry by default.

```
// Start the conference in audio only mode (no video is being received nor sent).
startAudioOnly: true,
// Every participant after the Nth will start video muted.
startVideoMuted: 0,
// Start calls with video muted. Unlike the option above, this one is only applied locally.
startWithVideoMuted: true,
```

**Comment by rogerdahl** [comment]
> Uncommenting these options in **.jitsi-meet-cfg/config.js** mutes the camera upon entry by default.

Thank you!

What does it mean that `startWithVideoMuted` is only applied locally?

I encourage you to ship with defaults that make it so that video is only turned on by a manual action by the person in front of the camera. Maybe not the best product to reference these days, but Zoom used to turn on the camera by default but that's now off by default:

![image](https://user-images.githubusercontent.com/561416/81490041-339e6b00-923a-11ea-8301-79e85ce6a1a4.png)

I think it's because the majority of people really don't want to appear on camera automatically.

**Comment by saghul** [comment]
We have implemented a “pre-join” screen which will let users choose the devices they want or mute them before angering the room.

It’s already on master but needs a couple more fixes before it can be rolled out.

**Comment by rogerdahl** [comment]
> angering

:)

**Comment by l3d00m** [comment]
Hi @saghul Can this be closed? The lobby feature is now implemented, right?

**Comment by Echolon** [comment]
@saghul  ^

**Comment by saghul** [comment]
Yes it can!
