### ISSUE TITLE
Android app startup crash.

### ISSUE THREAD

**Issue by ruojianll** [jitsi/jitsi-meet#2767]
The released app crash when startup without any prompts. 

1. I cloned the git repo `jitsi/jitsi-meet`.
2. Run `npm install`. There is an mistake of SASS. Then I changed the version of SASS to 'latest'.
3. Remove node-modules dir and run `npm cache clean --force`.
4. Run `npm install`.
5. Run`make`.
7. Generate android cert to android/app/ and change the build.gradle to apply the cert.
8. Run `./gradlew assembleRelease` in android/.
9. Run `./gradlew installRelease`.

I also try the app on emulator and it crash too.

Android SDK 26
build tool 26.02

**Comment by ruojianll** [comment]
The index.android.bundle is missing in released app. Try follow command:

`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res`

I don't know how to fix this bug by change the project. Hope somebody can do that. 

It works fine, but there is an another issue: All icons are missing.

**Comment by ruojianll** [comment]
I reopened this issue because others may suffer what happened on me.

**Comment by ryuheimat** [comment]
It currently works in debug version, but crash startup on release version.

**Comment by saghul** [comment]
What crash do you observe?

**Comment by ryuheimat** [comment]
Not sure, release version crash on startup. Can not see any screen or any error message.

**Comment by saghul** [comment]
Anything on `adb logcat` ?

**Comment by ryuheimat** [comment]
Oh, it's working. I was building on Android Studio, but it didn't work.
And now I build with ./gradlew command. And it works now.

**Comment by ms747** [comment]
Hello.
I'm having the same issue. I have also tried all the steps mentioned above. App perfectly works in debug. As soon as I install the release build it crashes. I was able to rather some info from logcat.

`E/unknown:ViewManager(10715): Error while updating prop autoComplete
E/unknown:ViewManager(10715): java.lang.reflect.InvocationTargetException
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.as$j.a(ViewManagersPropertyCache.java:83)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.aq$b.a(ViewManagerPropertyUpdater.java:132)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.aq.a(ViewManagerPropertyUpdater.java:51)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.j.a(NativeViewHierarchyManager.java:265)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.an$e.a(UIViewOperationQueue.java:200)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.an$h.c(UIViewOperationQueue.java:1109)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.an$h.a(UIViewOperationQueue.java:1080)
E/unknown:ViewManager(10715): 	at com.facebook.react.uimanager.e.b(GuardedFrameCallback.java:29)
E/unknown:ViewManager(10715): 	at com.facebook.react.modules.core.e$b.b(ReactChoreographer.java:166)
E/unknown:ViewManager(10715): 	at com.facebook.react.modules.core.a$a$1.doFrame(ChoreographerCompat.java:84)
E/unknown:ViewManager(10715): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
E/unknown:ViewManager(10715): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/unknown:ViewManager(10715): 	at android.view.Choreographer.doFrame(Choreographer.java:549)
E/unknown:ViewManager(10715): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/unknown:ViewManager(10715): 	at android.os.Handler.handleCallback(Handler.java:739)
E/unknown:ViewManager(10715): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/unknown:ViewManager(10715): 	at android.os.Looper.loop(Looper.java:135)
E/unknown:ViewManager(10715): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/unknown:ViewManager(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/unknown:ViewManager(10715): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/unknown:ViewManager(10715): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/unknown:ViewManager(10715): Caused by: java.lang.NoSuchMethodError: No virtual method setImportantForAutofill(I)V in class Lcom/facebook/react/views/textinput/c; or its super classes (declaration of 'com.facebook.react.views.textinput.c' appears in /data/app/org.jitsi.meet-1/base.apk)
E/unknown:ViewManager(10715): 	at com.facebook.react.views.textinput.ReactTextInputManager.setTextContentType(ReactTextInputManager.java:589)
E/unknown:ViewManager(10715): 	... 25 more
E/AndroidRuntime(10715): FATAL EXCEPTION: main
E/AndroidRuntime(10715): Process: org.jitsi.meet, PID: 10715
E/AndroidRuntime(10715): com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'autoComplete' of a view managed by: AndroidTextInput
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.as$j.a(ViewManagersPropertyCache.java:95)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.aq$b.a(ViewManagerPropertyUpdater.java:132)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.aq.a(ViewManagerPropertyUpdater.java:51)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:37)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.j.a(NativeViewHierarchyManager.java:265)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.an$e.a(UIViewOperationQueue.java:200)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.an$h.c(UIViewOperationQueue.java:1109)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.an$h.a(UIViewOperationQueue.java:1080)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.e.b(GuardedFrameCallback.java:29)
E/AndroidRuntime(10715): 	at com.facebook.react.modules.core.e$b.b(ReactChoreographer.java:166)
E/AndroidRuntime(10715): 	at com.facebook.react.modules.core.a$a$1.doFrame(ChoreographerCompat.java:84)
E/AndroidRuntime(10715): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:765)
E/AndroidRuntime(10715): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(10715): 	at android.view.Choreographer.doFrame(Choreographer.java:549)
E/AndroidRuntime(10715): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(10715): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(10715): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(10715): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10715): 	at android.app.ActivityThread.main(ActivityThread.java:5343)
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10715): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
E/AndroidRuntime(10715): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/AndroidRuntime(10715): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10715): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10715): 	at com.facebook.react.uimanager.as$j.a(ViewManagersPropertyCache.java:83)
E/AndroidRuntime(10715): 	... 22 more
E/AndroidRuntime(10715): Caused by: java.lang.NoSuchMethodError: No virtual method setImportantForAutofill(I)V in class Lcom/facebook/react/views/textinput/c; or its super classes (declaration of 'com.facebook.react.views.textinput.c' appears in /data/app/org.jitsi.meet-1/base.apk)
E/AndroidRuntime(10715): 	at com.facebook.react.views.textinput.ReactTextInputManager.setTextContentType(ReactTextInputManager.java:589)`
