### ISSUE TITLE
external api import error

### ISSUE THREAD

**Issue by Eraldo** [jitsi/jitsi-meet#2789]
When trying to load the external api script like this:

index.html:
```
...
<script src="https://meet.jit.si/external_api.min.js" type="text/javascript"></script>
...
```

I get the following error trace:
```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at https://meet.jit.si/external_api.min.js:1:106588
    at Array.forEach (<anonymous>)
    at https://meet.jit.si/external_api.min.js:1:106501
    at Object.<anonymous> (https://meet.jit.si/external_api.min.js:1:106796)
    at n (https://meet.jit.si/external_api.min.js:1:374)
    at Object.<anonymous> (https://meet.jit.si/external_api.min.js:1:94743)
    at Object.<anonymous> (https://meet.jit.si/external_api.min.js:1:102684)
    at n (https://meet.jit.si/external_api.min.js:1:374)
    at Object.<anonymous> (https://meet.jit.si/external_api.min.js:1:94414)
```

Any ideas what is going on? :)

**Comment by virtuacoplenny** [comment]
This occurs with just having the script loaded or while instantiating a new JitsiMeetExternalAPI instance?  Does the html file from doc/examples/api.html work? Is there any more detail you could share? Browser?

**Comment by Eraldo** [comment]
> This occurs with just having the script loaded or while instantiating a new JitsiMeetExternalAPI instance?

It occurs when loading the script.

> Does the html file from doc/examples/api.html work?

No, this line `<script src="https://meet.jit.si/external_api.js"></script>` is already causing the error.

> Is there any more detail you could share? Browser?

Sure, just tell me what you want to know. ;)

| info | details |
| --- | --- |
| Browser | Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by virtuacoplenny** [comment]
Is that syntax error showing up as a warning or an actual error in console? I've seen that before when the url has a fragment (#). Jitsi-meet uses the fragment (instead of query strings) for config overriding. Could that be it?

**Comment by virtuacoplenny** [comment]
There are probably a few ways to go about it. The way I would do it is add a breakpoint in parseURLParams within the source/code tab of the browser and look at what's getting evaluated; I'd click on the link to parseURLParams in the stack trace from the console, add my breakpoint, and refresh and start hovering over variables to see the context of the issue. From there I can see the error happens because parseURLParams is assuming the fragment has key/value pairs, so my fragment, which I'm testing by using `#anythinghere` is not split into key/value pairs so the error is caught and "Failed to parse {blah blah blah}" is printed. You could also look at what URL you're on and assume if it has a hash that doesn't have key/value pairs immediately after it that the issue is likely what I described.

Now...how to fix or avoid the issue is something else...

**Comment by Eraldo** [comment]
Yes. I can confirm that having a '#' in my url when loading the script causes the warning.

I added the script to my index.html however I only need it later on a different page. My frontend framework requires me to have it included in the index.html in order to bundle it correctly (at least that is the suggested/recommended way).

Any idea how to fix this or even ignore this particular warning?

**Comment by virtuacoplenny** [comment]
It's kind of already being ignored in the sense that it's in a try catch and then rest of the code moves on if an error is caught. How is it that a caught error and a warning print are affecting your app? I don't know good way to fix it without changing how jitsi-meet does query params or adding more explicit logic to parseURLParams. I guess the cop-out answer is PRs are welcome.

**Comment by insanicly** [comment]
So, there is no new development on this side, right?

**Comment by saghul** [comment]
Not that I'm aware of.
