### ISSUE TITLE
CONFERENCE FAILED: conference.setup_failed Error: ICE fail

### ISSUE THREAD

**Issue by c526537207** [jitsi/jitsi-meet#2805]
When the user joins the room, the following error will appear, how to solve?

`[modules/xmpp/JingleSessionPC.js] <r.peerconnection.oniceconnectionstatechange>:  (TIME) ICE failed P2P? false:	 24965.299999996205
Logger.js:125 [conference.js] <e.value>:  CONFERENCE FAILED: conference.setup_failed Error: ICE fail
    at r.peerconnection.oniceconnectionstatechange (JingleSessionPC.js:459)
    at RTCPeerConnection.peerconnection.oniceconnectionstatechange (TraceablePeerConnection.js:261)`

**Comment by damencho** [comment]
Are you using meet.jit.si or another deployment? Is it in p2p or not?

**Comment by c526537207** [comment]
It is p2p,using own deployment(quick install)

**Comment by damencho** [comment]
You need turn to be sure p2p will work, but if p2p fails it should fallback to jvb.

**Comment by c526537207** [comment]
@damencho Where to configure turn?

**Comment by c526537207** [comment]
@damencho I have done what you said, and I still have the error.

**Comment by c526537207** [comment]
@damencho Thank you for your help. The problem has been solved.

**Comment by Frindecent** [comment]
@c526537207 
@damencho 
can you help me with the issue. 

i configured turn server, i added the stun URL under p2p stun servers in config.js.
however i am not sure how to start configuring and enabling turn servers in prosody.

**Comment by damencho** [comment]
@Frindecent you need to enable the module https://modules.prosody.im/mod_turncredentials.html
and set the configs mentioned on that page.
You can enable it by downloading it from that page and putting it in some path accessible by the prosody user and adding for example:
plugin_paths = { "/srv/prosody-plugins" } and then restarting prosody. This should be enough.

**Comment by damencho** [comment]
Have you enabled the module?
```
modules_enabled = {
....
"turncredentials";
....
}
```

**Comment by Frindecent** [comment]
yes i have done that.

**Comment by damencho** [comment]
Check prosody logs for errors. Also, you can modify mod_turncredentials.lua adding some log to make sure that it is loaded, there is already log(https://hg.prosody.im/prosody-modules/file/7dbde05b48a9/mod_turncredentials/mod_turncredentials.lua#l14) if it is not loaded, maybe check for that in the logs.

**Comment by Frindecent** [comment]
I have this error in my logs.

does that mean prosody is picking up mod_turncredentials. and i should start looking towards mod_turncrentials.lua file or turn server configuration ( I installed coturn server on ubuntu 16.04 using apt-get and edited turnserver.conf for listening ports and 3478 and tls port 5479. Also installed letsencrypt ssl. and verified by telnet whether turn server is listening to port 443 and 3478) ?
since i used hg for prosody plugins all plugins were download and i provided path 
plugin_paths = {"/prosody-modules/"}
it has all folders for all prosody plugins and i edited the mod_turncredentials.lua file in there and added all required credentials.

I apologize for disturbing you alot. 
Thanks for helping me till here.. the main issue is that on web interface if p2p doesnot finds turn server it jumps back to jvm and caĺl continues but since i have built the react module myself for native apps and embeded in my project using react+swift and react+java for android. therefore on mobile side due to ice connection error the call drops. therefore, requiring turnserver configuration for prosody.

**Comment by damencho** [comment]
You forgot to paste the error.

**Comment by Frindecent** [comment]
the error you mentioned.
localhost error     turncredentials not configured
auth.Xxx.com error    turncredentials not configured.

**Comment by damencho** [comment]
Looking at the code, this means that turncredentials_host or turncredentials_secret is not configured in prosody.

**Comment by Frindecent** [comment]
hi @damencho . Sorry for trouble , i am pasting my mod_turncredentials.lua file here... because i have tried 100s of various combinations and still not able to get past this error. Can you help in identifying how i could not be entering correct credentials. 
-- XEP-0215 implementation for time-limited turn credentials
-- Copyright (C) 2012-2013 Philipp Hancke
-- This file is MIT/X11 licensed.

local st = require "util.stanza";
local hmac_sha1 = require "util.hashes".hmac_sha1;
local base64 = require "util.encodings".base64;
local os_time = os.time;
local secret = module:get_option_string("turncredentials_secret" = {username: "Admin", password: "XXX"});
local host = module:get_option_string("turncredentials_host" = {type: "turn", host:"1XX.3X.XXX.XX6"}); -- use ip addresses here to avoid further dns lookup latency
local port = module:get_option_number("turncredentials_port", 3478);
local ttl = module:get_option_number("turncredentials_ttl", 3600);
if not (secret and host) then
    module:log("error", "turncredentials not configured");
    return;
end

module:add_feature("urn:xmpp:extdisco:1");

module:hook("iq-get/host/urn:xmpp:extdisco:1:services", function(event)
    local origin, stanza = event.origin, event.stanza;
    if origin.type ~= "c2s" then
        return;
    end
    local now = os_time() + ttl;
    local userpart = tostring(now);
    local nonce = base64.encode(hmac_sha1(secret, tostring(userpart), false));
    origin.send(st.reply(stanza):tag("services", {xmlns = "urn:xmpp:extdisco:1"})
        :tag("service", { type = "stun", host = host, port = port }):up()
        :tag("service", { type = "turn", host = host, port = port, username = userpart, password = nonce, ttl = ttl}):up()
    );
    return true;
end);

**Comment by damencho** [comment]
Do you have values for turncredentials_host or turncredentials_secret in your prosody config?

**Comment by damencho** [comment]
This is not the original code of the module, return the default one and set those two config in your main prosody config file.

**Comment by Frindecent** [comment]
hi , the code is the same as of https://hg.prosody.im/prosody-modules/file/7dbde05b48a9/mod_turncredentials/mod_turncredentials.lua

i added only the values of turncredentials_host and turncredentials_secret. i thought maybe i am not getting them right.

no i dont have the values in prosody config file , i only added the values in mod_turncrentials.lua file. i will update prosody.cfg file and will let you know of results.

**Comment by damencho** [comment]
I don't see this in the link you pasted:
module:get_option_string("turncredentials_secret" = {username: "Admin", password: "XXX"});
local host = module:get_option_string("turncredentials_host" = {type: "turn", host:"1XX.3X.XXX.XX6"});

**Comment by Xowap** [comment]
@damencho same issue (?) here:

- Quick install
- Configured on `jitsi.delos.ltd` (and `*.jitsi.delos.ltd` is a CNAME of `jitsi.delos.ltd`)
- Did the Let's Encrypt configuration but nothing more

When I go to any room (like https://jitsi.delos.ltd/foobar) it doesn't work while on another install that I did the same way (from what I remember) it worked quite well from the beginning.

Any idea what is going on? If I need to install a turn server, why didn't I need it previously?

**Comment by damencho** [comment]
You didn't follow: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
Your jvb reports only its internal address and ipv6 address: 
<img width="757" alt="screen shot 2018-08-06 at 11 16 06" src="https://user-images.githubusercontent.com/3263098/43728289-3dfc8bba-996a-11e8-8452-6106393fce5b.png">

**Comment by damencho** [comment]
@zeronlee do not hijack issues. If you have a question or problem, write in the community forum: https://community.jitsi.org
