### ISSUE TITLE
sound is not working correctly

### ISSUE THREAD

**Issue by mayarichman** [jitsi/jitsi-meet#281]
Sometimes a participant is able to hear all other participants in a call, but no one is able to hear them. I know that their microphones are working properly because other applications, like Skype, work fine. All participants used Chrome in these instances.

Anyone else having sound issues?

**Comment by Zalmoxisus** [comment]
Yes, some of our participants faced this as well. Some of them solved this by restarting Chrome, but in some cases even this didn't help. I guess it could be because the device is being in use by other program or the Chrome doesn't point the right device by default. Maybe it can be solved if the meet will give the ability to participants to choose devices, as it is done on other sites (for example on beta.talky.io).

**Comment by yanas** [comment]
Chrome already gives the user the ability to choose between devices, however I agree that the application could try to make this choice more visible, as it's quite hidden in the browser window.
