### ISSUE TITLE
"Can't find variable: Set" error during some tests of phoenix app via wallaby when using jitsi-meet

### ISSUE THREAD

**Issue by tansaku** [jitsi/jitsi-meet#2852]
Loving jitsi-meet - it's awesome.

However we're getting an odd error in some acceptance tests:

```
ReferenceError: Can't find variable: Set
       e (https://cdn.jitsi.net/2706/libs/lib-jitsi-meet.min.js?v=2706:2)
```

more details here: https://github.com/keathley/wallaby/issues/353

Is there some way we can lock to a particular version of jitsi?

Also do you have any documentation on how jitsi gets pulled in from CDNs after we do the call to https://meet.jit.si/external_api.js?

Many thanks in advance

**Comment by virtuacoplenny** [comment]
The external api creates an iframe, which essentially just loads domain and roomName you set in the externa_api options. Mention of this is in doc/api.md. Because it just loads whatever domain you specify, which is maybe meet.jit.si, it's likely loading this repositories index.html, which loads lib-jitsi-meet through a script tag. I'm assuming the reason the error is happening because whatever environment you're testing on doesn't have support for Set and index.html loads polyfills after lib-jitsi-meet is downloaded.
