### ISSUE TITLE
how to maintain the same host even when i change my network provider

### ISSUE THREAD

**Issue by didihaye** [jitsi/jitsi-meet#2873]
Hello Jitsi-meet team,

forgive me but my english is a bit poor. Any way i'm a new user of jitsi-meet and there is a problem i still can't solve. The installation has been done successfuly but everytime my IP adress changes, i can no longer access the server. I guess because in the installation, jitsi requires an IP address and the moment i switch my ISP i no longer have access to the server. I tried it with the localhost, still aint working. Is there anyway to fix the IP address or any file i should edit, so i don't have to start the process of installation again. 

I'm using ubuntu server 16.04 on virtualbox.

Thanks in advance

**Comment by saghul** [comment]
Hi!

You can use a dynamic DNS provider such as duckdns: https://www.duckdns.org/ You'll need to run a small daemon which tells your IP address to the service, so it's updated automaticaly. The website should contain all instructions.

When you set it up you'll get a domain like "myserver.duckdns.org", so you can use that to access your server instead of the IP address.

**Comment by saghul** [comment]
Better do it before, so you can use that domain when prompted for it during install. Cheers!
