### ISSUE TITLE
offical list of compatible browsers with jitsi meet ?

### ISSUE THREAD

**Issue by DigitalCoder** [jitsi/jitsi-meet#2914]
Hi !
is there somewhere a list of compatible browsers with jitsi meet ? 
whichname, which version ?

and which extension, add-on or plugin exist to make browser as Safari compatible with Jitsi Meet, WebRTC ?

be cause I need to explain to my client exactly why it does not work with some users's device .

Thx

**Comment by virtuacoplenny** [comment]
Not necessarily an official list but there is some list that exists to show notifications about degraded browser support here: https://github.com/jitsi/lib-jitsi-meet/blob/fa24ac5289c5e73b2f5d4fe005cef8f9cfff8268/modules/browser/capabilities.json. Someone else might have a better answer.

Jitsi-meet should sort of work right now with Safari webrtc...but audio only due to some codec support issues on the bridge.

**Comment by saghul** [comment]
@damencho didn't we put this somewhere?

**Comment by damencho** [comment]
Nope, I don't think we have it on a page or something.

**Comment by shreeve** [comment]
Can someone who understands the deeper issues with Safari support, at least describe what the issue is with Safari support on a Mac?

Google's http://appr.tc app works fine with Safari and the following fork at least claims to have added support for Safari (but I think he was unable to support Firefox also, which isn't really that critical for me):

* https://github.com/Kukunin/lib-jitsi-meet/commits/master

I see that the following link implies that H.264 cannot be sent from the videobridge (which I think is wrong), but:

* https://github.com/jitsi/lib-jitsi-meet/blob/05b7ae60dc669a69b293fb0e93688fc0a78adb80/modules/browser/BrowserCapabilities.js#L194-L196

Do the issues preventing Safari support (even it's its just for p2p) exist on the side of Jitsi-Meet or lib-jitsi-meet or jicofo or jitsi-videobridge, etc.? It's pretty confusing to try to figure out.

if Google's http://appr.tc works just fine with Safari in p2p mode, shouldn't the code (assuming it's just modifications to the SDP) be brought over to jitsi-meet?
