### ISSUE TITLE
Missing instructions for build/run in Android Studio

### ISSUE THREAD

**Issue by scmcom** [jitsi/jitsi-meet#2929]
Unless I have missed something, there do not seem to be any instructions for how to build & run the app in AS. 

Would it be possible for someone to please give detailed instructions here?

**Comment by virtuacoplenny** [comment]
It looks like the [mobile README](https://github.com/jitsi/jitsi-meet/blob/6a0de0ddde18d25d2b966b04a21ca5105a723490/doc/mobile.md) points to the setup documentation in the react-native docs. Are the setup steps provided by react-native for Android Studio insufficient?

**Comment by virtuacoplenny** [comment]
Did you happen to run `npm install`? The error looks like a dependency is missing.

**Comment by scmcom** [comment]
That worked, thanks. It would be nice to add this to the Android instructions for future users. 

However, the Android app that runs is a red screen and says: "Could not connect to development server". Do I need to be running a server instance as well in order for this app to work properly? If so, where can I find instructions on how to do this?

**Comment by virtuacoplenny** [comment]
You don't have to be running a jitsi development server. Likely the problem is referring to some server spun up by react-native. At this point you're better off waiting for someone that works on jitsi mobile to respond or check out similar issues reported in the react-native repo. I've always used the command line (`react-native run-android`) to launch the android app when I've needed to test something so I'm unfamiliar with problems related to jitsi-meet and Android Studio.

As for updating the Android instructions, I actually encourage you to update them. I'd make sure to review and merge myself, although there might be a delay because of the CLA process.

**Comment by koala99** [comment]
I face the same questions， 'npm install ' work wrong, I use  'cnpm  install'  solve the issue
