### ISSUE TITLE
Lost video with more than 2 members

### ISSUE THREAD

**Issue by lfdominguez** [jitsi/jitsi-meet#2944]
Hello, Im using jitsi-meet with nginx as reverse proxy + openfire as XMPP server... when open the conference with 2 members the video works great, but when another member join, then lost all videos....

**Comment by damencho** [comment]
Have you tried this: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

**Comment by lfdominguez** [comment]
Works great... sorry and thanks for this jitsi-meet, only left connect jigasi....

**Comment by chrisdubia** [comment]
Hi @damencho.  Quick question for you.  I was able to install Jitsi on Azure successfully.  Similiar to @lfdominguez - when more than two members join, the video stops - but i still do see there avatar..No video though.  I see you reference "Have you tried this: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration" to adjust default values.  

I did execute this:

root@Video:~# service jitsi-videobridge status
● jitsi-videobridge.service - Jitsi Videobridge
   Loaded: loaded (/lib/systemd/system/jitsi-videobridge.service; enabled; vendo
   Active: active (running) since Wed 2019-07-17 13:40:24 UTC; 1min 39s ago
 Main PID: 1065 (java)
    Tasks: 105 (limit: 65000)
   CGroup: /system.slice/jitsi-videobridge.service
           └─1065 java -Xmx3072m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPat

Jul 17 13:40:24 Video systemd[1]: Starting Jitsi Videobridge...
Jul 17 13:40:24 Video systemd[1]: Started Jitsi Videobridge.
