### ISSUE TITLE
While using SDK 25 cordova build Failed.

### ISSUE THREAD

**Issue by afueo** [jitsi/jitsi-meet#2969]
I have a requirement to make Cordova plugin by Jitsi Android SDK  25 and build tool 25.0.3 but that is not working only work with targetSdkVersion  27( Android SDK API).
Is Jitsi Android SDK have minimum compileSdkVersion and targetSdkVersion for build?

**Comment by saghul** [comment]
These are the versions we specify when building the SDK: https://github.com/jitsi/jitsi-meet/blob/master/android/build.gradle#L132

We target API level 26 because we want to have Picture-in-Picture available. You can make your own build by changing those to other values, but you are on your own then.

**Comment by afueo** [comment]
I tried before but no success, I think other values have to change it.
https://github.com/afueo/cordova-plugin-jitsi-meet/blob/master/src/android/jitsiplugin.gradle

**Comment by saghul** [comment]
I don't think that enough. If you are using our Maven repo (which AFAIS you are) then the SDK is *already* built with API level 26. You seem to be building the plugin with API level 25, but the SDK is already built with level 26.

If you want to have the SDK built with level 25 you need to build it yourself and put it in some maven repo.
