### ISSUE TITLE
How to debug locally with Server Side Includes

### ISSUE THREAD

**Issue by ztl8702** [jitsi/jitsi-meet#3097]
## Question 
I have made some changes to `index.html`. I noticed there are include statements like  `<!--#include virtual="title.html" -->`. I guess they are Server Side Includes? 

Following the normal development workflow I can't use my local `index.html` because the request is proxied to the remote server. If I tweak `webpack.config.js` to not proxy `index.html`, then SSI cannot be resolved.

Do I have to deploy onto a web server in this case?

Thanks in advance.

**Comment by ztl8702** [comment]
Actually, the reason to modify `index.html` is to load external js files. I decided to load it in JavaScript instead. :see_no_evil:

**Comment by damencho** [comment]
I suppose your problem is using as a target deployment something as meet.jit.si where it uses cdn to serve files. So if you switch to using beta.meet.jit.si it should work fine and serve the files from the  local copy, or at least you can control them in here: https://github.com/jitsi/jitsi-meet/blob/master/webpack.config.js#L199
And you can always save meet.jit.si index.html file, delete the base cdn definition and serve it locally and there will be no ssi cause they were pre-generated when you were saving the page, ;) At least this is what I do when I want to debug something there :)

**Comment by jinixx** [comment]
Somehow related but not exactly to this issue. The SSI can be output to whatever I want if index.html is not proxied, so question below:

@damencho trying to change some settings on config.js / interface_config.js and test locally with webpackdevserver, however, the index.html is served thru proxy on the server. Forcing to serve with index.html in devServerProxyBypass causes cors error (of course). How can we use a locally served html and / or config.js / interface_config.js, so I do not have to deploy to server or change cors settings? Am I missing some instructions somewhere?

**Comment by jinixx** [comment]
Ok, I managed to work round this by using alpha.jitsi.net as proxy target, and bypassproxy on all browser request, returning 'index.html', additional changes needed is to add 
`writeToDisk: filePath => /index\.html$/.test(filePath),`
inside devServer config and html-webpack-plugin to output the required html on dev env.

**Comment by salimane** [comment]
hey @jinixx, could you please post your ``html-webpack-plugin`` config that solved the problem ?

**Comment by jinixx** [comment]
> hey @jinixx, could you please post your `html-webpack-plugin` config that solved the problem ?

I no longer use `html-webpack-plugin` but instead I implemented a ssi middleware on express dev server.

The previous way I used was because I have to load a different config for different environment. So I generated a different html based on node env.
1. `html-webpack-plugin` to generate your html according to you needs, like loading a different config or whatever
2. Replace SSI includes with injected strings. I used [ssi-webpack-plugin](https://www.npmjs.com/package/ssi-webpack-plugin).
3. devServerProxyBypass to bypass the paths you want to load locally.

```js
function devServerProxyBypass(req/* , res, proxyOptions */) {
    let { path: _path } = req;

    if (_path.endsWith('/favicon.ico')
            || _path.endsWith('.html')
            || localConfigRegex.test(_path)
            || _path.startsWith('/css/')
            || _path.startsWith('/doc/')
            || _path.startsWith('/fonts/')
            || _path.startsWith('/images/')
            || _path.startsWith('/sounds/')
            || _path.startsWith('/static/')
            || _path.startsWith('/lang/')
            || _path.endsWith('.wasm')) {
        return _path;
    }

    const configs = module.exports;

    /* eslint-disable array-callback-return, indent */

    if ((Array.isArray(configs) ? configs : Array(configs)).some(c => {
            if (_path.startsWith(c.output.publicPath)) {
                if (!minimize) {
                    // Since webpack-dev-server is serving non-minimized
                    // artifacts, serve them even if the minimized ones are
                    // requested.
                    return Object.keys(c.entry).some(e => {
                        const name = `${e}.min.js`;

                        if (_path.indexOf(name) !== -1) {
                            // eslint-disable-next-line no-param-reassign
                            _path = _path.replace(name, `${e}.js`);

                            return true;
                        }
                    });
                }
            }
        })) {
        return _path;
    }

    if (_path.startsWith('/libs/')) {
        return _path;
    }

    if (req.headers.accept && req.headers.accept.indexOf('html') !== -1) {
        return '/index.html';
    }
}
```

**Comment by salimane** [comment]
@jinixx thank you very much
