### ISSUE TITLE
LDAP loggin does not start a session

### ISSUE THREAD

**Issue by BrutalBirdie** [jitsi/jitsi-meet#3191]
## Description
---
Using Jitsi-meet version 2.10.5550-1 (1.0.3135-1 - jitsi-videobridge) with LDAP.
After logging in to host a room the page keeps unchanged.

## Current behavior
---
After logging in with LDAP the website keeps unchanged the session is not started.
A manual reload of the page is needed to start the session.

## Expected Behavior
---
After logging in with LDAP the website should start the session.

# Environment details
---
Debian 9.4
Jitsi-meet version 2.10.5550-1
jitsi-videobridge 1.0.3135-1

**Comment by damencho** [comment]
I suppose the version you mean is 
jitsi-meet 1.0.3135-1 and jitsi-videobridge 1066, which means you are using stable repo. There was a bug around authentication in stable, which is now fixed in unstable. Can you change your repo to unstable and upgrade and give it a try.

Please in the future, before opening new issues discuss your questions or problems in the community forum: https://community.jitsi.org/t/adding-jigasi-to-maven-repo/14119/5

**Comment by BrutalBirdie** [comment]
Will try that and report back.

**Comment by BrutalBirdie** [comment]
Solved by the new stable version
