### ISSUE TITLE
How can I use my own sturn/turn server?

### ISSUE THREAD

**Issue by lij2960** [jitsi/jitsi-meet#3220]
In /etc/jitsi/meet/jitsi.php2.cc-config.js file, I editor like this:

p2p: {
        enabled: true,
        useStunTurn: true,
        stunServers: [
            { urls: 'stun:coturn.uniauto.me' },
            { urls: 'turn:coturn.uniauto.me', credential: 'ling', password: '123456' }
        ],
        preferH264: true
    },

But it's not working.

And another quession.
I install the server in LAN, now I‘m mapping the port as:443, 5280, 5222, 5347, 4443
Is anyother port should be mapping?

**Comment by damencho** [comment]
Here is the answer to the first question: https://github.com/jitsi/jitsi-meet/blob/master/doc/turn.md
About the mapping: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration, only those ports are needed. TCP 443 (if running web server and jvb on same machine then forward and TCP 4443) and UDP 10000.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by boxuatheer** [comment]
Hi,

Thanks for the info! we are config the external TURN-server in jicofo-config and it works fine for jitsi-based web-terminal behind a TCP-proxy, but if a jiti-based Android-terminal is behind the same proxy, it will not work. we found that for jitsi-based Android-terminal, it seems our external TURN-server in jicofo-config doesn't work because it always go to our JVB directly(not go to external server). so could you tell me how to add a external TURN-server for jitsi-based Android-terminal? Thanks!
