### ISSUE TITLE
Preview of remote participants gets suspended

### ISSUE THREAD

**Issue by danionescu2007** [jitsi/jitsi-meet#3320]
After a little while, when I switch away the video from other participants, its preview (small video feed in the preview bar) gets dropped and, instead, the avatar is displayed in place of the preview. I suspect this is a "works as designed" as I found in a change log the following (https://download.jitsi.org/jitsi/changelogs/changelog-4506.html):

> build.4018
> Localize some xcap error messages.
> Uses the same history icon in contact list right button menu and chat file menu.
> Refactors the SoundLevelIndicator Component to not access the width of its parent and makes it available to bundles other than the UI bundle.
> Uses GTKLookAndFeel on KDE instead of the cross-platform LookAndFeel.
> **Refactors the detection of capture and playback/notification devices. Adds audio preview. Closes the video preview when switching away from it.**
> Fixes an ArrayIndexOutOfBoundsException in in the audio mixing.
> Adds support for PulseAudio on GNU/Linux.
> Gains performance by disabling the writing of the FMJ Registry file since it is not being loaded anyway.
> Fixes show/hide local video button.
> JITSI-1035 #resolve fixed Allows caller information to be passed to the command action handler on the incoming call event. Patch by Vieri Di Paola.
> Commit from translate.jitsi.org by user ibauersachs.: 1278 of 1278 messages translated (0 fuzzy).
> Fixes problems parsing sip messages using some locales.
> Commit from translate.jitsi.org by user ibauersachs.: 1278 of 1278 messages translated (0 fuzzy).
> Fixes build.
> Implements (native) volume control for the PulseAudio backend (on GNU/Linux).

I am not sure if the statement "Closes the video preview when switching away from it." applies to what I described in the begining.

What I want to accomplish is to have the preview of the remote participants always on, not to time-out.
Any suggestion will be much appreciated.

**Comment by damencho** [comment]
If you are talking about jitsi-meet, the changelog you have mentioned is about Jitsi Desktop and is not relevant to jitsi-meet.
The jitsi-meet changelog is here https://github.com/jitsi/jitsi-meet/commits/master or here for the stable release: https://github.com/jitsi/jitsi-meet/releases/latest

When you say the video preview is dropped and you see avatar, does the small icon changes to a 'ninja' icon, this happens when the bridge detects there is not enough download bandwidth on the client side and start switching videos in order to avoid dropping of the currently viewed video.

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by danionescu2007** [comment]
Thank you again, Damian! You saved my day, twice.
Regards++,
Dan
