### ISSUE TITLE
Not able to access by public IP

### ISSUE THREAD

**Issue by priyakh** [jitsi/jitsi-meet#3386]
I have installed jitsi-meet from https://github.com/jitsi/jitsi-meet.git local setup works fine but when i am trying to access it from public ip its not woking . help would be appreciate .

**Comment by damencho** [comment]
Checkout: https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration

Please in the future when you have questions or problems, before opening an issue, discuss them first on the community forum: https://community.jitsi.org as stated in the issues template, thank you.

**Comment by varma-nexge** [comment]
hi damencho
i have problem in haproxy configuration, actually haproxy is running in public server pointed to domain (video-conf.nexge.com) and installed jitsi meet application in two seperate server with domain as follows
server 1 : videoconf-primary.nexge.com
server 2 : videoconf-backup.nexge.com

on accessing jitsi severs able to do conference successfully, but while accessing through main domain it is redirecting to ip's of jitsi server i guess i have taken trace also instead of jitsi domain it is going to ip's

haproxy configuration
    
    log 127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon

    # turn on stats unix socket
    stats socket /var/lib/haproxy/stats

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block

defaults
        log     global
        mode    tcp
        option  tcplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000

frontend video
mode tcp
option http-keep-alive
option forwardfor
reqadd X-Forwarded-Proto:\ https
bind video-conf.nexge.com:443
default_backend jitsi_meet

backend jitsi_meet
mode tcp
balance roundrobin
server meet1 videoconf-primary.nexge.com:443 check
server meet2 videoconf-backup.nexge.com:443 check

Please help out of this, i want to use haproxy with two jitsi servers
