### ISSUE TITLE
defaultLanguage: 'de' not working properly !!!

### ISSUE THREAD

**Issue by gx110ewings** [jitsi/jitsi-meet#3446]
defaultLanguage: 'de' not working properly !!!

once language set in local storage on init , we can't change language by using defaultLanguage:'de' on refresh page.

**Comment by damencho** [comment]
Yep, this is known bug, but it needs a lot of resources to fix it, the storing comes from a library we use for i18n and the fact that this is not a common use case, cause normally this changes once before service is released and then its up to the user, the fix is not scheduled on your roadmap. So any interested we will love to review a contribution PR.

**Comment by qsdamar** [comment]
Is there made any progress here? More than 2 years later, I'm experiencing the same issue. 

Thanks in advance!
