### ISSUE TITLE
Jitsi customization like whatsapp, hangout. Video frozen, audio call through speaker phone issues

### ISSUE THREAD

**Issue by smbteam1** [jitsi/jitsi-meet#3449]
We tried to use Jitsi Meet video & audio calling feature in one of our Native Android & IOS App. We followed the GitHub repo  https://github.com/jitsi/jitsi-meet . 

In the app, we have one to one and group calling feature. 

Our actual requirement was to make use of Jitsi in same way as hangout or whats-app works. ie, when click on the call button , end user should be able to see the calling screen immediately, and should be able to click accept or reject.  For this purpose we have done some customization in Jisti Meet. 

**Below is what we have done in IOS:**

1. Downloaded the latest release from the Git repo and unzip it. ( jitsi-meet-2647 ,  Nov 16, 2017)

2. Done some customization in Jitsi Meet view.

3. After the customization archive the build and created the framework of Jitsi Meet

4. Then we linked the framework in our App through Xcode.

**Below is what we have done in Android:**   

    1. Downloaded the latest release from the Git  repo and unzip it.

    2. Done some customization in Jitsi Meet view.

    3. After the customization we assemble the release and published to a GitHub repo.

    4. In our app’s build.gradle we added the link as dependency.

Below is what we have done to manage one to one and group calling. For android we are using data push notification and for IOS we are using VOIP push notification.

**One to one Call**

1. When user initiate a call we create a dynamic room name and send a push notification to the receiver with the room name.
2. Once receiver accept the call immediately initiate Jisti Meet View and join the receiver to the room and send a push notification back to sender and join him to the same room. Thus both of them get connected.
3. We were setting some initial props before launching Jitsi Meet from native side to make an audio or video call both in android and iOS.
4. Once a user hangup a call we will send a call end push to the other user and forcefully leave that users from the room and destroy the Jitsi Meet View. Thus both of them get disconnected.

**Group call**

1. When a user initiate a group call we are creating a dynamic room name for the group. At the same time Jitsi Meet View get initiated for the sender and join into the room and wait for other members in the group to join.
2. In background we are sending a push notification to other member with the room name while the sender waits for other’s to join the room.
3. Once receives the push members can accept or reject the group call . The accepted members will join to the room.
4. The member who hangup the call will leave from the room.
5. Once all members leave the room then destroy Jitsi Meet View from the sender side.

For to make use the audio call feature, I just disabled the video from the video call.

Issues :

some times video and audio call frozen , some times lagging, some times end user is not at all getting the call. 
Also, audio call is always coming through the speaker phone.

Anybody of you have better way of implementation than I followed? 
Please help.

**Comment by lyubomir** [comment]
You're implementing "call flows" is how we've been referring to it internally at least. We did work on that and we did successfully make it work internally in Stride at Atlassian. You can still see that we worked on it though in Jitsi Meet SDK for Android and iOS: there are the callXXX config overrides/overwrites https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/functions.js#L31 that we added so that iOS consumers of the SDK can instruct CallKit though the SDK how calls are to identified and displayed; there's https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/incoming_call/IncomingCallView.java which implements an incoming call screen on Android. It worked as expected.

So I'd say that generally what you've done sounds right to me. Jitsi Meet is a rendezvous-like abstraction so adapting it to "call flows" mostly happens before the rendezvous and once both parties have one and the same meeting URL, they just meet there.

Why at times an end user is not getting a call at all? Well, that's supposed to happen before you bring Jitsi Meet into the game so I'd look into the "call flow"-related notifications/signaling that you're using to set the rendezvous i.e. meeting URL up. As I said above, that's not implemented by Jitsi Meet but by you, and it's mostly before you give control to Jitsi Meet SDK for Android and iOS.

Why audio and/or video are lagging at times? It could be anything really but I'd rather put it in the overall category of Jitsi Meet deployment specifics. You want to make sure that the network capacity at the clients and the servers is sufficient, that the devices of the clients are capable of sending and receiving audio and/or video with respect to CPU, network, etc. You should definitely be able to test it without your "call flows" logic. For example, use the Jitsi Meet app for Android and iOS with your deployment if possible and see how it fares there. You should definitely throw in Jitsi Meet for Web/desktop in there in the tests of your deployment as well to see whether the issues are specific to mobile or exist on Web/desktop as well. Again, the lag is going to happen after the call flows have set the rendezvous up so you may as well test for the lag without your "call flows" implementation and with our apps against your deployments. Compare that to our deployments if possible. For example, make your app set a rendezvous up on https://meet.jit.si or https://beta.meet.jit.si instead of your deployments.

The audio call is always coming through the speaker phone? It does sound like something that could be inside Jitsi Meet SDK for Android and iOS. @saghul, do you remember specifics about which OS tried to default to what device in audio and/or video calls or anything related to this really?

**Comment by carotkut94** [comment]
@smbteam1  this the same thing we are trying to achieve, but we were unable to use the aar files  which we generated for android and hosted them on github(but when we run the app with our own jits-sdk, it give  some weird issues related to JSC, the issue can be found at https://github.com/jitsi/jitsi-meet/issues/3399) can you share the method/process to follow in order to make it work.

to remove the lagging behind issues, what i am trying to do, is keep the jitsi meet view below the incoming call view, and when the call will come, i will show the incoming call view, and the mean time jitimeetview will load the conference url, in the background, but the issue i am facing with this approach is, if the user does not pick up the call, but the conference will be joined as jitsimeetview has the conference url, and video/audio streaming will start, even though the call was not picked up.
@lyubomir is there a way to have delegate/callback methods to mute unmute the call are the any methods which are exposed to java, which can be used to achieve this kind of functionality.

**Comment by saghul** [comment]
> The audio call is always coming through the speaker phone? It does sound like something that could be inside Jitsi Meet SDK for Android and iOS. @saghul, do you remember specifics about which OS tried to default to what device in audio and/or video calls or anything related to this really?

Video calls (even if video is muted) get their audio routed to the speaker. If you set `startAudioOnly` to `true` then it will start as an audio call, which gets its audio routed to the earpiece by default.

What props are you passing to the app @smbteam1 ?

**Comment by saghul** [comment]
> @lyubomir is there a way to mute unmute the call(via java code), are there any methods which are exposed to java, which can be used to achieve this kind of functionality.

No, this is not currently implemented.
