### ISSUE TITLE
Request for RN-Jitsimeet tutorial for beginners

### ISSUE THREAD

**Issue by vagnerpene** [jitsi/jitsi-meet#3459]
Hi everyone,
I am a jitsi-meet beginner and I would like to integrate my own React Native project with the jitsi-meet. Please, can someone provide me some light? Thank you

**Comment by saghul** [comment]
Hello! This has been asked before, but alas it's not an easy process because we focused on integration with native apps and not React Native apps.

The process would involve a number of manual steps, plus it wouldn't be future-proof because changes will be necessary.

I think it's possible to make this better / easier, but we haven't planned for it in the short term, sorry.

**Comment by vagnerpene** [comment]
Thank you @saghul and @lyubomir for your quick reply. So, is there a possibility to build my own project from jitsi-meet code or is it possible to customize it? How can I do? Apologies for my english, I am not an english native.
