### ISSUE TITLE
Virtual cam eror

### ISSUE THREAD

**Issue by KovalevArtem** [jitsi/jitsi-meet#3532]
## Description
Cannot use [obs-virtual-cam](https://github.com/CatxFish/obs-virtual-cam)

## Current behavior
When switching a real camera to a virtual one, the following happens:
![image](https://user-images.githubusercontent.com/36500228/46859813-82dea880-ce17-11e8-9025-332990f57d8a.png)
More details [here](https://github.com/CatxFish/obs-virtual-cam/issues/34).

# Environment details
OS Windows 1809

Google Chrome 69.0.3497.100
Opera 56.0.3051.36
Firefox 62.0.3 

OBS-VirtualCam 2.0.2
OBS 22.0.2

https://community.jitsi.org/t/cannot-use-a-virtual-camera-with-jitsi-meet-in-chrome-69/14896

**Comment by saghul** [comment]
Does this happen on meet.jit.si or your own deployment? (sorry, I can't test right now as I don't have a Window machine handy).

**Comment by saghul** [comment]
Thanks for confirming.

**Comment by KovalevArtem** [comment]
The problem is not solved

**Comment by KovalevArtem** [comment]
No closed pls

**Comment by KovalevArtem** [comment]
No closed pls

**Comment by KovalevArtem** [comment]
No closed pls

**Comment by danielsz** [comment]
Same here.

**Comment by kappapiana** [comment]
Same here. It works on the same settings with BigBlueButton, Hangouts, Zoom. The virtual camera is recognized by the settings, I even see the video feed, but when I start the meeting, it asks again for authorization, then again, but only two instances of the actual camera are provided.

Major bugger.

**Comment by nettings** [comment]
I can confirm that the current virtual camera feature on OBS 26.1.2 (from git) (on Linux, using v4l2loopback) does the same: virtual camera works readily in Zoom or VLC, but is not even offered as a choice in Firefox or Chrome when using Jitsi. Will get the chance tomorrow to test in BBB. I suspect you can ask for particular stream features in WebRTC that OBS+Loopback does not provide, so it doesn't show up. It's very likely not the color space, because that used to be configurable with the older ob4-v4l2sink, and it also never worked in Jitsi in any setting. I can also rule out the exclusive_caps option, I tried with and without.

**Comment by CarlosGrohmann** [comment]
Same here in Windows. Virtual camera is picked up by Google Meet in Firefox or Chrome or Edge but not by Jitsi.

**Comment by liquidthex** [comment]
Same Windows 10, Jitsi in FF or Chrome doesn't pick up virtual cam that other sites like whereby do.

**Comment by saghul** [comment]
What resolution does your virtual camera have?

**Comment by abramhindle** [comment]
In OBS I had to turn down the resolution for Jit.si in firefox nightly to see my virtual webcam.
Once I did that I could choose which camera.

I was using 1920x1080 and I turned it down to: 768x432.
I could get up to 1536x864 to work with the meet.jit.si site.
