### ISSUE TITLE
RANDOM_AVATAR_URL_PREFIX does not seem to be used by Android mobile app

### ISSUE THREAD

**Issue by chrisrobbo** [jitsi/jitsi-meet#3682]
Setting RANDOM_AVATAR_URL_PREFIX in interface_config.js  in order to change the avatars returned works fine in the browser version, but not in the Android version which seems to revert to the jitsi meeples . I was under the impression that this file is also used for the mobile apps - is this incorrect and if so, how do we change the avatars for mobile versions ? If not, is there something else which needs changing or is it a bug ?

**Comment by saghul** [comment]
At the moment interface_config.js is not loaded on mobile.

**Comment by chrisrobbo** [comment]
So how can the avatars be changed ? Can you point to the code which needs
changing ? I can't find it

**Comment by saghul** [comment]
You will need to edit the code here: https://github.com/jitsi/jitsi-meet/blob/957606b3f83ed0f5d401c4a48c843c099dbb7ecf/react/features/base/participants/functions.js#L47 since `interfaceConfig` doesn't exist on mobile yet, the default avatar service is chosen, which is set by js-utils, so you'd want to hardcode it there.

**Comment by chrisrobbo** [comment]
Thanks. Any idea when interfaceConfig will be used for mobile as well ? It
is a huge hole ...

**Comment by saghul** [comment]
Sorry, I cannot provide an ETA for it. It's not in our most immediate plans.
