### ISSUE TITLE
Adding phone number is not working

### ISSUE THREAD

**Issue by subhahu123** [jitsi/jitsi-meet#3731]
### Problem

- when trying to add phone number to invite people it shows error .

**Comment by subhahu123** [comment]
On http://meet.jit.si/

**Comment by aaronkvanmeerten** [comment]
This is a known issue with the build of JIgasi and jicofo currently deployed on meet.jit.si.  Dial-in should continue to work fine while we investigate further the root cause of the issue.  The symptom is that Jicofo stops seeing the Jigasi instances which are meant to be used for dial out.  We are investigating this, although the christmas/NYE period may slow down investigations somewhat.
