### ISSUE TITLE
Accept-Lang header is not respected

### ISSUE THREAD

**Issue by friedelwolff** [jitsi/jitsi-meet#3888]
When visiting Jitsi Meet for the first time (no profile or language preference set), it should ideally respond in the language best matching the HTTP Accept-Lang header.

Currently it seems to respond in English regardless. I am not sure if some i18n library is in use that should implement this, but this is something I picked up in my testing on the beta server of a new translation I just contributed. I tested it with a private browser window to ensure that no existing cookies are set.

**Comment by d-g** [comment]
It is extremely unfortunate that this bug has gone neglected.  I do not think itʼs reasonable to expect every single user of a software targeting the widest audience to know English enough not to get lost while following the path of ‘More actions’ / ‘Settings’ / ‘More’ / ‘Language’ (cf. bug#5865 [0]).

And the header is ‘Accept-Language’ rather than ‘Accept-Lang’ [1], so for the sake of googleability the thread worths retitling.

[0] https://github.com/jitsi/jitsi-meet/issues/5865
[1] https://tools.ietf.org/html/rfc7231#section-5.3.5

**Comment by luixxiul** [comment]
> It is extremely unfortunate that this bug has gone neglected.

mind creating a PR or something so that the team could find out the better solution?

**Comment by luixxiul** [comment]
how could you reproduce the issue consistently?

**Comment by d-g** [comment]
Suguru Hirahara <notifications@github.com> wrote:
> how could you reproduce the issue consistently?

1. Configure your browser to send `Accept-Language` where English languages have lower priorities than some others, e. g.: `ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7` (thatʼs what Chromium sends when `$LANGUAGE` is `ru_RU:ru`).

2. Run Jitsi Meet app in it.

In other words, something like this should do:

	$ LANG=ru_RU.UTF-8 LANGUAGE=ru_RU:ru chromium --temp-profile https://meet.jit.si/lang-test

### Expected result:

Jitsi Meet presents you an UI in a language with the highest priority out of available ones.

### Actual result:

It presents you an English UI.

**Comment by saghul** [comment]
I think thiss should be fixed by https://github.com/jitsi/jitsi-meet/commit/24052e9f9a3617ae068363775f4a2d9fcf2bc508

Language detection was previously broken.

**Comment by l3d00m** [comment]
I'd close this if this is assumed to be fixed, otherwise one could open a new issue or reopen this.
