### ISSUE TITLE
jitsi-meet on Safari iOS 11 without native app

### ISSUE THREAD

**Issue by bacbos** [jitsi/jitsi-meet#3939]
Hi

We're currently looking deeper into jitsi and were wondering if the fact that jitsi-meet is not supporting Safari on iOS out of the box (without the need of a native app) is due to technical reasons or just because support hasn't been implemented in the react-app yet? 

To our knowledge, iOS 11 now supports WebRTC (and SFU mode) as long as two separate media streams are being used (one for audio and one for video, the audio part of the video stream being set to "mute").

**Comment by damencho** [comment]
We are supporting desktop Safari in audio-only mode, we disabled video due to a bug and while waiting for them to fix it priorities changed. We will be spending more time on Safari support in the following months.
We have never tested it natively on iOS, but as that experience is not optimal for many reasons on Android and iOS that is disabled and we are focused on the mobile app and we are providing SDK to use it.

Please, when you have questions or problems use the community forum before opening new issues.

**Comment by Afondevi** [comment]
Hello !

I need to use visio call from mobile browser.
It’s available in jisti-meet right now or not ? Thanks

**Comment by saghul** [comment]
We are currently working on improving our Safari support. This is not currently available.

**Comment by rschiefer** [comment]
FYI - #5105
