### ISSUE TITLE
[Android] [SDK 2.0.0] Feedback when integrating new SDK to Riot.im application

### ISSUE THREAD

**Issue by bmarty** [jitsi/jitsi-meet#4068]
Hi,

I'm integrating Jitsi 2.0.0 to Riot. Conference call is well setup and working fine 👍 

My feedbacks so far:

- [ ] Is there a way to set the title of the screen? I have the pb reported (and fixed) here #4050, but there is no API (yet?) in JitsiMeetConferenceOptions to set the title
- [ ] currently we use a JitsiView, and there is a new method `leave()`. We are using `dispose()` for now, should I replace the call with `leave()`?
- [ ] embedded chat is not working well: text and button is hidden behind the keyboard. Also the chat is not displayed above the video as before.
- [ ] in the menu, clicking on "Meeting info" share the URL of the conf, which looks more like action "Invite someone", but maybe I do not understanf it correctly. "Invite someone" action is disabled.

These are not blocking issues, so I can push Riot to the prod with this SDK.

Thanks!

[Edit]
Also, when uploading Riot to the PlayStore it warned me that new permissions where added: android.permission.READ_CALENDAR and android.permission.WRITE_CALENDAR (Added from the react-native-calendar-events:1.6.4-jitsi-799011 manifest).

**Comment by FaizalMalik** [comment]
@saghul  - It would be helpful  , if we have the option to set title from our side...! now its showing the path of our url. It doesn't looks good... @bmarty  any updates ?

**Comment by saghul** [comment]
>     * Is there a way to set the title of the screen? I have the pb reported (and fixed) here #4050, but there is no API (yet?) in JitsiMeetConferenceOptions to set the title

There is no way to set the title as of yet. We need to see how this blends together with the conference subject. We have this concept (the XMPP MUC subject basically) but haven't exposed it to the UI yet.

>     * currently we use a JitsiView, and there is a new method `leave()`. We are using `dispose()` for now, should I replace the call with `leave()`?

First, I'd recomend you switch to using the `JitsiMeetActivity` directly, unless you have some very very specific needs. As for `leave` vs `dispose`, you can keep on calling `dispose` since it does a `leave` internally.

>     * embedded chat is not working well: text and button is hidden behind the keyboard. Also the chat is not displayed above the video as before.

I'm not seeing this in Jitsi Meet (the app). Can you post a screenshot?

>     * in the menu, clicking on "Meeting info" share the URL of the conf, which looks more like action "Invite someone", but maybe I do not understanf it correctly. "Invite someone" action is disabled.

These are 2 different things, related, which we need to refine a bit. Inviting someone requires a backend service which processes invites / dials out. Meeting info contains the meeting information just like before, with the system share sheet.

> Also, when uploading Riot to the PlayStore it warned me that new permissions where added: android.permission.READ_CALENDAR and android.permission.WRITE_CALENDAR (Added from the react-native-calendar-events:1.6.4-jitsi-799011 manifest).

That's correct, there is calendar integration now. If calendar access is provided, meeting notifications will be shown in the conference, and for those using the welcome page, upcoming meetings show up there.

**Comment by bmarty** [comment]
Thanks for feedback.

About the title, why not add a setTitle() method in the JitsiMeetConferenceOptions to configure the bundle as per #4050? This could be a temporally workaround to avoid having a conf id displayed.

Also can i remove the calendar permissions safely, i mean does jitsi will handle the lake of calendar permissions?
In riot we do not display the welcome page

Benoit

**Comment by saghul** [comment]
> About the title, why not add a setTitle() method in the JitsiMeetConferenceOptions to configure the bundle as per #4050? This could be a temporally workaround to avoid having a conf id displayed.

Yeah, I think that makes sense, since the local parameter would take precence over the room setting, but I need to double-check.

> Also can i remove the calendar permissions safely, i mean does jitsi will handle the lake of calendar permissions?
> In riot we do not display the welcome page

Yep, you can. We don't trigger any permissions prompt since that only happens on user action on the welcome page.

**Comment by saghul** [comment]
Thanks for the reminder, lovely bot :-)

All of the points should be addressed in our latest SDK release, 2.2.0. If there is anything extra missing / misbehaving please open a new issue.

Thank for the feedback!
