### ISSUE TITLE
[Android] Opened keyboard in chat window overlaps chat and chat input

### ISSUE THREAD

**Issue by olastor** [jitsi/jitsi-meet#4176]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed.
General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description

In the chat window on the mobile app the opened keyboard overlaps the text input and chat messages. It was not possible for me to see what has been typed.

![Screenshot_20190504-225107](https://user-images.githubusercontent.com/7479641/57184681-4e1f6500-6ebf-11e9-9cfd-43e580dad685.png)

---

## Current behavior

see description

---

## Expected Behavior

all content should be displayed above the keyboard (basic layout as in this random image from the internet: https://i.stack.imgur.com/gaXbR.png)

---

## Possible Solution
---

## Steps to reproduce

- Open Android App
- Join some room
- Open chat window by clicking on message icon in left bottom corner
- Start typing something in chat text input

---

# Environment details

- Phone: BQ Aquaris V
- Android: 7.1.2
- App Versoin: Jitsi Meet 19.1.0

---

**Comment by virtuacoplenny** [comment]
This should be fixed on latest master. https://github.com/jitsi/jitsi-meet/pull/4134.

**Comment by FinSlate** [comment]
![4875B36F-095F-4EBD-AC2C-F59384BC859E](https://user-images.githubusercontent.com/64149369/98706658-b668c580-2344-11eb-95fe-e6182ad77a52.png)
![29C4CB56-56FE-4FC9-9F54-928F341CDA7E](https://user-images.githubusercontent.com/64149369/98706663-b963b600-2344-11eb-99e7-f431159ec4c0.png)

Emoji keyboard hides textinput field

iOS 13.5 — JitsiMeet AppStore — iPhone XS Max

Steps to reproduce:
Enter conference
Open chat
Tap on TextInput field
Switch to emoji Keyboard

Expected:
TextInput field adjusts position on top of emoji keyboard 
Actual:
TextInput field is hidden (see screenshot)

Finally, toggling back to QWERTY keyboard doesn’t readjust/fix this issue.

I realize this issue is marked for Android- but I see in the code that there was ternary operator to adjust padding for just Android so maybe it can be adjusted there and will affect both? I tried applying that same fix to iOS with undesired results (too much padding).  

Thanks!
