### ISSUE TITLE
Displaying connection states

### ISSUE THREAD

**Issue by emcho** [jitsi/jitsi-meet#42]
OK, this is very important. We need to be able to tell users about their join progress. The idea is that when a user is joining a conference now, they are only seeing an avatar for an indefinitely long time and there's no way for them to know if that's because a join is in progress or because it has failed. We need to be able to tell this to users.

@fippo  Could you please add an API that sends notifications for join states? Maybe something that would allow progress tracking would be nice. I mean, in addition to the status message, the API can also say that we are at (very roughly) X% of getting there. Like for example: joining the room is 30%, getting an offer is 60%, sending our first candidate is 80%, getting audio is 90% and getting video is 100%. All this is about showing to a user their own state.

Showing to a user (focus?) the states of other participants would be a little bit trickier (but not much). Telling one participant about the state of another one would be trickiest because we'd basically have only joining the room (30%) getting their remote SSRC (70%?) and getting a video stream for a 100%

How does this sound? Keep in mind that this is just a sketch suggestion so please let me know if you have other ideas.

@yanas once @fippo  is ready, could you please glue that into the GUI? I think this would help a lot for all the cases  where people are still unable to join.

What do you guys think?

**Comment by raghbendranayak** [comment]
Hi Guys,
I have installed Jitsi meet at my own server and its working fine but My requirement is something below
User A will create an account with us in order to access live streaming classes.
Teaching class
User can chat (text)
User sets up their camera
When class begins: User’s main view is the presenter
User can still chat with group
User can receive help from the Support Instructor (SI)
User can only see the main presenter not all joined users also can hear to main presenter not all users. 

Support Instructors need to enter the class management dashboard
SI can chat (text) to users
SI can talk to user through audio – One at a time and only that one user can hear the audio of the SI. 

Is this possible in Jitsi meet and where I need to customization because when I install it I got only Jitsi meet code.

I follow this video to install jitsi meet.
https://www.youtube.com/watch?v=8KR0AhDZF2A

Please help me or provide some guidance on same so that I can achieve this.

**Comment by raghbendranayak** [comment]
Thanks for the guidance, let me post there.
