### ISSUE TITLE
jibri display name not being set or recognized

### ISSUE THREAD

**Issue by RcTomcat1** [jitsi/jitsi-meet#4298]
## Description
when i set requireDisplayName: true, in jitsi config i noticed that my jibri recording has exactly that window prompting for the display name in the middle.
I was told on the community forum that this was an issue with jitsi meet and that i should open a bug. 
https://community.jitsi.org/t/requiredisplayname-true-window/18240

## Current behavior
Enter Display Name always open in jibri recording when requireDisplayName: true is set

## Expected Behavior
Expected jitsi to accept the displayname send by jibri or not show the prompt for the displayname at all for the recorder.

## Steps to reproduce
Setting  requireDisplayName: true and starting a recording

# Environment details
Debian 9

**Comment by virtuacoplenny** [comment]
I at least see where the issue is. https://github.com/jitsi/jitsi-meet/blob/de60a70daf53f46afb92d9b5c63be1ca5c6e54fd/react/features/base/settings/reducer.js#L133. If displayname is defined in local storage, the jitsi-meet code does pick it up and read it. Then a default settings object is created. But because displayName is defaulted to "", which is technically a defined value, the displayName gets set as "".

**Comment by virtuacoplenny** [comment]
Been thinking about this more and I can't conclude what a decent fix is. Some fixes I'm juggling in my mind:
- Checking the return value of _.escape(window.localStorage.getItem('displayname')) and setting it to undefined if it's an empty string. That way the empty string doesn't get saved as the display name.
- Changing assignIfDefined somehow.
- Removing the local storage reading altogether and adding query params that jibri can use instead of reading from local storage. I prefer this one but am unsure of the work involved.

**Comment by virtuacoplenny** [comment]
Going with implementing the first option because it's the least risky, maybe. https://github.com/jitsi/jitsi-meet/pull/4299
