### ISSUE TITLE
keybase support

### ISSUE THREAD

**Issue by edmundlaugasson** [jitsi/jitsi-meet#4337]
You have ability to connect with Slack.
Would propose same functionality with Keybase - https://keybase.io/ - basically a free and open-source alternative to Slack.
Would be great if you could have similar connect button at https://meet.jit.si/ like currently the Slack button is.
Proposed an idea also here - https://github.com/keybase/keybase-issues/issues/3427

**Comment by edmundlaugasson** [comment]
It is a pity that no one has not paid attention to the current idea. I thought that you could be interested of spreading a word about Jitsi Meet...

**Comment by mathieujobin** [comment]
I second @edmundlaugasson idea. I'd would like to see Jitsi gaining popularity
and I would like to use Keybase for federated login as well.
but I'm not sure what can Jitsi do until Keybase actually has the required API

**Comment by saghul** [comment]
We already have an [iframe API](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) which other projects such as Matrix / Riot, Rocket.Chat and Zulip already use.

The Slack integration is a bit different due to how Slack addons work.

I don't see anything actionable for us here at this point. If anyone at Keybase is interested in pursuing this I'll be happy to help out.
