### ISSUE TITLE
Cant get reference to the APP object - iOS

### ISSUE THREAD

**Issue by civilordergone** [jitsi/jitsi-meet#4380]
@saghul Paul and I are trying to get reference to the APP property.

Inside the `base/app/components/BaseApp.js`, with the _createStore(), when I debug and reach this line:
```
if (typeof APP !== 'undefined') {
  APP.store = store;
}
```
It skips over that block.  APP is not defined.  

I know inside the `app.js`, it will define the window.APP, and it's not initializing it inside of `index.native.js`

So my two questions are:
1).  How do I get APP defined for iOS?
2).  How do I get APP.store defined as well.

**Comment by saghul** [comment]
`APP` is a legacy construct from the web side. The mobile app does not use it. What are you trying to accomplish?

**Comment by civilordergone** [comment]
We have coded things that make use of  `APP.conference` and `APP.store`.  Is it tough to enable for mobile app?

**Comment by saghul** [comment]
That is a no-go, because `APP.conference` is a wrapper around the conference object, which is not used on mobile.

Depending on what you did the usual is to use a connected component (ie, a component which uses `mapStateToProps` which gets what it needs from the store. In addition, using a middleware and reducer to interact with the store are the way to go.

I understand you will be frustrated when reading this, and I don't blame you. Alas, not all of the web code has been unified with mobile yet, so there is a split in some places. If you can provide a summary of what your changes are about, I can try to guide you on how to adapt them for mobile, it probably won't be a big change.

**Comment by pfisher** [comment]
To clarify a bit more on what we’re trying to do: we are building a hybrid iOS app and we want to utilize the externalAPI to render and handle core conference features, as well as to receive events from the jitsi-meet SDK and also to call into the API for custom behavior and logic that leveraged Jitsi. For example, we want to use the API to get notified about conferencePropertyChanged events, dataChannel/RTC events, participant join/leave events, and also to set presence, set custom localParticipantProperties, mute, and send custom dataChannel messages.

When you mention that The conference object is not used on mobile, are there specific impediments from using it on mobile? Or is it just that mobile is not actively using it currently.

We have extended jitsi-meet to add additional behavior on the externalAPI/API side, such as custom events and commands to support some of the functionality described above, so we can extend it further if necessary, in order to address some of these limitations, make APP.conference accessible, etc. 

Thanks for all your help and direction!

**Comment by saghul** [comment]
> When you mention that The conference object is not used on mobile, are there specific impediments from using it on mobile? Or is it just that mobile is not actively using it currently.

The conference object (conference.js in the root folder) is tied to othe modules wuch as UI, so it's not possible to tie into mobile without a million hacks. Then you'd have to chase all checks like `typeof APP === 'undefined'` which is used to detect web vs mobile (arguably we should check differently, but that's the point here) so I consider this a no-go.

If I were to do this, I'd also extend react/features/mobile/external-api which is similar to the web, but for mobile. It relies on Redux actions for dispatching events.
