### ISSUE TITLE
Audio mix-up for two independent recordings

### ISSUE THREAD

**Issue by martindisch** [jitsi/jitsi-meet#4627]
## Description
Made a recording during a call with a friend to check how I sounded. In the recording, you can not only hear our two voices, but also lots of people speaking what I'm guessing is Russian in the background. We did not hear these during the call, but they seem to be leaking into the recording.

I still have that recording, but don't feel comfortable sharing it publicly since I don't speak Russian and can't verify that the other people are talking about harmless stuff that can be made public.
If you need to hear it for analysis, I can share it privately with a developer if you want. Or I can publish it if a Russian speaker can verify for me that nothing sensitive is said.

## Current behavior
Hearing audio from other meetings in a recording.

## Expected Behavior
No leakage of audio into the recording of another meeting.

## Severity
While this won't stop me personally from using Jitsi (love it, by the way), I could see how it would be a serious issue, should it be reproducible, and even more so, if one could target a specific meeting (though that's a very big if).
But I'm mostly just interested in this because it's a very strange problem and I'd love to hear your guesses about what could have caused it.

# Environment details
* https://meet.jit.si/ on 2019-09-12T07:43:00Z
* One client using Chromium 76.0.3809.132 (Official Build) on Arch Linux (64-bit)
* One client using Firefox 69.0 on Windows 10

**Comment by saghul** [comment]
OK, we have been looking at this for the past few days and we now have a pretty good understanding of what happened. The issue was related to the deployment scripts we use on meet.jit.si. It was neither jitsi-meet, nor jibri related, which is why we will be closing it here. 

For the sake of completeness, here is what happened: when we autodeploy a new Jibri instance on AWS, for example when we scale up the number of available Jibri recorders, there used to be a short period of time (under a minute) during which the new instance appeared available to our system while its configuration wasn’t fully complete. If a person were to start a recording/live stream during that window, that session would be temporarily interrupted when the recorder configuration completed and then resumed again. If another user were to start another recording/live stream during the time of the interruption (between the cut and the resume) and if our system happened to select the same recorder to service that new recording/live stream, then the audio of the first recording/live stream would end up mixed into the file of the second session. 
    
We have traced the audio reported here to a YouTube live streaming session. We were able to find only one other occurrence of this problem where, 1 minute and 46 seconds of audio from a YouTube live stream were mixed over the audio of another meeting recording. 

The problem has been addressed on meet.jit.si since last Friday and at this point cannot happen any more. 

Thanks a lot for the report!
