### ISSUE TITLE
Internal error message

### ISSUE THREAD

**Issue by cmarquay** [jitsi/jitsi-meet#4687]
Hello,

Just have an internal error message when joining https://edplus.biz/1e0e3bacdff54e10a6f39a28e8dd19ab which offers me to join support here ...
I use Chrome on Windows10.

**Comment by damencho** [comment]
When having questions or problems use the community forum before opening new issues.

When reporting a problem, please give more details, what was not working, what was the expected behavior, what browser and version did you use, was it on meet.jit.si or some other deployment. If acceptable a screenshot will be helpful.
