### ISSUE TITLE
[FEATURE REQUEST] option to hide my own video in tile view

### ISSUE THREAD

**Issue by sebseb7** [jitsi/jitsi-meet#4697]

**Comment by saghul** [comment]
This doesn't sound like a good idea. How would the user know they are using the camera? (yes, there is the camera LED, but still)

**Comment by sboettcher** [comment]
A full hide is probably not necessary, but having it much smaller than the other ones would be really nice! In general the tiled view seems to waste a lot of screen estate with margins around the tiles, so having your own video smaller or just as a thumbnail for example would help with that.

**Comment by saghul** [comment]
Given how long this was open with no movement, it doesn't seem like it's going to happen anytime soon. Closing.

**Comment by romainreignier** [comment]
As mentioned by @sboettcher it would be nice to reduce our own video to a small thumbnail in tile mode to not waste space and see mainly the other participants.

Should I create a new issue or can this one be re-opened with a title rename to reduce the size and not totally remove the video?

Thank you.

**Comment by harry-7** [comment]
I +1 this. Can someone look into this please?

**Comment by etezel** [comment]
+1 for this request. Small view would be enough for my own video, and would leave more space for other participant's videos

**Comment by fr1sty** [comment]
+1 would be nice not having my own video taking up so much space. Also reducing/removing the margins around the videos would be nice. For example only showing the menu buttons/options when the user moves the cursor.

**Comment by markrosa** [comment]
+1 as well!
It would be good to be able to hide one's own video and maybe even others by a context menu entry. "Hide" could actually be "minimize"...

Thanks for all the great work!

**Comment by sirmspencer** [comment]
+1 for this.  Zoom does it BTW.  to do it better that zoom keep a thumbnail.  Its super bad in tile view when I am the third, it prevents the two people I want to see from taking up any meaningful amount of space on my screen.

**Comment by saghul** [comment]
We don’t have plans to change this in the short term.

**Comment by linndavis** [comment]
Really wish this were an option. As someone who gets video call fatigue super fast, it helps me out enormously to be able to get rid of my own silly face -- it makes it more like a regular conversation for me. IRL, you don't usually talk to people PLUS a mirror showing your own face.

Also, I want to put in a plug for complete hiding, rather than just minimizing. Having a little mini-me doesn't change much for me -- hiding myself entirely does.

**Comment by fr1sty** [comment]
In Firefox you can do a right click => inspect element on your own video and then press delete. That removes your own image, it helps me for now :)

**Comment by internetErik** [comment]
Thanks for creating and maintaining Jitsi - it's been such a help during the pandemic.

I host a meetup group that has been using Jitsu, and I've been told by members that they wish they could hide their own video for reasons similar to linndavis. They opt to use no video because of this even though they wish they could (and it is helpful for others to see each other). I wouldn't suggest it as a default because of what was mentioned in the second comment (good for people to know they are on camera beyond the led), but it would be useful for some of these people I have interacted with.

I know this issue is not a high priority and accept that this may not happen - just putting my 2 cents in. Thanks again

**Comment by BroderPeters** [comment]
I also think it would be nice to have it. From all video chat solutions I've experienced so far it seems to be pretty common to have either a small video of yourself or even none.
Personally it would be helpful, so I don't tend to always look on myself but focus more on the other participants.

Maybe having the option to toggle the visibility of your own video stream in the tile view could be a thing, like it is in Google Meet.

**Comment by mholtmanns** [comment]
+1 Every single other video conferencing system supports thumbnail view for client video, so I think this is a must have.

**Comment by thomasgentilhomme** [comment]
+1 That would be extremely useful, especially for production purposes when we don't need to see our own feed

**Comment by nicholas512** [comment]
> In Firefox you can do a right click => inspect element on your own video and then press delete. That removes your own video, it helps me for now :)

if you want to be able to undo it you can add this css rule:

```
div#localVideoTileViewContainer {
    display: none;
}
```

**Comment by D4RKONION** [comment]
+1 extremely important for webinar/stream production purposes. 

PS: Thanks @nicholas512 for the css rule, I added it to stylus so I could easily turn it off and on!

**Comment by tskj** [comment]
Having to see yourself constantly is mentally taxing, and I think everyone has had the experience of constantly looking at yourself rather than everyoen else. Sad that this issue has been closed, it's difficult to consider jitsi a serious player in the video conference space if they don't understand this.
