### ISSUE TITLE
if the video quality rule configurable？

### ISSUE THREAD

**Issue by longpan** [jitsi/jitsi-meet#4733]
There are 4 video quality as : "low bandwidth",  "low definition", "standard definition", "high definition"; 
the default video quality is  "high definition",  how to set the default quality to  "standard definition"?

Another qustion is that：can I take out the  "low definition" and "high defintion" option? When the bindwith Change， the video quality only fluctuate within "low bandwidth" and  "high definition".

**Comment by marclaporte** [comment]
I also think the default video quality (and bandwidth usage) should be lower. Perhaps even the lowest level.

**Comment by saghul** [comment]
@marclaporte I completely disagree. Why not give your users the best exprecience you possibly can, and have them lower the quality if they have constrraints we cannot detect? Note that we already lower the receiving quality automatically based on bandwidth use.

@longpan Sorry, looks like this issue fell through the cracks. Right now that option is pretty static and cannot be changed as you'd like.  The first option (selecting a given quality for every call) should be attainable though.

**Comment by marclaporte** [comment]
@saghul: not everyone lives in places with very high-speed and without limits. More than once, I have busted my monthly 4G plan because of Jitsi calls. This costs money.

It would be great if Jitsi Meet could tell how much bandwidth per hour I will use, at the current consumption. With a link to change the current "Manage video quality" setting.

Could Jitsi Meet remember my last setting? (It currently remembers my name)

Thanks!

**Comment by saghul** [comment]
> not everyone lives in places with very high-speed and without limits. More than once, I have busted my monthly 4G plan because of Jitsi calls. This costs money.

I know. That's why I said *constraints we cannot detect*.

> It would be great if Jitsi Meet could tell how much bandwidth per hour I will use, at the current consumption. With a link to change the current "Manage video quality" setting.

This is already available (minus the link) when you hover the "signal bars" icon on your own thumbnail:

<img width="400" alt="Screen Shot 2020-01-15 at 10 54 38" src="https://user-images.githubusercontent.com/317464/72423998-8f258400-3785-11ea-87a0-8f666f715f38.png">

> Could Jitsi Meet remember my last setting? (It currently remembers my name)

Yes, this should be doable.

**Comment by marclaporte** [comment]
Thank you for the screenshot of the bitrate. I have seen that interface, but I must have forgotten about it :-)

Usually, 4G connections have a cost per gig, consolidating upload and download. Perhaps we could have a new line with easier language for end users. Ex.:

At this rate, you will use 2.3 gigs of data per hour
and/or
At this rate, 1 gig of data will be used up in 32 minutes

So end users could experiment with the settings and estimate their bandwidth usage.

Thank you!

**Comment by saghul** [comment]
This sounds like a good idea! The place where the information is currently displayed is not ideal, however. I'll pass this along to the team and hopefully we can improve the UX in this regard.

Thanks for the feedback!

**Comment by longpan** [comment]
@saghul @marclaporte Thank you for answer and discuss the question patiently. I understand it and I will close the issue

**Comment by marclaporte** [comment]
Hi @longpan: can we re-open? This is not resolved yet.

Thanks!

**Comment by marclaporte** [comment]
Hi @longpan: I don't understand why you closed this. Can you please explain?
