### ISSUE TITLE
create the jitsi-meet framework for iOS error

### ISSUE THREAD

**Issue by xiefangzhenz** [jitsi/jitsi-meet#4828]
I am trying to create the jitsi-meet framework for iOS.

When I execute in the root jitsi-meet directory:
xcodebuild -workspace ios/jitsi-meet.xcworkspace -scheme JitsiMeet -destination='generic/platform=iOS' -configuration Release archive

It throws:

<code>
/bin/sh -c /Users/xiefangzhen/Library/Developer/Xcode/DerivedData/jitsi-meet-alonjqiqmhaeqmeoovmbgjfkclrt/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-DE3D81D6228B50FB00A6C149.sh

WebRTC framework has NO bitcode

~/Documents/develop/html/jitsi-meet/node_modules/react-native-webrtc/ios ~/Documents/develop/html/jitsi-meet/ios/sdk
Downloading files...
Command /bin/sh failed with exit code 35

** ARCHIVE FAILED **

The following build commands failed:
	PhaseScriptExecution Bitcode /Users/name/Library/Developer/Xcode/DerivedData/jitsi-meet-alonjqiqmhaeqmeoovmbgjfkclrt/Build/Intermediates.noindex/ArchiveIntermediates/JitsiMeet/IntermediateBuildFilesPath/sdk.build/Release-iphoneos/JitsiMeet.build/Script-DE3D81D6228B50FB00A6C149.sh
(1 failure)
</code>

**Comment by saghul** [comment]
What happens if you execute `node_modules/react-native-webrtc/tools/downloadBitcode.sh` ?

**Comment by xiefangzhenz** [comment]
It works！
Thanks! 
Why do this can solve it?

**Comment by saghul** [comment]
That script downloads the WebRTC framework builds with bitcode. The build process takes care of this already, but for some reason it failed the first time it ran.

**Comment by Shamsiddin** [comment]
@saghul Can You please give detailed instruction for building framework with bitcode? I don't know how to execute node_modules/react-native-webrtc/tools/downloadBitcode.sh

**Comment by Shamsiddin** [comment]
It seems I downloaded WebRTC framework with bitcode. Now My project giving an error like:

`/vendor/JitsiMeet.framework/JitsiMeet' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/vendor/JitsiMeet.framework/JitsiMeet' for architecture arm64`

Is there any chance to download JitsiMeet.framework with bitcode?

**Comment by saghul** [comment]
No, you’d need to build it yourself with bitcode.

You can edit ios/scripts/release-sdk.sh so it build it with bitclde.

**Comment by Shamsiddin** [comment]
It's very hard to understand for devs with no sh script experience. I don't know even how to edit it to build JitsiMeet.framework with bitcode and where to use this script in XCode project :(

**Comment by saghul** [comment]
Let’s take a step back. Why do you need bitcode in the first place?

**Comment by Shamsiddin** [comment]
When I installed `pod 'JitsiMeetSDK'` as shown in docs, already existing Alamofire is giving an error:

`'/DerivedData/myproject-hccnefkrglxvqjaurmuyhyvwpcbd/Build/Products/Debug-iphoneos/Alamofire/Alamofire.framework/Alamofire' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Developer/Xcode/DerivedData/myproject-hccnefkrglxvqjaurmuyhyvwpcbd/Build/Products/Debug-iphoneos/Alamofire/Alamofire.framework/Alamofire' for architecture arm64`

That's why I wanted to enable bitcode for JitsiMeet too.
Here's I'm attaching my Podfile and Podfile.lock. Can You please experience my Podfile(lock) and give a solution Please?
Thanks in advance! 

[Podfile.zip](https://github.com/jitsi/jitsi-meet/files/4385782/Podfile.zip)

**Comment by Shamsiddin** [comment]
@saghul, I think it worked.
After I change on my project's target `Build Settings -> Enable Bitcode -> No` compiletion is succeeded. 
So here's the conclusion: I installed as described in documentation using `Cocapods` BUT turned off `Build Settings -> Enable Bitcode` option on my project.
I home turning Bitcode off doesn't have any drawback.
Thanks!
