### ISSUE TITLE
jitsi-meet config shows incorrect values

### ISSUE THREAD

**Issue by rguenther-dz** [jitsi/jitsi-meet#4868]
## Description
jitsi-meet config shows incorrect values.
As described in https://community.jitsi.org/t/launch-moderator-with-default-settings/15057
the config options:
- Everyone starts hidden
- Everyone starts muted
have the same meaning as the settings in config.js startWithVideoMuted: true and startWithAudioMuted: true. 

## Current behavior
when i set e.g. startWithAudioMuted: true in config.js, the participants start muted. That's correct. 
But the config option Everyone starts muted shows false. This is not the actual behavoir.
Same with startWithVideoMuted.

## Expected Behavior
the initial value of Everyone starts muted and Everyone starts hidden should show the actual behavior of jitsi-meet, e.g. should be identical to the config setting of startWithVideoMuted and startWithAudioMuted

## Steps to reproduce
- set startWithAudioMuted to true in config.js
- start meeting and login as moderator
- config option Everyone starts muted shows false, this is incorrect
- connect participant to the meeting
- participants audio is muted, this is o.k.

# Environment details
latest docker setup

**Comment by saghul** [comment]
Those are two separate options. startWithAudioMuted is local policy, it’s the choice of the local user, whereas the “everyone” options are enforced by the moderator and are only available to the moderator.

Note that by default everyone is a moderator in the Docker setup, same as meet.jit.si, so that’s why they show up for everyone.

I acknowledge the options are ill named, but it’s hard to make changes there without breaking everyone’s installation and since privacy is at stake here we are very cautious.
