### ISSUE TITLE
Create xcframework instead of framework 

### ISSUE THREAD

**Issue by jeetkapadia** [jitsi/jitsi-meet#4984]
If you have a question about Jitsi Meet that is not a bug report or feature
request, please post it in https://community.jitsi.org

Questions posted to this repository will be closed.
I want to know whether I can create an xcframework of JitsiMeet framework. Since our App contains many 3rd party frameworks and we are moving all them to xcframework. is it possible in case of Jitsi as well?

**Comment by saghul** [comment]
It's not currently possible. This is something I'd like to look into, but I cannot provide an ETA.

**Comment by NishantTiwarins** [comment]
Hi @saghul 

Is there any update on this ? We are waiting for jitsiMeet xcframework. Please let me know if that is possible. Thanks

**Comment by saghul** [comment]
I have no update sorry. Nor do I have an ETA. Just so I can understand better, why are you waiting for it? As in, do you have a problem using our current framework? My undrestanding is that one can mix and match just fine.

**Comment by NishantTiwarins** [comment]
Hi 

Yes it can mix and match just fine but our SDK is created successfully in Xcframework and we were thinking that providing the dependencies also as an XCframework would be great because the sole purpose of XCframework is that it's compatible with every Xcode version so we don't need to support multiple Xcode versions.

**Comment by saghul** [comment]
I'm trrying to gauge importance here. From what you say, it would be nice to have, but it's not actively preventing you from using the SDK.

> the sole purpose of XCframework is that it's compatible with every Xcode version so we don't need to support multiple Xcode versions.

Hum, I'm not sure that's correct. Doesn't `BUILD_LIBRARY_FOR_DISTRIBUTION` (which we have turned on for the SDK) accomplish that already?

**Comment by NishantTiwarins** [comment]
Hi 

Correct me if i am wrong but as per my knowledge "Build library for distribution is done yes"  when we need to create an XCframework. Just doing "Build library for distribution to yes" does not makes the SDK compatible with all Xcode Version. We have already tried this at our end with JitsiMeet.framework for e.g The framework complied with Xcode version 11 does not work with xcode 11.2.1 since there was a change in swift version and this can be solved using xcframework

**Comment by saghul** [comment]
It has been a while, but when adding that in https://github.com/jitsi/jitsi-meet/issues/4812 IIRC it should work with different Xcode versions starting with 11.

**Comment by NishantTiwarins** [comment]
Hi,

I see you have created a new issue for building xcframework. Also I have checked again and framework build from xcode 11 is not working in future versions i.e xcode 11.2.1 or 11.3 and above. I feel the fix for this would be xcframework with build library for distribution setting enabled.
