### ISSUE TITLE
ipv6-Support missing in config of nginx on debian

### ISSUE THREAD

**Issue by GitNorb** [jitsi/jitsi-meet#5000]
I installed jitsi-meet last week on debian buster and it didn't create the listen line for ipv6.

`listen 443 ssl;` was available but `listen [::]:443 ssl;` was missing so nginx only listened on ipv4.

My server has an ipv6-address so for some people jitsi-meet worked and for all with ipv6 it didn't.

I added `listen [::]:443 ssl` to my config and now it works. Maybe you can add this line automatically at installation.

**Comment by saghul** [comment]
Makes sense, thanks for the report!

**Comment by gbonfiglio** [comment]
In my installation in addition to the above, this is what I have:

`root@jitsi:~# lsof -ni :443
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
java    1080      jvb  146u  IPv6  10994      0t0  TCP [2a02:898:202:c17::2a8]:https (LISTEN)
nginx   1129     root    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1131 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1133 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1134 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1135 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1137 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1138 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1139 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)
nginx   1140 www-data    8u  IPv4  19627      0t0  TCP *:https (LISTEN)`

For the reason mentioned by @GitNorb nginx is only listening on https over ipv4, but in addition to this jvb seems to be listening on port 443.

This was effectively breaking my dual stack setup - suggest it's considered a bug since if the hostname includes both A and AAAA then connections over IPv6 will end up in the wrong place.

**Comment by gbonfiglio** [comment]
Probably found the cause here: https://community.jitsi.org/t/jitsi-dev-nginx-not-installed-by-quick-install/13393

> if no nginx or apache is installed the quick install
method uses the jetty to serve the web, the jetty that is in jvb

Looks like this also works in "split horizon", if nginx isn't using port 443 over ipv6 then jvb/jetty will take over.

**Comment by Wesseldr** [comment]
Additional note (not really a bug of Jitsi but a behaviour for future reference in case some one else hits this....)
System affected: Ubuntu 18.04.4 LTS

After adding the line of @GitNorb (thank you for the solution) so NGINX is ipv6 aware...
NGINX might refuse to start up with the following error:
`Mar 21 19:58:20 meet systemd-resolved[737]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.`

This is due an incorrect linked of`/etc/resolve.conf`. (see: https://askubuntu.com/questions/1058750/new-alert-keeps-showing-up-server-returned-error-nxdomain-mitigating-potential) 

Solution is simple:
First check if you're affected with the old file link with:
```
ls -lsa /etc/resolv.conf
/etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```

Yes you are affected still, simple remove the link and re-create it like this:
```
sudo su -
rm /etc/resolv.conf
ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
```
Reboot Ubuntu and your Jitsi server will be nicely IPv4/IPv6 :-)

JWR
