### ISSUE TITLE
How to start Jitsi on mobile web site?

### ISSUE THREAD

**Issue by dmelechow** [jitsi/jitsi-meet#5123]
How to use Jitsi on mobile web site internally as in a browser? or Jitsi doesn't have such functionality? 

Now I inject Jitsi and on the web, it works well, but on the mobile web, I have redirection links as on the screenshot below.

![image](https://user-images.githubusercontent.com/11187627/76295638-0549f100-62c6-11ea-91a1-8da7841968e7.png)

**Comment by saghul** [comment]
We don't currently support using Jitsi on a mobile browser.

**Comment by freechelmi** [comment]
Hello , I m' sorry but I'm like to rephrase this request ( instead of creating a new issue) " Option to enable mobile browsers"  and to reopen it : 

We'd like a way to let our mobile users **decide** if they want to use their browsers on mobile device.

I totally understand that default package disable mobile web browsers to lower the support requests.

Right now I tried  **disableDeepLinking: true** in config.js , but you just get a gery page with js errors.

I wish this option would enable a "**continue anyway with your browser"** below the current apps link

**Comment by dmelechow** [comment]
@saghul Do you have a plan to support the mobile web version? Or Do you have some restrictions to do it?
