### ISSUE TITLE
Live streaming

### ISSUE THREAD

**Issue by 06900691** [jitsi/jitsi-meet#5146]
Non mi permette di accedere al video mentre provo a fare le dirette in streaming. Come faccio? 
Non riesco ad attivare la telecamera

**Comment by saghul** [comment]
Please try to write in English, we don't speak any italian. Try to describe the problem as acurately as you can: are you using the YouTube live streaming funcionality or is it a regular conferene? What browser are you using?

**Comment by bhack** [comment]
> It won't let me access the video while I'm trying to stream live. How do I do that?
I can't activate the camera

**Comment by badesemowo** [comment]
I believe this should be a new thread @echolon as #5718  was asking for a new feature whereas this issue is to fix a bug in an existing feature. 

Here is the feature request:  

It would be great for us to be able to Livestream from  meet.jit.si to 
a. Facebook Live 
b.  Instagram Live 
c.  Any other streaming platform 

Currently, I see that Livestream to Youtube already works.  Is there an ongoing effort to deliver on this? Is there a way to support so it can be fast tracked? 

Alternatively, is it possible to have a bit of direction from more experienced community members on how this feature can be implemented?  I may be able to get my dev team to work on this feature if we can get direction.

**Comment by grahamPegNetwork** [comment]
I opened #5718 which has been closed. I agree with the feature request @badesemowo proposes. 
While I have not looked into the relevant code yet, I would imagine it will involve:
1. Config/settings managing the streaming endpoint (these services are going to be RTMP I believe)
2. UI to accept stream keys

**Comment by Fahad-pnw** [comment]
@badesemowo @grahamPegNetwork  Hi, you found any leads into where to find the stream endpoints?
i'd also like to develop/work towards streaming jitsi meet to my own endpoint and figuring out where to begin with that.

**Comment by mikelnrd** [comment]
As well as the main social platforms that offer live streaming, there's https://mux.com/ that is targeted at developers. I just tested it myself recently and created an rtmp (actually an rtmps) streaming endpoint I could stream to in a few simple steps and was able to stream to it from zoom (and also ffmpeg on my local computer no problem).

I found this issue when researching how to use meet.jit.si with a custom streaming endpoint but alas only youtube is currently supported without self hosting. The goal in my case is to use jitsi for the webrtc browser client and self-host the live-stream video player too powered by mux instead of live streaming to youtube/facebook et al.

It'd be great to be able to select an option in the meet.jit.si interface and paste in a custom rtmps endpoint one day soon if that's doable!

I wonder... if you reached out to mux.com perhaps they'd be interested in helping out in some way - live streaming is what they specialise in after all and they make money the more people/companies are sending live streams to them.

https://mux.com/blog/intro-guide-how-to-figure-out-which-live-streaming-platform-to-use-and-why/
https://mux.com/blog/the-state-of-going-live-from-a-browser/

(not affiliated with mux.com in any way, just like their work!)

**Comment by grahamPegNetwork** [comment]
@Fahad-pnw The issue for me isn't finding the endpoints, that's trivially easy to do. The main issue is having the ability to drop that endpoint into code via config file, or let the user paste an endpoint directly in.

If development gets to a point where endpoints are required I can track them down.

**Comment by l3d00m** [comment]
I think the comments here can now be mostly redirected to either #2829 or #6156. They have in-detail request for some specific livestreaming features.
