### ISSUE TITLE
Problem with moderation

### ISSUE THREAD

**Issue by Sim59121** [jitsi/jitsi-meet#5190]
Hello,

## Description

When i launch a  video conference, i'm moderator and normally, i'm the only one. But, all the other participants also are moderator... So they can kick me, mute me etc...

I think, it's not normal 

## Current behavior

All people in the conference are moderator and not only the creator

## Expected Behavior

Only the creator is moderator (and the people he gave permissions to moderate).

## Possible Solution

I don't know

## Steps to reproduce

1. Launch a videoconference at https://meet.jit.si
2. Invite people
3. Asking newcomers to kick you, mute you etc...

# Environment details

I use Mozilla 74 on windows 10.

**Comment by damencho** [comment]
Please use the community forum when you have questions before opening new issues.

This is intentional how meet.jit.si is deployed/configured and there are no plans to change that. You can always deploy your own instance and leave so the first to join to be a moderator or you can enable authentication ...
