### ISSUE TITLE
automatic limit server load

### ISSUE THREAD

**Issue by David100mark** [jitsi/jitsi-meet#5240]
I really like the tool.
We are currently using it on our own server, which works really well. 
But because we got several other processes running on it, it would be a shame if a big conference would lead to slowing things down.
It would be really nice if you could configure a maximal server load. When this limit is reached, it should block new conferences from being added, or even new users from joining.

Thanks a lot
David

**Comment by saghul** [comment]
There is currently no way to accomplish that, AFAIK. Sorry!

**Comment by alexanderadam** [comment]
Actually it should easily be possible if you are using [`docker-jitsi-meet`](https://github.com/jitsi/docker-jitsi-meet). Because [Docker is able to limit memory, CPU and GPU for each container](https://docs.docker.com/config/containers/resource_constraints/).

You can also add it to your [`docker-compose.yml`](https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml), if you are using Docker compose.
You can read everything about it in [the official documentation](https://docs.docker.com/compose/compose-file/#resources).

**But** [you have to set it to version `'2.1'`](https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml#L1) **or** use compatibility mode if you want to specify it in the `docker-compose.yml`. Otherwise you have to use _swarm mode_ because [docker _compose_(!) stopped supporting resource limits otherwise](https://github.com/docker/compose/issues/4513#issuecomment-281478365).

So if you use compatibility mode (`docker-compose --compatibility up`) or [switched to version 2](https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources), you can add `resources.limits` to each service of your [`docker-compose.yml`](https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml). 

For instance

```yaml
services:
  web:
    image: jitsi/web
    […]
    resources:
      limits:
        cpus: '0.001'
        memory: 250M
[…]
```

**Comment by saghul** [comment]
That's a great point @alexanderadam ! Alas it doesn't handle the case of not allowing new meetings / participants, which the OP wanted.

**Comment by alexanderadam** [comment]
IMHO this variant is even better because

1. This way important meetings wouldn't be skipped
2. it still avoids "_a big conference […] lead[ing] to slowing things down_"

:wink:
