### ISSUE TITLE
Add ability to upload own image file for avatar

### ISSUE THREAD

**Issue by rugk** [jitsi/jitsi-meet#5254]
**Is your feature request related to a problem you are facing?**
Currently, you can only use Gravatar for avatars and you need to pass your mail for doing so. As I find this privacy-invading and don't want to use Gravatar nor provide my mail, I would like a better solution.

According to https://github.com/jitsi/jitsi-meet/issues/2060 and https://github.com/jitsi/jitsi-meet/issues/935 you can set your own avtar host domain as a server admin, but well… this does not really work on a public server and for everyone. In the end, it's just a different instance then, and it does not solve the mail problem either.

**Describe the solution you'd like**
I would like to just be able to upload my avatar as an image file. As simple as that, as any other website/forum can do.

**Describe alternatives you've considered**
All are already implemented.
Maybe you can fetch it from somewhere else, but as https://github.com/jitsi/jitsi-meet/issues/935 says, this feature has been removed. (Okay, would be possible to safely add if you proxy the images through your own server, but then it's also just the difference between drag/drop/select an image or paste an URL from a usability standpoint.)

No other ideas.

**Comment by damencho** [comment]
This will only work for instances that has authentication enabled, deployments like meet.jit.si cannot do it and then it comes all the GDPR questions and stuff so I don't see this to happen anytime soon if at all. 
Currently, all user sensitive information is in local storage on client PC and is never stored anywhere.
The approach is jitsi-meet to use information you pass (avatar link in jwt) or obtain it from a public resource. Like deploying your own avatar service and use it in your deployment.

**Comment by dbareis** [comment]
If the avatar from Gravatar gets stored locally (and not retrieved every time or stored on a server), then allowing a user to add their own image should be a trivial exercise.

**Comment by saghul** [comment]
Not really @dbareis . That avatar then needs to be sent to all other participants. Not impossible, but it would need to be done.

**Comment by davidak** [comment]
This is still needed.

**Comment by gh4tg** [comment]
I'm running JitsiMeet on an own instance and I was looking how to include an avatar picture, without using Gravatar, for an hour now.

Thank you for the explanation that it is not that easy to do this without fixed account, anyway I think that it's an important feature, most other solutions provide this "simple" feature.

So the avatar image has to be stored locally on the PC/webbrowser, together with the name, I believe it's no problem to implement that.

Second, this image has to be transfered to the other participants, prefarable like the name too or, when the camera is off, as video-stream, what would be quite stupid because of the needed bandwidth. Maybe a solution could be, just transfer it for a short moment and the other clients keep this image until the webcam is switched on again.

Thanks for any solution in advance :-)

**Comment by rugk** [comment]
As a user, if you want to have this feature now, you can use this Jitsi Hack for setting your avatar: https://jitsi-hacks.cketti.eu/hacks/change_avatar/

**Comment by didierm** [comment]
Go away, bot.

**Comment by saghul** [comment]
We have no plans to implement this.
