### ISSUE TITLE
Recorders Busy in https://meet.jit.si

### ISSUE THREAD

**Issue by anil-pugalia** [jitsi/jitsi-meet#5271]
I am consistently getting "All recorders are currently busy", when I do "Start recording" at https://meet.jit.si/<Room>.
![jitsi_error_snapshot](https://user-images.githubusercontent.com/941377/77134714-3b3d6100-6a8e-11ea-8811-fedf148aca45.png)

**Comment by damencho** [comment]
We are working on fixing this.

**Comment by anil-pugalia** [comment]
But then why did you close it. Is it already fixed? If not, by when is the plan to fix it?

**Comment by damencho** [comment]
As a start did you read the template at all when you created the issue? Second there is no issue with jitsi-meet. Third, you are posting a problem for a deployment in a open-source project, does that mean that all deployments using this project are broken, answer is no.
And last we know about the problem and instead of fixing it, we are replying to hundred messages like this, cause no body checks whether somebody already reported it and whether there is an answer for that report.
