### ISSUE TITLE
Re-install won't ask for hostname

### ISSUE THREAD

**Issue by galvaniccoffee** [jitsi/jitsi-meet#5435]
I followed the [quick install guide](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md) on a clean install of Ubuntu 18.04.3, but accidentally entered the wrong hostname when the installation prompted me. Due to this, the installation immediately failed.

I've tried to reinstall jitsi, but now the installation won't prompt me for a hostname anymore, but will instead use the one from the first installation and  therefore fail again. I've found countless threads with this exact problem, but none of the presented solutions seem to remove that hostname configuration from my system.
 
For removing jitsi completely, I've tried:
- `apt-get purge jigasi jitsi-meet jitsi-meet-web-config jitsi-meet-prosody jitsi-meet-turnserver jitsi-meet-web jicofo jitsi-videobridge` as stated in the quick install guide, run 3 times. 
- `apt-get autoclean && sudo  apt-get --force-yes remove && sudo  apt-get install --reinstall dpkg` as suggested [here](https://github.com/jitsi/jitsi-meet/issues/2663#issuecomment-376484424). The `jitsi-meet-web-config.postinst` file mentioned there does not exist on my system.
- `apt-get autoremove`
- Manually deleting `/etc/jitsi`, which all of the above fails to remove
- Rebooting my system

Even after all of this, the installation (`apt-get -y install jitsi-meet`) still manages to retrieve the wrong hostname from _somewhere_ and will fail.

I've noticed that `dpkg -l | grep -i jitsi` will still output
`rc  jitsi-videobridge2              2.1-157-g389b69ff-1                         all          WebRTC compatible Selective Forwarding Unit (SFU)`, but I don't know what that means.

**Comment by damencho** [comment]
Please use the community forum before opening new issues.

I think the guide needs an update, sorry for that. You also need `apt-get purge jitsi-videobridge2`

**Comment by sizrar** [comment]
Hi
I confirm that issue on debian strech and buster. My first install attempt failed and I couldn't go back in the installer to fix the issue, and since then even with tens of uninstall / reinstall I never could get the configuration screen again with apt. 
Yes, I read all the instructions and posts related to that issue, none worked. 
apt-get purge jitsi-videobridge2 
didn't fix it either. Removing manually the dpkg postinst files as suggested either. 
Between dpkg apt and jitsi, there is something going on not triggering the launch.

Best regards.

**Comment by cinderblock** [comment]
My installer failed because I have a non-standard nginx configuration. Specifically, the traditional `sites-available` does not exist on my system (because I think it's a stupid folder name and mine is just called `servers`). This cause the installer to fail. I've been trying to uninstall and purge everything to re-run the setup and finish the configuration but it refuses to run the setup process again.

PS, I would much rather have the option to do a manual setup. Example ngnix configs are fine but those of us that understand nginx might not want to use your configuration exactly. Currently, instructions to do a manual install/reverse proxy are basically non-existent.
