### ISSUE TITLE
web cam

### ISSUE THREAD

**Issue by giannny408** [jitsi/jitsi-meet#5492]
non riesco ad aprire la webcam

**Comment by alexanderadam** [comment]
1. Se possibile, dovresti comunicare in inglese.
2. Puoi provare https://test.webrtc.org/ e vedere che funziona lì?
3. Questo è probabilmente un duplicato di #5155

<hr>

1. If possible, try to communicate in English
2. Can you try whether your camera works at https://test.webrtc.org/?
3. This is probably a duplicate of #5155

/cc @saghul maybe it would make sense to make a sticky issue regarding Webcam issues? Otherwise all those duplicates will continue popping up…

**Comment by saghul** [comment]
Good call @alexanderadam I had never used pinnedd issssues before. Pinned https://github.com/jitsi/jitsi-meet/issues/5425

**Comment by alexanderadam** [comment]
@saghul you also might want to add the missing 'o' in the title (non-w_o_rking) :wink:

**Comment by saghul** [comment]
🤦‍♂

**Comment by alexanderadam** [comment]
Perfect :+1:

**Comment by Echolon** [comment]
@saghul I favor of #5425 I would also close all the listed issues to clean up the repo
