### ISSUE TITLE
Open source video-calling is more or less by definition dedicated to privacy; but you support only . . Chrome

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [jitsi/jitsi-meet#5516]
Open source video-calling is more or less by definition dedicated to privacy. Certainly that was a major reason I came to look at jitsi. But then your website says only certain browsers are supported and those browsers turn out to comprise, in their entirety . . Chrome. Chrome is notorious for being anti-privacy. I suppose your site *might* work reasonably well with some of the privacy-inflected versions of Chrome, or with Chromium. But come on! What about . . Firefox? Also - for video-calling software should be multi-platform too - what about Safari?

Still, you can develop what - and for what - you want, I suppose.

**Comment by saghul** [comment]
Please search before opening new duplicate issues. See: https://github.com/jitsi/jitsi-meet/issues/4758

**Comment by tuxayo** [comment]
@LinuxOnTheDesktop it's not that bad as «you support only . . Chrome»

Chromium is also recommended: https://web-cdn.jitsi.net/meetjitsi_3962.622/static/recommendedBrowsers.html

>  It looks like you're using a browser we don't fully support. 

Maybe the phrasing puts too much burden on Jitsi Meet's side.
It seems that this is also a lot of work on the side of Firefox to do for apps like Jitsi Meet to work correctly.

#4758 is a entry point to try to understand what's missing on both sides.

One of the factor we have to be conscious is that the huge difference of means between Chrome and Firefox. And that the fact that Google has web conferencing apps (Google Hangout and Google Meet) which means they obviously can focus resources to make it work great.
And also they can abuse their power due to market share to do things in the way that is the most convenient for them.
And if they lead the work on a given web standard, they will have the advantage that the final spec will be very close to their own implementation on which they started to work on it much earlier.

As users, I think on of the thing we can do it fund Firefox well. And also Jitsi Meet because it's one of our best tools out there for libre video calling.

An analysis (I An Not An Accountant) of Mozilla's budget report[1] shows that 90% of Mozilla's income is from contract with search engines. And only 0.74% of funding is from individuals. That's a 120/1 difference.

[1] french resource with some English citations from the report: https://colibris-wiki.org/revlibre/?PayeTonLL
