### ISSUE TITLE
Error verifying token err:not-allowed, reason:token required

### ISSUE THREAD

**Issue by c100k** [jitsi/jitsi-meet#5517]
## Description

Accessing with a link like https://subdomain.domain.io/room1?jwt=SOME_JWT does not provide the token to BOSH.

## Current behavior

The JWT is not available in BOSH session, therefore, the following line is logged in `/var/log/prosody/prosody.log`

```shell
conference.subdomain.domain.io:muc_domain_mapper	warn	Session filters applied
mod_bosh	info	New BOSH session, assigned it sid '04cc0a0c-95f5-4f5f-b953-ee162f2032fb'
general	warn	Error verifying token err:not-allowed, reason:token required
```

## Expected Behavior

There should not be the `warn` line since the JWT is provided. And it should validate the JWT. If valid, let the user access to the room.

## Possible Solution

There must be something removing the JWT from the query in some place. What does this `Session filters applied` do ?
Moreover, if we check in the Network tab of the browser, we see that `POST https://subdomain.domain.io/http-bind?room=room1` does not send any JWT.

## Steps to reproduce

1. Setup a server with token authentication (see environment details below)
1. Access https://subdomain.domain.io/room1?jwt=SOME_JWT
1. Check Prosody logs to see that the token is required

# Environment details

Here is the setup applied on a Vagrant virtual machine based on `'ubuntu/bionic64'`.

```shell
apt-get update
apt-get install -y wget
echo deb http://packages.prosody.im/debian bionic main | tee -a /etc/apt/sources.list
wget https://prosody.im/files/prosody-debian-packages.key -O- | apt-key add -
apt-get -y update
apt-get install -y prosody
apt-get install -y \
     liblua5.2-dev \
     sasl2-bin \
     libsasl2-dev \
     libssl1.0-dev \
     lua-basexx \
     lua-sec \
     luarocks \
     git \
     gcc \
     patch
luarocks install cyrussasl 1.1.0-1
luarocks install lua-cjson 2.1.0-1
luarocks install luajwtjitsi 1.3-7
luarocks install net-url 0.9-1

apt-get install -y nginx
wget -qO - https://download.jitsi.org/jitsi-key.gpg.key | apt-key add -
sh -c "echo 'deb https://download.jitsi.org stable/' > /etc/apt/sources.list.d/jitsi-stable.list"
apt-get -y update

# SSH into the machine

echo 127.0.0.1 localhost subdomain.domain.io | tee -a /etc/hosts
sudo apt-get install -y jitsi-meet (auto-generated cert)
sudo chmod 0644 /etc/prosody/certs/localhost.key
sudo apt-get install -y jitsi-meet-tokens
```

I made sure the `/etc/prosody/conf.d/localmeet.hbtn.io.cfg.lua` contains the values defined in the [documentation](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#jwt-token-authentication-prosody-plugin).

Also patched `/usr/share/jitsi-meet/prosody-plugins/mod_auth_token.lua` to use `hook_global` instead of `hook`.

One thing to notice : `sudo apt-get install -y jitsi-meet-tokens` did not update automatically the files, I had to do it manually using https://github.com/jitsi/jitsi-meet/blob/jitsi-meet_4335/debian/jitsi-meet-tokens.postinst. Maybe it can help.

**Comment by diegopso** [comment]
Hi, I am experiencing the same issue. Did you get any solution?

I noticed that nginx is not forwarding query params to BOSH, however, when I add them I get 502 from the nginx server.

**Comment by c100k** [comment]
Unfortunately, no. I was hoping to get some hints from the contributors who know the codebase better than we do. How did you change the nginx config to forward the query params?

**Comment by diegopso** [comment]
I changed the `proxy_pass` in the location /http-bind.

```
From:
proxy_pass      http://localhost:5280/http-bind;
To:
proxy_pass      http://localhost:5280$uri?$args;
```

**Comment by hiddehs** [comment]
I'm experiencing the same issue, I've used the install 'fix' from https://community.jitsi.org/t/jwt-not-working-on-debian-9/29495 to get Prosody 747 working correctly in the first place. 
But i got this blocking error after upgrading jitsi videobridge and jicofo last night (and then downgrading prosody to 747 again, to get it somewhat working). 

The request parameters were passed correctly before the update with the ```proxy_pass      http://localhost:5280/http-bind;``` nginx rule, so this should not be changed.

**Comment by diegopso** [comment]
Yes, it was a trial that didn't work, I just posted because it could help. 

I actually managed to solve following the last response here: https://community.jitsi.org/t/token-authentication-working-with-prosody-747-but-not-with-latest-version-ubuntu-18-04/26615. It lists every step in the order you should proceed.

**Comment by hiddehs** [comment]
Thanks for your response @diegopso , unfortunately I can't get the prosody server to work by following the steps from laurence.
Just a quick Q; which lua versions are installed / where is luajwtjitsi.lua located on your machine?
(context: https://community.jitsi.org/t/token-authentication-working-with-prosody-747-but-not-with-latest-version-ubuntu-18-04/26615/5?u=hidde)

**Comment by josuah** [comment]
I had the same issue and the problem was I was missing the audience ("aud":) and issuer ("iss":) from the token: https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md

It is also to be setup on the prosody part: "aud": and "iss": from the json should have values that are present in the `asap_accepted_issuers` and `asap_accepted_audiences` prosody settings.

This is the 3rd case I see (me/client, on forums, on another Github issue) so it would definitely not be the first time that happen.

There is no log through the whole chain from the client getting the token until the lua module that validates the token, so I do not know if the token was deleted client-side because it was lacking parameters, or deleted by the prosody module, or anything else...

There is an opportunity for improvement here : adding logs as soon as the token gets blocked.
