### ISSUE TITLE
jitsi meet android login password input box defaults to capital letter  

### ISSUE THREAD

**Issue by ageekhere** [jitsi/jitsi-meet#5673]
jitsi meet android login password input box defaults to a capital letter for the password
e.g
myusername
Mypassword
app v20.1.0

**Comment by saghul** [comment]
Thanks for the report!

**Comment by ageekhere** [comment]
is it also possible to add remember log in details?

**Comment by le-zell** [comment]
Two problems here : 

1. The password is "autoCaptitalized".

2. If i submit with a username with an space at the end, it won't work either

I think the problem is here : 

https://github.com/jitsi/jitsi-meet/blob/3dfcc8d80e81b48e583195e0b63816eb18ec6470/react/features/authentication/components/LoginDialog.native.js#L175

I would suggest to add 

> autoCapitalize = { 'none' } 

on password field either. 

And a trim js function on the username field (in the state component)
