### ISSUE TITLE
Better support for music-based sound

### ISSUE THREAD

**Issue by wolftune** [jitsi/jitsi-meet#5732]
I am doing music lessons via Jitsi, and I've found these issues:

- I get the noisy-mic alert because of the musical sounds
- The audio cuts off too readily as sounds fade

I learned that adding `#config.disableAP=true` to the URL should help. When I do that, it then loads but that part of the URL disappears. I'll have to check that it's working. That might just be the answer. So, adding that control the UI would be ideal. But that might be all I need really.

**Comment by sebo313** [comment]
Hi @wolftune, I am facing exactly the same issue as i would like to have **music-optimized** video conferencing instead of **speaker-optimized**. Have a look at [this comment](https://github.com/jitsi/jitsi-meet/issues/5462#issuecomment-612423322) which show the more specifc options of audio processing. I am testing them at the moment, maybe you can test them too and give feedback here in this issue?

Regarding the disappearing of URL extension I guess Jitsi takes the settings when starting the meeting and then its all set and no need anymore for showing the URL-extension.

**Comment by wolftune** [comment]
Those options sound superb! I'll try to test those! I guess this issue should be closed since that other issue seems the main relevant one.
