### ISSUE TITLE
Improve color design of 'Audio muted' and 'Camera off' button / symbol

### ISSUE THREAD

**Issue by Echolon** [jitsi/jitsi-meet#5801]
Hola!

During the recent sessions (and as my headset & OS don't like each other) I wondered very often if I am **muted or not**. Also, but still more obvious anyway, if the **camera was active or not**. By personal intuition I always check this by looking at the buttons below. The current state is not very clear in my view.

_Current situation if you are muted and camera is shut off_
<img src="https://user-images.githubusercontent.com/29168011/78817953-36583700-79d4-11ea-9951-e75f66994d73.png" width="170">

I'd rather prefer to see something more obvious. I also suggest to give a written response of that state (only if muted or off). Some users also didn't recognize that they were muted for some reason.

_More clear design of buttons_
_(Sorry for the crappy draft, just that you know what I am talking about)_
<img src="https://user-images.githubusercontent.com/29168011/78818031-4f60e800-79d4-11ea-8aab-64d8b54e7be0.png" width="170">

Thanks for Jitsi!
Saludos!

**Comment by Syonyk** [comment]
How is a slash through the mic/camera icons unclear, compared to the icons not having the slash?

The SVG resources for the icons are here: https://github.com/jitsi/jitsi-meet/tree/master/react/features/base/icons/svg - draft up what you're suggesting!

**Comment by Echolon** [comment]
I can mean both, either "Click to mute" or "It is muted". So actually its not very clear in my opinion.

Will check out, never worked with svg files.

**Comment by Echolon** [comment]
This is highly related: 
#5417 **Wrong color of buttons if there is no HANGUP button**

**Comment by joeytwiddle** [comment]
My suggestion:

- Further darken the "off" buttons, so they appear really sad.

- Use little red/green symbols to indicate the on/off state.

<img src="https://user-images.githubusercontent.com/911799/79117792-a7299580-7dbe-11ea-9932-e82371971642.png" width="400" />

**Comment by joeytwiddle** [comment]
Another option might be to darken the button foreground as well.

<img src="https://user-images.githubusercontent.com/911799/79301478-5039d280-7f1c-11ea-8b66-217b86a61118.png" width="400" />

**Comment by Echolon** [comment]
rel. #6191

**Comment by Echolon** [comment]
no stale

**Comment by nekohayo** [comment]
Part of the problem is being able to convey state more clearly than just a subtle "strike-through" shape (which I can confirm is _not_ so visually obvious to most people), but without decreasing contrast so much (because that is going to be another issue where some people won't be able to see/notice the button at all. Yes, it _will_ happen).

The color restrictions you are experiencing stem from the fact that the audio/video mute buttons are sitting right next to the red "Hang up" button. If the hang up button was located elsewhere and clearly labelled, you would not have the worry of conflicting colors between the (un)mute buttons and the leave button.

...which is exactly why Zoom put the "Leave Meeting" button as a very clear _label_ button in the corner instead of relying on an old phone pictogram (some people in newer generations might not even know what this represents, it's basically like a a banana at this point) and instead of keeping it close to the audio/video controls; because it lets them use the red color for the strike-through bar of the audio/video controls as well.

**Comment by nekohayo** [comment]
In reply to stale bot:

> I've had it with those mothaf'in' 🤖 on this mothaf'in' ✈!
> -- Samuel L. Jackson

**Comment by saghul** [comment]
This one was actually fixed with the toolbar redesign.
