### ISSUE TITLE
Why I can't use jitsi (https://meet.jit.si/) from my phone's web browser?

### ISSUE THREAD

**Issue by GasparVardanyan** [jitsi/jitsi-meet#5875]

**Comment by Echolon** [comment]
@GasparVardanyan 
No support forum, please review: community.jitsi.org.
Hint: you need to install the Jitsi Meet App from the Store.

@damencho can be closed

**Comment by silentshotghost** [comment]
try google chrome or [brave ](https://brave.com/sil506)(chromium) and switch to desktop mode if doesn't work use android or iPhone app

**Comment by saghul** [comment]
Please see: https://github.com/jitsi/jitsi-meet/pull/3518#issuecomment-611396665

**Comment by GasparVardanyan** [comment]
@silentshotghost I've tried it )), but can't see shared desktops in that way ((

**Comment by GasparVardanyan** [comment]
@saghul Can't see shared screens in that way ((

**Comment by anklimov** [comment]
Hi everybody
I've embedded Jitsi into mobile enabled web UI of my site and this is working pretty well without Apps at least on Chrome & FF on Android tablets & mobile 

(Unfortunately, using native Apps is not suitable for my particular use-case) 

Options to avoid deepLink and mobile App promo is below:

          var options = {
                roomName: "SomeName",
                parentNode: somenode,
                configOverwrite: {
                   disableDeepLinking: true
                },
                interfaceConfigOverwrite: {
                    MOBILE_APP_PROMO: false
              {
This couple of options allow mobile browsers operate as normal desktop.

But  this is not working properly with MIC on Apple devices (iPhone 6, iPad A1490 with recent iOS)

Please pay attention - CAM is working pretty well, and **Safari Browser is definitely can listen the sound around MIC** (popup for noisy environment are working), so the problem is not about permissions. But sound from MIC is not transferred to remote end.

Trying to use FireFox browser causes error popup on MIC activation:
_"unknown reason undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')"_

Trying to use Chrome causes permanent reconnecting/disconnecting cycles

Looks like the problem is somewhere in js code and, practically, really possible to make code, compatible with mobile browser

@saghul - may you, please, re-open issue?

**Comment by j2l** [comment]
I also noticed that `https://meet.jit.si/pouriphone#config.disableDeepLinking=true` on Chrome is still resulting in:
`unknown reason undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')`
![iphonejitsi](https://user-images.githubusercontent.com/65325/80006866-c1055f80-84c5-11ea-8ff1-1458b0cbd3cb.jpeg)
and
![iphonejitsi2](https://user-images.githubusercontent.com/65325/80006953-e1351e80-84c5-11ea-8299-d431233ca12f.jpeg)

**Comment by Vacika** [comment]
Having this issue when using Chrome on iPhone devices.
