### ISSUE TITLE
Jitsi screensharing

### ISSUE THREAD

**Issue by rosapedro** [jitsi/jitsi-meet#5884]
Hello!

I've been trying to use Jitsi Meet in Windows 7, with Chrome. Everything seems to work fine, except for the option "share entire screen". The "share" button is simply unavailable. Apparently, my browser is updated, and I couldn't figure anything out from the settings or security.

Any help would be apreciated.

**Comment by badesemowo** [comment]
Hi , I had this same issue on a Mac and discovered the issue was not really with Jitsi.  It was with my system settings at the OS level.  I needed to allow Chrome (my browser) to be able to do Screen Recording.   I believe Windows will have a similar setting for your browser.  

Please just remember that the screen sharing is not only used by Jitsi so you can also test with other solutions that use the same browser function  to share screen.  Also please note that not all browsers support the standard but you mentioned Chrome so that is probably not your issue. 

This link pointed me in the right direction to solve it on Mac . It may be useful for you too: https://crankwheel.zendesk.com/hc/en-us/articles/360009929339-macOS-Catalina-Can-t-share-full-screen-or-application-window

**Comment by Echolon** [comment]
related

Screen Sharing Broken in Chrome #4955

**Comment by rosapedro** [comment]
Thank you guys. I guess that did the trick.

**Comment by badesemowo** [comment]
Happy to have been able to help.  

For the next person that will stumble on this thread from Google, can you please update your comment with the EXACT steps you took to resolve your issue.
