### ISSUE TITLE
Optimizations for the Background Blur feature

### ISSUE THREAD

**Issue by prusnak** [jitsi/jitsi-meet#5912]
It seems there are two ways how to optimize the Background Blur feature.

1) There is a [WASM backend for TensorFlow](https://www.npmjs.com/package/@tensorflow/tfjs-backend-wasm) (used by the BodyPix model). According to [this chart](https://github.com/tensorflow/tfjs/tree/master/tfjs-backend-wasm#mobilenet-v2) it should provide a significant improvement over plain Javascript.

2) Using MobileNetV2 instead of MobileNetV1 should bring further improvements. See [this article](https://ai.googleblog.com/2018/04/mobilenetv2-next-generation-of-on.html) for more information. But it seems the upstream BodyPix model does not support MobileNetV2, yet.

**Comment by saghul** [comment]
@jallamsetty1 did you test with any of those?

@prusnak have you verified that those do indeed improve performance in our use case?

**Comment by prusnak** [comment]
No, I haven't. I'm just throwing ideas around here.

**Comment by jallamsetty1** [comment]
Thanks for the recommendations @prusnak, we tried #1 a couple of months back and we observed that the chrome tab was becoming unresponsive when we tried to use the WASM backend.
Here is what the bodyPix team had to say about that -
`WASM will likely not help here, since the WASM backend is 3-4X slower than the WebGL backend for "medium-sized" models like BodyPix, PoseNet and MobileNet. The WASM backend can be faster than the WebGL backend for ultra-lite models (1-3MB, 20-60M multiply-adds) like Face Detector.`
Will you be able try it to see if we are missing something ?

**Comment by prusnak** [comment]
I think we can close this then.
