### ISSUE TITLE
Cannot use camera via app

### ISSUE THREAD

**Issue by y2mk1ng** [jitsi/jitsi-meet#5980]
As described in the topic. Other functions of the Jitsi app go well, though.
OS: Android
![cswei_jitsi_issue](https://user-images.githubusercontent.com/53247382/79195616-253e7880-7e61-11ea-9f5a-460c5231c80a.png)

**Comment by auliarahmed** [comment]
did you have to allow camera permission?

**Comment by saghul** [comment]
What device and Android version are you using?

**Comment by y2mk1ng** [comment]
> 
> 
> did you have to allow camera permission?

Camera was allowed. It was still like this.

**Comment by y2mk1ng** [comment]
> 
> 
> What device and Android version are you using?

Sony Xperia smart phone. (Android 8.0.0)

**Comment by breversa** [comment]
Same here with :
- Jitsi Meet 20.2.1 (from F-Droid)
- Android 9.0 (LineageOS 16.0)
- LG G4 (h815)

**Comment by breversa** [comment]
I do NOT have this problem on :
- Android 9 (/e/ 0.8p) on Fairphone 2 (FP2)
- Android 7.1.1 (LineageOS 14.1) on Samsung Galaxy Tab 8" (SM-T310)

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Please refer to this issue first:  #5425 
If your issue is still existing I can reopen it then.
---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
