### ISSUE TITLE
Falla en el servidor de jitsi

### ISSUE THREAD

**Issue by Laem2020** [jitsi/jitsi-meet#6069]
hola, han habido hoy fallas en el servidor? usamos jitsi para clases de una academia de musica y tuvimos varias fallas.

**Comment by luixxiul** [comment]
See here https://github.com/jitsi/jitsi-meet/issues/5403 and close this issue if you find a duplicate there. If you cannot find, please provide additional information. Steps to reproduce the issue is very appreciated.

Consulte aquí https://github.com/jitsi/jitsi-meet/issues/5403 y cierre este problema si encuentra un duplicado allí. Si no puede encontrar, proporcione información adicional. Los pasos para reproducir el problema son muy apreciados.
