### ISSUE TITLE
Please remove "Trying to speak? You are muted" pop up

### ISSUE THREAD

**Issue by cbruchert** [jitsi/jitsi-meet#6100]
This pop up message is too frequent and annoying, please remove it or make it configurable.

**Comment by damencho** [comment]
It is already configurable https://github.com/jitsi/jitsi-meet/blob/master/config.js#L520

**Comment by damencho** [comment]
Please use the community forum when having questions and problems before opening new issues.

**Comment by cbruchert** [comment]
Waht do you mean I don't  have access to the server's configurations file. I need to disable is as a user.

**Comment by damencho** [comment]
So you want to report it probably for meet.jit.si deployment, this is not the place, that's why issue templates kindly ask to post your questions in the community forum. 
As you can see this setting is already available, but it is turned on for one of the deployment. 
This is the opensource project and we try to keep tracker for issues. And this project is deployed by multiple people it is not just meet.jit.si.

**Comment by aspiers** [comment]
I think this conclusion misses the point.  Within a single deployment (meet.jit.si as well as others) there will typically be some users who want to keep this pop up and others who want to get rid of it.  There are perfectly legitimate reasons for both use cases.  (If this is not obvious then let me know and I will explain why.)

So what is needed is some kind of client-side UI enhancement which allows the user to decide.  It could be as simple as a `Don't show this again` checkbox, or something slightly more sophisticated, e.g. a new setting.  But relying on the server-side setting for deployment-wide configuration is clearly inadequate.

Therefore I would humbly suggest reopening the issue and renaming it to `Add per-user setting for disabling "Trying to speak? You are muted" pop up` or similar.
