### ISSUE TITLE
Usernames with @ character not working

### ISSUE THREAD

**Issue by chris246** [jitsi/jitsi-meet#6150]
See also #2964

## Description
When entering a username containing an @ character (e.g. user@domain.tld), the web frontend is stuck at 'Connecting'.

No special error appears in the developer console.
Also, no HTTP with an auth request to /http-bind?room=foo is sent. Such a request is sent, if the username does not contain an @ (e.g. user).

(When appending the '@domain.tld' in prosody and using only the username, the login works. This is unfortunately not sufficient in my case, as different domains for the username have to be supported).

### Environment details
Debian 10 Using the provided apt packets. Default installation.
Auth backend for prosody is auth_dovecot

**Comment by Rouji** [comment]
Similar situation here. I think it should work if you configure your domains in prosody, as hinted at in the other issue. 
I would be very interested in a solution that takes usernames containing *arbitrary* domains as well though.

**Comment by chris246** [comment]
@Echolon Does it make sense to also label it as a bug?

**Comment by Echolon** [comment]
Hi,

we prefer to make it clear with more specified labels. Anyway thanks for suggesting!

Cheers

27 may. 2020 5:42:07 PM Christoph Schwarzenberg <notifications@github.com>:

**Comment by sherpya** [comment]
@ is not supported as per specs https://tools.ietf.org/html/rfc6122#page-20
the problem is jitsi does not even calls the auth plugin and hangs without saying nothing, i.e. username is invalid

**Comment by chris246** [comment]
That is of course unfortunate.

It would be beneficial to change the login UI (also in the Apps):
![grafik](https://user-images.githubusercontent.com/14861996/85755697-7515a780-b70e-11ea-9337-95335a621f00.png)
The placeholder suggests, that '@' is a valid character.

**Comment by Rouji** [comment]
> The placeholder suggests, that '@' is a valid character.

It *is* a valid character. Whatever you put after the @ just gets treated as the user's domain. 
The problem is if you put in a domain that Prosody doesn't know about, things get stuck.  

If my jitsi is running on jitsi.example.com and I put in user@jitsi.example.com, things work just fine. And if I'm reading the code right, the webapp actually appends that domain automatically anyway, if you don't put in an @ in that field.

FWIW, I've bodge-fixed this by patching the webapp to omit @ and anything after it in the username input...
`const jid = f.username.split("@")[0];`  
...and then having our home-grown auth plugin for Prosody deal with not having the domain to work with.
