### ISSUE TITLE
Allow Streaming to WebRTC general endpoint

### ISSUE THREAD

**Issue by ranjithrajv** [jitsi/jitsi-meet#6156]
**Is your feature request related to a problem you are facing?**
LiveStreaming is only available for Google-owned privacy-violating platform Youtube.

**Describe the solution you'd like*
Allow livestream to WebRTC general endpoint, so it can be easily embedded into HTML pages/WebApps/PWA.

**Describe alternatives you've considered**
I've tried looking for availability of other protocols like RTMP, seems this feature is not yet added too.

Meta issue: https://github.com/jitsi/jitsi-meet/issues/5146
Similar issue: https://github.com/jitsi/jitsi-meet/issues/2829

**Comment by rosa2** [comment]
If you want to get privacy community as your users, you have to give support to have all the tools that you offer to privative platforms to the open ones, if not, the community will go to other alternatives as BigBlueButton. Please, Jitsi people, be smart :)

**Comment by ranjithrajv** [comment]
Please reopen this issue. This is not yet fixed.

**Comment by yuvrajmakkena** [comment]
@saghul please re-open this issue, if this feature is yet to be added.

**Comment by saghul** [comment]
This is not something we plan to support.

**Comment by hex-m** [comment]
Thank you for the clarification @saghul! I think it would still be useful to keep this issue open to show that there is interest from the community - even if it's not on the roadmap.

The main argument for this feature would be <1 sec latency which is important in some use-cases.

There is a [project](https://gitlab.com/bbb-streaming/bbb-rtp-streamer) that implemented WebRTC-Streaming to a Janus Server for BigBlueButton Meetings.

**Comment by rosa2** [comment]
Yes @saghul please, leave it open.
I have talk with people that I teach the Jitsy existence and many times was asked why only Youtube.

**Comment by hex-m** [comment]
@rosa2 this may be a misunderstanding. Most streaming servers (YouTube, Twitch, PeerTube, Owncast, Open Streaming Platform, Facebook Live,...) use RTMP which was implemented as mentioned in https://github.com/jitsi/jitsi-meet/issues/2829. It's not well documented yet but you can put any `rtmp://` URL into the field that says "Enter your YouTube live stream key here".

This issue is about sending the stream to a streaming server using a different protocol than RTMP. This is most interesting for organizations that set up their own streaming server.

**Comment by saghul** [comment]
I don't see how reopening would help with anything. In fact I think it may be detrimental because it may seem like it's going to eventually happen, but as I mentioned, we have no plans for it.

The project @hex-m could easily be adapted to join Jitsi Meet calls. In fact it uses a very similar approach to Jibri: join the meeting with Chrome, driven by Selenium and stream the output somewhere. There is no need for Jitsi Meet to so anything specific for such project to exist.

If anyone wants to work on it, feel free to do so. We have created a GH org for such community driven projects: https://github.com/jitsi-contrib we'd be happy to host it there.
