### ISSUE TITLE
Create a CHANGELOG.md file

### ISSUE THREAD

**Issue by richb-hanover** [jitsi/jitsi-meet#6168]
**Is your feature request related to a problem you are facing?**

I have always wished that jitsi had a CHANGELOG.md file. It's a good way for non-developers to track important changes to the software (perhaps new Stable versions), and to disseminate important news. The following revived my interest. 

> In #4758 @damencho  wrote:
> 
> ... Stable jitsi-meet now is 2.0.4468...

Is there currently a way that people can discover this? 

**Describe the solution you'd like**

A CHANGELOG.md file could accomplish this. That file might only be updated when the main *meet.jit.si* server gets updated...

To keep it simple (and to minimize the effort), the entries could say: 
> 2020-04-?? 
> *output of `dpkg -l | grep jitsi` followed by...*
> * sentence about interesting change 1
> * sentence about interesting change 2
> * ... maybe with links to issues/forum discussions/etc...

As a practical matter, the CHANGELOG.md file could simply start with today's release and add new releases at the top. (I'm less interested in history.)

**Describe alternatives you've considered**

Create a README that tells people how to dig through sources, browser console messages, etc. to determine the current versions.

**Comment by damencho** [comment]
Have you looked at the changelog that is already generated?

**Comment by damencho** [comment]
```
https://github.com/jitsi/jitsi-meet/releases/tag/stable/jitsi-meet_4468
https://github.com/jitsi/jitsi-videobridge/releases/tag/stable/jitsi-meet_4468
https://github.com/jitsi/jicofo/releases/tag/stable/jitsi-meet_4468
```
They are also available though these links:
```
https://github.com/jitsi/jitsi-meet/releases/latest
https://github.com/jitsi/jicofo/releases/latest
https://github.com/jitsi/jitsi-videobridge/releases/latest
```

**Comment by tpo** [comment]
Also, links to stable releases had been maintained here: https://github.com/jitsi/jitsi-meet-release-notes . From there you can get to the change logs easily.

I'm not sure what the plan with those is, if they are published anywhere else then just under this repo, or why they are not updated any more.

Anyway I have updated them and kept them up to date for the last few days in my own fork of that repo: https://github.com/tpo/jitsi-meet-release-notes/ since I'm also interested in a change log.

Of course I'd be more than happy if upstream merged my updated release list in...

**Comment by chaoflow** [comment]
@damencho Since recently, I'm subscribed to the release notifications for jitsi, which I receive by email. Looking at the latest release, in order to assess whether I want to update, I had to:
1. Follow the link to the [release page](https://github.com/jitsi/jitsi-meet/releases/tag/stable/jitsi-meet_4546) contained in the e-mail
2. Follow the link to the changelog file
3. Acknowledge download and open in editor
4. Parse approx 200 lines / 100 items for whether they contain something I need

I think this could be improved by:
1. Using the generated changelog as base for a **structured changelog** taking ideas from [keepachangelog](https://keepachangelog.com/). Beyond the sections proposed there, I think it would make sense to have a dedicated **section for translations** or leave them in the other sections, with common prefix and grouped together
2. letting **release notes contain changelog verbatim** so it can be inspected right away in the release notification email
3. Gather these in a **top-level changelog file** for easy inspection of release history

Thank you everybody involved for this great tool!

**Comment by luixxiul** [comment]
See: https://github.com/jitsi/jitsi-meet/pull/6741 and https://github.com/jitsi/jitsi-meet-release-notes/issues/7#issuecomment-627882712

**Comment by tpo** [comment]
thanks for reopening @Echolon

**Comment by saghul** [comment]
We have made improvements to our change log generator and now release notes are automatically pushed to the release notes repo.

**Comment by richb-hanover** [comment]
As the OP for this issue, I want to say that these improvements to the Changelogs are excellent. I especially appreciate that the Changelog files give a date and version in each heading. (This helps solve the question, "Do I have the current version?" I can either look at my running version, or compare the date to when I most recently updated.)

One more tweak for to get full marks: Put the three bullet points on https://github.com/jitsi/jitsi-meet-release-notes/blob/master/README.md onto the main Jitsi page in the Release Notes section at https://github.com/jitsi/jitsi-meet

This would make these files even more obvious, and save a couple clicks. It could also emphasize that these files contain the latest version numbers and revision dates, something like this:

> *for the main Jitsi page*
> ## Release notes
>
> Release notes for Jitsi Meet are maintained in a [separate repository.]() View these files to see the current version number and the changelog for each released version. 
> 
> * Web: .....
> * Mobile apps: ...
> * Mobile SDKs: ...

THANKS!

**Comment by nsg** [comment]
The new CHANGELOG are much better, nice! Much easier find what's new. I like to keep track on what's happening in the projects I use (and deploy/support for other people) and a CHANGELOG (or a blog) is usually a good spot for that. It's still a little hard for me to understand phrases like `feat(pwa) add pwa specifics` ... no idea what pwa is. After some googleing I assume it may refer to "Progressive Web Apps" ... still, that tell me nothing that these "new specific progressive web app changes are".

I understand that these are programmatically generated, and you can only do what's possible from the source material (commits). [Other CHANGELOGS](https://github.com/matrix-org/synapse/blob/develop/CHANGES.md) or [blogs](https://www.home-assistant.io/blog/2020/11/18/release-118/) that I read are manually crafted (by a human) and I fully understand that this may be something you like to avoid. Writing software is fun, release notes are not. As a sysadmin release notes (or similar) may be the difference between me feeling the confidence to deploy and support a piece of code. If I have users I like to understand what will happen before I upgrade, and I also like to be able to understand that without to much of an effort.

Can we help? Maybe a crowdsourced release note/changelog/blogpost? Where is the script that generates the release notes? I have a few ideas how to improve and I would love to throw a PR for you to inspect (and of course possible reject).
