### ISSUE TITLE
requireDisplayNames doesn't actually require display names

### ISSUE THREAD

**Issue by ktechmidas** [jitsi/jitsi-meet#6488]
requireDisplayName doesn't actually require display names when enabled in the config js

When enabled user can just click Cancel on the display box and not get kicked...

**Comment by saghul** [comment]
It's a soft requirement, they can choose to not set anything and then the default will be used. Even if we make it a strong requiremeent the user could type "asdf" so there is not much benefit IMHO.

**Comment by ktechmidas** [comment]
In that case I’d rename the config option, but I suppose we can just remove the cancel button if I can find it in the css (or is it generated by JS?) 

Maybe have a look at having both options?.... The idea is if a user enters asdf they can be kicked by the moderator, if it looks like a soft requirement to the user they’re more likely to just cancel (I know I would)

I know you guys are probably getting a lot of feature requests that you’d find odd but I suppose the reason for that (and my question) is schools and companies are using it more - but thanks for the fantastic support 👍

**Comment by saghul** [comment]
I'm closing this since there is nothing really actionable. It's user input, so the moderator should decide what to do. If you want stronger guarantees, you can use JWT in your setup and have individual tokens per participant, that way the name won't be changeable, and they can be made so only a specific room is joined, for example.
