### ISSUE TITLE
Jitsi Meet app for iOS 9.3.5

### ISSUE THREAD

**Issue by eloydegen** [jitsi/jitsi-meet#6512]
I tried installing Jitsi Meet from the App Store on an iPad 2. I couldn't install it due to compatibility issues with this iOS version, which is 9.3.5. This is the highest possible version that can be installed on this device.

It would be great if the app could be compiled in a way that it could be used on older iOS devices. I'm nowhere near an iOS expert so I don't have any suggestions for a fix, sadly.

**Comment by raphj** [comment]
Sadly, this is probably not going to happen : https://github.com/jitsi/jitsi-meet/commit/e5c9c69ec9e7b6d4cde8eaf60602fbe012d41ba9

>  ios: drop iOS 9 support
> 
> WebRTC no longer actively fixes iOS 9 issues.

(I was looking for a way to use Jitsi Meet with somebody who has an iPad 2)

**Comment by eloydegen** [comment]
Would it be an acceptable patch to add this back, or is this not feasible because stuff breaks due to the missing WebRTC maintenance? Was it removed because of practical reasons or a security risk?

**Comment by raphj** [comment]
I can't speak for the maintainers, but I would not hold my breath.

As you can see in the patch, they removed annotations about the restriction of compatibility to higher versions of iOS. This means that they are probably not tracking what would not be compatible with iOS 9 and random things would break.

What's more, this kind of things need to be actively and constantly tested to be sure it is compatible with the current browsers and technologies currently used, and does not break people's conferences. So someone in the Jitsi Meet team would need to regularly check that things work with an iPad 2.

At the beginning of WebRTC, it was difficult to make Firefox and Chrome interoperate with WebRTC. Both ends would need to use the same browser.

Even today, Jitsi Meet has been having difficulties with _current_ versions of Firefox, partly because it lacks some feature they use now. I'd guess Jitsi Meet uses some kind of WebKit View component on iOS, that probably uses the Webkit version also used in Safari (9), because no app is allowed to embed their own (updated) browser engine. An old version of WebKit, released almost 5 years ago. So old that I need to install Debian Jessie (old old stable) to test my stuff against a similar version of WebKit and many things don't work on it.

And as you noticed, the library Jitsi Meet uses for WebRTC dropped support for iOS 9, so two years forward they are probably out of luck anyway.

**Comment by eloydegen** [comment]
> Even Skype dropped support for iOS 9.

That's exactly why I was looking for a replacement. Ended up with Zoom, sadly.

> This is a bit sad when it's a perfectly working device hardware-wise.

Fully agreed.

I think the issue can be closed, because it's very probably not going to be fixed.

**Comment by saghul** [comment]
We don’t use a WebView, we use webrtc.org’s framework.

It’s no longer maintained for iOS 9 or 10 so we dropped both.

Same goes for Android 4.

We si ply cannot commit to maintaining platforms that are not maintained upstream, sorry.
