### ISSUE TITLE
French administration advises a maximum of 6-12 users with Jitsi-meet

### ISSUE THREAD

**Issue by jerome-bouat** [jitsi/jitsi-meet#6524]
## Description
---
See the table of evaluated solutions :
https://cyberguerre.numerama.com/4405-pourquoi-ladministration-francaise-a-t-elle-autant-de-mal-a-remplacer-zoom.html

## Current behavior
---
Many issues blocks the virtual use of Jitsi-Meet with more than 6 users.

## Expected Behavior
---
Before the flows reach the JVB, the Jitsi-Meet system could throttle the quality of the emitted video depending of the probability to get a speaker status in the coming minutes.

## Possible Solution
---
Each instance of the web application could use a queue of the latest speakers and the micro muted information of each user in order to lower the quality of its emitted video : if the user has a older speaker rank and/or a muted micro then his/her web application instance would be nice and thus lower the quality of the emitted video. The coordination software would send to each web application instance the queue rank which triggers lower quality and if the mute status should be taken into account. This is a complementary quality management besides the JVB simulcast forwarding (which is more realtime). The web application instances would throttle this quality with a higher delay. However both quality throttling would help to fit the global limits of the room.

**Comment by saghul** [comment]
> Many issues blocks the virtual use of Jitsi-Meet with more than 6 users.

That is not correct. We support a lot more han 6?users.

The article mentions the tested their own instance, which might explain I guess. We have tons of > 6 person meetings every single day on meet.jit.si.

We do use a concept similar to what you described already: adaptive last N. The video bridge will only forward the video of the last N active participants, where N varies depending on the available bandwidth.

I’m closing this, because I really don’t see anything actionable.

**Comment by jerome-bouat** [comment]
> The video bridge will only forward the video
> of the last N active participants,
> where N varies depending on the available bandwidth.

Yes. But the fact is it doesn't work currently. Therefore many user prefer Zoom.

**Comment by pdarcos** [comment]
Quick question. Why does that site claim that Jitsi is French?

I've known Jitsi since it was still called Sip Communicator and I don't remember seeing many French devs back then. Back in those early days it was mainly Emil and his friends so I wonder how come the French now say it's french software. If anything one could say it's Bulgarian, but with all the different nationalities contributing to the source over the years it's actually European. How can the French claim it as french software? Did I miss something?

"Scaleway propose aussi des instances de Jitsi, la **technologie française open source** sur laquelle est construit Webconférence, mais il peine à faire mieux."

**Comment by saghul** [comment]
Because Emil was at Strasbourg university and SIP Communicator was his PhD project.

But yeah right now we have contributors from all around the world.

**Comment by jerome-bouat** [comment]
> > Many issues blocks the virtual use of Jitsi-Meet with more than 6 users.
> 
> That is not correct. We support a lot more han 6?users.
> 
> The article mentions the tested their own instance, which might explain I guess. We have tons of > 6 person meetings every single day on meet.jit.si.
> 
> We do use a concept similar to what you described already: adaptive last N. The video bridge will only forward the video of the last N active participants, where N varies depending on the available bandwidth.

Maybe that's the problem from user point of view. If users see blank screen for many persons then they think Jitsi-Meet doesn't work. If the JVB would forward video for each user which is providing one video stream, then the users would think it works. Maybe the JVB has to decimate the framerates and resolution even more for the last N user but it would still forward the video of each emitter.

**Comment by pdarcos** [comment]
> Because Emil was at Strasbourg university and SIP Communicator was his PhD project.
> 
> But yeah right now we have contributors from all around the world.

Ah ok, now I understand. I forgot Emil was at Strasbourg at the time. But claiming that Jitsi is French is a little ridiculous. It's like claiming that openssl is american, british, german, whatever
