### ISSUE TITLE
SetnumberOfParticipants functionality

### ISSUE THREAD

**Issue by nobels** [jitsi/jitsi-meet#6659]
Currently there is encryption with 2 users.

We created a wrapper and we would like to enforce max 2 users so the encryption is there.

There is the need for delicate conversations and encryption is needed/required.

The workaround is to set a password and only send it to the other user.

But the wrapper can have better controle of the settings for the users.

**Comment by saghul** [comment]
That is not accurate.

No matter the number of users, media is encrypted in transit, hop by hop. It is indeed decrypted by the video bridge since we need some information not otherwise available to perform smart video routing.

If you are using Chrome beta you can already use E2EE for all participants: https://jitsi.org/blog/e2ee/

Setting a meeting password has nothing to do with encryption.

In addition, limiting meetings to 2 participants doesn’t necessarily mean that the connection will be P2P. Often times you’ll need TURN and if your deployment doesn’t have it, or if TURN allocation fails for whatever reason, you’ll still connect via the video bridge.

As for setting participant limits, did we have a Prosody module for that @damencho ?

**Comment by damencho** [comment]
Yep mod_muc_max_occupants

**Comment by backnext321** [comment]
> If you are using Chrome beta you can already use E2EE for all participants
Does this mean E2EE for all participants will be available in Jitsi Meet with the next official Chrome update?
[Here ](https://www.computerworld.com/article/3378017/fast-forward-whats-coming-in-future-versions-of-chrome.html) I read : "As of Chrome 83 - which originally had a June 9 launch date"
