### ISSUE TITLE
Mobile SDK Heating & battery drain Issue, Phone Switch off with warning of over heating

### ISSUE THREAD

**Issue by maulikshah88** [jitsi/jitsi-meet#6683]
Recently, configured the jitsi on my private server and tested the mobile sdk in multiple android and iPhone devices. I tested with 20 participants for about 20-25 minutes and overall performance was good. In all device within half an hour battery drained  by  20-25% and in few android device got a warning message of phone over heating. 

Is there any solution to this issue? because with this its not possible to use the jitsi mobile version.

**Comment by saghul** [comment]
The only thing I can think of it to set lastN to a lower value so you don’t get that many videos, which is a shame, because your device is capable of handling them.

Video conferencing is CPU intensive, there is no way around it. Using hardware accelerated codecs may help, but at the expense of stability (we’ve seen so many crashes) and loss of simulcast, which has serious implications as well.

**Comment by maulikshah88** [comment]
@saghul thanks for your input, lastN  is not a proper solution to this issue. 
I was planning to use this for education but if we use lastN we cannot monitor the students behavior and interest in lecture. 
The problem persists with 2-3 participants also. I used all latest device including iPhone 11 and Few android latest models with higher CPU and ram configuration. I wondered I tested and using other conferencing solutions for my meetings in which there is no such issue is faced with any of this device.

**Comment by saghul** [comment]
Anything is on the table, this is all I got at the moment.

**Comment by pdarcos** [comment]
@maulikshah88 as @saghul explained the reason this happens is due to the fact that many devices don't support HW accelerated encoding/decoding of VP8 codec which jitsi uses (all newer iOS devices have the builtin capability on the intel chip but Apple chooses to not expose it since they only want h264 and h265 (HEVC). It's a commercial/patent/legal issue, not a technical one preventing Apple from offering VP8/9 hw encoding on iDevices. 

Android devices (specially the newer ones) should support VP8 hw encoding and many even support VP9 (hopefully will land on jitsi-meet repo one of these days), so if using only recent android devices with VP8 the battery shouldn't drain as much. Although you'll always get heat since the CPU (or GPU if hw accelerated) has to work hard to encode and decode the streams.

**Comment by saghul** [comment]
We intenttionally use the SW codec. HW codecs crash, hard. We first disabled it for Samsung, the biggest offender. Then Huawey was the topmost crashing manufacturer, at which point I wondered: "why even try, if these huge companies sselling billions of devices can't gett it right?".

There is also a very important factor: simulcast. You cannot do it with the HW codecs, only with the SW ones.

As for VP9, I'm not holding my breath. It's ssupposed to be more efficient on the network, at the expense of even more CPU usage, and that is not a nice tradeoff here.

**Comment by maulikshah88** [comment]
Thanks for providing clear details and reason behind the heating issue. So as of now there is no solution to heating issue. I think this is only thing most vulnerable issue with in jitsi mobile app otherwise its working fine you guys have done great work in it, but my results are very bad and 3 devices out 10 had got overheating warning message and call was disconnected and rest of the device including iPhone's was extremely heated in just 20-25 minutes and its not going to work especially when summers are very hot here :) and its difficult to ask users to use app until we don't get some proper solution to this. 
Thank you @saghul & @pdarcos for quick response and support.

**Comment by tdrp** [comment]
@maulikshah88 @pdarcos sorry to bring this back up but I am also seeing this issue consistently on iPhones, even modern ones (iPhone X+). It only takes 3 participants and 5 minutes for the iPhone to become too hot to hold. A quick at the app store reviews on Apple/Google for the Jitsi app seem to indicate this is a pervasive problem.

On that same iPhone, I regularly have hour-long Zoom conferences, Facebook, Skype and Whatsapp group video chats and that has never been a problem.

Doing a 1:1 call using AppRTC directly for a similar duration, does result in some heating but not too bad.

I am not familiar with the underlying technology to provide any useful feedback but some small thoughts:
1- Are the streams resized/encoded prior to sending based on the destination tile size? For example, if I am only being shown to other users in a small tile, is my full-size stream sent or just a small tile?

2- Is the CPU work distributed across processors in some way or are they just threads? I understand iPhone X+ has 6 processors but they have different purposes.

**Comment by saghul** [comment]
There are a couple more things we hopefully will try soon:

- lower the resolution from 720p (this also seems to be what other applications do)

- request a lower simulcast later fo received video (receive 360 or 480 instead of 720)

- add bandwidth limits for the P2P connection


I also have my own piece of anecdata: I’ve been using n iPhone 7 Plus for the last 3 years and regularly having 15+ people meetings no problem. Yes it does get warm, but so does playing a game...

**Comment by mhmdreza** [comment]
@saghul
Sorry to comment on closed issue, but some of our users encountered with the same issue. I have found a solution for android and I want to know your opinion on this idea.
Based on the android guide in [this link,](https://source.android.com/devices/architecture/hidl/thermal-mitigation#thermal-api) We can understand thermal state and act properly. My idea is to enter audio only mode when user reached CRITICAL thermal status code to prevent more heating and cause android to show overheating dialog or even shut down the phone which is very bad user experince.

**Comment by saghul** [comment]
That's not a bad idea! Would you like to explore this possibility in a pull request?

**Comment by mhmdreza** [comment]
@saghul
Yes.
I will do that if I don't find a better solution. 

But I currently want to search more in codebase. I just understand that in both [TileView](https://github.com/jitsi/jitsi-meet/blob/b944088d99247814222fa5fc7557f59faa482686/react/features/filmstrip/components/native/TileView.js#L102) and [FilmStrip](https://github.com/jitsi/jitsi-meet/blob/b944088d99247814222fa5fc7557f59faa482686/react/features/filmstrip/components/native/Filmstrip.js#L111), code renders all thumbnails.

This obviously leads to more power usage. why you don't use FlatList to prevent or even reduce frequency of this issue?

Also, I am gonna compare power usage of sending video and receiving video by profiling android app to make better decision in entering audio only  mode.

**Comment by saghul** [comment]
Our list barely changes, the dominating CPU usage factor is video encoding / decoding, I bet using a FlatList won't change anything in practice. But feel free to experiment!

**Comment by mhmdreza** [comment]
Sorry for asking a lot.

I think you misunderstood me. I was speaking about rendering video of a user and playing its video when it is not visible to user. For example with lastN about 15, React native render and play 15 videos that only 6 of them are visibile to user at a time. Those other 9 videos are rendered and getting updated multiple time in a second and cause more CPU usage (but I don't know how much more).

do You mean rendering 9 more videos do not increase CPU usage significantly?

**Comment by saghul** [comment]
Ah I see what you mean now.

We are cut implementing that for web, so doing the same on mobile is worth it too.

**Comment by sgbeal** [comment]
This is apparently still an issue. We recently migrated from public jitsi to a private server and, since doing so, the jitsi android app causes my phone (Samsung A03) to overheat after 20-odd minutes in a call with 4 call participants (myself included) over a 4G mobile network. The OS popped up a warning that the device was overheating, then killed off jitsi a moment later, then refused to allow me to start any apps for several minutes while it cooled down. We've been using jitsi public since the better part of 2 years without this issue. For whatever reason, using a private server appears to be the trigger.

Any hints as to what we can do on either the client or server to eliminate this would be greatly appreciated.

**Comment by saghul** [comment]
You can change the default codec to VP8 and that should help. The next release will do this automatically, but there was a regression that prevented us from applying the change.

**Comment by sgbeal** [comment]
My apologies for neglecting to follow up sooner, but wanted to report (for future readers who come across this) that switching the default codec to VP8 (see previous comment) indeed resolved the problem. We've had a number of hour+ conferences since then without any overheating.
