### ISSUE TITLE
One user with bad bandwidth crashes user experience for everyone

### ISSUE THREAD

**Issue by apoger** [jitsi/jitsi-meet#6689]
## Description
One user with a low bandwidth is enough to slow down and de-sync video and audio for everyone in a session.

## Current behavior
User experience drops to zero for all clients. Audio and video freezes, stutters. Everyone asks himself if it could be an issue on ones own connection.

## Expected Behavior
Only the user with the Bad connection should experience this. Also quality should be reduced drastically to maintain a somewhat working connection. Everyone sees who is the client with the bad connection.

## Possible Solution
Reduce quality only for the bad client. Protect the not affected users from the bad client.

## Steps to reproduce
Let someone join with  a slow wifi connection into a perfectly working 3 client webconference.

# Environment details
Mobile (Bad connection was on iOS. But it shouldn't matter)

**Comment by luixxiul** [comment]
> Bad connection was on iOS. But it shouldn't matter

Does this mean that the same issue happens even if that user joins the meeting with Android / desktop / laptop, anything but iOS as well? I am asking this as the issue might be related with the very device.

**Comment by richb-hanover** [comment]
I can offer a supporting anecdote. A week ago, I asked a bunch of 5-6 friends from a Linux user group to try out the `meet.jit.si` server. I was using Chrome (current) on macOS 10.15.4. Other participants were likely using browsers, (not the app) but I don't know which.

On that day, it turns out that my DSL service dropped from its normal (modest) speed to extremely slow - ~900kbps download.

*The conference was unusable.* People's images came in and out, audio was unreliable. As the organizer of this meeting, I was unwilling to drop out. But now I wonder if my slow connection was the cause.

**Comment by briatte** [comment]
I can report multiple instances of that happening in dozens of meetings.

**Comment by luixxiul** [comment]
@richb-hanover

> On that day, it turns out that my DSL service dropped from its normal (modest) speed to extremely slow - ~900kbps download.
> 
> _The conference was unusable._ People's images came in and out, audio was unreliable.

I believe it is different from the issue that opener has experienced, because there "One user with a low bandwidth is enough to slow down and de-sync video and audio for everyone in a session." Even though others' image came in and out on your side, it does not mean the rest of the participants experienced the same issue at the same time.

**Comment by richb-hanover** [comment]
I believe my report is relevant, even if I was not entirely clear. I certainly did have low bandwidth, and all the people (a half-dozen or so) had terrible performance. At various times, several people reported they could not hear or see each other (not just me). 

As I mentioned, since I was the "organizer", I did not drop out until we all agreed it was a failure. I think this is still a live issue.

**Comment by luixxiul** [comment]
@richb-hanover thanks for the follow-up!

**Comment by KevinRoebert** [comment]
Please reopen and fix

**Comment by nicolasbadia** [comment]
This is still an issue for us too.

**Comment by richb-hanover** [comment]
@devZer0 - The https://github.com/jitsi/jitsi-videobridge/issues/777 report you mention is over a year old. There has been significant work on the server since, so new data won't be regarded as duplicate.

If you had a bad experience recently, it's important to open a new issue so that developers can look at problems with fresh data. It doesn't have to be the full-bore scientific method. My [initial report](https://github.com/jitsi/jitsi-meet/issues/6689#issuecomment-628553889) was just anecdotal evidence (how many people, what browsers, other conditions).  Thanks for helping to improve jisti.
