### ISSUE TITLE
Desktop Notification for hand raising and participant presence change when screen sharing

### ISSUE THREAD

**Issue by octoquad** [jitsi/jitsi-meet#6772]
**Is your feature request related to a problem you are facing?**
If a user has one monitor and shares their screen for a presentation, the browser is normally minimized in order to give focus to the selected application for screen sharing.

This presents a small problem, as the person now sharing their screen can no longer view any hand raises or new participants joining the meeting.

**Describe the solution you'd like**
It might be beneficial to make use of the [Push API](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) to provide notifications while screen sharing is active for participants that raise their hand or if new participants join (or participants leaving). Notifications will only be active during screen sharing and could possibly be extended later on for other purposes.

The mechanisms already seem in place to detect if one or more screens are present. Hooking in a Push notification system when screen sharing starts, will make conversations a little bit more friendlier for a participant sharing their screen with a single monitor.

**Describe alternatives you've considered**
I don't have alternatives at this time.

**Comment by majewsky** [comment]
I would like to propose an alternative: Jitsi should be able to play an audio cue when someone raises their hand. This would also work well for speakers who don't look at their screen all the time (e.g. during a casual chat).

In either case (audio cue or notification), there should be some sort of rate-limiting so that users cannot spam the notification noises by repeatedly raising and lowering their hands.

**Comment by leo-lb** [comment]
Yes this would be very useful, especially in a classroom setting.
