### ISSUE TITLE
Please implent option for disable "invite more" and "not secure icon" in interface_config.js

### ISSUE THREAD

**Issue by ibrainventures** [jitsi/jitsi-meet#6801]
Thank you for all your development.

After a long customizing of the interface for our users, now - after updating the unstable
flow, there are 2 more information panels / icons on the meet html web-interface.

It would be great to give those two panels a disable option inside the interface_config.js, 
because in our use-case, both are more irrititating our users.

![grafik](https://user-images.githubusercontent.com/8803626/82463249-dff31380-9abc-11ea-802a-b907338b08f2.png)

1 = panel for "alone"
2 = icon for "insecure channelname"

Thanx very much.

**Comment by luixxiul** [comment]
ref: #6654

**Comment by ibrainventures** [comment]
may someone is struggling in the same problem, a un-guaranted but simple workaround to
step back on the release without both web-frontend features:

apt-get install jitsi-meet-web=1.0.4119-1

**Comment by LADYBEAR7819** [comment]
![](https://user-images.githubusercontent.com/8803626/82463249-dff31380-9abc-11ea-802a-b907338b08f2.png)

**Comment by luixxiul** [comment]
@LADYBEAR7819 please stop spamming.

**Comment by pandel** [comment]
This is an urgent problem: the "insecure channel" icon has to be removable in fully controlled or automated environments, where the user is unable to control room names.

See: https://github.com/jitsi/jitsi-meet/pull/6754

**Comment by RareAdventistBookProject** [comment]
I agree. This is a disaster. People like human readable room names, far beyond indecipherable strings.  They are much better to display and to share.  And rolling out this message, with a big red alert triangle, to every single user, of every jitsi Meet installation:   

**"The room name is insecure. Unwanted participants may join your conference."**

may have been well-intentioned, but is not good for anyone, particularly, the reputation of "Jitsi Meet".  

People don't read. They will think and say "this thing I'm using is insecure".  Then they will tell people, "I tried that, but it kept saying "insecure"".  We have got 70-year-old ladies in our rooms, what does this "security alert" tell them?  What are they supposed to do about these so-called "unwanted participants".  They will think a pervert is coming to get them.  And why?  Because someone chose to name the room "/DavesRoom" instead of /7cfc0894c398bdf670bf111ed56e4c55??

It is indeed a big, urgent problem to get this warning icon out of the package, or have the option to disable it in some simple way.  I can think of a number of ways to notify a moderator or administrator that using human readable room names might be a security issue, (eg, bomb-able), which is likely one of the smallest of all problems we have in the world today.   These ideas might include things like documentation, notes in an installer, or a configurable option which defaults to on, but which may easily be turned off, shown only to the moderator etc..

But using the text 

**"The room name is insecure. Unwanted participants may join your conference.**

Is right out.  It would not have entered into my mind.  It's okay to tell an operator these things, but incorrect to display to a USER.  

To say nothing of the face that the information itself is incorrect. Room names which are "words" are kind of the intention of the whole thing.  They are not technically "insecure".  They are no less secure than hashes, but are eminently more usable.   This security option seems to be more of a reaction to the Zoom news story du-jure, than a well-thought and executed security plan.

**Comment by RareAdventistBookProject** [comment]
The quick fix, when the inevitable hordes show up hoping to turn this thing off.. is to hide it with css..

`/usr/share/jitsi-meet/css/all.css `

look for 
`.large-video-labels .circular-label.insecure{background:#d77976}`

Replace with:
`.large-video-labels .circular-label.insecure{display:none!important;background:#d77976}`

or you could do something (as root) like, 

```
cd /usr/share/jitsi-meet/
cp all.css all.css.dist
sed -i 's/.large-video-labels .circular-label.insecure{background:#d77976}/.large-video-labels .circular-label.insecure{display:none!important;background:#d77976}/g' all.css
```

**Comment by luixxiul** [comment]
If you need a quick fix, hiding with CSS as you mentioned seems to me the easiest and fastest way available right now.

In my humble opinion, until https://github.com/jitsi/jitsi-meet/issues/5653 will be addressed the insecure icon makes sense at https://meet.jit.si since there actually may unwanted participants join your conference if you pick up a common room name and that PR was intended to fix the urgent issue no matter how hasty it *seems* from the outside of the development team.

Still, I feel quite sad and sorry for the developer when I see someone calls something on GitHub projects a "disaster" or "urgent problem" if they can be fixable on your side...

**Comment by RareAdventistBookProject** [comment]
I amended my comment for you, but consider these should always be matters of what is right, not who is right.  If you're going to have configuration options that make sense for the demo site, you might consider prefixing them with some Hungarian notation, and not consider the community only secondarily, and a large base of installed systems as a red-headed step-child.  An installed, and configured system should have no fear of an update, and this is only seeking for your success.  Everything is fixable on my side.  At some point that fix becomes rm -rf  Many projects have lost their way from an inability to understand this.

**Comment by luixxiul** [comment]
> consider these should always be matters of what is right, not who is right. If you're going to have configuration options that make sense for the demo site, you might consider prefixing them with some Hungarian notation, and not consider the community only secondarily, and a large base of installed systems as a red-headed step-child. 

It would be worth noting that there have been already volunteers around the project as well like me, who have experienced an issue and felt that the community was treated just secondly (as you would see clearly on https://github.com/jitsi/jitsi-meet/issues/6164#issue-602399107) and then are trying to help the project. ie. members at @jitsi/bug-marshalls etc. instead of complaining.

If you stick with the fact that what the right thing is, there is honestly nothing I could do but say "sorry for your loss" and recommend you to push a PR as that is how open source projects are expected to work. Complaining will not fix the issue, as a matter of fact.

**Comment by saghul** [comment]
Folks, please chill.

Yes, we made a mistake by not having this off by default nor configurable.

On master it’s already off by default (though we’ll likely review it and keep it enabled on meet.jit.si) and there is a config option. The option needs a bit of polish though, hopefully that gets done this week.

@RareAdventistBookProject The same way bad decisions drive people away from a project, self-entitled users drive voluntary contributors like @luixxiul away. Please consider that even if things may look a certain way, nothing here is arbitrary. Alienating project members is likely not going to get you what you need.

**Comment by itabix** [comment]
Thank you saghul. Some people may be overly aggressive or just mis-speak and sound that way, but the huge majority of users are completely thrilled with what all the developers are doing and truly appreciate all you do and how responsive you are to our requests and comments. Jitsi is great and getting greater.

**Comment by saghul** [comment]
https://github.com/jitsi/jitsi-meet/pull/7012

**Comment by MagicFab** [comment]
Nice wording! I was about to submit something similar, glad this is moving forward. Thank you!

**Comment by garfenter** [comment]
Thank you for your work, I'm just testing this new functionality, I'm testing this from the API IFrame and can't find the attribute to disable the "You are the only one in the meeting message". Can it be hidden from the interfaceConfigOverwrite or configOverwrite? Thanks for your help.

**Comment by adamthewan** [comment]
@saghul I have made a PR to create an additional `interfaceConfig` called `SHOW_INVITE_MORE_HEADER`, so we can disable it using `interfaceConfigOverwrite` 
https://github.com/jitsi/jitsi-meet/pull/7021

**Comment by gigabyteservice** [comment]
@saghul  I want to show the "Invite button" when the user is along but even after HIDE_INVITE_MORE_HEADER: false I can't able to see the Invite more button on the header
