### ISSUE TITLE
dpkg-buildpackage doesn't actually do any building

### ISSUE THREAD

**Issue by obfusk** [jitsi/jitsi-meet#6824]
I noticed that running `dpkg-buildpackage -A -us -uc` doesn't actually do any building. Unless you run `npm install && make` beforehand, it will happily generate a package missing e.g. `libs/`. AFAIK this is not the expected behaviour; if there are good reasons for it, it should maybe at least be documented?

**Comment by damencho** [comment]
In order to have the version of the package available in the index.html we execute some sed commands after making before executing dpkg-buildpackage.
```
sed -i.bak  -e "s/app.bundle.min.js?v=[[:digit:]]*/app.bundle.min.js?v=$VERSIONMIN/" index.html
sed -i.bak  -e "s/lib-jitsi-meet.min.js?v=[[:digit:]]*/lib-jitsi-meet.min.js?v=$VERSIONMIN/" index.html
sed -i.bak  -e "s/all.css/all.css?v=$VERSIONMIN/" index.html
sed -i.bak  -e "s/interface_config.js?v=[[:digit:]]*/interface_config.js?v=$VERSIONMIN/" index.html
```
This is the reason. We plan to add an .sh file when we change the versioning scheme, the same we have it for jvb, jibri and jigasi and that .sh file will have all those commands.
