### ISSUE TITLE
Jitsi doesn't seem to use h.264 for calls

### ISSUE THREAD

**Issue by jrmuizel** [jitsi/jitsi-meet#6874]
### Steps to reproduce:

Start a call with Firefox and join it with Chrome on the same macOS computer.

### Expected behavior:

Jitsi should take advantage of the hardware h264 encoder to reduce power usage.

### Actual behavior:

Profiling Firefox shows a bunch of time being spent in the vp8 encoder.

### Server information:

- Jitsi Meet version: https://meet.jit.si/

### Client information:

- Browser / app version: Firefox 78
- Operating System: macOS 10.15

**Comment by saghul** [comment]
This is intentional. As much praise as H.264 gets, it crashes, a lot. Specially the hardware encoders / decoders. I just reported a crash bug to Chrome today.

You can enable it yourself on your own deployment: https://github.com/jitsi/jitsi-meet/blob/21fe3c87a6cc2c9ec0fa68af70af08c347750d77/config.js#L371

**Comment by jrmuizel** [comment]
Are there any known crashes that happen in Firefox with the hardware encoder/decoders?

**Comment by jrmuizel** [comment]
Or a list for both browsers?

**Comment by saghul** [comment]
Not that I’m aware of.

Note that it’s not the only issue. Lack of simulcast used to be the main one, and while some (all?) browsers have added it, I don’t know how mature it is.

As I said, you can turn it on for your deployment, and gather some numbers.
