### ISSUE TITLE
Upgrade removes Nginx turnserver module

### ISSUE THREAD

**Issue by paulmenzel** [jitsi/jitsi-meet#6889]
Upgrading the packages below

    -jicofo 1.0-538-1 all
    -jitsi-meet 1.0.4322-1 all
    -jitsi-meet-prosody 1.0.3919-1 all
    -jitsi-meet-turnserver 1.0.3919-1 all
    -jitsi-meet-web 1.0.3919-1 all
    -jitsi-meet-web-config 1.0.3919-1 all
    +jicofo 1.0-592-1 all
    +jitsi-meet 2.0.4661-1 all
    +jitsi-meet-prosody 1.0.4154-1 all
    +jitsi-meet-turnserver 1.0.4154-1 all
    +jitsi-meet-web 1.0.4154-1 all
    +jitsi-meet-web-config 1.0.4154-1 all
    +jitsi-videobridge2 2.1-207-ga4bfc7f2-1 all

the symbolic link `/etc/nginx/modules-enabled/60-jitsi-meet.conf` to `/usr/share/jitsi-meet-turnserver/jitsi-meet.conf` was removed, breaking the Web interface.

Adding the symlink back, got the setup working again.

**Comment by damencho** [comment]
I just tested installing latest stable and updating to latest from unstable and could not reproduce the issue.
I see that you had been using quite old version of jitsi-meet-turnserver, before bumping jitsi-meet to 2.0. In the beginning when we introduced there were quite a lot changes in there that happen and a lot of bugs we were clearing, so I suppose this is one of them
I think latest are safe and those should not happen, that's why I tested from stable to unstable upgrade. 
Thanks for the report, if this happen again please open a new issue or re-open this one.
