### ISSUE TITLE
Pinning multiple fellow Jitsers

### ISSUE THREAD

**Issue by h-intveen** [jitsi/jitsi-meet#6906]
**Is your feature request related to a problem you are facing?**
I am participant in accessibility user group where we have digital videomeetings.
Some of these attendees are deaf.
The deaf attendees use sign language to communicate with other deaf attendees.
They also need a sign language translator to be able to 'speak' with non-deaf attendees.

**Describe the solution you'd like**
For this to work the deaf attendees and the sign language translator must be able to simultaneously view the deaf fellow Jitsers, so they must be able to pin their (tilted) video views.

**Describe alternatives you've considered**
Pinning functionality exists in for example commercial products like Microsoft Teams (multiple pins) or Cisco Webex (single pin) but not in open source videoconferencing I have seen so far.

**Comment by mdingemanse** [comment]
Strongly co-signing this one. I often work with teams that include deaf people and one or more sign language interpreters. Our deaf coparticipants need to be able to pin/spotlight/highlight the interpreter AND the current speaker.

A few scenarios that would work and that would be enormously helpful:
1. Allow up to 4 spotlighted streams, to be picked by participants for whom this feature is allowed by the host (I am not aware of scenarios where you'd need >4). This is what Zoom and MS Teams already do with their 'multiple pin' feature. It is not allowed for everyone by default because it has bandwidth implications. In Tile mode, spotlighted streams would move to top left position in the order in which they are picked. In Speaker mode, this would mean getting a tile display of the selected streams.

2. Allow up to 2 spotlighted streams (e.g., interpreters) and besides those highlight current speaker based on speakership (which may be changing). This would be more fitting for a setting in with multiple conversational parties whose contributions need to be interpreted by 1 or 2 interpreters. In Tile mode, spotlighted streams would move to top left position in the order in which they are picked. In Speaker mode, this would amount to a tile display of the pinned streams plus the currently active one.

3. Allow users to rearrange tiles in tile view so that their preferred streams (e.g., interpreters) are where they need them to be. 

Of these, #3 strikes me as low hanging fruit that would already be enormously helpful. It would be a great start that would make Jitsi more accessible to a wider range of users. But some version of #1 and #2 are necessary to avoid the visual onslaught of looking for one's interpreters AND trying to find the current speaker amidst the visual onslaught of a tile of faces or quickly changing active speakers.

It would be wonderful Jitsi, as the prime open video calling software, would also be ahead in terms of accessibility.

**Comment by kuvahaku** [comment]
+1

**Comment by amsnek** [comment]
also a huge +1 from me
this would help for so many use cases, WAI especially

**Comment by philippd8e** [comment]
I'd be really interested into this too, any researches other commentators would like to share?

**Comment by ZathrasXI** [comment]
+1 from me too. These suggestions would making meetings significantly more accessible as deaf people could pin the interpreter and the pesentation.

**Comment by Lavialee** [comment]
I am also behind this, I believe this to be a crutial step in improving the app

**Comment by markgalassi** [comment]
I would recommend pinning this issue as open: any disability feature should not be closed for inactivity.

**Comment by amsnek** [comment]
i would upvote this as well (keep open)

**Comment by creaperfectweb** [comment]
+1

**Comment by badirdev** [comment]
I would also like to upvote this issue. Currently working on a project where I need to pin multiple users on tile view at all times. Have researched solutions to no avail. Currently, as new users join the meeting the tile view is rearranging by itself. Would be super helpful to have either the users choose which participant is pinned, or having this coded into the iframe API.

**Comment by mauricioluz** [comment]
+1. This feature is very important.

**Comment by mauricioluz** [comment]
+1

**Comment by augustoicaro** [comment]
It would be awsome have this feature on jitsi

**Comment by jbrundige** [comment]
What is the state of this issue?

**Comment by saghul** [comment]
It's being worked on.

**Comment by saghul** [comment]
This has landed already and it's available in beta!

**Comment by bitalmaz** [comment]
> This has landed already and it's available in beta!

Pin remote work fine, but unpin remote not work!

**Comment by saghul** [comment]
We are still ironing some kinks out, thanks for the feedback!

**Comment by jbrundige** [comment]
I just tried this on https://beta.meet.jit.si/. It seems to only work for 1 participant at a time. Is it supposed to work for multiple participants?

**Comment by damencho** [comment]
Go to settings under more and change the setting:

![image](https://user-images.githubusercontent.com/3263098/168688985-f94637b0-7a7d-4229-831c-a9d2f57014bd.png)

1 is the default value.

**Comment by jbrundige** [comment]
Great! Thank you
