### ISSUE TITLE
Jitsi should become the most privacy-oriented meeting system

### ISSUE THREAD

**Issue by amonpuschel** [jitsi/jitsi-meet#6950]
Please make jitsi the online meeting tool that protects privacy best. This would be a unique selling point and would allow the use of jitsi in schools and education.

An important point is the trust that jitsi must earn. OpenSource helps a lot in this respect. 

However, it is only half the battle if the self-hosted server does it, but not a client. Therefore all clients must be OpenSource. A Jitsi server must not connect to a closed source client. 

Transparency is an important point. This also includes discussions like https://github.com/jitsi/jitsi-meet/issues/5799, which must not be stalled.

**Comment by luixxiul** [comment]
I am going to close this ticket because this is a bug and feature request tracker.

BUT please don't get me wrong; you are greatly welcome to continue your discussion on https://community.jitsi.org. There are fanatic users out there who believes the value of open source.

In order to reopen this issue, you need to specify which tasks exactly are needed to make Jitsi Meet more privacy oriented meeting system. Let's revisit this ticket once the concrete tasks will have been specified.
