### ISSUE TITLE
Chromeos chromebook chrome update causes SIGSEGV with video

### ISSUE THREAD

**Issue by nottledim** [jitsi/jitsi-meet#6974]
Just updated my chromebook from 81.0.4044 to 83.0.4013 and since doing it meet.jit.si crashes with SIGSEGV when a second user joins. It seems to be related to video because it doesn't happen when camera disabled.

I've also logged a feedback report with Google.  Tried all suggestions for fixing "Aw Snap" problems (clearing cache and cookies etc) but it doesn't help.

Android app on chromebook is not affected (i,e. it still works).

**Comment by saghul** [comment]
We reported something alike but it only happened when using H.264 and hardware acceleration, but that it’s not the case here since we have it disabled on meet.jit.si.

Unfortunately all you can do is wait for Google to fix it with an update. Unless there is a way to workaround it, but we’d need to reproduce it first.

**Comment by hugbe8** [comment]
same situation for me 
Version 84.0.4147.33 (Build officiel) beta (32 bits)

**Comment by jmhammond** [comment]
This is still occurring on both the stable Version 83.0.4103.97 (Official Build) (64-bit) on Pixelbook eve and the beta version on v84.

**Comment by nottledim** [comment]
Problem disappeared, so far as I'm concerned, following recent updates to chrome.
