### ISSUE TITLE
Jitsi meet server Hangs after running for several hours.

### ISSUE THREAD

**Issue by patelmohit829** [jitsi/jitsi-meet#6981]
I have running multiple server instances (AWS, IBM and other local servers). In all of the instances I've faced a common issue, i.e. the server hangs after running for several hours.

The solution I got so far is to restart by using the following commands:

systemctl restart jitsi-videobridge2.service
systemctl restart jicofo.service
systemctl restart prosody.service
systemctl restart prosody.service

Can anyone please help me out to find the solution for this

Many thanks in advance!

**Comment by WonderCRM** [comment]
Ubuntu srv 20.04 on VMWare, works stably without freezes.

**Comment by sanvila** [comment]
You should probably monitor (for example, with tools like prometheus) the amount of RAM and CPU used by your machines. Otherwise you will never know whether or not they have enough memory or if they are overloaded when they crash.

Without such information, I would not even know where to start to fix this issue if I was the author.

**Comment by Echolon** [comment]
@patelmohit829 may you have an answer to the question? That would help a lot!

**Comment by Echolon** [comment]
I will close this until feedback is provided.
