### ISSUE TITLE
Enable Picture in Picture for Firefox

### ISSUE THREAD

**Issue by Yajo** [jitsi/jitsi-meet#6989]
**Is your feature request related to a problem you are facing?**
I'd love to be able to see jitsi video while browsing other apps, specifically useful IMHO when sharing my screen.

**Describe the solution you'd like**
Firefox ships [this picture in picture mode](https://support.mozilla.org/en-US/kb/about-picture-picture-firefox) that would just work if we were able to use it in jitsi.

**Describe alternatives you've considered**
Split to a separate window and reduce it.

**Comment by Echolon** [comment]
@Yajo 

I think that should work already?

Related issues:

How to stop service when exit Picture in Picture mode #5573 
Support for speaker-view picture-in-picture on chrome #6534

**Comment by saghul** [comment]
"This feature is designed to work on most web videos. Though some videos will not display the blue toggle hovering over it. We only show it for videos that include an audio track, and that are also of sufficient size and play length. "

I think this might be why you don't see it. Our video element contains just a video track, since audio tracks are rendered in an audio element. Nothing we can do on our side I'm afraid.

**Comment by Yajo** [comment]
That must be it, yes.I guess it's worth keeping under the radar https://bugzilla.mozilla.org/show_bug.cgi?id=1463402
null
