### ISSUE TITLE
Please reconsider way of manage codebase at GitHub and use basic functions at least

### ISSUE THREAD

**Issue by luixxiul** [jitsi/jitsi-meet#7011]
**Is your feature request related to a problem you are facing?**

While I know the development team is indifferent to use functions to manage issues / PRs list, please **at least** consider to use basic functions available like below, in order to avoid critical regressions, some of which even break the stable releases. That should not happen.

1. Please **stop merging commits or PRs to `master` directly**.
2. Please **create branches based on the types of binaries** (`stable`, `testing`,  `nightly`)
3. Please **create releases based on these branches**
4. Please **set milestones** and use them

These are basic functions available at GitHub, and there are reasons why they are available. There is a lot of regressions that could have been avoided if these functions had been properly used. 

I would recommend you to do 1 and 2 at least. Every change should be applied to `nightly` at first, and then apply them **`testing` for testing**, and apply them to to **`stable`** once they are actually proved **stable**.

Please stop messing around the master branch. It's too risky and not reasonable. Reverting commits on master branch should be avoided at any cost, and can be avoided if you manage branches and releases wisely.

See https://github.com/RocketChat/Rocket.Chat/pull/17870 for a great example. They know what they are doing.

**Comment by luixxiul** [comment]
See: https://github.com/jitsi/jitsi-meet/issues/6801#issuecomment-635905233 (due to https://github.com/jitsi/jitsi-meet/pull/6754) 

[Admitting](https://github.com/jitsi/jitsi-meet/issues/6801#issuecomment-636283245) that merging the function was mistake and reverting the commit is not the essential solution. The essential solution should be to establish a systematic way of managing releases.

**Comment by saghul** [comment]
There are a number of ways to approach the development of a project.

What you describe is the process of a project which is more akin to a packaged application with a fixed set of goals.

This is not that.

This project follows a model closer to a "rolling release" style (think or Arch Linux for example).

The resources required to do what you ask for are not reasonable. There is just not enough workforce to manually test what our automated testing doesn't cover, every day.

Our stable releases are based on what we run on meet.jit.si, they are snapshots of what we know is tried and true on production. Again, this is analogous to Arch LInux, a release is not goal driven but a snapshot in time.

Now, that aside, we have made mistakes. They are specially visible now, because our user number have gone sky high. So this is what we are planning to do:

- Create release branches for our meet.jit.si releases (not all of these branches will result in a stable release, but they should help avoid last-minute hacks to get a release out)
- Gradually introduce unit tests specially for things that are hard to test end-to-end.

> Reverting commits on master branch should be avoided at any cost,

That's *your* opinion. I wholeheartedly disagree. Look at Chromium or Nodejs for good examples of successful projects which are not shy of reverts when things go inadvertently wrong.

<hr />

I respect your opinion, and given virtually unlimited time and resources it would indeed be a good idea to do something like what you propose. But we don't live in that reality.

**Comment by luixxiul** [comment]
Hello,

> Look at Chromium or Nodejs for good examples of successful projects which are not shy of reverts when things go inadvertently wrong.

> given virtually unlimited time and resources it would indeed be a good idea to do something like what you propose. But we don't live in that reality.

I am very sorry but honestly, I rationally cannot understand what you say. There are many questions that occur to me, like: Are you saying you are following the way of the ultra-large projects like Chromium / Nodejs while you claim at the same time that you don't have the virtually unlimited time and resources that are available only to such ultra-large projects? if Jitsi is thought to be similar to Arch Linux, is it reasonable to compare Jitsi with Chromium (that is a packaged application)? Does Jitsi have the enough manpower to maintain snapshots like Arch Linux does, and did you research that maintaining snapshots like Arch Linux would actually require less manpower? Did you study on that point and compared models to decide which one is best for Jitsi Meet? Is what you think is best not `it's just your opinion`?

I totally understand and appreciate you are going to introduce how to handle codebase and I am thrilled to see the future development (yet ultimately `it's none of my business` as both you and I would agree), but nobody appreciates (and at least, I hate) to be told `it's just your opinion` (as you quite often do) based on apparently imperfect reasoning. 

Take care,

**Comment by saghul** [comment]
Hey,



>  am very sorry but honestly, I rationally cannot understand what you say.

What I'm saying is there is more than one way to do things. And I gave you concrete examples of other projects which do things differently. That doesn't mean we follow a specific model to the letter, we just cherry-pick things and use whatever works for us. Just like everyone else I think. Nobody came up with a given model, everything is iterative.

> but nobody appreciates (and at least, I hate) to be told `it's just your opinion` (as you quite often do) based on apparently imperfect reasoning.

Sorry, I don't mean to sounds dismissive or anything, let me try to elaborate. There are many people who come and say how something "should be done". There is no absolute truth, no silver bullet to how every software project has to be managed, so when I say "it's your opinion" I mean it literally. You think that is the right way, I may think otherwise. Moreover, I may even agree with you, but there are constraints you might not be aware of which swing things one way or another.

I think we both chase the same goal here: make the project better, easier to use and contribute to. I can't speak to where things will go in a year or 5, but I do know that the model you propose is not attainable right now.
