### ISSUE TITLE
Import pt-BR translation to code

### ISSUE THREAD

**Issue by filhocf** [jitsi/jitsi-meet#712]
Can update the brazilian portuguese to code? Thanks in advance.

**Comment by filhocf** [comment]
Some update?

**Comment by filhocf** [comment]
Somebody can give some news about how import the translation from transfix to code? I can do it, since someone give a way/page/orientation for.

**Comment by ibauersachs** [comment]
@gpolitis It's usually clicking on "Commit all to VCS" on the [language page](http://translate.jitsi.org/pt_BR/jitsi-meet/) in Pootle. This fails for pt_BR - I need to check Pootle. I'll need to check that, might take a few days.

@filhocf pt_BR is missing 120 words in the translation. Would you mind finishing the it?

**Comment by filhocf** [comment]
@ibauersachs pt_BR is done. Thank you by your return.

**Comment by ibauersachs** [comment]
Fixed and committed.

(FYI: i18next-conv required the iso-language code to be all lowercase.)

**Comment by ibauersachs** [comment]
Hm, that was too early: i18next uses _ to distinguish contexts, so it's not possible to use pt_BR as a language code in languages.json and I resorted to ptBR.

Can someone (@gpolitis or @hristoterezov) please update the main application to handle that? I don't know the Meet code well enough to fiddle with it. I think it's at app.js#L111 and the change might be as simple as doing something like `language.length ==4 ? language.substr(0,2)+'-'+language.substr(2,2) : language`.

**Comment by hristoterezov** [comment]
@ibauersachs Thanks for investigating the issue. We will update the meet application. But I'm not sure I fully understand the issue.

>  i18next uses _ to distinguish contexts, so it's not possible to use pt_BR as a language code in languages.json and I resorted to ptBR.

I'm not sure what do you mean "i18next uses _ to distinguish contexts". Is this a problem with the pootle integration (when we import/export the json files) or the js i18next library?

If we are using ptBR as a language code in language.json can't we use ptBR for suffix of the filenames as well? Or the filename is coming from pootle and we can't (or is going to be hard) to change it? Otherwise having pt_BR suffix for filenames and ptBR for json keys seems to me a little inconsistent. But if we don't have other easy options I don't think it's big deal. WDYT?

**Comment by ibauersachs** [comment]
@hristoterezov The thing with the _ is just how i18next ext works. Thus we cannot use pt_BR as a key in a language file (languages.json). The _ in pt_BR comes from Pootle, which uses country specific locales like that (instead of e.g. with a dash).

Anyway, I was simply trying to avoid messing further with the already very brittle po<->json conversion script. Which I did anyway now and it seems to be working.

Can you please verify that Portuguese (Brazil) can now be selected and close the issue if that works?

**Comment by hristoterezov** [comment]
@ibauersachs  Thank you for the fix!

The new languages were not included to the selectbox. I included all of them except Armenian and Occitan because for these 2 there isn't anything translated into the files. 

After PR #740 is merged Portuguese (Brazil) will be included in the select box and it will work.

**Comment by EdemarSantos** [comment]
@hristoterezov, the i18next supports hypen?

My suggestion is to use "language-region" ("pt-BR", hyphen separator) format,
as used in HTTP "Accept-Language" (RFC 7231) (ISO639-1 + ISO 3166-1 alfa-2).

The "language_territory" ("pt_BR", underscore separator) format
conforms to ISO 15897 (POSIX locales and POSIX charmaps) / BCP 47 standard.

A good unofficial reference: 
http://www.i18nguy.com/unicode/language-identifiers.html

@ibauersachs, the lack of a standard is a nightmare!
@filhocf , "show de bola!"
