### ISSUE TITLE
I can't seem to replace the DEFAULT_LOGO_URL. It worked fine about a week ago, now I just see the jitsi watermark

### ISSUE THREAD

**Issue by the-timoye** [jitsi/jitsi-meet#7162]

**Comment by Echolon** [comment]
@the-timoye thank you for your report. Can you please provide a proper title and fill out the issue template?
That would be helpful!

**Comment by saghul** [comment]
This is intentional. All we ask for when people use the external API for meet.jit.si is to keep the logo, since well, we maintain the infrastructure. This is mentioned in the documentation, right at the very top: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe

You can of course change it in your own deployment.
