### ISSUE TITLE
iOS SDK not working with Xcode 11.4

### ISSUE THREAD

**Issue by ShubhGar** [jitsi/jitsi-meet#7234]
I try to use iOS SDK but  unable to build in Xcode 11.4.
![Screenshot 2020-07-03 at 6 16 09 PM](https://user-images.githubusercontent.com/24808854/86551602-21535b80-bf63-11ea-92d7-c248d389f6aa.png)

**Comment by aokudan** [comment]
Please help

**Comment by saghul** [comment]
What SDK version are you trying to use?

**Comment by ShubhGar** [comment]
i am using pod

**Comment by saghul** [comment]
What pod version did you specify?

**Comment by ShubhGar** [comment]
Did not specify any version

**Comment by saghul** [comment]
Can you reproduce the problem with the SDK sample projects?

**Comment by jakobwoegerbauer** [comment]
I have the same problem with Xcode Version 12.0 beta 4 and JitsiMeetSDK 2.8.1 in our project and the SDK sample project (swift-pip) as well.
The error message is:
```
Failed to build module 'JitsiMeet' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.25.2 clang-1200.0.27.1)'
```
We had a similar problem when we built a fat library for a customer. We solved it by providing a XCFramework instead of a fat binary framework. See [this](https://www.andresalla.dev/en/2020/06/02/the-end-of-fat-binaries-xcframeworks/) or [this](https://dev.to/quangdecember/building-your-own-xcframework-2kk6) for examples.

**Comment by adityariyadi** [comment]
I use Xcode 12.0 just upgrade from 11.2 because of the same experience.

failed to build module 'JitsiMeet' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)

I change Build Libraries for Distribution to Yes,  doesn't solve the problem.

**Comment by saghul** [comment]
SDK 2.10.2 is now out, compiled with Xcode 12.

**Comment by adityariyadi** [comment]
thank you very much. It works like charm.
