### ISSUE TITLE
Neither video nor audio on IPv6-only system

### ISSUE THREAD

**Issue by memcopy** [jitsi/jitsi-meet#7349]
### Description:

I disabled IPv4 on my PC and only kept the IPv6 addresses. After that I visited meet.jit.si. 
While the website itself works fine, there is neither video nor audio in the conferences.
On my own hosted jitsi instance I have the same issues.

I assume IPv6 support is broken, or the default configuration is wrong.

### Steps to reproduce:

1. Remove all ipv4 addresses: ip addr del xxx.xxx.xxx./xx dev ensXXX
2. Open meet.jit.si in browser
3. Join conference
4. Open the same conference in other browser tab
5. Video and audio are broken

### Expected behavior:
I expect the conference to just work because not NAT is involved. This setup should be much simpler
without ICE, stun and there-like.

### Actual behavior:

No video and audio in the conferences.

### Server information:
meet.jit.si

### Client information:

- Browser / app version: Chromium 84.0.4147.89 Arch Linux
- Operating System: Arch Linux (latest)

**Comment by PaulosV** [comment]
This issue is still an issue. WIth an IPv6-only network, without any IPv4 connectivity or NAT64, no calls can be performed. Even with two IPv6-only clients, the call still does not connect.

The web interface is fully functional and does not indicate connectivity issues, but there is no audio/video.

Notable errors from the console:
```
api.amplitude.com/:1 Failed to load resource: net::ERR_ADDRESS_UNREACHABLE
...
callstats-ws.min.js:29 POST https://auth.callstats.io/authenticate net::ERR_ADDRESS_UNREACHABLE
...
callstats-ws.min.js:29 GET https://collector.callstats.io/clockSync net::ERR_ADDRESS_UNREACHABLE
...
VM13 app.bundle.min.js:414 WebSocket connection to 'wss://rtcstats-server.jitsi.net//test-ipv6-now' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE
...
BridgeChannel.js:83 WebSocket connection to 'wss://meet-jit-si-eu-central-1b-s37-jvb-40-78-107.jitsi.net/colibri-ws/default-id/8cdb7255c1607ae6/fba534e4?pwd=xyz' failed: Error in connection establishment: net::ERR_ADDRESS_UNREACHABLE
```

All of these hostnames - but mainly  `meet-jit-si-eu-central-1b-s37-jvb-40-78-107.jitsi.net` and `rtcstats-server.jitsi.net` do not resolve to an IPv6 address.

(OT: The only client which seems not to have issues with IPv6 WebRTC is Chromium / Chrome.)
