### ISSUE TITLE
 unexpected meeting name collision when there's a "/" in url.

### ISSUE THREAD

**Issue by mebassett** [jitsi/jitsi-meet#7359]
### Description:

When I type in a meeting url, e.g.,
"https://meet.jit.si/is-this-a-bug/20/07/2020" (or something else with
slashes) I expect the full string after the first slash to be the name
of the meeting, e.g. "is-this-a-bug/20/07/2020".

### Steps to reproduce:

1.  Using firefox on the deskptop, start a meeting at "https://meet.jit.si/is-this-a-bug/20/07/2020"
2.  Have a friend (also using firefox on the desktop)  go to"https://meet.jit.si/yes-it-is/20/07/2020"

### Expected behavior:

you are both in different meetings.

### Actual behavior:

 you're both in meeting "2020", possibly with some strangers.

### Server information:

found on https://meet.jit.si

### Client information:

- Firefox 78 
- Gnome shell 3.36.3 / fedora 

haven't tested with other systems but I expect its the same.

**Comment by aaronkvanmeerten** [comment]
This issue is related to the way we handle 'tenant' URLs, where we do nginx redirects interally.  We are currently inadvertently redirecting multiple times until we find the format "/ROOM" or "/TENANT/ROOM", and then serving the index.html page.  This means all rooms above are actually just 07/2020 no matter what else you prepend.

The immediate solution is to stop handling the longer URLs at all, and serving the 404 page for them.  A longer-term solution if longer URLs are desired is to do some kind of munging to allow them to become valid additions to the XMPP room names using some sort of character replacement.  For now we'll likely do the 404 solution so as not to confuse anyone.  I've got a PR open to our internal infrastructure repo to resolve this in the next release of meet.jit.si.

**Comment by bgrozev** [comment]
Conference names with 2-slashes are no longer valid on meet.jit.si
