### ISSUE TITLE
mobile: VoIP hot action buttons

### ISSUE THREAD

**Issue by 532910** [jitsi/jitsi-meet#7371]
Buttons:
1. switch front-back camera
2. sound device selection
are first-class actions and must be accessible in one tap.

**Comment by 532910** [comment]
Native android dialer:
![image](https://user-images.githubusercontent.com/14617699/88123391-7a61f700-cbd3-11ea-9866-9e6b10fa02b5.png)

**Comment by saghul** [comment]
Those are heavily dependent on your use case.

The dialer app is not particularly a good example because it doesn’t have video so it has a lot more scree real state to put controls on.

This topic is highly subjective and we keep making improvements to our UI as we move forward. There is a redesign which has been delayed a bit, but expect changes in this area.
