### ISSUE TITLE
Mobile app forgets server address

### ISSUE THREAD

**Issue by Lominean** [jitsi/jitsi-meet#7373]
### Description:

Jitsi Meet on iOS doesn't save custom server address, but changes back to meet.jit.si on each relaunch.

### Steps to reproduce:

1. Open Jitsi Meet app on iOS.
2. Open Settings view.
3. Enter a server address, other than `meet.jit.si`.
4. Leave settings.
5. Leave app and then force quit.
6. Reopen app, check what it says in server field and try to join the room.

### Expected behavior:

The entered server address should be saved and used.

### Actual behavior:

Entered server address is forgotten and replaced with `meet.jit.si`.

### Server information:

- Jitsi Meet version: ?
- Operating System: ?

### Client information:

- Browser / app version: Jitsi Meet 20.3.1
- Operating System: iOS 13.6 (iPhone)

### Additional information:

Have tried reinstalling app. Tested with two different self hosted Jitsi servers.

**Comment by gcoretech** [comment]
Rooms that used to work with the previous Jitsi Meet version don't work anymore because all rooms are openend on meet.jitsi.si. Entering the self-hosted Jitsi server's address in preferences did not work until deleting and re-installing the app.
While the app is running it is possible to use those rooms on the self-hosted server again but just until the app is closed.
Then the server defaults back to meet.jitsi.si
iOS Version installed is 20.3.1 (Build 81)

**Comment by saghul** [comment]
I could reproduce the issue and have a pretty good guess as to what caused this, I hope to have a fix soon.

**Comment by saghul** [comment]
Fix on https://github.com/jitsi/jitsi-meet/pull/7374 New builds are on the way. Sorry for the trouble!

**Comment by gcoretech** [comment]
That was quick, thanks a lot!
