### ISSUE TITLE
Make focus username configurable (ex. focusUserJid)

### ISSUE THREAD

**Issue by kevin-olbrich** [jitsi/jitsi-meet#7376]
**Is your feature request related to a problem you are facing?**
The username "focus" is hardcoded in many places and thus can not be customized.
Community thread: https://community.jitsi.org/t/no-traffic-to-jvb-from-client/70817

**Describe the solution you'd like**
Make username for "focus" configurable.
Example config.js: focusUserJid: 'meet-focus@auth.jitsi-meet.example.com',

**Describe alternatives you've considered**
Keep, document it and / or remove variable declaration.

**Comment by paweldomas** [comment]
thanks for the report, yeah it needs to be cleaned up

**Comment by vali-um** [comment]
Hi,

I ran into problems as i wanted to change the focus user jid to fit our environment. So i scanned though occurences that harcode the 'focus' jid, which i only found in lib-jitsi-meet, and patched it to use the setting and fallback to 'focus'.

A sidenote: I've noticed the functions setFocusUserJid() getFocusUserJid() modules/xmpp/moderator.js. I don't really understand why the FocusUserJid is set from the iq message instead of combining Focus with the configured auth domain

thanks for adding the documentation about this, would have saved me a lot of trouble to read this earlier (totally my fault...)

[focus_configurable.txt](https://github.com/jitsi/jitsi-meet/files/5421942/focus_configurable.txt]
