### ISSUE TITLE
Allow auto join feature 

### ISSUE THREAD

**Issue by dipankar08** [jitsi/jitsi-meet#7398]
I want to use jitsi inside web application as a iframe.but it should join automatically when user create the object.

I see that there is an api for hang up. Is it possible to api for join and restart ?

**Comment by saghul** [comment]
When you use the iframe API the room is one of the parameters you pass, so the room will be auto-joined. https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#api--new-jitsimeetexternalapidomain-options

**Comment by vesper8** [comment]
Did you get this to work @dipankar08 ?

I'm using https://github.com/mycurelabs/vue-jitsi-meet and while I do pass the room name, and user name, the user still needs to click 'join meeting'. So this is not what I would consider "auto join". Yes perhaps the user doesn't have to type the name of the room, but they still have to join the meeting.. and since this is a web integration I too would like to be able to auto-join (the meeting). Is this possible @saghul ?

**Comment by saghul** [comment]
You can pass the `prejoinPageEnabled` config override to false to skip the pre-join page.

**Comment by vesper8** [comment]
that works! thank you!
