### ISSUE TITLE
Chrome camera permissions issue

### ISSUE THREAD

**Issue by fred-dev** [jitsi/jitsi-meet#7478]
### Description:

I am having an issue with chrome not asking for camera permissions on chrome Version 84.0.4147.105 (Official Build) (64-bit). I am using jitsi meet on my site, but also see this exact same behaviour when visiting https://meet.jit.si. In firefox the behaviour is correct.
 It seems the method that jitsi meet uses to get camera permissions has been depreciated, it will only get microphone access. When the user tries to enable the camera it will add an access request that can be found by clicking in the camera icon in the address bar of chrome (this does not appear until the enable camera button is pressed in the standard jitsi interface), but no popup or user prompt is triggered.

### Steps to reproduce:

1. Remove any camera and microphone permissions for jitsi sites in chrome
2. Using chrome go to https://jitsi.org/
3. Click start a meeting
4 .Click go on the next page

### Expected behavior:

The site should try to get permission to access the camera and microphone and prompt a pop up, or at least show the video blocked in the address bar

### Actual behavior:

Chrome gets access to the microphone but not the camera.
Chrome shows an error that permission to the camera was denied 
Chrome address bar shows only a microphone Icon, permission cannot be given for the camera from this point

The console shows

`Logger.js:154 2020-08-07T14:05:41.803Z [features/base/tracks] Failed to create local tracks Array(2)0: "audio"1: "video"length: 2__proto__: Array(0) s`

![Screen Shot 2020-08-07 at 16 06 33](https://user-images.githubusercontent.com/1588629/89654519-0d37ac80-d8c9-11ea-8ced-0075d4c94afa.png)

### Server information:

- Jitsi Meet version: Current version deployed on https://meet.jit.si/
- Operating System: Current version deployed on https://meet.jit.si/

### Client information:

- Browser / app version: Google chrome Version 84.0.4147.105 (Official Build) (64-bit)

- Operating System: Mac OSX  version 10.15.6 (19G73)

**Comment by Echolon** [comment]
Very good, thanks!

**Comment by Y0ngg4n** [comment]
any updates here?

**Comment by feketegy** [comment]
This is also happening for me, it looks like a bug on jitsi

**Comment by saghul** [comment]
That's very odd. What do you see when you tap on the mic icon on the address bar?

**Comment by feketegy** [comment]
@saghul Tapping on the microphone or camera instantly gives me a "User denied permission" without showing the popup to allow the mic or camera. In the site settings in Chrome it's already allowed for the website.


It also works in Safari and Firefox, but not in Chrome.


The error I'm getting is:

![image](https://user-images.githubusercontent.com/489775/98663755-27fb4080-2352-11eb-8645-bbe02a813c62.png)

And the error log expanded, `gum.permission_denies`

![image](https://user-images.githubusercontent.com/489775/98663864-4b25f000-2352-11eb-9fc0-b0320dfb5015.png)

**Comment by saghul** [comment]
If you go to `chrome://settings/content/camera` do you see something like this?

<img width="783" alt="Screenshot 2020-11-10 at 11 47 17" src="https://user-images.githubusercontent.com/317464/98664332-87ede900-234a-11eb-910e-b76202d2b647.png">

If so, it looks like you might have rejected the permission at some point, remove the block by clocking on the trashcan and try again.

**Comment by feketegy** [comment]
Yes

**Comment by feketegy** [comment]
In the mean time I fixed the issue, the problem in my case, was this HTTP header which I removed: `add_header Content-Security-Policy "upgrade-insecure-requests";`

I'm guessing Jitsi Meet sends some scripts through HTTP and it was treated by the browser as secure and the respective security policies were applied which caused the error.

I still think this is a bug on Jitsi's end.

**Comment by saghul** [comment]
> Yes, removed it, switched to allow but the issue still occurs.

So you had blocked it. There is nothing we can do in our code about that.

> In the mean time I fixed the issue, the problem in my case, was this HTTP header which I removed: `add_header Content-Security-Policy "upgrade-insecure-requests";`

Removed it from where? Are you running your own deployment? The original report was for meet.jit.si, if you are using your own you should mention that, otherwise it's a guessing game.

> I'm guessing Jitsi Meet sends some scripts through HTTP and it was treated by the browser as secure and the respective security policies were applied which caused the error.
> 
> I still think this is a bug on Jitsi's end.

I don't know what resource that could be. Can you check the network tab and see what request goes through HTTP? I checked meet.jit.si and I don't see any.

**Comment by feketegy** [comment]
@saghul So it was blocked for some reason, but only the camera not the microphone, but I also wrote that I switched to "allow" refreshed the page and the error was still occurring.


I'm not running my own deployment, I'm using Jitsi Meet, the cloud version of Jitsi, the HTTP header was removed from the webserver configurations which server the website where Jitsi is embedded on.


These were the errors I posted in the comment above with screenshots. I wasn't getting any other errors, but by removing the HTTP header fixed the error and I could activate the microphone and camera just fine.


I write I'm guessing this is a bug on Jitsi's side, because that HTTP header I removed, relates to content being served through HTTP, if the header present, the webserver treats those requests as HTTPS and applies the necessary security policies.

If you say no requests are being sent through HTTP then you may look into what security policies Chrome changed in recent versions, I saw that they tightened security now, because the error was occurring in Chrome only, not Safari or Firefox.

**Comment by saghul** [comment]
> I'm not running my own deployment, I'm using Jitsi Meet, the cloud version of Jitsi, the HTTP header was removed from the webserver configurations which serves the website where Jitsi is embedded on.

Can you please detail your setup? I don't understand what that web server might be doing if you are not hosting your own infra. A URL which I can use to try to reproduce the problem would be helpful.

**Comment by feketegy** [comment]
@saghul I can't show you a link, because it's a client's project. Basically the website is a generic wordpress website, it's a conference event website which is hosted on our servers and we're using Jitsi Meet to host the video chat on one of the inner pages on the website.

This is how it's embedded on the page

    const domain = 'meet.jit.si';
    const options = {
          roomName: params.get('id'),
          width: '100%',
          height: '100%',
          parentNode: document.querySelector('#meet'),
          userInfo: {
              email: user.email,
              displayName: user.display_name
          },
         configOverwrite: {
             disableDeepLinking: true,
         },
         interfaceConfigOverwrite: {
             TOOLBAR_BUTTONS: [
                 'microphone', 'camera', 'closedcaptions', 'desktop', 'fullscreen',
                 'fodeviceselection', 'hangup',
                 'etherpad',
                 'videoquality', 'filmstrip', 'feedback',
                 'tileview', 'download', 'help', 'chat'
             ],    
             SHOW_CHROME_EXTENSION_BANNER: false
         }
    };
    const api = new JitsiMeetExternalAPI(domain, options);
    api.addEventListener('readyToClose', () => {
        api.dispose();
    });

**Comment by t0fte** [comment]
This solved my Chrome / Jitsi issue when the camera didn´t get permissions even though I´ve given it all permissions. Disabling MediaFoundation Video Capture. Check video... Hope it can help! Cheers! [https://www.youtube.com/watch?v=3K5i5EauMWo](url)

https://www.youtube.com/watch?v=3K5i5EauMWo
