### ISSUE TITLE
Unable to kick out user from meeting

### ISSUE THREAD

**Issue by aniyanm** [jitsi/jitsi-meet#7542]
### Description:

I tried to kick someone from the meeting but it is not working as expected.

### Steps to reproduce:

1. User A  joined the meeting. 
2. Moderator trying to kick out user A

### Expected behavior:

User A should leave the meeting once he is kicked out of the meeting

### Actual behavior:

User A's screen will freeze for  few seconds and then he will be asked to rejoin the meeting.

### Server information:

- Jitsi Meet version:  latest
- Operating System: Ubuntu 18

### Client information:

- Browser / app version: Chrome
- Operating System: Windows

### Additional information:

Got this error in browser console:    Strophe: TypeError: Cannot read property 'getId' of undefined

**Comment by damencho** [comment]
Is this default installation without altering any config?

**Comment by yogeshsolankigithub** [comment]
I am also facing the same issue. well it is working fine when i  am  using "meet.jit.si" but i have hosted my  own  server and also  did some  configuration changes  in the configuration file.

It throws the following error in browser console:TypeError: Cannot read property 'getId' of undefined

**Comment by vineetStartele** [comment]
I was also getting the same error if i follow the link(https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart). above link is good for ubuntu 20.04 because it installs prosody version 0.11.7.bionic4 . above link is not good for ubuntu 18.04 because it installs prosody version 0.10.0-build1. 
**Solution for installation on ubuntu 18.04 not 20.04**  
1) create a new ubuntu system or format everything on existing ubuntu system. 
2) sudo nano /etc/apt/sources.list.d/prosody.list
3)deb https://packages.prosody.im/debian bionic main
4) wget https://prosody.im/files/prosody-debian-packages.key
5)sudo apt-key add prosody-debian-packages.key
6)rm prosody-debian-packages.key
7) sudo apt update
 after above step follow link (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) for further installation.
**NOTE** = when asked for hostname during installation , do not enter ip address(like x.x.x.x) or localhost .
