### ISSUE TITLE
Please support Peertube (and/or other) embedding

### ISSUE THREAD

**Issue by highvoltage** [jitsi/jitsi-meet#7601]
The functionality to play YouTube videos work great.

It would be even better if Jitsi Meet also supported playing videos from a PeerTube instance (or even allow to paste an embed code).

**Comment by DeusFigendi** [comment]
I'd like to endorse this feature request for this reason:

Currently I am in a weekly call with some friends and we're talking about a tv shows episode. So well to be more able to talk about it it's cool to have the same image of the episode. To do so the last times I shared my screen running netflix to show the scenes to my fellows. Skipping forth and back etc. etc.
That was cool but it's poor quality, since my upstream at home is pretty bad (like 2MBit/s) to stream two video streams (screen sharing plus cam video of myself) plus my CPU/GPU wasn't so happy too I think.
So I thought it might be a cool idea to upload the video in "not listed" to YouTube and than share it within the jitsi session so everyone can watch it simultaneously. Unfortunately YouTube striked/blocked the video instantly when I uploaded it, even if I set it so "not listed". I think sharing with a handful of my friends is totally legal (in most countries) because it's just like watching it on the same display (at least it's not "publishing" eh?). But hardly possible using YouTube.

For this I would love if I could share videos from other platforms (I also would prefer peertube) and/or simple video-files which I can control (play pause skip…) for all folks in the call.

**Comment by saghul** [comment]
Does peertube provide an iframe API equivalent to that of YouTube? If so, enabling it for PeerTube would be trivial.

**Comment by DeusFigendi** [comment]
> Does peertube provide an iframe API equivalent to that of YouTube? If so, enabling it for PeerTube would be trivial.

Yes it does, here is the relevant documentation:
https://docs.joinpeertube.org/#/api-embed-player
https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/api/embeds.md

(same content)

**Comment by madmath03** [comment]
I too very would like to see a PeerTube (and other platforms) share support.

Another idea that is kind of related is PeerTube recent developments to support live streams: Chocobozzz/PeerTube#3250
It's still something in progress but once it comes out, it would be great to share a Live Stream from PeerTube.

**Comment by shoei101** [comment]
I actually just posted a question in the community forums about this!  this would be a great feature!  crossing fingers.

**Comment by pachainti** [comment]
It seems that it already works [link](https://github.com/jitsi/jitsi-meet/issues/8283).

**Comment by saghul** [comment]
> It seems that it already works [link](https://github.com/jitsi/jitsi-meet/issues/8283).

That's different. This is about embedding, that is about streaming.

**Comment by Guiraud** [comment]
So is there a way to  live stream a Jitsi visio ?

**Comment by saghul** [comment]
Yes, you can just paste an aritrary RTMP url and that will work.

**Comment by Guiraud** [comment]
Thanks for this very interesting info.
I meant is a Jitsi meeting capable to have a RTMP url  ?

**Comment by saghul** [comment]
It's capable of *streaming* a meeting to any RTMP endpoint

**Comment by lapor-kris** [comment]
So, PeerTube is still not supported by Jitsi to share on the meeting?
At least it does not work at the moment...

**Comment by lapor-kris** [comment]
But it is for the YouTube...

**Comment by saghul** [comment]
I know. That why I said it's NOT supported (for PeerTube). I didn't mention it explicitly because that's what we've been talking about the entire thread :-)

**Comment by lapor-kris** [comment]
Thanks. Are there any plans to change that?

**Comment by saghul** [comment]
Not at the moment. But we'd welcome a PR that implements it.

**Comment by lapor-kris** [comment]
Unfortunately I am not able to do that, because I don't know how to program, nor where to start :)
But will try to find out if any of my friends would help me. Thanks

**Comment by madmath03** [comment]
Hi @saghul 

Just curious to know since your mentioned [implementation would be trivial with iframe API](https://github.com/jitsi/jitsi-meet/issues/7601#issuecomment-722987515),  and apparently it does, could you give any pointers on how to do this ?

**Comment by rasos** [comment]
It is possible to play a video from a Peertube instance when generating a download link and paste that in the field for Youtube videos. As the video is being downloaded first, I recommend only short videos and a low resolution (360p).

![fair tube_videoDownload](https://user-images.githubusercontent.com/485723/145253401-57eb27f9-b843-4622-bb64-9eb0f7acd456.png)
