### ISSUE TITLE
Android TV Leanback Support

### ISSUE THREAD

**Issue by ikogan** [jitsi/jitsi-meet#7623]
**Is your feature request related to a problem you are facing?**
Some of our conference rooms are setup with Android TV devices. While we can sideload the Jitsi Meet app on to them, the interface leaves a lot to be desired.

**Describe the solution you'd like**
Proper leanback UI support would be great, similar to the experience you get on the electron app.

- Chat bar accessible on the left
- Control with a remote (arrow keys, play/pause mute, etc.)
- Install-able from the play store
- Leanback launcher icon
- End to end encryption (eventually)

**Describe alternatives you've considered**
[Jami](https://jami.net/) has Android TV support but it seems like it's protocol is super buggy. I did try it in Chrome but I recall the experience wasn't great. We're still just hooking up laptops to the screen every time we use those rooms.

**Comment by Lantizia** [comment]
Mind if I just quickly ask 'Android TV' device you're running, the version of the OS/firmware it's on (or if it's a custom Android TV release like LineageOS) and what webcam you're using?

I'm finding it **rare** to find Android hardware that actually supports external USB webcams out of the box.

**Comment by saghul** [comment]
My Nvidia Shield TV does detect USB webcams, at least a couple of Logitech ones I tried.

**Comment by ikogan** [comment]
Yeah, I originally used an Nvidia Shield TV with a Logitech webcam but I also just tested on the new Chromecast with Google TV and that seems to work too. Right now you absolutely need a mouse and keyboard to navigate the interface. I can't even use the on-screen keyboard to enter text into the various text boxes.

For the Chromecast you'll need a USB C hub that supports power delivery and has some USB ports as the device only has one USB C port.

**Comment by Lantizia** [comment]
Well I've got 3 x Logitech C920's here and 2 x Nvidia Shield (2017, 16GB models)... I'll have to test if that combination works (but I suspect it will if something similar worked for @saghul).

For this Jitsi Meet project... I don't really want to give up one of my Shield boxes for it!  So I've bought one of the new Chromecast with Google TV instead since @ikogan says they work (with one of these hubs... [https://www.ebay.co.uk/itm/284006748208](https://www.ebay.co.uk/itm/284006748208))  

Here's hoping it works with this portrait display!... [https://www.amazon.co.uk/SWEDX-Kiosk-42-4K-UHD-White/dp/B00U2EOG3G](https://www.amazon.co.uk/SWEDX-Kiosk-42-4K-UHD-White/dp/B00U2EOG3G).

Kind of hoping the Jitsi Meet app shows who is talking at the top of the screen and then others down the bottom... and since the screen is human-height it'll be a good way of doing telepresence for a local LUG I'm involved with (which is looking for ways to go semi-virtual with COVID-19).

But I agree on getting proper leanback support and better Android TV integration!  The app (especially on Android TV) will just have to make it clear about the external USB webcam support thing being an Android / hardware problem.

**Comment by Lantizia** [comment]
Well that seems like a rather crazy policy, especially as this feature request is less than a year old.  I for one would still like to see proper Android TV support.

**Comment by ikogan** [comment]
Still interested.

**Comment by Lantizia** [comment]
Still interested.

**Comment by erdnuesse** [comment]
same here. using 2 hubs now, just to get a mouse working, which is super annoying. the direction toggles should enable button hihlighting and being able to navigate the interface with would be a huge improvement for the UI

**Comment by saghul** [comment]
Since nothing has happened, I'd say it's time to close this.

We have no plans to add leanback support to the Jitsi Meet app per se.

We experimented with having the app be a Spot TV and the mobile app be the remote, and if / when we have time we might go that route, but we just can't at the moment.
