### ISSUE TITLE
I need to support armv7 \ armv7s

### ISSUE THREAD

**Issue by MuZiLee** [jitsi/jitsi-meet#7747]
We used the latest version in the testing process, but we found that arm was not supported when testing iPhon 5\iPhon 5C and iPad3.
And the operating system requires ios 11.0+. How could this be a problem?
I need to support ios 9.0+, please help me, thank you

**Comment by MuZiLee** [comment]
Is there a compilation tutorial or something that I want to compile manually, as I need to do

**Comment by saghul** [comment]
We only support iOS 11+, and no armv7 supports iOS 11, do we dropped the architecture. WebRTC itself doesn't support older iOS versions, so you are fully on your own here. Sorry, but there is not much we can do here as the main library we depend on doesn't care about old iOS versions. You can use an old SDK release (2.4 should do).

**Comment by MuZiLee** [comment]
@saghul 
Are you saying that if we want to support ARMV7 / ARMV7s, we need three end downgrades?
Will this affect the existing apps?

Can you tell me 2.4 SDK which ones support ARMV7? What files are affected in the project?
Can I manually switch 2.4 ARMV7 code to 2.8+ SDK?

**Comment by saghul** [comment]
Rather than downgrading, you must not upgrade.

> Will this affect the existing apps?

I guess not for you, since you will be stuck with the old SDK version until you drop iOS < 11.

SDK 2.5.0 was the first one to drop iOS 10: https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md#250-2019-12-13 I no longer remember when we dropped iOS 9.

Here is the commit which dropped iOS 10: https://github.com/jitsi/jitsi-meet/commit/792f506425f3be1c46042871f2c2e03d403a87e2#diff-2505890afb91c875be64ad195a1502a6 as you can see keeping a fork with those changes is doable, but I wouldn't recommend it. In addition, you'd have to compile WebRTC itself on your own, since the binaries we provide are built for iOS >= 11.

**Comment by MuZiLee** [comment]
ok, thank you, @saghul 

Using iOS10+ will solve most of my current problems.
Armv7s: Iphon 5\iPhone 5C \iPad4;
I want to try to use the JITsiMeet in armV7S. How can I compile the ARMV7s version?
I give you the CPU architecture table for iOS.

![image](https://user-images.githubusercontent.com/7467318/93953859-01bc1a00-fd7f-11ea-9858-077e40c09094.png)

**Comment by MuZiLee** [comment]
![image](https://user-images.githubusercontent.com/7467318/93954294-f0274200-fd7f-11ea-901f-ba7ea7e404f7.png)

**Comment by MuZiLee** [comment]
Or can I compile the ARMV7s and ARMV7 frameworks in the 2.4.2 branch?

**Comment by saghul** [comment]
SDK 2.4.2 should have those architectures already.

**Comment by MuZiLee** [comment]
ok, thanks for your response, my friends. I think I should try 2.4.2 again. thank you
