### ISSUE TITLE
Remove "Copy and share meeting link" in PreJoinPageEnabled if disableInviteFunctions=true

### ISSUE THREAD

**Issue by tsproesser** [jitsi/jitsi-meet#7894]
Guess no more words needed :) This surely is an invite function and should be hidden, if no invite functions are desired.

**Comment by saghul** [comment]
Not really. You can just copy the URL from the browser's address bar. Inviting functionality is something different, as it includes phone dial in/out and potential integration with a people directory.

**Comment by alelasantillan** [comment]
> Not really. You can just copy the URL from the browser's address bar. Inviting functionality is something different, as it includes phone dial in/out and potential integration with a people directory.

In my use case, I put jitsi into an iframe to hide the room address on the browser's address bar. 

The invite is still working in the prejoin room even if disableInviteFunctions=true.

To be coherent with the actual functionality of the prejoin room the parameter should read instead something like:
disableInviteFunctionsExceptInLobby=true
or something like that (it sound ridiculous, I know, but now is totally misleading).

So I ask to change the functionality of disableInviteFunctions=true
to affect also the "Copy and share meeting link" of prejoin.

Another solution would be having two parameteres:
disableInviteFunctionForPrejoin=true
disableInviteFunctionForRoom=true

Otherwise the prejoin functionality is useless in my use case.
