### ISSUE TITLE
APP_NAME no longer works in interfaceConfigOverwrite when embedding Jitsi-Meet

### ISSUE THREAD

**Issue by Warchamp7** [jitsi/jitsi-meet#7985]
### Description:

In a previous release, specifying an APP_NAME in interfaceConfigOverwrite would cause jitsi-meet embeds to display the APP_NAME when requesting camera and/or microphone permission.

After updating recently, this is no longer the case and instead the embed always lists "**Jitsi Meet**"

### Steps to reproduce:

1. Configure options for a jitsi-meet embed
2. Include an APP_NAME under interfaceConfigOverwrite
3. Embed a new JitsiMeetExternalAPI with the options

### Expected behavior:

The browser requests permission for the specified APP_NAME

### Actual behavior:

The browser requests permission for "**Jitsi Meet**" instead of the specified APP_NAME

![chrome_2020-10-27_06-14-19](https://user-images.githubusercontent.com/1554753/97288386-27c05880-181c-11eb-8e59-dece4658da28.png)

### Server information:

- Jitsi Meet version: 2.0.5142-1
- Operating System: Debian GNU/Linux 10

### Client information:

- Browser / app version: Chrome 86.0.4240.111 
- Operating System: Windows 10

### Additional information:
N/A

**Comment by izakgl** [comment]
If you're embedding meet.jit.si there are some things you cannot override, including watermark and app name. This is something you have to accept if you're using their infrastructure.

You can check [here](https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/config/interfaceConfigWhitelist.js) what is possible to override in the interface_config through iframe api.

If you use your own deployment, things are a bit different because you can edit interface_config.js on the server directly.

**Comment by izakgl** [comment]
You still can't override these settings through iframe api, but like I mentioned you can change them on the server where you're hosting jitsi-meet. Just edit the interface_config.js in your config folder.

**Comment by Warchamp7** [comment]
The issue is I'm overriding it to different values on different embeds, not universally across all our embeds.

I could modify the whitelist, but that will get overwritten every time we update

**Comment by izakgl** [comment]
That makes sense yes. If you're building it from source, you could fork the project, modify the whitelist and rebuild it. Then when you merge updates to your fork, your changes should not be overwritten.

If, however, you're installing it from the debian package, I unfortunately don't have a good answer for you.

**Comment by saghul** [comment]
I think we broke your use-case @Warchamp7, sorry about that. I think we could implement an extension mechanism for whitelisted items to be removed on meet.jit.si, in order to allow this to remain as it was. However, this would require those who want the app name configurable to rebuild the frontend... Hum. Need to think about it some more.

**Comment by coccochanel** [comment]
> 
> 
> You still can't override these settings through iframe api, but like I mentioned you can change them on the server where you're hosting jitsi-meet. Just edit the interface_config.js in your config folder.

hi dear,

where i can find this file in my server?

Thanks

**Comment by saghul** [comment]
Sorry we kept this open for so long. Due to people not following our pretty loose guidelines we had to strengthen the checks. This is no longer overridable unless you rebuild the frontend yourself.
