### ISSUE TITLE
Video quality deteriorates while using screenshare with camera

### ISSUE THREAD

**Issue by Omegapol** [jitsi/jitsi-meet#8032]
## Description
---
If user enables his camera while using screenshare, quality of the video deteriorates very badly. 
Disabling camera, makes video quality go back to normal.

I noticed that amount of participants influences the resulting quality.

## Current behavior
---
Shared screen quality deteriorates when video from camera is on

## Expected Behavior
---
Shared screen quality should remain the same

## Possible Solution
---
N/A 

## Steps to reproduce
---
Set up a conference with multiple participants
Start screensharing
Start video from camera

# Environment details
---
Participants:
 5x chrome on Windows
 4x chrome on Mac

User's ideal resolution lowered to 640x480
p2p disabled

Config:
[config.js.txt](https://github.com/jitsi/jitsi-videobridge/files/5423969/config.js.txt)

Log:
[1603383268502.log](https://github.com/jitsi/jitsi-videobridge/files/5424092/1603383268502.log)

**Comment by jallamsetty1** [comment]
@torreylyons, looks like your bridge channel is not setup properly, this might result in lot of other issues w.r.t dominant speaker switching, lastN and layer suspension. You might wanna fix that first.
```
BridgeChannel.js:88 WebSocket connection to 'wss://strefa-ciszy.com/colibri-ws/172.22.0.5/a7ae9217089904f6/3f079ab0?pwd=4ujgkj1744rg4g074rl4jedb3k' failed: Error during WebSocket handshake: Unexpected response code: 404
_initWebSocket @ BridgeChannel.js:88
t @ BridgeChannel.js:107
Logger.js:154 2020-10-22T16:10:33.374Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onclose>:  Channel closed by server
Logger.js:154 2020-10-22T16:10:33.374Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onclose>:  Channel closed: 1006 
o @ Logger.js:154
e.onclose @ BridgeChannel.js:376
Logger.js:154 2020-10-22T16:10:36.673Z [modules/RTC/BridgeChannel.js] <l._send>:  Bridge Channel send: no opened channel.

```
I also noticed that you don't have simulcast disabled for desktop sharing which would explain the video quality issue you are running into when you enable the camera. Please uncomment testing.capScreenshareBitrate in config.js and check if you see the same issue.

**Comment by Omegapol** [comment]
@jallamsetty1 thanks for the feedback!
We'll test on our next meeting and let you know if this solves the issue.

**Comment by jallamsetty1** [comment]
> Note also that the aspect ratio of the screen share appears to be fixed after the user turns on the picture-in-picture mode with the camera. Once the camera is on if the area being shared changes, the aspect ratio of the video sent out is clipped to the original aspect ratio.

This shouldn't be happening anymore. Earlier, we were resizing the desktop track to 720p whenever the camera was turned on to conserve cpu on the client machine. We have noticed that this is causing blurriness in the last few chrome releases. We have stopped resizing the desktop track by default and moved that logic behind a config.js setting - https://github.com/jitsi/jitsi-meet/blob/master/config.js#L284.
I believe this issue has been resolved and will be closing the ticket as the fix for this issue has been released on https://meet.jit.si and will be also be available in the next release of the stable builds. Please feel free to re-open the ticket if you think it doesn't fix your issue.
