### ISSUE TITLE
OBSERVATION: [Unstable Release] Chrome renderer wrecking havoc on "VIRT" memory with Jibri activated

### ISSUE THREAD

**Issue by Freddie-m** [jitsi/jitsi-meet#8160]
### Description:

Not sure how important it is to report this since it's still an unstable build, but per chance it could prove to be helpful observation, here: I noticed that in the latest (as at when I ran it) unstable, the chrome renderer process spikes the virtual memory unusually when Jibri starts recording. The actual RAM still looks fine (<1% of total available memory), but the spike in the virtual memory stood out. I didn't run the server long enough to confirm whether this eventually affects observed performance but the spike was so noticeable, I felt it was worth mentioning.

### Steps to reproduce:

1. Launch htop
2. Start a Jitsi meeting
3. Observe readings on htop
4. Start recording the meeting with Jibri
5. Observe readings on htop

### Expected behavior:

VIRT should not spike so ominously

### Actual behavior:

With this release, when you activate Jibri (to start recording), the VIRT memory instantly shoots up into danger range and it stays there for as long as Jibri is recording. I've personally never noticed this in other versions/releases, so it stood out to me.

![Screen Shot 2020-11-25 at 2 48 44 PM](https://user-images.githubusercontent.com/63688942/100275910-abaa5500-2f2e-11eb-8493-952e62d24cc8.png)

### Server information:

- Jitsi Meet version: 2.0.5286-1
- Operating System: Ubuntu Server 20.04 LTS

![Screen Shot 2020-11-25 at 1 45 05 PM](https://user-images.githubusercontent.com/63688942/100276435-8538e980-2f2f-11eb-8db7-20eb5697f3a5.png)

### Client information:

- Browser / app version: Chromium Version 88.0.4299.0 (Developer Build) (x86_64)
- Operating System: Mac OSX 10.13.6

### Additional information:

Again, this might be a moot point if it's already known and being addressed, as the build is in the unstable phase. Just mentioning the observation, just in case...

**Comment by saghul** [comment]
Does the same thing happen if you have 3 participants in a room instead of recording it?

**Comment by fremzy** [comment]
Hmm..mm I don't think so, but I can't swear I explicitly checked that. I'll check later and report back.

**Comment by fremzy** [comment]
Ok, just checked and the answer indeed is "No". No spike whatsoever with 3 participants; spike only happens when Jibri enters. I tested a bunch of scenarios to rule out possible cause from my personal configuration:

**1. VP9, No simulcast, 3 participants - fine**
![Screen Shot 2020-11-25 at 6 20 56 PM](https://user-images.githubusercontent.com/63688942/100292844-a6113700-2f4f-11eb-99bc-d0d0440276d5.png)


**2. VP9, No simulcast, 3 participants + Jibri - Spike!**
![Screen Shot 2020-11-25 at 6 25 53 PM](https://user-images.githubusercontent.com/63688942/100292878-cd680400-2f4f-11eb-9dbf-a582fc042856.png)

**3. VP9, Simulcast, 3 participants - fine**
![Screen Shot 2020-11-25 at 6 32 29 PM](https://user-images.githubusercontent.com/63688942/100292904-ed97c300-2f4f-11eb-8a54-ca346143ad8f.png)

**4. VP9, Simulcast, 3 participants + Jibri - Spike!**
![Screen Shot 2020-11-25 at 6 33 39 PM](https://user-images.githubusercontent.com/63688942/100292933-056f4700-2f50-11eb-9bd9-0098a5c9e746.png)


**5. VP8, Simulcast, 3 participants - fine**



**6. VP8, Simulcast, 3 participants + Jibri - Spike!**
![Screen Shot 2020-11-25 at 6 39 03 PM](https://user-images.githubusercontent.com/63688942/100292955-1f108e80-2f50-11eb-97be-a7c23e3d5eb6.png)


And it makes sense to me that I only saw the spike when Jibri entered the meeting because the culprit is the **_chrome renderer_** process which is only used by Jibri. 

One other thing to note (and this may just be my mind): it seemed like my mobile device got warm pretty quickly on this release. It felt warm within just a few minutes of using it for this test. I noticed this earlier too. 🤔
