### ISSUE TITLE
Reduce Canvas size to improve performance 

### ISSUE THREAD

**Issue by freechelmi** [jitsi/jitsi-meet#849]
Currently Jitsi shows speaker webcam on the whole interface area which really takes 100% of the CPU even on powerful machines ( Firefox / Ubuntu 16.04 ) .

As default the canvas area should be smaller to use less CPU. ( 1/3 of the screen for example )

A button should be available to switch to bigger canvas size

**Comment by tuxayo** [comment]
I confirm the performance issue with the canvas size.

By monitoring CPU usage during a call and switching between a very small window a very big one (easy to do with a dualscreen), I can a see a significant difference.

**Comment by saghul** [comment]
The canvas size doesn't matter that much, it's the received video resolution. You can change that with the eye icon:

<img width="2032" alt="screen shot 2018-01-09 at 16 52 04" src="https://user-images.githubusercontent.com/317464/34729672-a700e766-f55d-11e7-85cb-424dd6465a00.png">

It will still fill the screen, but the resolution will be lower, thus reducing CPU usage.

**Comment by tuxayo** [comment]
I was able to measure this in a voice-only conference call.

Any proposal about how can I or someone else double check this so we can be sure to close this issue or to reopen it?

**Comment by saghul** [comment]
> I was able to measure this in a voice-only conference call.

Was your video muted, the remote's or both? This has significance.

> Any proposal about how can I or someone else double check this so we can be sure to close this issue or to reopen it?

That's kinda hard because it depends on a number of factors. I'd say a good start is to measure, change something, measure again. Under the same conditions, of course.

Unless there are numbers to back it up, everything is pure speculation.

**Comment by tuxayo** [comment]
> Was your video muted, the remote's or both? This has significance.

There was no video displayed in the call. But due to another issue, there was a screensharing that didn't work (we couldn't see it) and I can't guarantee that the sharer did stop the screensharing after we gave up on using it.
So maybe there was a non visible video feed being processed (and impacted by the windows)

So I need to try again. And collect better data during the next conference call.
