### ISSUE TITLE
external_api.js: extra JSON encoding on interfaceConfigOverwrite

### ISSUE THREAD

**Issue by yourcelf** [jitsi/jitsi-meet#853]
Parameters passed as members of the `interfaceConfigOverwrite` parameter to the constructor for `JitsiMeetExternalAPI` are [encoded as URL parameters](https://github.com/jitsi/jitsi-meet/blob/99ca38d13ff73f0a88a7263b74f664bd21183c3c/modules/API/external/external_api.js#L133-L141).  When read by jitsi-meet, they are decoded in [util.js's getConfigParamsFromURL](https://github.com/jitsi/jitsi-meet/blob/99ca38d13ff73f0a88a7263b74f664bd21183c3c/utils.js#L45-L67).

The [documentation](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md), while somewhat scant, appears to indicate that one can pass parameters like this:

    {
        DEFAULT_LOCAL_DISPLAY_NAME: username,
        DEFAULT_REMOTE_DISPLAY_NAME: "Cohort",
        TOOLBAR_BUTTONS: "microphone,camera,etherpad,sharedvideo,settings",
    }

However, when these parameters are decoded, `getConfigParamsFromURL` assumes that each is separately JSON encoded value -- even if the expected parameters are simple values like strings.  This means that it is necessary to explicitly JSON-encode each value separately (in the case of strings, this means effectively double-quoting them):

    {
        DEFAULT_LOCAL_DISPLAY_NAME: JSON.stringify(username),  // -> "\"username\""
        DEFAULT_REMOTE_DISPLAY_NAME: JSON.stringify("Cohort"), // ->  "\"Cohort\""
        TOOLBAR_BUTTONS: JSON.stringify("microphone,camera,etherpad,sharedvideo,settings")
    }

Failure to do this extra encoding results in confusing warnings in the console about JSON-decoding parameters, and the values being ignored.

This should ideally be fixed so that JSON encoding is either not needed, or handled internally by `JitsiMeetExternalAPI()` when encoding the URL parameters.  Alternatively, the behavior and necessary encoding of parameters should be documented.

**Comment by damencho** [comment]
I was facing similar issue these days by using the url params. The problem was that I was passing the params as config.someConfig=sometext and was getting the errors from getConfigParamsFromURL and my config was ignored. I fixed it by passing: config.someConfig="sometext".
Did you try passing all params with quotes, does it work for you? I see that it is ok for DEFAULT_REMOTE_DISPLAY_NAME and TOOLBAR_BUTTONS, and you only need to fix - DEFAULT_LOCAL_DISPLAY_NAME to be "username".

Could you please in the future send emails to the mailinglist before opening issues, thanks.

**Comment by yourcelf** [comment]
Yes, quoting parameters works (that's the same effect as `JSON.stringify`).  The URL parameters are assumed to be JSON-decodable.
