### ISSUE TITLE
Publish external_api.js as an npm module

### ISSUE THREAD

**Issue by yourcelf** [jitsi/jitsi-meet#854]
It would be very useful to have [`external_api.js`](https://github.com/jitsi/jitsi-meet/blob/99ca38d13ff73f0a88a7263b74f664bd21183c3c/modules/API/external/external_api.js) published as a standalone npm module that could be used within webpack/browserify projects.  It is currently only available [(as documented here)](https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md) in a format intended to be used within a global `<script>` tag.

**Comment by damencho** [comment]
This had been discussed several times while creating the library.
The idea of the library and the external_api is that they all come with a backend and all projects that use it needs to source it from a common location. In order to install it, you install jitsi-meet, which comes in a combination with jicofo and videobridge and later by updating you update all backend and libraries/apis. 
Please use the mailinglist prior opening issues.

**Comment by damsorian** [comment]
what about this topic in 2020?, I think we need a npm package to install the external_api.js, in order to follow the best practices in the modern frameworks

cc @damencho
