### ISSUE TITLE
How to use H264 instead of VP8 for video

### ISSUE THREAD

**Issue by laolsson** [jitsi/jitsi-meet#877]
Hi,

I followed the quick install guide here:
https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md

and it all works well, using VP8 video codec.

However, I can't figure out how to change the video codec to be H264, how do I do that?

I have tried setting the preferred codec in Firefox but this does not seem to change the sent SDP.

Thanks,
Lars

**Comment by thedracle** [comment]
laolsson,

Jicofo is responsible for sending the codecs that the bridge itself supports.

Since the bridge is the proxy for all of your PeerConnections, it will only negotiate the codecs that the bridge itself advertises.

If you patch src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java you can add any codecs you like, including VP9. 

Here is an example patch I use for H.264:

`@@ -192,6 +192,23 @@ private static void addVideoToContent(ContentPacketExtension content,
         absSendTime.setURI(URI.create(RTPExtension.ABS_SEND_TIME_URN));
         rtpDesc.addExtmap(absSendTime);
 
+        // a=rtpmap:107 H264/90000
+        int h264pt = 107;
+        PayloadTypePacketExtension h264
+            = addPayloadTypeExtension(rtpDesc, h264pt, Constants.H264, 90000);
+
+        // a=rtcp-fb:107 ccm fir
+        h264.addRtcpFeedbackType(createRtcpFbPacketExtension("ccm", "fir"));
+
+        // a=rtcp-fb:107 nack
+        h264.addRtcpFeedbackType(createRtcpFbPacketExtension("nack", null));
+
+        // a=rtcp-fb:107 nack pli
+        h264.addRtcpFeedbackType(createRtcpFbPacketExtension("nack", "pli"));
+
+        // a=rtcp-fb:107 goog-remb
+        h264.addRtcpFeedbackType(createRtcpFbPacketExtension("goog-remb", null));
+
         // a=rtpmap:100 VP8/90000
         int vp8pt = 100;
         PayloadTypePacketExtension vp8
@@ -213,12 +230,18 @@ private static void addVideoToContent(ContentPacketExtension content,
         {
             addParameterExtension(
                 vp8, "x-google-min-bitrate", String.valueOf(minBitrate));
+            addParameterExtension(
+                h264, "x-google-min-bitrate", String.valueOf(minBitrate));
+
         }
 
         if (startBitrate != -1)
         {
             addParameterExtension(
                 vp8, "x-google-start-bitrate", String.valueOf(startBitrate));
+
+            addParameterExtension(
+                h264, "x-google-start-bitrate", String.valueOf(startBitrate));
         }
 
         if (useRtx)
`

**Comment by zosnap** [comment]
I tried this, and it does cause jicofo to advertise h264 in its jingle messages, but in a test conference between a regular chrome window and an incognito chrome window I don't get a video connection. Audio works as normal but the screen just shows "chrome is having connectivity issues...". Do I need to do anything else to chrome or the videobridge to make this work with h264? There aren't any obvious errors in the console, but it does say that the video is muted ("video is now active <video muted=​"true" autoplay "...). Do I need to do something to unmute it? Attaching chrome console log and logs from the docker container running jicofo, jvb, prosody, and nginx in case those help. 

[conference_chrome.txt](https://github.com/jitsi/jitsi-meet/files/670011/conference_chrome.txt)
[conference_docker.txt](https://github.com/jitsi/jitsi-meet/files/670012/conference_docker.txt)

**Comment by thedracle** [comment]
zosnap,

I remember now I ran into this same issue with Chrome- so I went back and dug through my checkins and found this.

Precedes: 

    H264 must be uppercase or Chrome loses its shit.

--------- src/main/java/org/jitsi/jicofo/util/JingleOfferFactory.java ---------
index 471738b..45e2186 100644
@@ -195,7 +195,7 @@ private static void addVideoToContent(ContentPacketExtension content,
         // a=rtpmap:107 H264/90000
         int h264pt = 107;
         PayloadTypePacketExtension h264
-            = addPayloadTypeExtension(rtpDesc, h264pt, Constants.H264, 90000);
+            = addPayloadTypeExtension(rtpDesc, h264pt, Constants.H264.toUpperCase(), 90000);
 
         // a=rtcp-fb:107 ccm fir
         h264.addRtcpFeedbackType(createRtcpFbPacketExtension("ccm", "fir"));

**Comment by gpolitis** [comment]
@thedracle I just tried on latest Chrome stable (62.0.3202.75) both in p2p mode and in multi-party mode and it works correctly whether it is lower or upper case; however, there may have been an issue with older Chrome versions (and this is a very old issue).

**Comment by saghul** [comment]
Have you set the `preferH264` setting in the configuration? It defaults to false.

**Comment by sliderxtm** [comment]
is any solution without patch jicofo?
