### ISSUE TITLE
Remove vendor lock-ins in Jitsi

### ISSUE THREAD

**Issue by ranjithrajv** [jitsi/jitsi-meet#8908]
### Is your feature request related to a problem you are facing?
It is becoming extremely tough to use Jitsi with restrictions on choosing limited choices of providers like YouTube for streaming/sharing video and DropBox for storing a recorded video on Jitsi. 

Jitsi has always been one of the most loved FOSS video conferencing solution, but vendor lock-ins with YouTube & DropBox are great pain points. I appeal to the developers/contributors to prioritize working on this issue to remove restrictions, improve accessibility and adoption of Jitsi.

### Describe the solution you'd like
**Remove vendor lock-in in streaming feature**
Instead of restricting to stream to just YouTube, 

- [ ]  [ Allow Streaming to WebRTC general endpoint ](https://github.com/jitsi/jitsi-meet/issues/6156)

- [ ] [ Allow streaming to general RTMP endpoint ](https://github.com/jitsi/jitsi-meet/issues/2829)

**Remove vendor lock-in in recording feature**
Instead of restricting to just DropBox as the only provider for storage,

- [ ] Allow to store recorded video in any virtual drive platforms

**Remove vendor lock-in in to share a video**
Instead of restricting to just to share a video from YouTube,

- [ ] Allow to share a video from any video hosting platform

P.S.: Consider this as a meta issue for listing all sub-issues requesting to remove vendor lock-ins in Jitsi OR requesting to add more providers, please add them in comments.

**Comment by rajasekharponakala** [comment]
Yes. Instead of streaming to just YoutTube , we need endpoints like WebRTC and RTMP. And yes, remove vendor lock-ins.

**Comment by saghul** [comment]
I've spent a nontrivial amount of time trying to articulate my thoughts before responding.  This is a mixture of project direction and personal feelings, but I cannot separate both, so here we go.

> It is becoming extremely tough to use Jitsi with restrictions on choosing limited choices of providers like YouTube for streaming/sharing video and DropBox for storing a recorded video on Jitsi.

I find this incredibly hard to believe.

Jitsi Meet can stream to arbitrary RTMP endpoints already, so you don't need to use YouTube for that, just pass an RTMP URL instead of the YouTube channel ID. Yes, this feature is not very discoverable at the moment, we need to improve on that.

Recording to services other than dropbox has been available for a very long time. In your Jitsi Meet deployment you can use the finalize script on Jibri to upload the file anywhere.

> I appeal to the developers/contributors to prioritize working on this issue to remove restrictions, improve accessibility and adoption of Jitsi.

Everyone wants to save the world but nobody wants to do the dishes. Are you up for working on these?

>     * [ Allow Streaming to WebRTC general endpoint ](https://github.com/jitsi/jitsi-meet/issues/6156)

This is unlikely to happen. There is no such a thing. You'd need to coordinate signalling, it's not like you can just send media to a  random IP and port. That means you'd need to establish a WebRTC connection with some other platform. We are not going to build a streaming platform. So your best course of action is to stream to RTMP and then use some platform such as Red5 to consume it via WebRTC if that's what you need.

>     * Allow streaming to general RTMP endpoint

As I mentioned earlier, this has been available for a while, while not very visible.

>     * Allow to store recorded video in any virtual drive platforms

As I mentioned, this is already possible in your own deployment. If you want it fully integrated like currently Dropbox is, then all I can say is that patches are welcome, we are not planning on working on more storage providers in the near future. We have applied for Google Summer of Code and this was one of the proposed projects but alas we got rejected the past 2 years in a row. Hopefully it happens next year.

>     * Allow to share a video from any video hosting platform

I have some good news. We will soon be launching a hackathon where this is one of the suggested projects. Integrating with PeerTube, more specifically.

> P.S.: Consider this as a meta issue for listing all sub-issues requesting to remove vendor lock-ins in Jitsi OR requesting to add more providers, please add them in comments.

I don't think this is useful and will be closing this issue, sorry. I believe we have open issues for the pending issues already, this issue adds nothing on top of that.

**Comment by saghul** [comment]
FYI: https://jitsi.org/blog/winning-over-the-classroom-with-jitsi/
