### ISSUE TITLE
Cannot chose the speaker used anymore safari 

### ISSUE THREAD

**Issue by PxBCPG** [jitsi/jitsi-meet#9094]
### Description:

Cannot chose the mic used anymore

### Steps to reproduce:

1. Create a room in Jitsi in safari 
2. Try to change your speaker ! 

### Expected behavior:

If you click on the mic, you will have the possibility to change the mic, and only the mic (before you were able to change your speaker)

### Server information:

- Jitsi Meet version: official server
- Operating System: official server (meet.jit.si)

### Client information:

- Browser / app version: Safari
- Operating System: macOS

### Additional information:

Maybe it have been removed with an update
It is a major problem, especially when you use a headset which have a sound balance (game and chat)

**Comment by jallamsetty1** [comment]
Speaker selection is not supported by Safari at the moment, the browser doesn't even enumerate the audio output devices available. There was webkit [bug](https://bugs.webkit.org/show_bug.cgi?id=197623) filed for this but there are no indications from Apple if they will be fixing this because of privacy concerns. Closing this as it not an application bug.
