### ISSUE TITLE
Email invite could use some customization and cleanup

### ISSUE THREAD

**Issue by mrose17** [jitsi/jitsi-meet#9114]
cf., https://github.com/jitsi/jitsi-meet/pull/9001 ... Here's what we see when sharing an invite via email. The first image shows the security check to invoke the Mail app, the second image shows the result. Note two things: first, the HTML markup is showing literally in the second image; and, second, the subject line says "Join 8x8 Meet meeting". For the JaaS, there ought to be a way of customizing this, i.e., instead of "8x8 Meet" something like "Brave Together", etc.
![116454857-43c9a480-a815-11eb-8b1f-93eea69ba261](https://user-images.githubusercontent.com/400552/116599796-89aa6980-a8f6-11eb-8845-4452e56c5d80.png)
![116454851-42987780-a815-11eb-895d-df2bb099f6cd](https://user-images.githubusercontent.com/400552/116599800-8adb9680-a8f6-11eb-99fe-d6ebe7b967f2.png)

**Comment by saghul** [comment]
Hey Marshall!

In order to fill in the email with a single link everything needs be in the mailto URL. As far as I can tell that dialog which shows the full link is displayed by Brave, isn't it? I cannot see it when using Safari. I know it's there because it shows up when I "peek":

![IMG_2900](https://user-images.githubusercontent.com/317464/116666160-f0815e80-a99a-11eb-9339-ec8823fc2530.PNG)

Not sure what can be done on our side here.

Then once the email client opens I don't see the raw HTML markup:

![IMG_2901](https://user-images.githubusercontent.com/317464/116666199-fb3bf380-a99a-11eb-9fb2-2094350c47e9.PNG)

So it looks to me like a bug in Brave for iOS when handling mailto URLs.

Regarding the JaaS branding part, we'll look into it.

**Comment by saghul** [comment]
No you didn't miss anything. The subject is composed by a config option called APP_NAME which defaults to 8x8 Meet on 8x8.vc. We'll be looking at making that changeable on your side.

**Comment by mrose17** [comment]
Thank you!

**Comment by muscat1** [comment]
Added a config option that enables overwriting the specific app name that gets displayed in the email subject. See: https://github.com/jitsi/jitsi-meet/pull/9201
