### ISSUE TITLE
Video often freezes and is out of sync on iOS

### ISSUE THREAD

**Issue by iccub** [jitsi/jitsi-meet#9343]
### Steps to reproduce:

1. Have a call on together.brave.com with cameras enabled

### Actual behavior:

Video is often choppy, or freezes. It freezes for people not currently speaking too.

### Server information:

- Jitsi Meet version:
- Operating System:

### Client information:

- Browser / app version:
- Operating System:

**Comment by stephendonner** [comment]
Is this on both iOS and Android, @iccub?  How many participants?  Was this the 8+ call you had the other day?  And, just to confirm, this was with our standard `lastN` configuration of `1`, right @mrose17?

**Comment by iccub** [comment]
Yes it was the 8+ call, perhaps next time we can screen record the whole call to make it easier to notice

**Comment by mrose17** [comment]
i suspect that this isn't specific to iOS, but may just be the way that global conferences have glitches. there is a lot of variable latency and i see this (rarely) on desktop as well. Miami has "odd" connectivity at times (i'm not sure why).

**Comment by jallamsetty1** [comment]
This issue has been fixed in master [here](https://github.com/jitsi/lib-jitsi-meet/pull/1635) and will be deployed to 8x8.vc in the next release.

**Comment by mrose17** [comment]
cc: @stephendonner

**Comment by stephendonner** [comment]
Verified `FIXED` as best I can tell using the following clients, in a single call, using the `talk.brave.com` endpoint, which points to `8x8.vc`'s JaaS under the hood:
* iPad Pro (iOS 14.7 public beta)
* iPhone 6s (iOS 14.4.2)
* iPhone 8 Plus (iOS 14.7 public beta)
* Google Pixel XL (Android 10)
* MacBook Pro (macOS 11.4)
* Origin desktop PC (Windows 10)

Brave versions:
* iOS: 1.27.1 (21.6.22.16)
* Android: 1.26.71, Chromium 91.0.4472.120
* desktop: 1.26.67, Chromium 91.0.4472.114

![Image from iOS](https://user-images.githubusercontent.com/387249/123882219-2be8cc80-d8fb-11eb-8464-74e3766bc66c.png)

I disabled the camera on the desktop clients, and tried to make sure that the iOS clients had video and audio going, as much as possible (2 at a time, due to our `lastN` configuration).

I only observed noticeable lag / slight freezes when other clients left or joined, or there was heavy network activity on my local / Wi-Fi network (such as downloading a huge file).  In all cases, within a few seconds (3 or so, max), video and audio caught up (looked like video on fast-forward mode, in that moment).

We can and should file specific bugs if we see this / other streaming issues, again.

/cc @iccub @Brandon-T for posterity

**Comment by zsinba** [comment]
how about this issue?
