### ISSUE TITLE
Cannot hear anyone if block all devices on Safari

### ISSUE THREAD

**Issue by st-rkalinov** [jitsi/jitsi-meet#9535]
### Description:

If I make/join a conference on meet.jit.si with Safari browser but block the access for the microphone AND camera, after that I cannot hear anyone in the conference.
If I block only ONE of the devices there is no problem.

### Steps to reproduce:

1. Make/Join some conference on meet.jit.si with Safari browser
2. Block the access to the microphone and the camera

### Expected behavior:

Should hear the audio of the other without any problem

### Actual behavior:

Doesn't hear anyone in the conference

### Client information:

- Browser / app version: Safari Version 14.0.3 
- Operating System: MacOS BigSur version 11.2

**Comment by jallamsetty1** [comment]
The browser doesn't let the application to play the audio track if the permission to use the microphone is denied. This is a browser limitation and the application cannot workaround this limitation. Please open a webkit bug for this.

`"Failed to play audio track! retry: 3 ; Error: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."
`
Closing this issue as it is not an application issue.
