### ISSUE TITLE
Implement E2EE in terms of RTCRtpScriptTransform

### ISSUE THREAD

**Issue by jbg** [jitsi/jitsi-meet#9585]
Firefox [plans to implement `RTCRtpScriptTransform`](https://bugzilla.mozilla.org/show_bug.cgi?id=1631263) ([and `SFrameTransform`](https://bugzilla.mozilla.org/show_bug.cgi?id=1715625), but possibly with lower priority) from the WebRTC Encoded Transform spec, but not the older, and [now removed from the draft](https://github.com/w3c/webrtc-encoded-transform/commit/f6164614cab72eb89a2ca7ad04eecd3552df2438), `createEncodedStreams` function which Jitsi Meet uses for E2EE.

FaceTime Web's use of `RTCRtpScriptTransform` appears to have created some motivation for getting it implemented in Firefox quickly, and Safari already supports it. Given that `createEncodedStreams` has been removed from the draft, ongoing support in Chrome and its derivatives can't be guaranteed anyway.

It would therefore be beneficial to move Jitsi Meet's E2EE over to using the likely-to-be-standardised APIs (`RTCRtpScriptTransform` if it's possible to implement it only in terms of that, since it appears it will get wider support more rapidly).

**Comment by fippo** [comment]
i do not see Chrome very motivated to implement the new API, rather adding back the battle-tested API in https://github.com/w3c/webrtc-encoded-transform/pull/111

**Comment by jbg** [comment]
In that case we could possibly use a shim to provide `createEncodedStreams` using `RTCRtpScriptTransform` on Firefox & Safari. Your linked issue contains a comment alluding to such a shim, but doesn't provide any reference. It seems like it should be possible to implement it though.

**Comment by youennf** [comment]
> In that case we could possibly use a shim to provide `createEncodedStreams` using `RTCRtpScriptTransform` on Firefox & Safari.

That might be ok for prototyping but you might experience main thread jank in RTCRtpScriptTransform implementations in that case since you would send back encoded data to window context.
If you are already using a worker to do the encryption/decryption (as a transform stream or as a function taking a readable and writable), the code to support both APIs, although annoying, should be straightforward and fairly small.

**Comment by saghul** [comment]
We are indeed during all encryption / decryption in a worker at the moment.

**Comment by youennf** [comment]
Good to know that you are already doing processing in a worker.
I uploaded a PR which is updating webrtc samples end-to-end example to use RTCRtpScriptTransform if available at https://github.com/webrtc/samples/pull/1468.
That might be relevant to the work you would need to do here.

**Comment by saghul** [comment]
@youennf I made a PR adding support for it here: https://github.com/jitsi/lib-jitsi-meet/pull/1696 let's see how it goes. First tests show I can get video from Chrome to show on Safari, but not the other way around. Since our code is the same, any pointers as to how to start debugging? I tested with STP 130.

**Comment by initpwn** [comment]
@saghul Hi, 
Are there any plans or any updates on implementing SFrameTransform? 
Specifically, E2EE support on WebKit based browsers.

**Comment by saghul** [comment]
We already implement RTCRtpScriptTransform which allows us to use the same code in all supported browsers.

It is, however, behind a flag still since it needs more testing.

**Comment by saghul** [comment]
Only Chromium and Safari implement this currently. This PR added Safari support behind a flag: https://github.com/jitsi/lib-jitsi-meet/pull/1696 see line ~101.

Any feedback is welcome.
