### ISSUE TITLE
Stop cropping video.

### ISSUE THREAD

**Issue by MariasStory** [jitsi/jitsi-meet#969]
Hi, I do like the way jitsi-meet is improving. One of the issues I have now is that the video is cropped in order to fill the screen. I don't agree with the solution. I would like to see every pixel that is transmitted. Can you please scale the video in order to have a best fit by the biggest video dimension.

**Comment by MariasStory** [comment]
Ping 1.

**Comment by Nemra1** [comment]
ping 2.

**Comment by gradinaruvasile** [comment]
If you have your own server, there is an option in 
/usr/share/jitsi-meet/interface_config.js

`VIDEO_LAYOUT_FIT: 'both',`

This can be set to "height" or "width" and the video wil be fit  to height or width. Usually height is the better choice.

**Comment by hlwsmith** [comment]
This issue is the one that is currentlu preventing me from using Jitsi meet. It's great I can set this how I want on the server (I will try this), though this is an expensive solution for a casual user. I suggest that on phones and small screens the current setup looks good. On desktops, not so much. A user settable solution would be ideal.

**Comment by emcho** [comment]
The solution indicated by @gradinaruvasile is settable by users who deploy jitsi meet. We would be open to take a patch that also makes it configurable through settings. I am closing this issue until this happend

**Comment by EliterScripts** [comment]
@emcho @gradinaruvasile I don't believe this fixes the problem. I am having a similar problem too! I really want this to scale down.
