### ISSUE TITLE
Facing issue archiving IOS Jitsi meet sdk

### ISSUE THREAD

**Issue by Sbhonagiri** [jitsi/jitsi-meet#9965]
Able to run the IOS build successfully but facing issue while archiving the build please find the attached screenshot for the errors, help is highly appreciated.

![7afdcacae2a3a83f395ae4e36413dd35a52e7cd8](https://user-images.githubusercontent.com/17709729/133841395-c18311bc-1ec5-4f80-8909-9e7db90136d9.png)

**Comment by Sbhonagiri** [comment]
@jallamsetty1 Could you please have a look into the issue reported and advise needful to be done

**Comment by saghul** [comment]
What steps are you following exactly?

**Comment by Sbhonagiri** [comment]
Please find the Steps followed:
Running the project on Mac OS
1)Setup Jisti meet project
2)installed the pre requisites node and npm
3)Installed cocoapods
4)from the jitsi project path ran npm install -g react-native-cli
5)then cd to ios folder path and installed pods
6)Then doublicked the ios/jitsi-meet.xcworkspace file, project has been launched on the Xcode
7)able to build the project successfully
8)Facing issue while performing archive

**Comment by saghul** [comment]
Did you run "npm install" before running "pod install"?

**Comment by Sbhonagiri** [comment]
> Did you run "npm install" before running "pod install"?

Yes i have run npm install from jitsi project path and pod install from ios path

**Comment by Sbhonagiri** [comment]
@saghul Could you please help this is a blocker for me in generating the build

**Comment by saghul** [comment]
Something is not right in your project, have you made many changes to Jitsi Meet? I see Xcode is failing because it cannot find node_modules/react-native-webrtc/ios/WebRTC.framework, but we have switched to XCFramework a long time ago and it's now in node_modules/react-native-webrtc/apple/

You seem to be using an old Jitsi Meet with a newer react-native-webrtc. That is not going to work without specific changes.
